// Decompiled by AS3 Sorcerer 6.20
// www.as3sorcerer.com

//lloyd_fla.MainTimeline

package lloyd_fla
{
    import flash.display.MovieClip;
    import flash.events.Event;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.geom.Point;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
            addEventListener(Event.ADDED_TO_STAGE, this.__setPerspectiveProjection_);
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        public function getAudio():Array
        {
            return (new Array(Run_start, lloyd_demonFang2, lloyd_jumpVoice, lloyd_swordrain, lloyd_beast, lloyd_attackU, lloyd_beastroar, lloyd_risingfalcon, lloyd_hurt2, lloyd_dead, lloyd_dead2, lloyd_hitHard1, lloyd_hurt, lloyd_hitHard2, lloyd_jumpSound, lloyd_jumpSound2, lloyd_sonicthrust, lloyd_taunt, lloyd_taunt2, lloyd_tempest, lloyd_demonfang, lloyd_tigerblade, lloyd_winVoice, lloyd_footstep, lloydwin, lloyd_grunt1, lloyd_grunt2, lloyd_grunt3, lloyd_grunt4, lloyd_grave_blade, lloyd_echo_swing, lloyd_thrustmiss, lloyd_slashmiss, lloyd_dair, lloyd_slash1, lloyd_slash2, lloyd_thrust1, lloyd_thrust2));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"lloyd",
                "displayName":"Lloyd",
                "linkage_id":"lloyd",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"lloyd_head",
                "seriesIcon":"talesOf",
                "width":24,
                "height":45,
                "jumpSpeed":15,
                "jumpSpeedMidair":15,
                "jumpStartup":2,
                "shortHopSpeed":7.5,
                "max_jumpSpeed":6.5,
                "dodgeSpeed":8,
                "gravity":1.2,
                "weight1":84,
                "power":"lloyd",
                "norm_xSpeed":4.5,
                "max_xSpeed":10,
                "max_ySpeed":14,
                "fastFallSpeed":16,
                "accel_start":1.5,
                "accel_start_dash":1.35,
                "accel_rate":1.2,
                "accel_rate_air":1.1,
                "decel_rate":-0.97,
                "decel_rate_air":-0.12,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":2,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_delay":9,
                "getup_roll_delay":0,
                "itemScaleRatio":0.833333333333333,
                "special_type":2,
                "normalStats_id":"lloyd",
                "specialStats_id":null,
                "sounds":{
                    "jump":"lloyd_jumpVoice",
                    "jump_midair":"lloyd_jumpSound",
                    "hurt":"lloyd_hurt",
                    "hurt2":"lloyd_hurt2",
                    "hurtBad":"lloyd_hitHard1",
                    "hurtBad2":"lloyd_hitHard2",
                    "dead":"lloyd_dead",
                    "dead2":"lloyd_dead2",
                    "pummel":"tos_swordcut",
                    "screenko":"lloyd_hitHard2",
                    "starko":null,
                    "ledge_grab":null,
                    "winTheme":"lloydwinv2"
                },
                "hurtFrames":3,
                "grabDamage":2
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "canFallOff":false,
                    "reenableTimer":10,
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt2",
                    "attackVoice3_id":"lloyd_grunt3",
                    "attackVoice4_id":"lloyd_grunt4",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackSound2_id":"tos_swordswing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":5,
                            "hitLag":8,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":60,
                            "power":0,
                            "kbConstant":70,
                            "effectSound":"tos_swordcut"
                        },
                        "attackBox2":{
                            "damage":3,
                            "priority":1,
                            "hitStun":5,
                            "hitLag":8,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":60,
                            "power":0,
                            "kbConstant":70,
                            "effectSound":"tos_swordcut"
                        }
                    }
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"lloyd_attackU",
                    "attackSound1_id":"tos_swordswing",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":5,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"sliceRed",
                            "direction":100,
                            "power":50,
                            "kbConstant":95,
                            "effectSound":"lloyd_thrust2"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt2",
                    "attackVoice3_id":"lloyd_grunt3",
                    "attackVoice4_id":"lloyd_grunt4",
                    "attackSound1_id":"lloyd_slashmiss",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":95,
                            "power":80,
                            "kbConstant":95,
                            "effectSound":"lloyd_slash2"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":95,
                            "power":80,
                            "kbConstant":95,
                            "effectSound":"lloyd_slash2"
                        },
                        "attackBox3":{
                            "damage":9,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":95,
                            "power":80,
                            "kbConstant":95,
                            "effectSound":"lloyd_slash2"
                        },
                        "attackBox4":{
                            "damage":9,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":95,
                            "power":80,
                            "kbConstant":95,
                            "effectSound":"lloyd_slash2"
                        }
                    }
                },
                "a_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt2",
                    "attackVoice3_id":"lloyd_grunt3",
                    "attackVoice4_id":"lloyd_grunt4",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"sliceRed",
                            "direction":90,
                            "power":95,
                            "kbConstant":50,
                            "effectSound":"tos_swordcut"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt2",
                    "attackVoice3_id":"lloyd_grunt3",
                    "attackVoice4_id":"lloyd_grunt4",
                    "attackSound1_id":"lloyd_thrustmiss",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":5,
                            "hitStun":6,
                            "selfHitStun":3,
                            "effect_id":"sliceBlue",
                            "direction":30,
                            "power":29,
                            "kbConstant":96,
                            "effectSound":"lloyd_thrust2"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "reenableTimer":8,
                    "chargeClick":true,
                    "attackVoice1_id":null,
                    "attackVoice2_id":"lloyd_beast",
                    "attackSound1_id":"lloyd_beastroar",
                    "attackSound2_id":"lloyd_echo_swing",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":8,
                            "selfHitStun":9,
                            "camShake":8,
                            "effect_id":"beastHit",
                            "direction":40,
                            "power":40,
                            "kbConstant":65,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":null,
                    "attackVoice2_id":"lloyd_swordrain",
                    "attackVoice3_id":"lloyd_sonicthrust",
                    "attackVoice4_id":"lloyd_tigerblade",
                    "attackSound1_id":"lloyd_echo_swing",
                    "attackSound2_id":"lloyd_echo_swing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"sliceRed",
                            "direction":330,
                            "power":10,
                            "kbConstant":10,
                            "effectSound":"lloyd_thrust1"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"sliceRed",
                            "direction":330,
                            "power":10,
                            "kbConstant":10,
                            "effectSound":"lloyd_thrust1"
                        }
                    }
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":1,
                    "allowControl":true,
                    "attackVoice1_id":"lloyd_tempest",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.15,
                            "selfHitStun":0,
                            "effect_id":"sliceBoth",
                            "direction":65,
                            "power":25,
                            "kbConstant":0,
                            "effectSound":"tos_swordcut"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.15,
                            "selfHitStun":0,
                            "effect_id":"sliceBoth",
                            "direction":65,
                            "power":25,
                            "kbConstant":0,
                            "effectSound":"tos_swordcut"
                        }
                    }
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt2",
                    "attackVoice3_id":"lloyd_grunt3",
                    "attackVoice4_id":"lloyd_grunt4",
                    "attackSound1_id":"lloyd_slashmiss",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":1,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"sliceBlue",
                            "direction":80,
                            "power":40,
                            "kbConstant":77,
                            "effectSound":"tos_swordcut"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":1,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"sliceBlue",
                            "direction":80,
                            "power":40,
                            "kbConstant":77,
                            "effectSound":"tos_swordcut"
                        },
                        "attackBox3":{
                            "damage":10,
                            "priority":1,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"sliceBlue",
                            "direction":80,
                            "power":40,
                            "kbConstant":77,
                            "effectSound":"tos_swordcut"
                        }
                    }
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt2",
                    "attackVoice3_id":"lloyd_grunt3",
                    "attackVoice4_id":"lloyd_grunt4",
                    "attackSound1_id":"lloyd_slashmiss",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":11,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"sliceRed",
                            "direction":40,
                            "power":23,
                            "kbConstant":95,
                            "effectSound":"tos_swordcut"
                        },
                        "attackBox2":{
                            "damage":11,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"sliceRed",
                            "direction":40,
                            "power":23,
                            "kbConstant":95,
                            "effectSound":"tos_swordcut"
                        },
                        "attackBox3":{
                            "damage":11,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"sliceRed",
                            "direction":40,
                            "power":23,
                            "kbConstant":95,
                            "effectSound":"tos_swordcut"
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt2",
                    "attackVoice3_id":"lloyd_grunt3",
                    "attackVoice4_id":"lloyd_grunt4",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"sliceRed",
                            "direction":160,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":84,
                            "effectSound":"tos_swordcut"
                        }}
                },
                "a_air_down":{
                    "refreshRate":1,
                    "resetMovement":true,
                    "air_ease":0,
                    "canFallOff":false,
                    "attackVoice1_id":"lloyd_risingfalcon",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackSound2_id":"lloyd_dair",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"sliceRed",
                            "direction":325,
                            "reversableAngle":false,
                            "power":35,
                            "kbConstant":90,
                            "meteorBounce":false,
                            "effectSound":"tos_swordcut"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"sliceRed",
                            "direction":325,
                            "reversableAngle":false,
                            "power":35,
                            "kbConstant":90,
                            "meteorBounce":false,
                            "effectSound":"tos_swordcut"
                        }
                    }
                },
                "b":{
                    "cancelWhenAirborne":false,
                    "customChargeGlow":"DFoverlay",
                    "attackVoice1_id":"lloyd_demonFang2",
                    "attackVoice2_id":"lloyd_demonfang",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackSound2_id":"tos_swordswing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "hasEffect":false,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":45,
                            "power":0,
                            "kbConstant":70,
                            "effectSound":"tos_swordcut"
                        },
                        "attackBox2":{
                            "damage":3,
                            "hasEffect":false,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":45,
                            "power":0,
                            "kbConstant":70,
                            "effectSound":"tos_swordcut"
                        }
                    }
                },
                "b_air":{
                    "allowControl":true,
                    "allowControlGround":false,
                    "reenableTimer":30,
                    "customChargeGlow":"DFoverlay",
                    "attackVoice1_id":"lloyd_demonFang2",
                    "attackVoice2_id":"lloyd_demonfang",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackSound2_id":"tos_swordswing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "hasEffect":false,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":45,
                            "power":0,
                            "kbConstant":70,
                            "effectSound":"tos_swordcut"
                        },
                        "attackBox2":{
                            "damage":3,
                            "hasEffect":false,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":45,
                            "power":0,
                            "kbConstant":70,
                            "effectSound":"tos_swordcut"
                        }
                    }
                },
                "b_up":{
                    "cancelWhenAirborne":false,
                    "xSpeedAccel":1,
                    "xSpeedAccelAir":1.5,
                    "xSpeedDecay":-0.15,
                    "xSpeedDecayAir":-0.15,
                    "allowControl":true,
                    "attackVoice1_id":"lloyd_tigerblade",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackSound2_id":"tos_swordswing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":1,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"sliceBlue",
                            "direction":80,
                            "power":80,
                            "kbConstant":20,
                            "effectSound":"tos_swordcut"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":1,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"sliceBlue",
                            "direction":80,
                            "power":80,
                            "kbConstant":20,
                            "effectSound":"tos_swordcut"
                        },
                        "attackBox3":{
                            "damage":7,
                            "priority":1,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"sliceBlue",
                            "direction":80,
                            "power":80,
                            "kbConstant":20,
                            "effectSound":"tos_swordcut"
                        }
                    }
                },
                "b_up_air":{
                    "cancelWhenAirborne":false,
                    "xSpeedAccel":1,
                    "xSpeedAccelAir":1.5,
                    "xSpeedDecay":-0.15,
                    "xSpeedDecayAir":-0.15,
                    "allowControl":true,
                    "isRecoveryMove":true,
                    "disableJump":true,
                    "attackVoice1_id":"lloyd_tigerblade",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackSound2_id":"tos_swordswing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":1,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"sliceBlue",
                            "direction":80,
                            "power":80,
                            "kbConstant":20,
                            "effectSound":"tos_swordcut"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":1,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"sliceBlue",
                            "direction":80,
                            "power":80,
                            "kbConstant":20,
                            "effectSound":"tos_swordcut"
                        },
                        "attackBox3":{
                            "damage":7,
                            "priority":1,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"sliceBlue",
                            "direction":80,
                            "power":80,
                            "kbConstant":20,
                            "effectSound":"tos_swordcut"
                        }
                    }
                },
                "b_forward":{
                    "refreshRate":100,
                    "xSpeedDecay":0.8,
                    "xSpeedDecayAir":-0.05,
                    "chargetime_max":60,
                    "forceUseAtMaxCharge":true,
                    "canFallOff":false,
                    "attackVoice1_id":null,
                    "attackVoice2_id":"lloyd_sonicthrust",
                    "attackSound1_id":"tos_swordswing",
                    "attackSound2_id":"big_swing",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":6,
                            "chargedPriority":7,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"sliceBlue",
                            "direction":29,
                            "power":60,
                            "kbConstant":80,
                            "effectSound":"tos_swordcut"
                        }}
                },
                "b_forward_air":{
                    "refreshRate":100,
                    "xSpeedDecay":0.8,
                    "xSpeedDecayAir":-0.05,
                    "chargetime_max":60,
                    "forceUseAtMaxCharge":true,
                    "canFallOff":false,
                    "attackVoice1_id":null,
                    "attackVoice2_id":"lloyd_sonicthrust",
                    "attackSound1_id":"tos_swordswing",
                    "attackSound2_id":"big_swing",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":6,
                            "chargedPriority":7,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"sliceBlue",
                            "direction":29,
                            "power":60,
                            "kbConstant":80,
                            "effectSound":"tos_swordcut"
                        }}
                },
                "b_down":{
                    "refreshRate":100,
                    "resetMovement":true,
                    "stale":false,
                    "canFallOff":false,
                    "allowFastFall":false,
                    "attackVoice1_id":"lloyd_grave_blade",
                    "attackSound1_id":"brawl_punch_m",
                    "attackSound2_id":"sw_tos_singleslash",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":-1,
                            "hitStun":6,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "camShake":5,
                            "effect_id":"graveRocks",
                            "direction":110,
                            "power":110,
                            "kbConstant":10,
                            "onlyAffectsGround":true,
                            "effectSound":null
                        }}
                },
                "b_down_air":{
                    "disableForCPU":true,
                    "enabled":false
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt2",
                    "attackVoice3_id":"lloyd_grunt3",
                    "attackVoice4_id":"lloyd_grunt4",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackSound2_id":"tos_swordswing",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":0,
                            "hitStun":5,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"sliceBlue",
                            "direction":100,
                            "reversableAngle":false,
                            "power":45,
                            "kbConstant":95,
                            "bypassNonGrabbed":true,
                            "effectSound":"tos_swordcut"
                        }}
                },
                "throw_forward":{
                    "refreshRate":5,
                    "canFallOff":false,
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt2",
                    "attackVoice3_id":"lloyd_grunt3",
                    "attackVoice4_id":"lloyd_grunt4",
                    "attackSound1_id":"tos_swordswing",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":20,
                            "reversableAngle":false,
                            "power":0,
                            "kbConstant":0,
                            "bypassNonGrabbed":true,
                            "effectSound":"tos_swordcut"
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt2",
                    "attackVoice3_id":"lloyd_grunt3",
                    "attackVoice4_id":"lloyd_grunt4",
                    "attackSound1_id":"tos_swordswing",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":3,
                            "effect_id":"sliceRed",
                            "direction":135,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":100,
                            "bypassNonGrabbed":true,
                            "effectSound":"tos_swordcut"
                        }}
                },
                "throw_down":{
                    "refreshRate":100,
                    "canFallOff":false,
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt2",
                    "attackVoice3_id":"lloyd_grunt3",
                    "attackVoice4_id":"lloyd_grunt4",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackSound2_id":"tos_swordswing",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":-1.1,
                            "selfHitStun":0,
                            "effect_id":"sliceRed",
                            "direction":0,
                            "reversableAngle":false,
                            "power":0,
                            "kbConstant":0,
                            "bypassNonGrabbed":true,
                            "effectSound":"tos_swordcut"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt2",
                    "attackVoice3_id":"lloyd_grunt3",
                    "attackVoice4_id":"lloyd_grunt4",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"sliceRed",
                            "direction":40,
                            "power":55,
                            "kbConstant":65,
                            "effectSound":"tos_swordcut"
                        }}
                },
                "ledge_attack":{
                    "maintainSpeed":true,
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt2",
                    "attackVoice3_id":"lloyd_grunt3",
                    "attackVoice4_id":"lloyd_grunt4",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackSound2_id":"tos_swordswing",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":45,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"tos_swordcut"
                        }}
                },
                "getup_attack":{
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt2",
                    "attackVoice3_id":"lloyd_grunt3",
                    "attackVoice4_id":"lloyd_grunt4",
                    "attackSound1_id":"tos_swordswing",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "direction":45,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"lloyd_slash2"
                        }}
                },
                "kirby":{
                    "cancelWhenAirborne":false,
                    "customChargeGlow":"DFoverlay",
                    "attackVoice1_id":"Kirby_Attack04",
                    "attackVoice2_id":"Kirby_Attack04",
                    "attackVoice3_id":"lloyd_sonicthrust",
                    "attackVoice4_id":"lloyd_tigerblade",
                    "attackVoice5_id":"lloyd_grunt2",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackSound2_id":"tos_swordswing",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "hasEffect":false,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":45,
                            "power":0,
                            "kbConstant":70,
                            "effectSound":"tos_swordcut"
                        }}
                },
                "kirby_air":{
                    "allowControl":true,
                    "allowControlGround":false,
                    "reenableTimer":30,
                    "customChargeGlow":"DFoverlay",
                    "attackVoice1_id":"Kirby_Attack04",
                    "attackVoice2_id":"Kirby_Attack04",
                    "attackVoice3_id":"lloyd_sonicthrust",
                    "attackVoice4_id":"lloyd_tigerblade",
                    "attackVoice5_id":"lloyd_grunt2",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackSound2_id":"tos_swordswing",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "hasEffect":false,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":45,
                            "power":0,
                            "kbConstant":70,
                            "effectSound":"tos_swordcut"
                        }}
                },
                "special":{
                    "refreshRate":1,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"lloyd_grunt1",
                    "attackVoice2_id":"lloyd_grunt3",
                    "attackSound1_id":"magic_screech",
                    "attackSound2_id":"smallblast",
                    "attackSound3_id":"fire",
                    "attackBoxes":{"attackBox":{
                            "sdiDistance":0,
                            "damage":2,
                            "priority":0,
                            "hitStun":400,
                            "selfHitStun":0,
                            "camShake":0,
                            "effect_id":"effect_hit3",
                            "direction":0,
                            "power":0,
                            "kbConstant":0,
                            "effectSound":"sw_scratch"
                        }}
                }
            };
            var _local_4:Object = {"demonfang":{
                    "linkage_id":"lloyd_wave",
                    "width":38,
                    "height":36,
                    "time_max":30,
                    "xspeed":11,
                    "yspeed":4,
                    "controlInitDirection":true,
                    "gravity":4,
                    "maxgravity":3,
                    "xoffset":18,
                    "canFallOff":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":3,
                                "sdiDistance":0,
                                "priority":0,
                                "hitStun":5,
                                "selfHitStun":0,
                                "effect_id":"beastHit",
                                "direction":55,
                                "power":15,
                                "kbConstant":77,
                                "effectSound":"brawl_punch_m"
                            }}}
                }};
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("lloyd");
        }

        public function getGUID():String
        {
            return ("45af93ac-000a-4b46-b897-f7cc4a79d50b");
        }

        public function __setPerspectiveProjection_(_arg_1:Event):void
        {
            root.transform.perspectiveProjection.fieldOfView = 55;
            root.transform.perspectiveProjection.projectionCenter = new Point(275, 200);
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package lloyd_fla

