// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//ness_fla.MainTimeline

package ness_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public var ikNode_1:nessbase;

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        public function getAudio():Array
        {
            return (new Array(starstorm_sound, ness_throw, ness_psi3, ness_psi2, ness_psi1, ness_yoyoCharge, ness_yoyo, ness_thunder, ness_throw, ness_starKO, ness_pkThunder, ness_pkFlash, ness_pkFire, ness_okay, ness_magnetAbsorb, ness_magnetLoop, ness_jumpSound2, ness_jumpSound, ness_jump, ness_hurtBad1, ness_hurtBad2, ness_hurt1, ness_hurt2, ness_fsmashLand, ness_flashProjectile, ness_flashExplode, ness_fireShoot, ness_finalSmash, ness_entrance2, ness_entrance1, ness_death2, ness_death1, ness_batSwing, ness_attackU, ness_attackF, ness_attackD, ness_grunt4, ness_grunt3, ness_grunt2, ness_grunt1, ness_theme, smaash_hit, ness_pkThunder2, ness_dizzy, ness_win1, ness_SMAAAASH_swing));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"ness",
                "displayName":"Ness",
                "linkage_id":"nessbase",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"ness_head",
                "seriesIcon":"mother_symbol1",
                "width":20,
                "height":40,
                "revivalEffect":null,
                "jumpSpeed":12.75,
                "jumpSpeedMidair":11,
                "jumpStartup":2,
                "shortHopSpeed":6.375,
                "max_jumpSpeed":8,
                "midAirJumpConstant":11,
                "midAirJumpConstantDelay":1,
                "dodgeSpeed":5.8,
                "gravity":1.07,
                "weight1":94,
                "power":"ness",
                "norm_xSpeed":4,
                "max_xSpeed":8.9,
                "max_ySpeed":10,
                "fastFallSpeed":13,
                "accel_start":0.1,
                "accel_start_dash":1.07154,
                "accel_rate":1,
                "accel_rate_air":0.7,
                "decel_rate":-1.18,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":20,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_delay":12,
                "getup_roll_delay":0,
                "itemScaleRatio":0.91,
                "special_type":1,
                "normalStats_id":"ness",
                "specialStats_id":null,
                "sounds":{
                    "jump":"ness_jump",
                    "jump_midair":null,
                    "hurt":"ness_lift",
                    "hurt2":"ness_hurt2",
                    "hurtBad":"ness_hurtBad1",
                    "hurtBad2":"ness_hurtBad2",
                    "dead":"ness_death1",
                    "dead2":"ness_death2",
                    "pummel":"brawl_punch_s",
                    "screenko":"ness_hurtBad2",
                    "starko":"ness_starKO",
                    "ledge_grab":null,
                    "winTheme":"NessVictory"
                },
                "hurtFrames":1,
                "grabDamage":2
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "combo_max":2,
                    "canFallOff":false,
                    "attackVoice1_id":"ness_grunt1",
                    "attackSound1_id":"brawl_swing_s",
                    "attackSound2_id":"brawl_swing_s",
                    "attackSound3_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":70,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_s"
                        },
                        "attackBox2":{
                            "damage":3,
                            "priority":1,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":70,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_s"
                        }
                    }
                },
                "a_up":{
                    "refreshRate":5,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ness_attackU",
                    "attackSound1_id":"ness_yoyoCharge",
                    "attackSound2_id":"ness_yoyo",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":4,
                            "chargedPriority":5,
                            "hitStun":5,
                            "hitLag":-1.34,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":90,
                            "power":20,
                            "kbConstant":15,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":35,
                            "kbConstant":126,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_forward":{
                    "xSpeedDecay":1,
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackSound1_id":"ness_psi2",
                    "attackSound2_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":4,
                            "effect_id":"effect_hit1",
                            "direction":40,
                            "power":64,
                            "kbConstant":45,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":43,
                            "power":12,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forwardsmash":{
                    "refreshRate":150,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ness_attackF",
                    "attackSound1_id":"ness_batSwing",
                    "attackSound2_id":"ness_SMAAAASH_swing",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":0,
                            "chargedPriority":6,
                            "hitStun":5,
                            "selfHitStun":4,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"ness_fsmashLand"
                        }}
                },
                "a_down":{
                    "refreshRate":5,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ness_attackD",
                    "attackSound1_id":"ness_yoyoCharge",
                    "attackSound2_id":"ness_yoyo",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":4,
                            "chargedPriority":5,
                            "hitStun":5,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":90,
                            "power":20,
                            "kbConstant":30,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air":{
                    "doubleJumpCancel":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":100,
                    "air_ease":11,
                    "allowControl":true,
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":52,
                            "power":20,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_air_up":{
                    "doubleJumpCancel":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":5,
                            "hitStun":2,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":84,
                            "power":30,
                            "kbConstant":120,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_air_forward":{
                    "doubleJumpCancel":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":99,
                    "allowControl":true,
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackSound1_id":"ness_psi1",
                    "attackSound2_id":"brawl_swing_s",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":4,
                            "hitStun":1,
                            "hitLag":11,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":50,
                            "power":21,
                            "kbConstant":0,
                            "shock":true,
                            "effectSound":"brawl_magic_s"
                        }}
                },
                "a_air_backward":{
                    "doubleJumpCancel":true,
                    "allowControl":true,
                    "maintainSpeed":true,
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":0,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "shock":true,
                            "effect_id":"effect_heavyHit",
                            "direction":150,
                            "reversableAngle":false,
                            "power":20,
                            "kbConstant":100,
                            "camShake":7,
                            "effectSound":"brawl_magic_xl"
                        }}
                },
                "a_air_down":{
                    "refreshRate":150,
                    "doubleJumpCancel":true,
                    "allowControl":true,
                    "maintainSpeed":true,
                    "canUseInAir":true,
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":90,
                            "kbConstant":70,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "b":{
                    "conserveJumpConstant":false,
                    "air_ease":3,
                    "chargetime_max":70,
                    "forceUseAtMaxCharge":true,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "attackVoice1_id":"ness_pkFlash",
                    "attackSound1_id":"ness_flashProjectile",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":1,
                            "selfHitStun":2,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "conserveJumpConstant":false,
                    "air_ease":3,
                    "chargetime_max":70,
                    "forceUseAtMaxCharge":true,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "attackVoice1_id":"ness_pkFlash",
                    "attackSound1_id":"ness_flashProjectile",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":1,
                            "selfHitStun":2,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "refreshRate":100,
                    "resetMovement":true,
                    "isLongRangeMove":true,
                    "cancelWhenAirborne":false,
                    "conserveJumpConstant":false,
                    "air_ease":2,
                    "isRecoveryMove":true,
                    "attackVoice1_id":"ness_pkThunder",
                    "attackVoice2_id":"ness_pkThunder2",
                    "attackSound1_id":"ness_thunder",
                    "attackBoxes":{"attackBox":{
                            "damage":25,
                            "shock":true,
                            "priority":7,
                            "hitStun":6,
                            "selfHitStun":4,
                            "effect_id":"effect_firehit1",
                            "direction":30,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":"brawl_zap_l"
                        }}
                },
                "b_up_air":{
                    "refreshRate":100,
                    "resetMovement":true,
                    "conserveJumpConstant":false,
                    "cancelWhenAirborne":false,
                    "air_ease":2,
                    "isRecoveryMove":true,
                    "attackVoice1_id":"ness_pkThunder",
                    "attackVoice2_id":"ness_pkThunder2",
                    "attackSound1_id":"ness_thunder",
                    "attackBoxes":{"attackBox":{
                            "damage":25,
                            "shock":true,
                            "priority":7,
                            "hitStun":6,
                            "selfHitStun":4,
                            "effect_id":"effect_firehit1",
                            "direction":30,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":"brawl_zap_l"
                        }}
                },
                "b_forward":{
                    "attackDelay":15,
                    "isLongRangeMove":true,
                    "doubleJumpCancel":true,
                    "attackVoice1_id":"ness_pkFire",
                    "attackSound1_id":"ness_fireShoot",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":1,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"sw_bigscratch"
                        }}
                },
                "b_forward_air":{
                    "doubleJumpCancel":true,
                    "conserveJumpConstant":false,
                    "attackVoice1_id":"ness_pkFire",
                    "attackSound1_id":"ness_fireShoot",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":1,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"sw_bigscratch"
                        }}
                },
                "b_down":{
                    "jumpCancelAttack":true,
                    "air_ease":3,
                    "combo_max":999,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "allowFastFall":false,
                    "attackSound1_id":"ness_magnetLoop",
                    "attackSound2_id":"ness_magnetAbsorb",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":-1,
                            "sdiDistance":1.5,
                            "hitStun":2,
                            "hitLag":20,
                            "selfHitStun":2,
                            "direction":80,
                            "power":60,
                            "kbConstant":75,
                            "shock":true,
                            "effectSound":"brawl_magic_m"
                        }}
                },
                "b_down_air":{
                    "jumpCancelAttack":true,
                    "doubleJumpCancelAttack":true,
                    "conserveJumpConstant":false,
                    "air_ease":3,
                    "combo_max":999,
                    "holdRepeat":true,
                    "allowDoubleJump":true,
                    "attackSound1_id":"ness_magnetLoop",
                    "attackSound2_id":"ness_magnetAbsorb",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":-1,
                            "sdiDistance":1.5,
                            "hitStun":2,
                            "hitLag":-5,
                            "selfHitStun":2,
                            "direction":80,
                            "power":60,
                            "kbConstant":75,
                            "shock":true,
                            "effectSound":"brawl_magic_m"
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackVoice5_id":"ness_throw",
                    "attackSound1_id":"ness_psi2",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":-1,
                            "hitStun":0,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "direction":83,
                            "power":50,
                            "kbConstant":83,
                            "shock":true,
                            "bypassNonGrabbed":true,
                            "effectSound":"ness_jumpSound"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackVoice5_id":"ness_throw",
                    "attackSound1_id":"ness_psi2",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":-1,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":39,
                            "power":85,
                            "kbConstant":20,
                            "bypassNonGrabbed":true,
                            "effectSound":"ness_jumpSound"
                        }}
                },
                "throw_back":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackVoice5_id":"ness_throw",
                    "attackSound1_id":"ness_psi3",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":-1,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":140,
                            "reversableAngle":false,
                            "power":55,
                            "kbConstant":115,
                            "shock":true,
                            "bypassNonGrabbed":true,
                            "effectSound":"ness_jumpSound"
                        }}
                },
                "throw_down":{
                    "refreshRate":5,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackVoice5_id":"ness_throw",
                    "attackSound1_id":"ness_fireShoot",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "hasEffect":false,
                            "priority":-1,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_firehit1",
                            "direction":270,
                            "reversableAngle":false,
                            "power":0,
                            "kbConstant":60,
                            "burn":true,
                            "bypassNonGrabbed":true,
                            "meteorBounce":false,
                            "effectSound":"fire"
                        }}
                },
                "crouch_attack":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":0,
                            "hitLag":-1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":30,
                            "power":15,
                            "kbConstant":20,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":0,
                            "hitLag":20,
                            "weightKB":110,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":30,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "attackVoice1_id":"ness_grunt1",
                    "attackVoice2_id":"ness_grunt2",
                    "attackVoice3_id":"ness_grunt3",
                    "attackVoice4_id":"ness_grunt4",
                    "attackSound1_id":"brawl_swing_s",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":1,
                            "direction":40,
                            "power":69,
                            "kbConstant":57,
                            "effectSound":null
                        }}
                },
                "kirby":{
                    "conserveJumpConstant":false,
                    "air_ease":3,
                    "chargetime_max":70,
                    "forceUseAtMaxCharge":true,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "attackVoice1_id":"ness_pkFlash",
                    "attackSound1_id":"ness_flashProjectile",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":1,
                            "selfHitStun":2,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "conserveJumpConstant":false,
                    "air_ease":3,
                    "chargetime_max":90,
                    "holdRepeat":true,
                    "maintainSpeed":true,
                    "attackVoice1_id":"kirby_ness",
                    "attackSound1_id":"ness_flashProjectile",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":1,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"sw_bigscratch"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"ichigo_bankai",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":0,
                            "power":2,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object = {
                "ness_pkflash":{
                    "linkage_id":"ness_pkflashproj",
                    "width":45,
                    "height":45,
                    "time_max":200,
                    "xspeed":0.5,
                    "yspeed":-8,
                    "influenceXMovement":3.5,
                    "influenceYMovement":0,
                    "influenceXFactor":0.1,
                    "influenceYFactor":0,
                    "gravity":1,
                    "maxgravity":-0.8,
                    "rideGround":false,
                    "yoffset":-40,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "damage":30,
                                "priority":5,
                                "hitStun":14,
                                "selfHitStun":3,
                                "effect_id":"effect_hit1",
                                "direction":58,
                                "power":59,
                                "kbConstant":79,
                                "shock":true,
                                "poisonInterval":0,
                                "poisonLength":0,
                                "effectSound":"brawl_magic_xl"
                            }}}
                },
                "ness_pkthunder":{
                    "linkage_id":"ness_pkthunderproj",
                    "width":20,
                    "height":20,
                    "time_max":70,
                    "trailEffect":"ness_pkthundertrail",
                    "trailEffectInterval":2,
                    "trailEffectRotate":true,
                    "xspeed":9,
                    "calcAngle":true,
                    "controlDirection":90,
                    "rocketSpeed":24,
                    "rocketRotation":true,
                    "yoffset":-40,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":8,
                                "priority":3,
                                "hitStun":3,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "effect_id":"effect_hit1",
                                "direction":55,
                                "power":70,
                                "kbConstant":20,
                                "shock":true,
                                "effectSound":"brawl_zap_m"
                            }}}
                },
                "ness_pkfire":{
                    "linkage_id":"ness_pkfireproj",
                    "width":20,
                    "height":20,
                    "time_max":8,
                    "xspeed":16,
                    "rideGround":false,
                    "xoffset":34,
                    "yoffset":-9,
                    "attack_idle":{
                        "refreshRate":5,
                        "attackBoxes":{"attackBox":{
                                "damage":2,
                                "priority":5,
                                "sdiDistance":1.6,
                                "hitStun":3,
                                "selfHitStun":0,
                                "effect_id":null,
                                "direction":90,
                                "power":5,
                                "kbConstant":10,
                                "burn":true,
                                "effectSound":"brawl_fire_m"
                            }}
                    }
                },
                "ness_pkfire_air":{
                    "linkage_id":"ness_pkfireproj_air",
                    "width":20,
                    "height":20,
                    "time_max":8,
                    "xspeed":11,
                    "yspeed":11,
                    "gravity":0.01,
                    "xoffset":25,
                    "yoffset":5,
                    "attack_idle":{
                        "refreshRate":5,
                        "attackBoxes":{"attackBox":{
                                "damage":2,
                                "priority":5,
                                "sdiDistance":1.6,
                                "hitStun":3,
                                "selfHitStun":0,
                                "effect_id":null,
                                "direction":90,
                                "power":5,
                                "kbConstant":10,
                                "burn":true,
                                "effectSound":"brawl_fire_m"
                            }}
                    }
                },
                "ness_starstorm":{
                    "linkage_id":"starstormeteor",
                    "time_max":300,
                    "trailEffectInterval":0,
                    "ghost":true,
                    "rotate":true,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "limit":6,
                    "surviveDeathBounds":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":20,
                                "priority":-1,
                                "hitStun":1,
                                "selfHitStun":0,
                                "effect_id":"effect_hit3",
                                "direction":55,
                                "power":60,
                                "kbConstant":75,
                                "bypassShield":true,
                                "effectSound":"ssb_hit1"
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("ness");
        }

        public function getGUID():String
        {
            return ("4e1cd2be-4e9d-4fae-8fb9-d81ed2ba93d9");
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package ness_fla

