// Decompiled by AS3 Sorcerer 6.20
// www.as3sorcerer.com

//megaman_fla.MainTimeline

package megaman_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        public function getAudio():Array
        {
            return (new Array(bhb1, bhb2, explodehit3, fair_sfx, megaJumpSound, mmvictory, megaallright, megahurt, megajump1, megajump2, megaman_blast, megaman_blast2, megaman_bomb, megaman_dash, megaman_dead, megaman_explosion, megaman_finalsmash, megaman_hit, megaman_laser, megaman_letsdoit, megaman_pulse, megaman_shoot, megaman_switch, megaman_warp, megaman_zap, megaman_zap2, megaman_zap3, midjump, mmtaunt2, mm_shield, bair_sfx, megaman_water2, megaman_water3, wheelcutter, mm3_land, mm_spin, mm_fsmash_shoot, mm_guts_throw, mm_fire2, mm_missile, mm_detonate, mm_select));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"megaman",
                "displayName":"Mega%20Man",
                "linkage_id":"megaman",
                "linkage_id2":null,
                "linkage_id_special":"megaman_special",
                "thumbnail":"megaman_head",
                "seriesIcon":"mmicon",
                "width":38,
                "height":53,
                "revivalEffect":null,
                "jumpSpeed":15,
                "jumpSpeedMidair":14,
                "jumpStartup":2,
                "shortHopSpeed":8,
                "max_jumpSpeed":8.45,
                "dodgeSpeed":8,
                "gravity":1.27,
                "weight1":104,
                "weight2":0,
                "power":"megaman",
                "norm_xSpeed":5.5,
                "max_xSpeed":8.8,
                "max_ySpeed":13.1,
                "fastFallSpeed":15.5,
                "accel_start":0.59,
                "accel_start_dash":1.154,
                "accel_rate":1,
                "accel_rate_air":0.7,
                "decel_rate":-1.01,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":60,
                "tetherGrab":false,
                "roll_speed":25,
                "roll_delay":8,
                "getup_roll_delay":0,
                "itemScaleRatio":0.769230769230769,
                "special_type":0,
                "normalStats_id":"megaman",
                "specialStats_id":"megaman_special",
                "sounds":{
                    "jump":null,
                    "jump_midair":null,
                    "hurt":"megaman_hit",
                    "hurt2":null,
                    "hurtBad":"megaman_hit",
                    "hurtBad2":null,
                    "dead":"megaman_dead",
                    "dead2":null,
                    "pummel":"brawl_punch_m",
                    "screenko":null,
                    "starko":null,
                    "ledge_grab":null,
                    "winTheme":"MegamanVictory"
                },
                "hurtFrames":2,
                "grabDamage":2,
                "fs_time_limit":600
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":100,
                    "combo_max":2,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "reenableTimer":18,
                    "attackSound1_id":"brawl_swing_s",
                    "attackSound2_id":"brawl_swing_s",
                    "attackSound3_id":"brawl_swing_l",
                    "attackSound4_id":"megaman_zap2",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":60,
                            "power":20,
                            "kbConstant":60,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "a_up":{
                    "cancelWhenAirborne":false,
                    "refreshRate":1,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"megaman_blast2",
                    "attackBoxes":{"attackBox":{
                            "ignoreChargeDamage":true,
                            "damage":1,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":225,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"sw_minihit"
                        }}
                },
                "a_up_tilt":{
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_m",
                    "cpuAttackQueue":"throw_up;throw_down;a_up_tilt;a_air;a_air_up;",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":6,
                            "selfHitStun":4,
                            "effect_id":"effect_heavyHit",
                            "direction":100,
                            "power":70,
                            "kbConstant":127,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_forward":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackSound1_id":"megaman_dash",
                    "cpuAttackQueue":"a_air;a_air_backward;a_air_forward;a_forwardsmash;",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":65,
                            "power":30,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forward_tilt":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackSound1_id":"fire",
                    "attackSound2_id":"sw_brawl_swing_M",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_firehit1",
                            "direction":38,
                            "power":45,
                            "kbConstant":92,
                            "burn":true,
                            "effectSound":"sw_scratch"
                        }}
                },
                "a_forwardsmash":{
                    "attackDelay":2,
                    "xSpeedDecay":-1,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"megaman_shoot",
                    "attackSound2_id":"mm_fsmash_shoot",
                    "attackBoxes":{"attackBox":{
                            "damage":16,
                            "priority":4,
                            "chargedPriority":6,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_firehit1",
                            "direction":30,
                            "power":30,
                            "kbConstant":98,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"swing",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":5,
                            "hitStun":4,
                            "selfHitStun":4,
                            "effect_id":"effect_hit1",
                            "direction":35,
                            "power":67,
                            "kbConstant":99,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":3,
                    "allowControl":true,
                    "attackSound1_id":"brawl_swing_s",
                    "cpuAttackQueue":"a_air;a_air_up;a_air_forward;",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":94,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackSound1_id":"megaman_zap3",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":-1,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"punch2"
                        }}
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":3,
                    "allowControl":true,
                    "attackSound1_id":"fair_sfx",
                    "cpuAttackQueue":"a_air_forward;a_forward_tilt;throw_forward;throw_down;throw_up;b_forward;",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":5,
                            "sdiDistance":0.5,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":20,
                            "kbConstant":60,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "xSpeedDecayAir":-1,
                    "allowControl":true,
                    "attackSound1_id":"bair_sfx",
                    "attackSound2_id":"brawl_swing_s",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":5,
                            "effect_id":"effect_firehit1",
                            "direction":35,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"mm_fire2"
                        }}
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackSound1_id":"brawl_swing_s",
                    "attackSound2_id":"megaman_laser",
                    "cpuAttackQueue":"a_air;a_air_up;a_air_backward;",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":11,
                            "priority":-1,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":35,
                            "kbConstant":105,
                            "effectSound":"brawl_zap_m"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":-1,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":75,
                            "power":35,
                            "kbConstant":75,
                            "effectSound":"brawl_zap_m"
                        }
                    }
                },
                "b":{
                    "cancelWhenAirborne":false,
                    "isLongRangeMove":true,
                    "xSpeedCap":9,
                    "chargetime_max":45,
                    "holdRepeat":true,
                    "jumpFrame":"f1",
                    "allowJump":true,
                    "allowRun":true,
                    "allowTurn":true,
                    "allowDoubleJump":true,
                    "linkFrames":true,
                    "reenableTimer":3,
                    "attackSound1_id":null,
                    "attackSound2_id":"megaman_shoot",
                    "attackSound3_id":"megaman_blast",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":-0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":"punch2"
                        }}
                },
                "b_air":{
                    "xSpeedCap":9,
                    "isLongRangeMove":true,
                    "allowControl":true,
                    "chargetime_max":45,
                    "holdRepeat":true,
                    "jumpFrame":"f1",
                    "allowJump":true,
                    "allowTurn":true,
                    "allowDoubleJump":true,
                    "linkFrames":true,
                    "reenableTimer":3,
                    "attackSound1_id":null,
                    "attackSound2_id":"megaman_shoot",
                    "attackSound3_id":"megaman_blast",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":"punch2"
                        }}
                },
                "b_up":{
                    "cancelWhenAirborne":false,
                    "airCancel":true,
                    "air_ease":5,
                    "xSpeedCap":5.94,
                    "allowControl":true,
                    "hitEffect":"beat_flyaway",
                    "disableForCPU":true,
                    "reenableTimer":99999,
                    "disableJump":true,
                    "attackSound1_id":"megaman_pulse",
                    "attackSound2_id":"megaman_shoot",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":20,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_up_air":{
                    "cancelWhenAirborne":false,
                    "airCancel":true,
                    "air_ease":5,
                    "xSpeedCap":5.94,
                    "allowControl":true,
                    "hitEffect":"beat_flyaway",
                    "isRecoveryMove":true,
                    "disableForCPU":true,
                    "reenableTimer":99999,
                    "disableJump":true,
                    "attackSound1_id":"megaman_pulse",
                    "attackSound2_id":"megaman_shoot",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":20,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"sw_scratch"
                        }}
                },
                "b_forward":{
                    "resetMovement":true,
                    "combo_max":999,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "attackSound1_id":"mm_shield",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "priority":7,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":45,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":105,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "allowTurboInterrupt":false,
                            "hasEffect":false,
                            "hitStun":0,
                            "selfHitStun":0,
                            "reverse_projectile":true
                        }
                    }
                },
                "b_forward_air":{
                    "combo_max":999,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "attackSound1_id":"mm_shield",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "priority":7,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":45,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":105,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "allowTurboInterrupt":false,
                            "hasEffect":false,
                            "hitStun":0,
                            "selfHitStun":0,
                            "reverse_projectile":true
                        }
                    }
                },
                "b_down":{
                    "resetMovement":true,
                    "air_ease":0,
                    "jumpFrame":"switch5",
                    "allowFastFall":false,
                    "attackSound1_id":"megaman_switch",
                    "attackSound2_id":"mm_select",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":"kick"
                        }}
                },
                "b_down_air":{
                    "resetMovement":true,
                    "air_ease":0,
                    "jumpFrame":"switch5",
                    "allowFastFall":false,
                    "reenableTimer":80,
                    "attackSound1_id":"megaman_switch",
                    "attackSound2_id":"mm_select",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":"kick"
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackSound1_id":null,
                    "attackSound2_id":"brawl_swing_m",
                    "cpuAttackQueue":"a_up;a_up_tilt;throw_up;a_up_tilt;throw_down;a_air_backward",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":2,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":100,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":25,
                            "bypassNonGrabbed":true,
                            "effectSound":"sw_minihit"
                        }}
                },
                "throw_forward":{
                    "refreshRate":10,
                    "canFallOff":false,
                    "attackSound1_id":"megaman_blast",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "hasEffect":true,
                            "priority":0,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":100,
                            "shock":true,
                            "bypassNonGrabbed":true,
                            "effectSound":"smallshock"
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackSound1_id":"megaman_explosion",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":150,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":10,
                            "effectSound":"punch2"
                        }}
                },
                "throw_down":{
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_m",
                    "cpuAttackQueue":"b;b_air;a_air;a_air_forward;a_forward;",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "forceTumbleFall":true,
                            "meteorBounce":false,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":1,
                            "hitLag":3,
                            "effect_id":"effect_heavyHit",
                            "direction":60,
                            "power":40,
                            "kbConstant":0,
                            "bypassNonGrabbed":true,
                            "effectSound":"megaman_water2"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_l",
                    "cpuAttackQueue":"a_up_tilt;a_forward_tilt;a_forwardsmash;a_air;a_air_forward;",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":6,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":50,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "cancelWhenAirborne":false,
                    "maintainSpeed":true,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "getup_attack":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackSound1_id":"megaman_blast2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_firehit1",
                            "direction":45,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"brawl_zap_s"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_firehit1",
                            "direction":45,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"brawl_zap_s"
                        }
                    }
                },
                "kirby":{
                    "cancelWhenAirborne":false,
                    "isLongRangeMove":true,
                    "xSpeedCap":4.55,
                    "chargetime_max":45,
                    "holdRepeat":true,
                    "allowJump":true,
                    "allowRun":true,
                    "allowTurn":true,
                    "allowDoubleJump":true,
                    "reenableTimer":6,
                    "attackSound1_id":null,
                    "attackSound2_id":"megaman_shoot",
                    "attackSound3_id":"megaman_blast",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":"punch2"
                        }}
                },
                "kirby_air":{
                    "xSpeedCap":4.55,
                    "isLongRangeMove":true,
                    "chargetime_max":45,
                    "holdRepeat":true,
                    "allowJump":true,
                    "allowRun":true,
                    "allowTurn":true,
                    "allowDoubleJump":true,
                    "reenableTimer":6,
                    "attackSound1_id":null,
                    "attackSound2_id":"megaman_shoot",
                    "attackSound3_id":"megaman_blast",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":"punch2"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"megaman_letsdoit",
                    "attackSound1_id":"megaman_finalsmash",
                    "attackSound2_id":"mario_powerup2",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":7,
                            "hitStun":5,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":60,
                            "shock":true,
                            "effectSound":"brawl_zap_l"
                        }}
                },
                "switch_rollingcutter":{
                    "attackDelay":10,
                    "allowControl":true,
                    "canFallOff":false,
                    "jumpFrame":"rolling",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "switchBlock":{
                    "parentAttack":"b",
                    "linkFrames":true,
                    "attackDelay":7,
                    "isLongRangeMove":true,
                    "allowControl":true,
                    "allowControlGround":false,
                    "canFallOff":false,
                    "attackSound1_id":"mm_guts_throw",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":null
                        }}
                },
                "switchBlock_air":{
                    "parentAttack":"b",
                    "linkFrames":true,
                    "attackDelay":7,
                    "isLongRangeMove":true,
                    "allowControl":true,
                    "allowControlGround":false,
                    "canFallOff":false,
                    "attackSound1_id":"mm_guts_throw",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":null
                        }}
                },
                "switchBomb":{
                    "parentAttack":"b",
                    "linkFrames":true,
                    "allowControl":true,
                    "isLongRangeMove":true,
                    "allowControlGround":false,
                    "canFallOff":false,
                    "attackSound1_id":"megaman_shoot",
                    "attackSound2_id":"mm_missile",
                    "attackSound3_id":"mm_detonate",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":-1,
                            "selfHitStun":0,
                            "direction":80,
                            "power":50,
                            "kbConstant":60,
                            "effectSound":null
                        }}
                },
                "switchBomb_air":{
                    "parentAttack":"b",
                    "linkFrames":true,
                    "allowControl":true,
                    "isLongRangeMove":true,
                    "allowControlGround":false,
                    "canFallOff":false,
                    "attackSound1_id":"megaman_shoot",
                    "attackSound2_id":"mm_missile",
                    "attackSound3_id":"mm_detonate",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":-1,
                            "selfHitStun":0,
                            "direction":80,
                            "power":50,
                            "kbConstant":60,
                            "effectSound":null
                        }}
                },
                "switchBHB":{
                    "parentAttack":"b",
                    "linkFrames":true,
                    "allowControl":true,
                    "isLongRangeMove":true,
                    "allowControlGround":false,
                    "combo_max":999,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":100,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "switchBHB_air":{
                    "parentAttack":"b",
                    "linkFrames":true,
                    "allowControl":true,
                    "isLongRangeMove":true,
                    "allowControlGround":false,
                    "combo_max":999,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":100,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "switchBlade":{
                    "parentAttack":"b",
                    "linkFrames":true,
                    "refreshRate":4,
                    "isLongRangeMove":true,
                    "attackDelay":5,
                    "allowControl":true,
                    "allowControlGround":false,
                    "combo_max":9999,
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":3,
                            "hitStun":1,
                            "hitLag":-1,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":20,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "switchBlade_air":{
                    "parentAttack":"b",
                    "linkFrames":true,
                    "refreshRate":4,
                    "isLongRangeMove":true,
                    "attackDelay":5,
                    "allowControl":true,
                    "allowControlGround":false,
                    "combo_max":9999,
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":3,
                            "hitStun":1,
                            "hitLag":-1,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":20,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "switchBuster":{
                    "parentAttack":"b",
                    "linkFrames":true,
                    "xSpeedCap":4.55,
                    "isLongRangeMove":true,
                    "allowControl":true,
                    "chargetime_max":45,
                    "holdRepeat":true,
                    "allowJump":true,
                    "allowRun":true,
                    "allowTurn":true,
                    "allowDoubleJump":true,
                    "linkFrames":true,
                    "reenableTimer":6,
                    "attackSound1_id":null,
                    "attackSound2_id":"megaman_shoot",
                    "attackSound3_id":"megaman_blast",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":0,
                            "direction":95,
                            "power":45,
                            "kbConstant":40,
                            "effectSound":"punch2"
                        }}
                },
                "switchBuster_air":{
                    "parentAttack":"b",
                    "linkFrames":true,
                    "xSpeedCap":9,
                    "isLongRangeMove":true,
                    "allowControl":true,
                    "chargetime_max":45,
                    "holdRepeat":true,
                    "allowJump":true,
                    "allowTurn":true,
                    "allowDoubleJump":true,
                    "linkFrames":true,
                    "reenableTimer":3,
                    "attackSound1_id":null,
                    "attackSound2_id":"megaman_shoot",
                    "attackSound3_id":"megaman_blast",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":"punch2"
                        }}
                },
                "switch6":{
                    "cancelWhenAirborne":false,
                    "isLongRangeMove":true,
                    "xSpeedCap":4.55,
                    "allowControl":true,
                    "chargetime_max":45,
                    "holdRepeat":true,
                    "jumpFrame":"f1",
                    "allowJump":true,
                    "allowRun":true,
                    "allowTurn":true,
                    "allowDoubleJump":true,
                    "linkFrames":true,
                    "reenableTimer":6,
                    "attackSound1_id":null,
                    "attackSound2_id":"megaman_shoot",
                    "attackSound3_id":"megaman_blast",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":"punch2"
                        }}
                }
            };
            var _local_4:Object = {
                "megaman_buster1":{
                    "linkage_id":"megaman_bullet",
                    "width":10,
                    "height":9,
                    "time_max":60,
                    "xspeed":10,
                    "ghost":false,
                    "xoffset":17,
                    "yoffset":-28,
                    "limit":10,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "hasEffect":false,
                                "damage":2,
                                "priority":-1,
                                "hitStun":2,
                                "selfHitStun":0,
                                "effect_id":"effect_heavyHit",
                                "direction":0,
                                "power":0,
                                "kbConstant":0,
                                "effectSound":null
                            }}}
                },
                "megaman_buster2":{
                    "linkage_id":"megaman_bullet2",
                    "width":20,
                    "height":20,
                    "time_max":75,
                    "xspeed":11,
                    "ghost":false,
                    "xoffset":19,
                    "yoffset":-7.25,
                    "limit":3,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "damage":7,
                                "reversableAngle":false,
                                "priority":1,
                                "hitStun":2,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "effect_id":"effect_heavyHit",
                                "direction":50,
                                "power":25,
                                "kbConstant":70,
                                "effectSound":"brawl_zap_s"
                            }}}
                },
                "megaman_buster3":{
                    "linkage_id":"megaman_bullet3",
                    "width":20,
                    "height":20,
                    "time_max":75,
                    "xspeed":12,
                    "ghost":false,
                    "xoffset":29,
                    "yoffset":-7.25,
                    "limit":3,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "damage":12,
                                "priority":2,
                                "hitStun":3,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "effect_id":"effect_heavyHit",
                                "direction":50,
                                "power":25,
                                "kbConstant":70,
                                "effectSound":"brawl_zap_m"
                            }}}
                },
                "megaman_buster_full":{
                    "linkage_id":"megaman_blastshot",
                    "width":35,
                    "height":19,
                    "time_max":75,
                    "xspeed":15,
                    "ghost":false,
                    "xoffset":19,
                    "yoffset":-7.25,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "damage":15,
                                "priority":6,
                                "hitStun":8,
                                "selfHitStun":0,
                                "effect_id":"effect_hit3",
                                "direction":40,
                                "power":60,
                                "kbConstant":100,
                                "shock":true,
                                "effectSound":"brawl_zap_l"
                            }}}
                },
                "megaman_gutsman":{
                    "linkage_id":"megaman_gutsblock",
                    "width":32,
                    "height":32,
                    "time_max":90,
                    "xspeed":12.5,
                    "yspeed":-16,
                    "gravity":2.5,
                    "maxgravity":21,
                    "xoffset":10,
                    "yoffset":-50,
                    "canBeAbsorbed":false,
                    "limit":2,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":9,
                                "priority":4,
                                "hitStun":3,
                                "selfHitStun":0,
                                "direction":45,
                                "power":60,
                                "kbConstant":70,
                                "effectSound":"megaman_explosion"
                            }}}
                },
                "megaman_crashman":{
                    "linkage_id":"megaman_crashbomb",
                    "width":16,
                    "height":15,
                    "time_max":200,
                    "xspeed":16,
                    "xoffset":23,
                    "yoffset":-8,
                    "canBeAbsorbed":false,
                    "sticky":true,
                    "latch":true,
                    "limit":1,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "hasEffect":false,
                                "priority":-1,
                                "hitStun":2,
                                "selfHitStun":0,
                                "direction":38,
                                "power":0,
                                "kbConstant":0,
                                "effectSound":null
                            }}}
                },
                "megaman_galaxyman":{
                    "linkage_id":"megaman_blackholebomb",
                    "width":15,
                    "height":15,
                    "time_max":999,
                    "xspeed":6,
                    "ghost":true,
                    "influenceYMovement":5,
                    "influenceYFactor":0.5,
                    "maxgravity":0.2,
                    "xoffset":23,
                    "yoffset":-7,
                    "sticky":true,
                    "limit":1,
                    "limitOverwrite":false,
                    "lockSize":true,
                    "attack_idle":{
                        "refreshRate":999,
                        "attackBoxes":{"attackBox":{
                                "damage":0,
                                "reversableAngle":false,
                                "hasEffect":true,
                                "priority":7,
                                "hitStun":5,
                                "hitLag":0,
                                "selfHitStun":0,
                                "direction":90,
                                "power":0,
                                "kbConstant":0,
                                "effectSound":"mm_fire2"
                            }}
                    }
                },
                "megaman_nitroman":{
                    "linkage_id":"megaman_metalblade",
                    "width":15,
                    "height":15,
                    "time_max":45,
                    "canFallOff":true,
                    "xspeed":10,
                    "yspeed":-3,
                    "gravity":1,
                    "maxgravity":20,
                    "bounce_decay":0,
                    "xoffset":25,
                    "yoffset":-15,
                    "canBeAbsorbed":false,
                    "limit":3,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":6,
                                "shieldDamage":16,
                                "priority":4,
                                "hitStun":-1.2,
                                "selfHitStun":1,
                                "effect_id":"effect_swordSlash",
                                "direction":92,
                                "power":68,
                                "kbConstant":80,
                                "effectSound":"sw_strongslash"
                            }}}
                },
                "megaman_hardknuckle":{
                    "linkage_id":"hardknuckle",
                    "time_max":21,
                    "xdecay":4,
                    "xspeed":21,
                    "xoffset":23,
                    "yoffset":-23,
                    "limit":1,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":16,
                                "priority":6,
                                "hitStun":5,
                                "selfHitStun":5,
                                "effect_id":"effect_hit1",
                                "direction":22,
                                "power":50,
                                "kbConstant":98,
                                "effectSound":"brawl_punch_l"
                            }}}
                },
                "megaman_iceslasher1":{
                    "linkage_id":"megaman_upairproj",
                    "width":10,
                    "height":10,
                    "time_max":45,
                    "yspeed":-11,
                    "ghost":true,
                    "rotate":true,
                    "xoffset":3.1,
                    "yoffset":-44.5,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":12,
                                "priority":2,
                                "hitStun":4,
                                "selfHitStun":0,
                                "effect_id":"effect_hit3",
                                "direction":-9,
                                "power":20,
                                "kbConstant":125,
                                "effectSound":"brawl_magic_s"
                            }}}
                },
                "megaman_iceslasher2":{
                    "linkage_id":"megaman_upairprojsplit",
                    "width":10,
                    "height":10,
                    "time_max":45,
                    "yspeed":-11,
                    "ghost":true,
                    "rotate":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":2,
                                "priority":1,
                                "hitStun":4,
                                "selfHitStun":0,
                                "effect_id":"effect_hit3",
                                "direction":-9,
                                "power":20,
                                "kbConstant":100,
                                "effectSound":"brawl_magic_s"
                            }}}
                },
                "megaman_napalmbomb":{
                    "linkage_id":"megaman_throwbomb",
                    "width":20,
                    "height":17,
                    "time_max":25,
                    "xspeed":-6.5,
                    "yspeed":-27,
                    "ghost":true,
                    "gravity":5,
                    "maxgravity":1,
                    "xoffset":-15,
                    "yoffset":-8,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "sticky":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":8,
                                "priority":0,
                                "hitStun":1,
                                "selfHitStun":0,
                                "effect_id":"effect_heavyHit",
                                "direction":45,
                                "power":60,
                                "kbConstant":100,
                                "effectSound":"bombexplode"
                            }}}
                },
                "megaman_cutter":{
                    "linkage_id":"megaman_rollingcutter",
                    "width":21,
                    "height":15,
                    "time_max":80,
                    "xdecay":1,
                    "xspeed":16,
                    "yspeed":8,
                    "gravity":2,
                    "maxgravity":0.4,
                    "xoffset":13,
                    "yoffset":-13,
                    "canBeAbsorbed":false,
                    "boomerang":true,
                    "limit":1,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":5,
                                "priority":1,
                                "hitStun":3,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "effect_id":"effect_swordSlash",
                                "direction":20,
                                "power":50,
                                "kbConstant":115,
                                "effectSound":null
                            }}}
                },
                "megaman_tornado":{
                    "linkage_id":"mm_tornado_proj",
                    "width":27,
                    "height":38,
                    "time_max":45,
                    "yspeed":-8,
                    "rotate":false,
                    "xoffset":6,
                    "yoffset":-44.5,
                    "attack_idle":{
                        "refreshRate":4,
                        "attackBoxes":{"attackBox":{
                                "damage":9,
                                "priority":-1,
                                "hitStun":1,
                                "selfHitStun":0,
                                "effect_id":"effect_hit3",
                                "direction":90,
                                "power":50,
                                "kbConstant":0,
                                "effectSound":"sw_brawl_hit_S"
                            }}
                    }
                },
                "megaman_sawblade":{
                    "linkage_id":"megaman_saw",
                    "width":28,
                    "height":28,
                    "time_max":60,
                    "xspeed":10,
                    "rotate":true,
                    "rideGround":false,
                    "xoffset":13,
                    "yoffset":-13,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":5,
                                "priority":1,
                                "hitStun":3,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "effect_id":"effect_swordSlash",
                                "direction":20,
                                "power":50,
                                "kbConstant":115,
                                "effectSound":null
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getChar2(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"megaman_special",
                "displayName":"Mega%20Man",
                "linkage_id":"megaman_special",
                "linkage_id2":null,
                "linkage_id_special":"megaman",
                "thumbnail":"megaman_head_special",
                "seriesIcon":null,
                "width":38,
                "height":53,
                "jumpSpeed":10,
                "jumpSpeedMidair":10,
                "shortHopSpeed":5,
                "max_jumpSpeed":8,
                "dodgeSpeed":10,
                "gravity":1.4,
                "weight1":104,
                "weight2":0,
                "power":"megaman",
                "norm_xSpeed":5.5,
                "max_xSpeed":8.8,
                "max_ySpeed":12,
                "fastFallSpeed":13,
                "accel_start":0.5,
                "accel_start_dash":1.154,
                "accel_rate":1,
                "accel_rate_air":0.7,
                "decel_rate":-1.01,
                "decel_rate_air":-0.15,
                "holdJump":true,
                "max_jump":99999999,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":16,
                "roll_delay":8,
                "getup_roll_delay":0,
                "itemScaleRatio":0.769230769230769,
                "special_type":0,
                "normalStats_id":"megaman",
                "specialStats_id":"megaman_special",
                "sounds":{
                    "jump":null,
                    "jump_midair":null,
                    "hurt":"megaman_hit",
                    "hurt2":null,
                    "hurtBad":"megaman_hit",
                    "hurtBad2":null,
                    "dead":"megaman_dead",
                    "dead2":null,
                    "pummel":null,
                    "screenko":null,
                    "starko":null,
                    "ledge_grab":null,
                    "winTheme":"MegamanVictory"
                },
                "hurtFrames":1,
                "canHoldItems":false,
                "canThrow":false,
                "canUseItems":false,
                "fs_time_limit":600
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "a_up":{
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "a_up_tilt":{
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "a_forward":{
                    "maintainSpeed":true,
                    "allowRun":true,
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "a_forward_tilt":{
                    "maintainSpeed":true,
                    "allowRun":true,
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "a_forwardsmash":{
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "a_down":{
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "a_air":{
                    "allowControl":true,
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "a_air_up":{
                    "allowControl":true,
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "a_air_forward":{
                    "allowControl":true,
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "a_air_backward":{
                    "allowControl":true,
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "a_air_down":{
                    "allowControl":true,
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "b":{
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "b_up_air":{
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "b_forward":{
                    "maintainSpeed":true,
                    "allowRun":true,
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "b_forward_air":{
                    "maintainSpeed":true,
                    "allowRun":true,
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "b_down":{
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "b_down_air":{
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "throw_up":{"attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":0,
                            "selfHitStun":0,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}},
                "throw_forward":{"attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":0,
                            "selfHitStun":0,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}},
                "throw_back":{"attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":0,
                            "selfHitStun":0,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}},
                "throw_down":{"attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":0,
                            "selfHitStun":0,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}},
                "crouch_attack":{
                    "attackSound1_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":14,
                            "effectSound":null
                        }}
                },
                "ledge_attack":{"attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":0,
                            "selfHitStun":0,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}},
                "getup_attack":{},
                "kirby":{"attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":0,
                            "selfHitStun":0,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}},
                "kirby_air":{"attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":0,
                            "selfHitStun":0,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}},
                "special":{
                    "resetMovement":true,
                    "invincible":true,
                    "canUseInAir":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":0,
                            "power":2,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object = {"megaman_special_proj":{
                    "linkage_id":"megaman_rushbullet",
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "width":20,
                    "height":10,
                    "time_max":90,
                    "xspeed":12,
                    "stale":false,
                    "xoffset":25,
                    "yoffset":-22,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":15,
                                "priority":7,
                                "hitStun":3,
                                "selfHitStun":0,
                                "effect_id":"effect_hit2",
                                "direction":45,
                                "power":23,
                                "kbConstant":71,
                                "effectSound":"brawl_bomb_s"
                            }}}
                }};
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("megaman");
        }

        public function getGUID():String
        {
            return ("716b3fa7-a83b-42fe-b781-3ac8f0063fd6");
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package megaman_fla

