// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//donkeykong_fla.MainTimeline

package donkeykong_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function getAudio():Array
        {
            return (new Array(dk_footstep, Barrel_jumped_over, arcade_dead, dkclap, clap, dkdash, dkfairwhif, dkjump1, dkjump2, dkland, dkslam, dkwhif, dkwin, dk_nspecial, dk_taunt2, dk_starko, groundpound, arcadeintro, arcade_jump, Level_intro, dk_entrance_sfx, dk_entrance_vfx, dk_uspecial, dk_nspecial_charging, brawl_dk_swing_H, brawl_dk_swing_M, brawl_dk_swing_S, arcade_tune, dk_grunt1, dk_grunt2, dk_grunt3, dk_grunt4, dk_smashF, dk_smashU, dk_smashD, dk_hurt1, dk_hurt2, dk_hurtBad1, dk_hurtBad2, dk_dizzy, dk_edgegrab, dk_tech, dk_death1, dk_death2, dk_spin));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"donkeykong",
                "displayName":"Donkey%20Kong",
                "linkage_id":"dkong",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"dkhead",
                "seriesIcon":"dkicon",
                "width":69,
                "height":75,
                "jumpSpeed":15.5,
                "jumpSpeedMidair":15.5,
                "jumpStartup":2,
                "shortHopSpeed":8.8,
                "max_jumpSpeed":8.5,
                "dodgeSpeed":9,
                "gravity":1.3,
                "weight1":114,
                "power":"dkong",
                "norm_xSpeed":4,
                "max_xSpeed":10,
                "max_ySpeed":16,
                "fastFallSpeed":19,
                "accel_start":1.2,
                "accel_start_dash":1.014,
                "accel_rate":1,
                "accel_rate_air":1.8,
                "decel_rate":-1.15,
                "decel_rate_air":-0.125,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_delay":8,
                "getup_roll_delay":0,
                "itemScaleRatio":0.740740740740741,
                "special_type":4,
                "normalStats_id":"donkeykong",
                "specialStats_id":null,
                "sounds":{
                    "jump":"dkjump1",
                    "jump_midair":"dkjump2",
                    "hurt":"dk_hurt1",
                    "hurt2":"dk_hurt2",
                    "hurtBad":"dk_hurtBad1",
                    "hurtBad2":"dk_hurtBad2",
                    "dead":"dk_death1",
                    "dead2":"dk_death2",
                    "pummel":"brawl_punch_m",
                    "screenko":"dk_hurt2",
                    "starko":"dk_starko",
                    "ledge_grab":"dk_edgegrab",
                    "winTheme":"DKVictory"
                },
                "hurtFrames":3,
                "shieldBreakPower":21,
                "grabDamage":3,
                "fs_time_limit":600
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":100,
                    "combo_max":1,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack2",
                    "attackVoice3_id":"ichigo_attack5",
                    "attackSound1_id":"brawl_dk_swing_S",
                    "attackSound2_id":"brawl_dk_swing_M",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":20,
                            "kbConstant":60,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"dk_smashU",
                    "attackSound1_id":"brawl_dk_swing_H",
                    "attackSound2_id":"dkclap",
                    "attackBoxes":{"attackBox":{
                            "damage":18,
                            "priority":6,
                            "hitStun":8,
                            "selfHitStun":6,
                            "camShake":14,
                            "effect_id":"effect_hit1",
                            "direction":90,
                            "power":42.8,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_up_tilt":{
                    "attackVoice1_id":"dk_grunt1",
                    "cpuAttackQueue":"a_air_up;a_air_down;a_up_tilt",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":"brawl_dk_swing_M",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":11,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "reversableAngle":false,
                            "power":45,
                            "kbConstant":105,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox2":{
                            "damage":11,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "reversableAngle":false,
                            "power":45,
                            "kbConstant":105,
                            "effectSound":"brawl_punch_m"
                        }
                    }
                },
                "a_forward":{
                    "xSpeedAccel":10,
                    "xSpeedAccelAir":10,
                    "xSpeedDecay":-1,
                    "xSpeedDecayAir":-1,
                    "heavyArmor":6,
                    "canFallOff":false,
                    "attackVoice1_id":"dk_grunt1",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":"dkdash",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":2,
                            "camShake":5,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "power":100,
                            "kbConstant":30,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forward_tilt":{
                    "attackVoice1_id":"dk_grunt1",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":"brawl_dk_swing_M",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":3,
                            "camShake":5,
                            "effect_id":"effect_lightHit",
                            "direction":33,
                            "power":30,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_forwardsmash":{
                    "refreshRate":100,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"dk_smashF",
                    "attackSound1_id":"brawl_dk_swing_H",
                    "attackSound2_id":"dkclap",
                    "attackBoxes":{"attackBox":{
                            "damage":20,
                            "priority":6,
                            "hitStun":8,
                            "hitLag":-1.1,
                            "selfHitStun":7,
                            "camShake":13,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":32.1,
                            "kbConstant":87.74,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"dk_smashD",
                    "attackSound1_id":"brawl_dk_swing_H",
                    "attackSound2_id":"dkslam",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":17,
                            "priority":6,
                            "hitStun":8,
                            "hitLag":-1.07,
                            "selfHitStun":6,
                            "camShake":12,
                            "effect_id":"effect_heavyHit",
                            "direction":115,
                            "power":37.5,
                            "kbConstant":107,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":17,
                            "priority":6,
                            "hitStun":8,
                            "hitLag":-1.07,
                            "selfHitStun":6,
                            "camShake":12,
                            "effect_id":"effect_heavyHit",
                            "direction":115,
                            "power":37.5,
                            "kbConstant":107,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"dk_grunt1",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":"brawl_dk_swing_M",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":42,
                            "power":35,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_s"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":4,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":42,
                            "power":35,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_s"
                        }
                    }
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "cpuAttackQueue":"a_air_up;a_air;a_air_forward;a_up_tilt;a_up",
                    "attackVoice1_id":"dk_grunt1",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":"brawl_dk_swing_M",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":4,
                            "hitLag":-1.12,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "power":32,
                            "kbConstant":70,
                            "effectSound":"whack"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":4,
                            "hitStun":4,
                            "hitLag":-1.12,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "power":32,
                            "kbConstant":70,
                            "effectSound":"whack"
                        }
                    }
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"dk_grunt1",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":"dkfairwhif",
                    "attackSound2_id":"brawl_dk_swing_H",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":5,
                            "hitStun":8,
                            "hitLag":-1.1,
                            "selfHitStun":5,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":21.4,
                            "kbConstant":127,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":5,
                            "hitStun":8,
                            "hitLag":-1.1,
                            "selfHitStun":5,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":21.4,
                            "kbConstant":127,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox3":{
                            "damage":12,
                            "priority":5,
                            "hitStun":8,
                            "hitLag":-1.1,
                            "selfHitStun":5,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":21.4,
                            "kbConstant":127,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "cpuAttackQueue":"a_air;a_air_backward",
                    "attackVoice1_id":"dk_grunt1",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":"brawl_dk_swing_M",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":150,
                            "reversableAngle":false,
                            "power":21.4,
                            "kbConstant":89,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":150,
                            "reversableAngle":false,
                            "power":21.4,
                            "kbConstant":89,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"dk_grunt1",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":"brawl_dk_swing_H",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":16,
                            "priority":6,
                            "hitStun":5,
                            "selfHitStun":3,
                            "camShake":4,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":38,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":16,
                            "priority":6,
                            "hitStun":5,
                            "selfHitStun":3,
                            "camShake":4,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":38,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "b":{
                    "linkCharge":"b_air",
                    "refreshRate":100,
                    "linkCharge":true,
                    "cancelWhenAirborne":false,
                    "allowControlGround":false,
                    "chargetime_max":72,
                    "charge_retain":true,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "customChargeGlow":"dk_chargebar",
                    "useChargeBar":false,
                    "attackVoice1_id":"dk_nspecial",
                    "attackSound1_id":"dk_spin",
                    "attackSound2_id":"brawl_dk_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":6,
                            "chargedPriority":7,
                            "hitStun":5,
                            "selfHitStun":5,
                            "camShake":4,
                            "effect_id":"effect_heavyHit",
                            "direction":25,
                            "power":15,
                            "kbConstant":70,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "b_air":{
                    "linkCharge":"b",
                    "refreshRate":100,
                    "linkCharge":true,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargetime_max":72,
                    "charge_retain":true,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "customChargeGlow":"dk_chargebar",
                    "useChargeBar":false,
                    "attackVoice1_id":"dk_nspecial",
                    "attackSound1_id":"dk_spin",
                    "attackSound2_id":"brawl_dk_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":6,
                            "chargedPriority":7,
                            "hitStun":5,
                            "selfHitStun":5,
                            "camShake":3,
                            "effect_id":"effect_heavyHit",
                            "direction":25,
                            "power":15,
                            "kbConstant":70,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "b_up":{
                    "cancelWhenAirborne":false,
                    "xSpeedAccel":2.75,
                    "xSpeedAccelAir":2,
                    "xSpeedDecayAir":-0.7,
                    "superArmor":true,
                    "air_ease":3.5,
                    "xSpeedCap":3,
                    "canFallOff":false,
                    "isRecoveryMove":true,
                    "attackSound1_id":"whoosh1",
                    "attackSound2_id":"dk_spin",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":29,
                            "power":50,
                            "kbConstant":70,
                            "effectSound":"whack"
                        }}
                },
                "b_up_air":{
                    "xSpeedAccel":4,
                    "cancelWhenAirborne":false,
                    "xSpeedAccelAir":4,
                    "xSpeedDecayAir":-0.7,
                    "superArmor":true,
                    "air_ease":3.5,
                    "xSpeedCap":8,
                    "allowControl":true,
                    "isRecoveryMove":true,
                    "attackSound1_id":"whoosh1",
                    "attackSound2_id":"dk_spin",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":29,
                            "power":50,
                            "kbConstant":70,
                            "effectSound":"whack"
                        }}
                },
                "b_forward":{
                    "resetMovement":true,
                    "allowControlGround":false,
                    "cpuAttackQueue":"a_forwardsmash;a_down;b",
                    "canFallOff":false,
                    "allowFastFall":false,
                    "reenableTimer":12,
                    "attackVoice1_id":"dk_grunt1",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":"brawl_dk_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":271,
                            "power":20,
                            "kbConstant":40,
                            "pitfall":30,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_forward_air":{
                    "resetMovement":true,
                    "air_ease":0,
                    "allowControlGround":false,
                    "canFallOff":false,
                    "reenableTimer":12,
                    "attackVoice1_id":"dk_grunt1",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":"brawl_dk_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":271,
                            "power":30,
                            "kbConstant":40,
                            "pitfall":30,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_down":{
                    "refreshRate":5,
                    "jumpCancelAttack":true,
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":5,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":110,
                            "power":95,
                            "kbConstant":15,
                            "onlyAffectsGround":true,
                            "effectSound":"ssb_hit1"
                        }}
                },
                "b_down_air":{"attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":25,
                            "selfHitStun":0,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}},
                "throw_up":{
                    "attackVoice1_id":"dk_grunt1",
                    "cpuAttackQueue":"a_air_up;a_air_down",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh2",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "direction":85,
                            "reversableAngle":false,
                            "power":70,
                            "kbConstant":70,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_forward":{
                    "cancelWhenAirborne":false,
                    "xSpeedCap":2,
                    "xSpeedAccel":1.6,
                    "xSpeedAccelAir":4,
                    "allowFastFall":false,
                    "attackVoice1_id":"dk_grunt1",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":-1.05,
                            "selfHitStun":0,
                            "direction":48,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":56,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "throw_back":{
                    "flip":true,
                    "attackVoice1_id":"dk_grunt1",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":39,
                            "reversableAngle":false,
                            "power":54,
                            "kbConstant":105,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_down":{
                    "attackVoice1_id":"dk_grunt1",
                    "cpuAttackQueue":"crouch_attack;a;a_up_tilt;a_air_down;a_air_up;a_air_forward",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh2",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":-1.07,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":75,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":80,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "crouch_attack":{
                    "attackVoice1_id":"dk_grunt1",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":"whoosh3",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":37,
                            "power":40,
                            "kbConstant":60,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"dk_grunt1",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":"brawl_dk_swing_M",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":4,
                            "hitStun":0,
                            "weightKB":100,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "getup_attack":{
                    "attackVoice1_id":"dk_grunt1",
                    "attackVoice2_id":"dk_grunt2",
                    "attackVoice3_id":"dk_grunt3",
                    "attackVoice4_id":"dk_grunt4",
                    "attackSound1_id":"brawl_dk_swing_M",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":2,
                            "weightKB":100,
                            "selfHitStun":2,
                            "direction":43,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"brawl_punch_m",
                            "effect_id":"effect_hit3"
                        }}
                },
                "kirby":{
                    "refreshRate":100,
                    "cancelWhenAirborne":false,
                    "allowControlGround":false,
                    "chargetime_max":72,
                    "charge_retain":true,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "customChargeGlow":"dk_chargebar",
                    "useChargeBar":false,
                    "attackVoice1_id":"kirby_DK",
                    "attackSound1_id":"dk_spin",
                    "attackSound2_id":"brawl_dk_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":6,
                            "chargedPriority":7,
                            "hitStun":5,
                            "selfHitStun":5,
                            "camShake":4,
                            "effect_id":"effect_heavyHit",
                            "direction":25,
                            "power":15,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "kirby_air":{
                    "refreshRate":100,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargetime_max":72,
                    "charge_retain":true,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "customChargeGlow":"dk_chargebar",
                    "useChargeBar":false,
                    "attackVoice1_id":"kirby_DK",
                    "attackSound1_id":"dk_spin",
                    "attackSound2_id":"brawl_dk_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":6,
                            "chargedPriority":7,
                            "hitStun":5,
                            "selfHitStun":5,
                            "camShake":3,
                            "effect_id":"effect_heavyHit",
                            "direction":25,
                            "power":15,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "lock_y_target":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.45,
                            "selfHitStun":0,
                            "direction":0,
                            "power":2,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object = {
                "fs_proj_1":{
                    "linkage_id":"donkeykong_arcadebarrel",
                    "width":50,
                    "height":50,
                    "time_max":150,
                    "ghost":true,
                    "gravity":10,
                    "maxgravity":20,
                    "bounce":6.5,
                    "bounce_decay":0.4,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":14,
                                "shieldDamage":90,
                                "priority":-1,
                                "hitStun":12,
                                "selfHitStun":6,
                                "effect_id":"effect_hit1",
                                "direction":25,
                                "power":40,
                                "kbConstant":100,
                                "effectSound":"brawl_punch_m"
                            }}}
                },
                "fs_proj_2":{
                    "linkage_id":"donkeykong_arcadebarrel",
                    "width":50,
                    "height":50,
                    "time_max":150,
                    "ghost":true,
                    "gravity":10,
                    "maxgravity":20,
                    "bounce":6.5,
                    "bounce_decay":0.4,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":14,
                                "shieldDamage":90,
                                "priority":-1,
                                "hitStun":12,
                                "selfHitStun":6,
                                "effect_id":"effect_hit1",
                                "direction":25,
                                "power":40,
                                "kbConstant":100,
                                "effectSound":"brawl_punch_m"
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("donkeykong");
        }

        public function getGUID():String
        {
            return ("1c0a5cc2-123d-415f-8c2b-44031b295965");
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package donkeykong_fla

