// Decompiled by AS3 Sorcerer 6.20
// www.as3sorcerer.com

//tails_fla.MainTimeline

package tails_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        public function getAudio():Array
        {
            return (new Array(Run_start, tails_starko, new_Tails_win2, tails_F, tails_U, tails_D, tails_bshot, tails_dead, tails_fs, tails_hurt, tails_jump, tails_doublejump, tails_taunt, tails_victory, tails_win, tailsSwing1, tailsSwing2, tailsSwing3, tails_bVoice, tails_rev, tails_release, sonic_revEX, sonic_jump1, sonic_jump2, fsReady, tails_grunt1, tails_grunt2, tails_grunt3, tails_grunt4, tails_dead2, tails_hurt, tails_hurt2, tails_hurtBad2, tails_fs_vfx, tails_newB, tails_sigh, tails_sideB, tails_taunt2));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"tails",
                "displayName":"Tails",
                "linkage_id":"tails",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"tails_head",
                "seriesIcon":"sonic_symbol1",
                "width":15,
                "height":31,
                "jumpSpeed":12,
                "jumpSpeedMidair":11.5,
                "jumpStartup":2,
                "shortHopSpeed":8.5,
                "max_jumpSpeed":7.3,
                "midAirTurn":true,
                "dodgeSpeed":7,
                "gravity":1.1,
                "weight1":82,
                "power":"tails",
                "norm_xSpeed":4.5,
                "max_xSpeed":11,
                "max_ySpeed":14.7,
                "fastFallSpeed":18,
                "accel_start":1,
                "accel_start_dash":1.4,
                "accel_rate":1.5,
                "accel_rate_air":0.95,
                "decel_rate":-0.97,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":4,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_delay":8,
                "getup_roll_delay":0,
                "itemScaleRatio":0.69,
                "special_type":4,
                "normalStats_id":"tails",
                "specialStats_id":null,
                "sounds":{
                    "jump":"tails_jump",
                    "jump_midair":"tails_doublejump",
                    "hurt":"tails_hurt",
                    "hurt2":"tails_hurt2",
                    "hurtBad":"tails_hurtBad",
                    "hurtBad2":"tails_hurtBad2",
                    "dead":"tails_dead",
                    "dead2":"tails_dead2",
                    "pummel":"kick",
                    "screenko":"tails_hurtBad2",
                    "starko":"tails_starko",
                    "ledge_grab":null,
                    "winTheme":"SonicVictory"
                },
                "hurtFrames":5,
                "grabDamage":1,
                "fs_time_limit":600
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":100,
                    "xSpeedDecay":-0.95,
                    "canFallOff":false,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackSound1_id":"tailsSwing1",
                    "attackSound2_id":"tailsSwing2",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":60,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "a_up":{
                    "refreshRate":777,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"tails_U",
                    "attackSound1_id":"tailsSwing3",
                    "attackBoxes":{"attackBox":{
                            "damage":17,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":90,
                            "power":40,
                            "kbConstant":97,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackSound1_id":"tailsSwing2",
                    "cpuAttackQueue":"a_up_tilt;a_up;a_air;b_forward;b_forward_air;a_forwardsmash;a_air_forward",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "power":60,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forward":{
                    "refreshRate":99,
                    "xSpeedDecay":-1,
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "chargeInAir":false,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackSound1_id":"tails_rev",
                    "attackSound2_id":"tailsSwing1",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":132,
                            "power":70,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackSound1_id":"tailsSwing2",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":35,
                            "power":20,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"tails_F",
                    "attackSound1_id":"tailsSwing3",
                    "attackSound2_id":"punch",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":12,
                            "selfHitStun":5,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":20,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"tails_D",
                    "attackSound1_id":"tailsSwing1",
                    "attackSound2_id":"tailsSwing2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":18,
                            "priority":6,
                            "chargedPriority":7,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":50,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":6,
                            "chargedPriority":7,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":50,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox3":{
                            "damage":14,
                            "priority":6,
                            "chargedPriority":7,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":50,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackSound1_id":"tails_rev",
                    "attackSound2_id":"tailsSwing1",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":65,
                            "power":5,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackSound1_id":"tailsSwing2",
                    "cpuAttackQueue":"a_air;a_air_backward;a_air_forward",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":-1.15,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":90,
                            "power":15,
                            "kbConstant":115,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":90,
                            "power":15,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "hit_ease":-3,
                    "allowControl":true,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackSound1_id":"tailsSwing2",
                    "cpuAttackQueue":"a_air; a_air_down;a_air_forward;b_forward;b_forward_air",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":38,
                            "power":20,
                            "kbConstant":95,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":38,
                            "power":20,
                            "kbConstant":95,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":99,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackSound1_id":"tailsSwing1",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":35,
                            "power":30,
                            "kbConstant":105,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackSound1_id":"sw_brawl_swing_H",
                    "cpuAttackQueue":"a_up_tilt;a_up;a_down",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":11,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":286,
                            "power":15,
                            "kbConstant":85,
                            "effectSound":"punch2"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":286,
                            "power":15,
                            "kbConstant":85,
                            "effectSound":"punch2"
                        }
                    }
                },
                "b":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "attackVoice1_id":"tails_newB",
                    "attackSound1_id":"tails_bshot",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "b_air":{
                    "allowControl":true,
                    "isHorizontalRecoveryMove":true,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "reenableTimer":3000,
                    "attackVoice1_id":"tails_newB",
                    "attackSound1_id":"tails_bshot",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "b_up":{
                    "cancelWhenAirborne":false,
                    "refreshRate":2,
                    "allowControl":true,
                    "attackSound1_id":"tails_rev",
                    "attackSound2_id":"tails_doublejump",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":-1,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":150,
                            "power":80,
                            "kbConstant":60,
                            "effectSound":"sw_brawl_hit_S",
                            "hitLag":-0.8
                        }}
                },
                "b_up_air":{
                    "cancelWhenAirborne":false,
                    "air_ease":4,
                    "allowControl":true,
                    "refreshRate":2,
                    "isRecoveryMove":true,
                    "attackSound1_id":"tails_rev",
                    "attackSound2_id":"tails_doublejump",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":-1,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":150,
                            "power":80,
                            "kbConstant":60,
                            "effectSound":"sw_brawl_hit_S",
                            "hitLag":-0.8
                        }}
                },
                "b_forward":{
                    "cancelWhenAirborne":false,
                    "airCancel":true,
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "chargeInAir":false,
                    "allowJump":true,
                    "attackSound1_id":"tails_sideB",
                    "cpuAttackQueue":"a_air;a_air_forward;a_air_down;a_air_backward;a_up;a_up_tilt;throw_up;crouch_attack",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":3,
                            "hitLag":-0.55,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":35,
                            "power":50,
                            "kbConstant":30,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":3,
                            "priority":1,
                            "hitStun":3,
                            "hitLag":-0.55,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":35,
                            "power":50,
                            "kbConstant":30,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox3":{
                            "damage":3,
                            "priority":1,
                            "hitStun":3,
                            "hitLag":-0.55,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":35,
                            "power":50,
                            "kbConstant":30,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "b_forward_air":{
                    "cancelWhenAirborne":false,
                    "airCancel":true,
                    "maintainSpeed":true,
                    "chargeInAir":false,
                    "allowJump":true,
                    "linkFrames":true,
                    "attackSound1_id":"tails_sideB",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":3,
                            "hitLag":-0.55,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":35,
                            "power":50,
                            "kbConstant":30,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":3,
                            "priority":1,
                            "hitStun":3,
                            "hitLag":-0.55,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":35,
                            "power":50,
                            "kbConstant":30,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox3":{
                            "damage":3,
                            "priority":1,
                            "hitStun":3,
                            "hitLag":-0.55,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":35,
                            "power":50,
                            "kbConstant":30,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "b_down":{
                    "refreshRate":100,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "airCancel":true,
                    "xSpeedDecay":-1,
                    "xSpeedDecayAir":-1,
                    "chargetime_max":43,
                    "forceUseAtMaxCharge":true,
                    "attackSound1_id":"tails_rev",
                    "attackSound2_id":"tails_release",
                    "attackBoxes":{"attackBox":{
                            "reversableAngle":false,
                            "damage":8,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "power":35,
                            "kbConstant":102,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_down_air":{
                    "refreshRate":100,
                    "resetMovement":true,
                    "cancelWhenAirborne":true,
                    "allowJump":true,
                    "airCancel":true,
                    "xSpeedDecay":-1,
                    "xSpeedDecayAir":-1,
                    "chargetime_max":43,
                    "forceUseAtMaxCharge":true,
                    "attackSound1_id":"tails_rev",
                    "attackSound2_id":"tails_release",
                    "attackBoxes":{"attackBox":{
                            "reversableAngle":false,
                            "damage":8,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "power":35,
                            "kbConstant":102,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_up":{
                    "allowControl":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackSound1_id":"tails_doublejump",
                    "attackSound2_id":"tailsSwing2",
                    "cpuAttackQueue":"a_air_backward;a_air_up;a_air;a_air_forward;a_up",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":0,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":80,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":60,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackSound1_id":"tailsSwing1",
                    "cpuAttackQueue":"b;a_air_forward;b_forward",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "reversableAngle":false,
                            "power":70,
                            "kbConstant":60,
                            "bypassNonGrabbed":true,
                            "effectSound":null
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackSound1_id":"tailsSwing2",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":-1,
                            "selfHitStun":0,
                            "effect_id":"effect_hit1",
                            "direction":160,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":60,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_down":{
                    "refreshRate":4,
                    "canFallOff":false,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "hasEffect":false,
                            "priority":-1,
                            "hitStun":12,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":60,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":80,
                            "bypassNonGrabbed":true,
                            "effectSound":"tails_rev"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackSound1_id":"tailsSwing2",
                    "cpuAttackQueue":"a_air;a_air_forward;a_forward;a_air_backward;b;b_forward",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":75,
                            "power":20,
                            "kbConstant":105,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":75,
                            "power":20,
                            "kbConstant":105,
                            "effectSound":"brawl_punch_m"
                        }
                    }
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"tails_grunt4",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "priority":3,
                            "hitStun":4,
                            "weightKB":100,
                            "selfHitStun":4,
                            "effect_id":"effect_hit2",
                            "direction":31,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"kick"
                        },
                        "attackBox2":{
                            "damage":3,
                            "priority":3,
                            "hitStun":4,
                            "weightKB":100,
                            "selfHitStun":4,
                            "effect_id":"effect_hit2",
                            "direction":31,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"kick"
                        }
                    }
                },
                "getup_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"tails_grunt1",
                    "attackVoice2_id":"tails_grunt2",
                    "attackVoice3_id":"tails_grunt3",
                    "attackVoice4_id":"tails_grunt4",
                    "attackSound1_id":"tails_rev",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":2,
                            "hitStun":3,
                            "weightKB":100,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":25,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "kirby":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "attackVoice1_id":"Kirby_Attack01",
                    "attackSound1_id":"tails_bshot",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":0.45,
                            "selfHitStun":0,
                            "direction":10,
                            "power":-1000,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "kirby_air":{
                    "refreshRate":1000,
                    "allowControl":true,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "reenableTimer":3000,
                    "attackVoice1_id":"Kirby_Attack01",
                    "attackSound1_id":"tails_bshot",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":0.45,
                            "selfHitStun":0,
                            "direction":10,
                            "power":-1000,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"tails_fs_vfx",
                    "attackVoice2_id":"tails_sigh",
                    "attackSound1_id":"tails_fs",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.45,
                            "selfHitStun":0,
                            "direction":0,
                            "power":2,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object = {
                "tails_cannon":{
                    "linkage_id":"tails_b_v2",
                    "width":35,
                    "height":35,
                    "time_max":40,
                    "trailEffectInterval":0,
                    "xspeed":6,
                    "influenceXMovement":0,
                    "influenceYMovement":0,
                    "influenceXFactor":0,
                    "influenceYFactor":0,
                    "rotate":true,
                    "gravity":0.01,
                    "maxgravity":0.05,
                    "xoffset":25,
                    "yoffset":-15,
                    "limit":3,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":9,
                                "shieldDamage":35,
                                "priority":6,
                                "hitStun":2,
                                "selfHitStun":0,
                                "effect_id":"effect_hit3",
                                "direction":100,
                                "power":90,
                                "kbConstant":15,
                                "shock":true,
                                "effectSound":"brawl_magic_s"
                            }}}
                },
                "tails_cannon_air":{
                    "linkage_id":"tails_b_v2",
                    "width":35,
                    "height":35,
                    "time_max":40,
                    "xspeed":4,
                    "yspeed":4,
                    "rotate":true,
                    "gravity":0.1,
                    "maxgravity":0.05,
                    "xoffset":15,
                    "yoffset":-5,
                    "limit":3,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":9,
                                "shieldDamage":35,
                                "priority":6,
                                "hitStun":2,
                                "selfHitStun":0,
                                "effect_id":"effect_hit3",
                                "direction":100,
                                "power":90,
                                "kbConstant":15,
                                "shock":true,
                                "effectSound":"brawl_magic_s"
                            }}}
                },
                "fs_proj_1":{
                    "linkage_id":"tails_plane_shot",
                    "time_max":9,
                    "ghost":true,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":3,
                                "priority":0,
                                "sdiDistance":5,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "direction":-2,
                                "power":20,
                                "kbConstant":100,
                                "effectSound":null
                            }}}
                },
                "fs_proj_2":{
                    "linkage_id":"tails_plane_bomb",
                    "time_max":22,
                    "ghost":true,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":20,
                                "priority":0,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "direction":45,
                                "power":45,
                                "kbConstant":110,
                                "effectSound":null
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("tails");
        }

        public function getGUID():String
        {
            return ("d83b1ca4-568d-44e9-9de3-d850b54b1643");
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package tails_fla

