package sora_fla
{
   import com.mcleodgaming.ssf2api.core.SSF2API;
   import flash.display.MovieClip;
   import flash.system.Security;
   
   public dynamic class MainTimeline extends MovieClip
   {
       
      
      public function MainTimeline()
      {
         super();
         addFrameScript(0,this.frame1);
      }
      
      public function initAPI(param1:*) : Class
      {
         return SSF2API.init(param1);
      }
      
      public function getAudio() : Array
      {
         return new Array(sora_jumpSound,sora_windSFX,sorawin,sora_thunder,key_swing,key_hit,sora_thisisit,sora_this,sora_take,sora_thunderSFX,sora_letsgo,sora_jumpVoice,sora_hurtBad,sora_hurt2,sora_hurt1,sora_freeze,sora_fireSFX,sora_fire,sora_die,sora_taunt2,sora_attackF2,sora_attackF1,sora_attackD,sora_uspec,sora_fspec,sora_attack4,sora_attack3,sora_attack2,sora_attack1,khII_hurtBad2,khII_whatever,khII_weDidIt,khII_starko,khII_letsGo,khII_donaldGoofy,khII_comeOn,khII_allRight,khII_allInADaysWork,goofy_sora,donald_fireworkspop,sora_attackU,donald_firework,sora_explosion,donald_sora,sora_blizzardSFX,key_hit1,key_hit2,key_hit3,key_hit4,key_hit5,noticeSound,fireHitSound,elecShock);
      }
      
      public function getChar1(param1:Object) : Object
      {
         var _loc2_:Object = new Object();
         _loc2_ = {
            "statsName":"sora",
            "displayName":"Sora",
            "linkage_id":"sora",
            "linkage_id2":null,
            "linkage_id_special":null,
            "thumbnail":"sora_head",
            "seriesIcon":"khicon",
            "width":31,
            "height":45,
            "jumpSpeed":14,
            "jumpSpeedMidair":12,
            "jumpStartup":2,
            "shortHopSpeed":7,
            "max_jumpSpeed":8,
            "dodgeSpeed":9,
            "gravity":1.05,
            "weight1":90,
            "power":"sora",
            "norm_xSpeed":4.9,
            "max_xSpeed":9.8,
            "max_ySpeed":11.5,
            "fastFallSpeed":14,
            "accel_start":1.25,
            "accel_start_dash":1.25,
            "accel_rate":1.3,
            "accel_rate_air":0.7,
            "decel_rate":-1.09,
            "decel_rate_air":-0.15,
            "holdJump":false,
            "max_jump":1,
            "max_projectile":10,
            "tetherGrab":false,
            "roll_speed":26,
            "roll_delay":8,
            "getup_roll_delay":0,
            "itemScaleRatio":0.86,
            "special_type":2,
            "normalStats_id":"sora",
            "specialStats_id":null,
            "sounds":{
               "jump":"sora_jumpVoice",
               "jump_midair":"sora_attackU",
               "hurt":"sora_hurt",
               "hurt2":"sora_hurt2",
               "hurtBad":"sora_hurtBad",
               "hurtBad2":"sora_hurtBad2",
               "dead":"sora_die",
               "dead2":null,
               "pummel":"key_hit",
               "screenko":null,
               "starko":"khII_starko",
               "ledge_grab":null,
               "winTheme":"SoraVictory"
            },
            "hurtFrames":1,
            "grabDamage":1,
            "fs_time_limit":263
         };
         var _loc3_:Object = new Object();
         _loc3_ = {
            "a":{
               "refreshRate":100,
               "combo_max":2,
               "canFallOff":false,
               "reenableTimer":14,
               "attackVoice1_id":"sora_attack1",
               "attackVoice2_id":"sora_attack2",
               "attackVoice3_id":"sora_attack3",
               "attackVoice4_id":"sora_attack4",
               "attackSound1_id":"key_swing",
               "attackBoxes":{"attackBox":{
                  "damage":3,
                  "priority":1,
                  "hitStun":2,
                  "weightKB":0,
                  "selfHitStun":1,
                  "effect_id":"kh_stars",
                  "direction":80,
                  "power":10,
                  "kbConstant":40,
                  "effectSound":"key_hit1"
               }}
            },
            "a_up":{
               "chargetime_max":40,
               "canFallOff":false,
               "chargeClick":true,
               "attackVoice1_id":"sora_attackU",
               "attackSound1_id":"sora_windSFX",
               "attackSound2_id":"key_swing",
               "attackBoxes":{"attackBox":{
                  "damage":16,
                  "priority":4,
                  "hitStun":8,
                  "selfHitStun":3,
                  "effect_id":"effect_hit3",
                  "direction":90,
                  "power":28,
                  "kbConstant":80,
                  "effectSound":"brawl_punch_m"
               }}
            },
            "a_up_tilt":{
               "canFallOff":false,
               "attackVoice1_id":"sora_attack1",
               "attackVoice2_id":"sora_attack2",
               "attackVoice3_id":"sora_attack3",
               "attackVoice4_id":"sora_attack4",
               "attackSound1_id":"key_swing",
               "cpuAttackQueue":"a_up;a_up_tilt;a_forwardsmash;b_up;a_air;a_air_forward",
               "attackBoxes":{"attackBox":{
                  "damage":6,
                  "priority":2,
                  "hitStun":2,
                  "selfHitStun":1,
                  "effect_id":"kh_stars",
                  "direction":90,
                  "power":60,
                  "kbConstant":50,
                  "effectSound":"key_hit3"
               }}
            },
            "a_forward":{
               "xSpeedDecay":-1,
               "canFallOff":false,
               "attackVoice1_id":"sora_attack1",
               "attackVoice2_id":"sora_attack2",
               "attackVoice3_id":"sora_attack3",
               "attackVoice4_id":"sora_attack4",
               "attackSound1_id":"key_swing",
               "cpuAttackQueue":"b_forward",
               "attackBoxes":{"attackBox":{
                  "damage":9,
                  "priority":3,
                  "hitStun":3,
                  "selfHitStun":1,
                  "effect_id":"kh_stars",
                  "direction":70,
                  "power":46,
                  "kbConstant":90,
                  "effectSound":"key_hit4"
               }}
            },
            "a_forward_tilt":{
               "canFallOff":false,
               "attackVoice1_id":"sora_attack1",
               "attackVoice2_id":"sora_attack2",
               "attackVoice3_id":"sora_attack3",
               "attackVoice4_id":"sora_attack4",
               "attackSound1_id":"key_swing",
               "attackBoxes":{
                  "attackBox":{
                     "damage":8,
                     "priority":2,
                     "hitStun":3,
                     "selfHitStun":1,
                     "effect_id":"kh_stars",
                     "direction":45,
                     "power":12,
                     "kbConstant":95,
                     "effectSound":"key_hit3"
                  },
                  "attackBox2":{
                     "damage":8,
                     "priority":2,
                     "hitStun":3,
                     "selfHitStun":1,
                     "effect_id":"kh_stars",
                     "direction":45,
                     "power":12,
                     "kbConstant":95,
                     "effectSound":"key_hit3"
                  }
               }
            },
            "a_forwardsmash":{
               "refreshRate":500,
               "chargetime_max":40,
               "canFallOff":false,
               "chargeClick":true,
               "attackVoice1_id":"sora_attackF1",
               "attackVoice2_id":"sora_attackF2",
               "attackSound1_id":"key_swing",
               "attackBoxes":{"attackBox":{
                  "camShake":1,
                  "damage":12,
                  "priority":4,
                  "hitStun":8,
                  "selfHitStun":8,
                  "effect_id":"kh_stars",
                  "direction":45,
                  "power":30,
                  "kbConstant":108,
                  "effectSound":"key_hit5"
               }}
            },
            "a_down":{
               "refreshRate":2,
               "chargetime_max":40,
               "canFallOff":false,
               "chargeClick":true,
               "attackVoice1_id":"sora_attackD",
               "attackSound1_id":"key_swing",
               "attackSound2_id":"sora_explosion",
               "attackSound3_id":"dash2",
               "attackBoxes":{
                  "attackBox":{
                     "damage":1,
                     "priority":7,
                     "hitStun":1,
                     "hitLag":-1.1,
                     "selfHitStun":1,
                     "effect_id":"effect_heavyHit",
                     "direction":-5,
                     "power":55,
                     "kbConstant":50,
                     "effectSound":"key_hit2"
                  },
                  "attackBox2":{
                     "damage":2,
                     "priority":7,
                     "hitStun":1,
                     "hitLag":-1.1,
                     "selfHitStun":1,
                     "effect_id":"effect_heavyHit",
                     "direction":-5,
                     "power":55,
                     "kbConstant":50,
                     "effectSound":"key_hit2"
                  }
               }
            },
            "a_air":{
               "canFallOff":true,
               "cancelWhenAirborne":true,
               "allowControl":true,
               "attackVoice1_id":"sora_attack1",
               "attackVoice2_id":"sora_attack2",
               "attackVoice3_id":"sora_attack3",
               "attackVoice4_id":"sora_attack4",
               "attackSound1_id":"key_swing",
               "cpuAttackQueue":"b_up_air;b_forward_air;a_up_tilt;a_forwardsmash;a_air_forward;a_air_down;a_air;a_air;a_air_up",
               "attackBoxes":{
                  "attackBox":{
                     "damage":3,
                     "priority":2,
                     "hitStun":3,
                     "selfHitStun":1,
                     "effect_id":"kh_stars",
                     "direction":82,
                     "power":25,
                     "kbConstant":40,
                     "reversableAngle":false,
                     "effectSound":"key_hit1"
                  },
                  "attackBox2":{
                     "damage":3,
                     "priority":2,
                     "hitStun":3,
                     "selfHitStun":1,
                     "effect_id":"kh_stars",
                     "direction":82,
                     "power":25,
                     "kbConstant":40,
                     "reversableAngle":false,
                     "effectSound":"key_hit1"
                  }
               }
            },
            "a_air_up":{
               "canFallOff":true,
               "cancelWhenAirborne":true,
               "allowControl":true,
               "attackVoice1_id":"sora_attack1",
               "attackVoice2_id":"sora_attack2",
               "attackVoice3_id":"sora_attack3",
               "attackVoice4_id":"sora_attack4",
               "attackSound1_id":"key_swing",
               "cpuAttackQueue":"a_air_forward;b_forward_air;b_forward_air;a_air_up;b_up_air",
               "attackBoxes":{"attackBox":{
                  "damage":6,
                  "priority":3,
                  "hitStun":2,
                  "selfHitStun":2,
                  "effect_id":"kh_stars",
                  "direction":75,
                  "power":40,
                  "kbConstant":86,
                  "effectSound":"key_hit1"
               }}
            },
            "a_air_forward":{
               "canFallOff":true,
               "cancelWhenAirborne":true,
               "allowControl":true,
               "attackVoice1_id":"sora_attack1",
               "attackVoice2_id":"sora_attack2",
               "attackVoice3_id":"sora_attack3",
               "attackVoice4_id":"sora_attack4",
               "attackSound1_id":"key_swing",
               "cpuAttackQueue":"a_air_forward;b_forward_air;b_forward_air;a_air_up;b_up_air",
               "attackBoxes":{"attackBox":{
                  "damage":14,
                  "priority":3,
                  "hitStun":3,
                  "selfHitStun":1,
                  "effect_id":"kh_stars",
                  "direction":45,
                  "power":10,
                  "kbConstant":82,
                  "effectSound":"key_hit3"
               }}
            },
            "a_air_backward":{
               "canFallOff":true,
               "cancelWhenAirborne":true,
               "hit_ease":5,
               "allowControl":true,
               "attackVoice1_id":"sora_attack1",
               "attackVoice2_id":"sora_attack2",
               "attackVoice3_id":"sora_attack3",
               "attackVoice4_id":"sora_attack4",
               "attackSound1_id":"key_swing",
               "attackBoxes":{
                  "attackBox":{
                     "damage":7,
                     "priority":3,
                     "hitStun":5,
                     "selfHitStun":1,
                     "effect_id":"kh_stars",
                     "direction":80,
                     "reversableAngle":false,
                     "power":30,
                     "kbConstant":100,
                     "effectSound":"key_hit3"
                  },
                  "attackBox2":{
                     "damage":7,
                     "priority":3,
                     "hitStun":5,
                     "selfHitStun":1,
                     "effect_id":"kh_stars",
                     "direction":80,
                     "reversableAngle":false,
                     "power":30,
                     "kbConstant":100,
                     "effectSound":"key_hit3"
                  }
               }
            },
            "a_air_down":{
               "canFallOff":true,
               "cancelWhenAirborne":true,
               "allowControl":true,
               "attackVoice1_id":"sora_attack1",
               "attackVoice2_id":"sora_attack2",
               "attackVoice3_id":"sora_attack3",
               "attackVoice4_id":"sora_attack4",
               "attackSound1_id":"key_swing",
               "attackBoxes":{
                  "attackBox":{
                     "damage":6,
                     "priority":2,
                     "hitStun":4,
                     "selfHitStun":2,
                     "effect_id":"kh_stars",
                     "direction":60,
                     "reversableAngle":false,
                     "power":81,
                     "kbConstant":35,
                     "effectSound":"key_hit2"
                  },
                  "attackBox2":{
                     "damage":6,
                     "priority":2,
                     "hitStun":4,
                     "selfHitStun":2,
                     "effect_id":"kh_stars",
                     "direction":60,
                     "reversableAngle":false,
                     "power":81,
                     "kbConstant":35,
                     "effectSound":"key_hit2"
                  }
               }
            },
            "b":{
               "cancelWhenAirborne":false,
               "attackVoice1_id":"sora_fspec",
               "attackBoxes":{"attackBox":{
                  "damage":0,
                  "priority":0,
                  "hitStun":5,
                  "hitLag":0.9,
                  "selfHitStun":0,
                  "direction":0,
                  "power":0,
                  "kbConstant":1,
                  "shock":true,
                  "effectSound":null
               }}
            },
            "b_air":{
               "cancelWhenAirborne":false,
               "xSpeedDecayAir":-1,
               "air_ease":2,
               "attackVoice1_id":"sora_fspec",
               "attackBoxes":{"attackBox":{
                  "damage":0,
                  "priority":0,
                  "hitStun":5,
                  "hitLag":0.9,
                  "selfHitStun":0,
                  "direction":0,
                  "power":0,
                  "kbConstant":1,
                  "shock":true,
                  "effectSound":null
               }}
            },
            "b_up":{
               "cancelWhenAirborne":false,
               "airCancel":true,
               "attackVoice1_id":"sora_uspec",
               "attackSound1_id":"key_swing",
               "attackBoxes":{"attackBox":{
                  "damage":9,
                  "reversableAngle":false,
                  "priority":4,
                  "hitStun":3,
                  "selfHitStun":1,
                  "effect_id":"kh_stars",
                  "direction":59,
                  "power":90,
                  "kbConstant":20,
                  "effectSound":"key_hit4"
               }}
            },
            "b_up_air":{
               "cancelWhenAirborne":false,
               "airCancel":true,
               "isRecoveryMove":true,
               "disableJump":true,
               "attackVoice1_id":"sora_uspec",
               "attackSound1_id":"key_swing",
               "attackBoxes":{"attackBox":{
                  "damage":9,
                  "reversableAngle":false,
                  "priority":4,
                  "hitStun":3,
                  "selfHitStun":1,
                  "effect_id":"kh_stars",
                  "direction":59,
                  "power":90,
                  "kbConstant":20,
                  "effectSound":"key_hit4"
               }}
            },
            "b_forward":{
               "cancelWhenAirborne":false,
               "air_ease":0,
               "resetMovement":true,
               "xSpeedDecayAir":-1,
               "attackVoice1_id":"sora_fspec",
               "attackSound1_id":"sora_flowmotion1",
               "attackSound2_id":"sora_flowmotion2",
               "attackBoxes":{"attackBox":{
                  "damage":5,
                  "priority":4,
                  "hitStun":5,
                  "hitLag":-1,
                  "selfHitStun":0,
                  "effect_id":"kh_stars",
                  "direction":95,
                  "power":0,
                  "kbConstant":80,
                  "weightKB":150,
                  "canDI":false,
                  "effectSound":"sw_bigscratch"
               }}
            },
            "b_forward_air":{
               "cancelWhenAirborne":false,
               "air_ease":0,
               "isRecoveryMove":true,
               "resetMovement":true,
               "xSpeedDecayAir":-1,
               "attackVoice1_id":"sora_fspec",
               "attackSound1_id":"sora_flowmotion1",
               "attackSound2_id":"sora_flowmotion2",
               "cpuAttackQueue":"a_air_forward;b_forward_air;b_forward_air;a_air_up;b_up_air;a_air_backward",
               "attackBoxes":{"attackBox":{
                  "damage":5,
                  "priority":4,
                  "hitStun":5,
                  "hitLag":-1,
                  "selfHitStun":0,
                  "effect_id":"kh_stars",
                  "direction":95,
                  "power":0,
                  "kbConstant":80,
                  "weightKB":150,
                  "canDI":false,
                  "effectSound":"sw_bigscratch"
               }}
            },
            "b_down":{
               "resetMovement":true,
               "cancelWhenAirborne":false,
               "air_ease":0,
               "jumpFrame":"thunder",
               "reenableTimer":999,
               "attackVoice1_id":"sora_thunder",
               "attackSound1_id":"key_swing",
               "attackSound2_id":"sora_thunderSFX",
               "attackBoxes":{"attackBox":{
                  "damage":0,
                  "priority":0,
                  "hitStun":5,
                  "hitLag":0.9,
                  "selfHitStun":0,
                  "direction":0,
                  "power":0,
                  "kbConstant":1,
                  "shock":true,
                  "effectSound":null
               }}
            },
            "b_down_air":{
               "resetMovement":true,
               "air_ease":0,
               "jumpFrame":"thunder",
               "reenableTimer":999,
               "attackVoice1_id":"sora_thunder",
               "attackSound1_id":"key_swing",
               "attackSound2_id":"sora_thunderSFX",
               "attackBoxes":{"attackBox":{
                  "damage":0,
                  "priority":0,
                  "hitStun":5,
                  "hitLag":0.9,
                  "selfHitStun":0,
                  "direction":0,
                  "power":0,
                  "kbConstant":1,
                  "shock":true,
                  "effectSound":null
               }}
            },
            "throw_up":{
               "canFallOff":false,
               "attackVoice1_id":"sora_attack1",
               "attackVoice2_id":"sora_attack2",
               "attackVoice3_id":"sora_attack3",
               "attackVoice4_id":"sora_attack4",
               "attackSound1_id":"key_swing",
               "attackBoxes":{"attackBox":{
                  "damage":6,
                  "priority":0,
                  "hitStun":3,
                  "hitLag":-1.05,
                  "selfHitStun":3,
                  "effect_id":"kh_stars",
                  "direction":90,
                  "reversableAngle":false,
                  "power":56,
                  "kbConstant":105,
                  "bypassNonGrabbed":true,
                  "effectSound":"key_hit4"
               }}
            },
            "throw_forward":{
               "canFallOff":false,
               "attackVoice1_id":"sora_attack1",
               "attackVoice2_id":"sora_attack2",
               "attackVoice3_id":"sora_attack3",
               "attackVoice4_id":"sora_attack4",
               "attackSound1_id":"key_swing",
               "attackBoxes":{"attackBox":{
                  "damage":2,
                  "hasEffect":false,
                  "priority":0,
                  "hitStun":3,
                  "selfHitStun":2,
                  "effect_id":"kh_stars",
                  "direction":40,
                  "reversableAngle":false,
                  "power":40,
                  "kbConstant":70,
                  "bypassNonGrabbed":true,
                  "effectSound":"key_hit1"
               }}
            },
            "throw_back":{
               "flip":true,
               "canFallOff":false,
               "attackVoice1_id":"sora_freeze",
               "attackSound1_id":"sora_blizzardSFX",
               "attackBoxes":{"attackBox":{
                  "damage":9,
                  "priority":0,
                  "hitStun":1,
                  "hitLag":-1.1,
                  "selfHitStun":1,
                  "effect_id":"effect_icehit",
                  "direction":120,
                  "reversableAngle":false,
                  "power":70,
                  "kbConstant":0,
                  "bypassNonGrabbed":true,
                  "freeze":15,
                  "effectSound":"effect_icehit"
               }}
            },
            "throw_down":{
               "refreshRate":5,
               "flip":true,
               "canFallOff":false,
               "attackVoice1_id":"sora_take",
               "attackVoice2_id":"sora_this",
               "attackSound1_id":"woosh",
               "attackSound2_id":"key_swing",
               "attackBoxes":{"attackBox":{
                  "damage":5,
                  "priority":0,
                  "hitStun":5,
                  "hitLag":-1.05,
                  "selfHitStun":2,
                  "effect_id":"kh_stars",
                  "direction":50,
                  "reversableAngle":false,
                  "power":46,
                  "kbConstant":125,
                  "bypassNonGrabbed":true,
                  "effectSound":"key_hit2"
               }}
            },
            "crouch_attack":{
               "canFallOff":false,
               "attackVoice1_id":"sora_attack1",
               "attackVoice2_id":"sora_attack2",
               "attackVoice3_id":"sora_attack3",
               "attackVoice4_id":"sora_attack4",
               "attackSound1_id":"key_swing",
               "attackBoxes":{"attackBox":{
                  "damage":4,
                  "priority":2,
                  "hitStun":3,
                  "selfHitStun":3,
                  "effect_id":"kh_stars",
                  "direction":70,
                  "power":35,
                  "kbConstant":100,
                  "effectSound":"key_hit1"
               }}
            },
            "ledge_attack":{
               "canFallOff":false,
               "maintainSpeed":true,
               "attackVoice1_id":"sora_attack1",
               "attackVoice2_id":"sora_attack2",
               "attackVoice3_id":"sora_attack3",
               "attackVoice4_id":"sora_attack4",
               "attackSound1_id":"key_swing",
               "attackBoxes":{"attackBox":{
                  "damage":3,
                  "priority":2,
                  "hitStun":0,
                  "weightKB":110,
                  "selfHitStun":0,
                  "effect_id":"kh_stars",
                  "direction":30,
                  "power":0,
                  "kbConstant":100,
                  "effectSound":"key_hit1"
               }}
            },
            "getup_attack":{
               "attackVoice1_id":"sora_attack1",
               "attackVoice2_id":"sora_attack2",
               "attackVoice3_id":"sora_attack3",
               "attackVoice4_id":"sora_attack4",
               "attackSound1_id":"key_swing",
               "attackBoxes":{"attackBox":{
                  "damage":5,
                  "priority":2,
                  "hitStun":4,
                  "selfHitStun":1,
                  "direction":45,
                  "power":100,
                  "kbConstant":43,
                  "effectSound":"key_hit1"
               }}
            },
            "kirby":{
               "cancelWhenAirborne":false,
               "xSpeedDecay":-1,
               "air_ease":2,
               "allowControl":true,
               "jumpFrame":"fire",
               "attackVoice1_id":"kirby_fire",
               "attackSound1_id":"sora_fireSFX",
               "attackBoxes":{"attackBox":{
                  "damage":10,
                  "priority":4,
                  "hitStun":1,
                  "hitLag":-1.05,
                  "selfHitStun":1,
                  "effect_id":"effect_firehit1",
                  "direction":48,
                  "power":67,
                  "kbConstant":88,
                  "effectSound":null
               }}
            },
            "kirby_air":{
               "cancelWhenAirborne":false,
               "xSpeedDecay":-1,
               "air_ease":2,
               "allowControl":true,
               "jumpFrame":"fire",
               "reenableTimer":15,
               "attackVoice1_id":"kirby_fire",
               "attackSound1_id":"sora_fireSFX",
               "attackBoxes":{"attackBox":{
                  "damage":8,
                  "priority":4,
                  "hitStun":1,
                  "hitLag":-1.05,
                  "selfHitStun":0,
                  "effect_id":"effect_firehit1",
                  "direction":48,
                  "power":55,
                  "kbConstant":80,
                  "effectSound":null
               }}
            },
            "special":{
               "resetMovement":true,
               "cancelWhenAirborne":false,
               "invincible":true,
               "air_ease":0,
               "combo_max":8,
               "forceComboContinue":true,
               "canUseInAir":true,
               "attackVoice1_id":"khII_letsGo",
               "attackVoice2_id":"khII_donaldGoofy",
               "attackVoice3_id":null,
               "attackVoice4_id":"khII_yah",
               "attackVoice5_id":"khII_huh",
               "attackVoice6_id":"khII_hmm",
               "attackVoice7_id":"sora_attack4",
               "attackVoice8_id":"sora_attack5",
               "attackVoice9_id":"sora_attack6",
               "attackVoice10_id":"sora_attack7",
               "attackVoice11_id":"sora_thisisit",
               "attackVoice12_id":"donald_sora",
               "attackVoice13_id":"goofy_sora",
               "attackSound1_id":"whoosh3",
               "attackSound2_id":"whoosh2",
               "attackSound3_id":"whoosh1",
               "attackBoxes":{"attackBox":{
                  "damage":3,
                  "priority":7,
                  "hitStun":1,
                  "selfHitStun":0,
                  "effect_id":"kh_stars",
                  "direction":50,
                  "power":0,
                  "kbConstant":0,
                  "effectSound":"key_hit"
               }}
            },
            "fire":{
               "cancelWhenAirborne":false,
               "xSpeedDecay":-1,
               "air_ease":2,
               "allowControl":true,
               "jumpFrame":"fire",
               "reenableTimer":15,
               "attackVoice1_id":"khII_getOff",
               "attackBoxes":{"attackBox":{
                  "damage":10,
                  "priority":4,
                  "hitStun":3,
                  "hitLag":-1.05,
                  "selfHitStun":3,
                  "effect_id":"effect_firehit1",
                  "direction":45,
                  "power":75,
                  "kbConstant":20,
                  "burn":true,
                  "effectSound":null
               }}
            },
            "blizzard":{
               "attackDelay":12,
               "allowControl":true,
               "jumpFrame":"blizzard",
               "reenableTimer":20,
               "attackVoice1_id":"khII_allRight",
               "attackBoxes":{"attackBox":{
                  "damage":0,
                  "priority":0,
                  "hitStun":0,
                  "hitLag":0,
                  "selfHitStun":0,
                  "direction":0,
                  "power":0,
                  "kbConstant":1,
                  "effectSound":null
               }}
            },
            "thunder":{
               "resetMovement":true,
               "cancelWhenAirborne":false,
               "air_ease":0,
               "jumpFrame":"thunder",
               "reenableTimer":999,
               "attackVoice1_id":"khII_haha",
               "attackBoxes":{"attackBox":{
                  "damage":0,
                  "priority":0,
                  "hitStun":5,
                  "hitLag":0.9,
                  "selfHitStun":0,
                  "direction":0,
                  "power":0,
                  "kbConstant":1,
                  "shock":true,
                  "effectSound":null
               }}
            }
         };
         var _loc4_:Object = {
            "sora_wind":{
               "linkage_id":"invisible",
               "time_max":11,
               "ghost":true,
               "stale":false,
               "limit":1,
               "lockTrajectory":true,
               "canFallOff":false,
               "attack_idle":{"attackBoxes":{"attackBox":{
                  "damage":0,
                  "hasEffect":false,
                  "priority":-1,
                  "hitStun":0,
                  "hitLag":0,
                  "selfHitStun":0,
                  "camShake":0,
                  "direction":-4,
                  "power":42,
                  "kbConstant":5,
                  "bypassShield":true,
                  "effectSound":null
               }}}
            },
            "sora_strikeraid":{
               "linkage_id":"sora_strikeraidproj",
               "width":35,
               "height":26,
               "time_max":38,
               "xdecay":2.4,
               "xspeed":20,
               "xoffset":30,
               "yoffset":-17,
               "canBeAbsorbed":false,
               "limit":1,
               "attack_idle":{"attackBoxes":{"attackBox":{
                  "damage":1,
                  "priority":3,
                  "hitStun":1,
                  "selfHitStun":0,
                  "effect_id":"kh_stars",
                  "direction":-9,
                  "power":45,
                  "kbConstant":0,
                  "reversableAngle":false,
                  "effectSound":"key_hit5"
               }}}
            },
            "sora_thunder":{
               "linkage_id":"sora_thunderproj",
               "width":107,
               "height":73,
               "time_max":30,
               "ghost":true,
               "xoffset":84.25,
               "yoffset":2.5,
               "attack_idle":{"attackBoxes":{"attackBox":{
                  "damage":5,
                  "priority":5,
                  "hitStun":6,
                  "selfHitStun":0,
                  "effect_id":"effect_hit2",
                  "direction":-3,
                  "power":40,
                  "kbConstant":142,
                  "effectSound":"elecShock"
               }}}
            },
            "sora_blizzard":{
               "linkage_id":"sora_blizzardproj",
               "width":20,
               "height":25,
               "time_max":40,
               "xspeed":8,
               "xoffset":33,
               "yoffset":5.25,
               "attack_idle":{"attackBoxes":{"attackBox":{
                  "damage":10,
                  "priority":3,
                  "hitStun":3,
                  "selfHitStun":0,
                  "effect_id":"effect_icehit",
                  "direction":45,
                  "power":45,
                  "kbConstant":13,
                  "freeze":22,
                  "effectSound":null
               }}}
            }
         };
         var _loc5_:Object = null;
         return {
            "cData":_loc2_,
            "aData":_loc3_,
            "iData":_loc5_,
            "pData":_loc4_
         };
      }
      
      public function getID() : String
      {
         return "sora";
      }
      
      public function getGUID() : String
      {
         return "57068ce5-ad07-446a-8a80-5a2939219e9f";
      }
      
      function frame1() : *
      {
         Security.allowDomain("*mcleodgaming.com*");
         this.visible = false;
         stop();
      }
   }
}
