// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//zelda_fla.MainTimeline

package zelda_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function getAudio():Array
        {
            return (new Array(shelda_victory, shelda_transform1, shelda_transform2, shelda_transform3, shelda_transform4, shelda_fs1, shelda_fs2, sheik_death1, sheik_death2, sheik_dizzy, sheik_dsmash, sheik_edgegrab, sheik_finalsmash1, sheik_finalsmash2, sheik_fsmash, sheik_grunt1, sheik_grunt2, sheik_grunt3, sheik_grunt4, sheik_hurt1, sheik_hurt2, sheik_hurtBad1, sheik_hurtBad2, sheik_jump1, sheik_jump2, sheik_needle, sheik_starko, sheik_taunt1, sheik_taunt3, sheik_tech, sheik_usmash, sheik_swing_s, sheik_swing_m, sheik_swing_l, sheik_needle_charge, sheik_needle_throw, sheik_uspec1, sheik_uspec2, sheik_uspec3, sheik_dashattack, sheik_usmash_sfx, sheik_whip, zelda_death1, zelda_death2, zelda_dizzy, zelda_dsmash, zelda_edgegrab, zelda_fsmash, zelda_grunt1, zelda_grunt2, zelda_grunt3, zelda_grunt4, zelda_hurt1, zelda_hurt2, zelda_hurtBad1, zelda_hurtBad2, zelda_jump, zelda_lift, zelda_nspec, zelda_sleep, zelda_usmash, zelda_starko, zelda_magic_s, zelda_nayru, zelda_magic_m, zelda_uspec1, zelda_uspec2, zelda_din2, zelda_din1, zelda_uair, zelda_uspec_vfx, zelda_din_vfx, zelda_din_charge, zelda_finalsmash1, zelda_finalsmash2));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"zelda",
                "displayName":"Zelda",
                "linkage_id":"zelda",
                "linkage_id2":"sheik",
                "linkage_id_special":null,
                "thumbnail":"zelda_head",
                "seriesIcon":"zeldaicon",
                "width":36,
                "height":57,
                "jumpSpeed":14,
                "jumpSpeedMidair":14.5,
                "jumpStartup":3,
                "shortHopSpeed":7.3,
                "max_jumpSpeed":6,
                "dodgeSpeed":8,
                "gravity":1.17,
                "weight1":90,
                "power":"zelda",
                "norm_xSpeed":3,
                "max_xSpeed":8.7,
                "max_ySpeed":10,
                "fastFallSpeed":11.4,
                "accel_start":1.1,
                "accel_start_dash":0.97,
                "accel_rate":1.1,
                "accel_rate_air":0.95,
                "decel_rate":-1.17,
                "decel_rate_air":-0.135,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":26,
                "roll_delay":13,
                "itemScaleRatio":0.833333333333333,
                "special_type":1,
                "normalStats_id":"zelda",
                "specialStats_id":null,
                "sounds":{
                    "jump":"zelda_jump",
                    "jump_midair":null,
                    "hurt":"zelda_hurt1",
                    "hurt2":"zelda_hurt2",
                    "hurtBad":"zelda_hurtBad1",
                    "hurtBad2":"zelda_hurtBad2",
                    "dead":"zelda_death1",
                    "dead2":"zelda_death2",
                    "pummel":"brawl_magic_s",
                    "screenko":"zelda_hurtBad2",
                    "starko":"zelda_starko",
                    "ledge_grab":null,
                    "winTheme":"zeldaWin2"
                },
                "hurtFrames":3,
                "grabDamage":1
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "canFallOff":false,
                    "attackSound1_id":"zelda_magic_s",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":45,
                            "power":25,
                            "kbConstant":100,
                            "shock":true,
                            "effectSound":"brawl_magic_s"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":45,
                            "power":25,
                            "kbConstant":100,
                            "shock":true,
                            "effectSound":"brawl_magic_s"
                        }
                    }
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"zelda_usmash",
                    "attackSound1_id":"zelda_magic_s",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":1,
                            "hitLag":-1.3,
                            "selfHitStun":0,
                            "direction":130,
                            "power":25,
                            "kbConstant":10,
                            "effectSound":"brawl_magic_s"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackSound1_id":"zelda_magic_s",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":1,
                            "hitLag":-1.25,
                            "effect_id":"effect_hit3",
                            "direction":75,
                            "power":70,
                            "kbConstant":60,
                            "shock":true,
                            "effectSound":"brawl_magic_s"
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":1,
                            "hitLag":-1.25,
                            "effect_id":"effect_hit3",
                            "direction":75,
                            "power":70,
                            "kbConstant":60,
                            "shock":true,
                            "effectSound":"brawl_magic_s"
                        }
                    }
                },
                "a_forward":{
                    "resetMovement":true,
                    "xSpeedDecay":-1.35,
                    "canFallOff":false,
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackSound1_id":"zelda_magic_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "hitLag":-1.15,
                            "effect_id":"effect_hit3",
                            "shock":true,
                            "direction":75,
                            "power":62,
                            "kbConstant":53,
                            "effectSound":"brawl_magic_m"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "hitLag":-1.15,
                            "effect_id":"effect_hit3",
                            "shock":true,
                            "direction":75,
                            "power":62,
                            "kbConstant":53,
                            "effectSound":"brawl_magic_m"
                        }
                    }
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "allowFastFall":false,
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.27,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":110,
                            "power":70,
                            "kbConstant":70,
                            "effectSound":"brawl_magic_m",
                            "shock":true
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.27,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":110,
                            "power":70,
                            "kbConstant":70,
                            "effectSound":"brawl_magic_m",
                            "shock":true
                        }
                    }
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"zelda_fsmash",
                    "attackSound1_id":"zelda_magic_m",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_hit3",
                            "direction":-9,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_magic_m"
                        }}
                },
                "a_down":{
                    "refreshRate":90,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"zelda_dsmash",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":-1,
                            "chargedPriority":-1,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":20,
                            "power":28,
                            "kbConstant":103,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":-1,
                            "chargedPriority":-1,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":20,
                            "power":28,
                            "kbConstant":103,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackSound1_id":"zelda_magic_s",
                    "attackSound2_id":"zelda_magic_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "shieldDamage":3,
                            "priority":2,
                            "hitStun":2,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":90,
                            "power":28,
                            "kbConstant":100,
                            "effectSound":"brawl_magic_s"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":2,
                            "hitStun":2,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":115,
                            "power":26,
                            "kbConstant":100,
                            "effectSound":"brawl_magic_s"
                        },
                        "attackBox3":{
                            "damage":1,
                            "priority":2,
                            "hitStun":2,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":115,
                            "power":26,
                            "kbConstant":100,
                            "effectSound":"brawl_magic_s"
                        }
                    }
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackSound1_id":"zelda_uair",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_firehit1",
                            "direction":95,
                            "power":49,
                            "kbConstant":91,
                            "effectSound":"brawl_fire_l"
                        }}
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":68,
                            "hitLag":-1,
                            "power":43,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "shieldDamage":20,
                            "damage":15,
                            "direction":47,
                            "power":45,
                            "kbConstant":95,
                            "priority":5,
                            "hitStun":12,
                            "hitLag":-1.07,
                            "selfHitStun":16,
                            "shock":true,
                            "effectSound":"brawl_magic_xl"
                        },
                        "attackBox3":{
                            "damage":7,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":68,
                            "hitLag":-1,
                            "power":43,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox4":{
                            "damage":7,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":68,
                            "hitLag":-1,
                            "power":43,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":55,
                            "hitLag":-1,
                            "power":32,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":20,
                            "shieldDamage":25,
                            "direction":42,
                            "power":40,
                            "kbConstant":103,
                            "priority":6,
                            "hitStun":16,
                            "hitLag":-1.1,
                            "selfHitStun":12,
                            "shock":true,
                            "effectSound":"brawl_magic_xl"
                        },
                        "attackBox3":{
                            "damage":6,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":55,
                            "hitLag":-1,
                            "power":32,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox4":{
                            "damage":6,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":55,
                            "hitLag":-1,
                            "power":32,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":275,
                            "power":28,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":16,
                            "direction":270,
                            "shieldDamage":25,
                            "power":40,
                            "kbConstant":90,
                            "priority":4,
                            "hitStun":16,
                            "hitLag":-1,
                            "selfHitStun":12,
                            "effectSound":"brawl_magic_xl",
                            "shock":true
                        }
                    }
                },
                "b":{
                    "refreshRate":2,
                    "air_ease":3,
                    "attackVoice1_id":"zelda_nspec",
                    "attackSound1_id":"zelda_nayru",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":75,
                            "power":20,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S",
                            "effect_id":"effect_swordSlash"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":75,
                            "power":20,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S",
                            "effect_id":"effect_swordSlash"
                        },
                        "attackBox4":{
                            "allowTurboInterrupt":false,
                            "hitStun":0,
                            "selfHitStun":0,
                            "hasEffect":false,
                            "reverse_projectile":true
                        },
                        "attackBox3":{
                            "damage":1,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":75,
                            "power":20,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S",
                            "effect_id":"effect_swordSlash"
                        }
                    }
                },
                "b_air":{
                    "refreshRate":2,
                    "air_ease":3,
                    "isHorizontalRecoveryMove":true,
                    "attackVoice1_id":"zelda_nspec",
                    "attackSound1_id":"zelda_nayru",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":75,
                            "power":20,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S",
                            "effect_id":"effect_swordSlash"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":75,
                            "power":20,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S",
                            "effect_id":"effect_swordSlash"
                        },
                        "attackBox4":{
                            "allowTurboInterrupt":false,
                            "hitStun":0,
                            "selfHitStun":0,
                            "hasEffect":false,
                            "reverse_projectile":true
                        },
                        "attackBox3":{
                            "damage":1,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":75,
                            "power":20,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S",
                            "effect_id":"effect_swordSlash"
                        }
                    }
                },
                "b_up":{
                    "air_ease":2,
                    "allowControlGround":false,
                    "disableForCPU":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecayAir":-0.35,
                    "attackVoice1_id":"zelda_uspec_vfx",
                    "attackSound1_id":"zelda_uspec1",
                    "attackSound2_id":"zelda_uspec2",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":90,
                            "power":41,
                            "kbConstant":70,
                            "effectSound":"sw_brawl_hit_S.wav"
                        }}
                },
                "b_up_air":{
                    "air_ease":2,
                    "allowControlGround":false,
                    "disableForCPU":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecayAir":-0.35,
                    "isHorizontalRecoveryMove":true,
                    "isRecoveryMove":true,
                    "attackVoice1_id":"zelda_uspec_vfx",
                    "attackSound1_id":"zelda_uspec1",
                    "attackSound2_id":"zelda_uspec2",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":90,
                            "power":41,
                            "kbConstant":70,
                            "effectSound":"sw_brawl_hit_S.wav"
                        }}
                },
                "b_forward":{
                    "air_ease":3,
                    "chargetime_max":70,
                    "isLongRangeMove":true,
                    "forceUseAtMaxCharge":true,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "attackVoice1_id":"zelda_din_vfx",
                    "attackSound1_id":"zelda_din1",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":1,
                            "selfHitStun":2,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_forward_air":{
                    "air_ease":3,
                    "chargetime_max":70,
                    "isLongRangeMove":true,
                    "forceUseAtMaxCharge":true,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "attackVoice1_id":"zelda_din_vfx",
                    "attackSound1_id":"zelda_din1",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":1,
                            "selfHitStun":2,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_down":{
                    "air_ease":5,
                    "attackSound1_id":"shelda_transform1",
                    "attackSound2_id":"shelda_transform2",
                    "attackSound3_id":"shelda_transform3",
                    "attackSound4_id":"shelda_transform4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":25,
                            "selfHitStun":0,
                            "effect_id":"effect_hit3",
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_down_air":{
                    "air_ease":5,
                    "attackSound1_id":"shelda_transform1",
                    "attackSound2_id":"shelda_transform2",
                    "attackSound3_id":"shelda_transform3",
                    "attackSound4_id":"shelda_transform4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":25,
                            "selfHitStun":0,
                            "effect_id":"effect_hit3",
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackSound1_id":"zelda_magic_s",
                    "attackSound2_id":"zelda_magic_m",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":90,
                            "power":55,
                            "kbConstant":68,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_magic_m"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":30,
                            "reversableAngle":false,
                            "power":82,
                            "kbConstant":25,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_magic_m"
                        }}
                },
                "throw_back":{
                    "flip":true,
                    "canFallOff":false,
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":40,
                            "reversableAngle":false,
                            "power":55,
                            "kbConstant":115,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_magic_m"
                        }}
                },
                "throw_down":{
                    "canFallOff":false,
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackSound1_id":"brawl_magic_m",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_hit3",
                            "direction":112,
                            "reversableAngle":false,
                            "power":48,
                            "kbConstant":120,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_magic_m"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":280,
                            "power":55,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":2,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_hit3",
                            "direction":300,
                            "power":55,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":16,
                            "selfHitStun":0,
                            "effect_id":"effect_hit3",
                            "direction":30,
                            "power":83,
                            "kbConstant":13,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":16,
                            "selfHitStun":0,
                            "effect_id":"effect_hit3",
                            "direction":30,
                            "power":83,
                            "kbConstant":13,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "getup_attack":{
                    "attackVoice1_id":"zelda_grunt1",
                    "attackVoice2_id":"zelda_grunt2",
                    "attackVoice3_id":"zelda_grunt3",
                    "attackVoice4_id":"zelda_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":6,
                            "priority":0,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "direction":0,
                            "power":40,
                            "kbConstant":100,
                            "effect_id":"effect_hit3",
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":6,
                            "priority":0,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "direction":0,
                            "power":40,
                            "kbConstant":100,
                            "effect_id":"effect_hit3",
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "kirby":{
                    "refreshRate":1,
                    "air_ease":3,
                    "attackVoice1_id":"zelda_nspec",
                    "attackSound1_id":"zelda_nayru",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":0,
                            "direction":25,
                            "power":0,
                            "kbConstant":60,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "kirby_air":{
                    "refreshRate":1,
                    "air_ease":3,
                    "isHorizontalRecoveryMove":true,
                    "attackVoice1_id":"zelda_nspec",
                    "attackSound1_id":"zelda_nayru",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":0,
                            "direction":25,
                            "power":0,
                            "kbConstant":60,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "air_ease":0,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackVoice1_id":"zelda_finalsmash1",
                    "attackVoice2_id":"zelda_finalsmash2",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":60,
                            "selfHitStun":0,
                            "direction":90,
                            "power":0,
                            "kbConstant":0
                        }}
                }
            };
            var _local_4:Object = {
                "dinsfire":{
                    "linkage_id":"dins_fire",
                    "width":45,
                    "height":45,
                    "time_max":78,
                    "xdecay":-0.8,
                    "xspeed":4,
                    "influenceYMovement":12,
                    "influenceYFactor":3,
                    "maxgravity":-0.4,
                    "yoffset":-40,
                    "canBeReversed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":9,
                                "ignoreChargeDamage":true,
                                "priority":3,
                                "hitStun":4,
                                "selfHitStun":1,
                                "effect_id":"effect_firehit1",
                                "direction":58,
                                "power":65,
                                "kbConstant":80,
                                "burn":true,
                                "poisonInterval":0,
                                "poisonLength":0,
                                "effectSound":null
                            }}}
                },
                "lightarrow":{
                    "linkage_id":"light_arrow",
                    "width":133,
                    "height":42,
                    "time_max":100,
                    "xspeed":60,
                    "ghost":true,
                    "xoffset":62,
                    "yoffset":-35,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":42,
                                "priority":-1,
                                "sdiDistance":0,
                                "hitStun":6,
                                "selfHitStun":0,
                                "effect_id":"Arrow_explode",
                                "direction":45,
                                "power":75,
                                "kbConstant":75,
                                "bypassShield":true,
                                "effectSound":"brawl_punch_l"
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getChar2(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"sheik",
                "displayName":"Sheik",
                "linkage_id":"sheik",
                "linkage_id2":"zelda",
                "linkage_id_special":null,
                "thumbnail":"sheik_head",
                "seriesIcon":"zeldaicon",
                "width":36,
                "height":57,
                "jumpSpeed":15.8,
                "jumpSpeedMidair":15.8,
                "jumpStartup":2,
                "shortHopSpeed":9,
                "max_jumpSpeed":6.5,
                "dodgeSpeed":8,
                "gravity":1.23,
                "weight1":90,
                "power":"sheik",
                "norm_xSpeed":4,
                "max_xSpeed":10.6,
                "max_ySpeed":12.2,
                "fastFallSpeed":16.3,
                "accel_start":1.1,
                "accel_start_dash":1.3,
                "accel_rate":1,
                "accel_rate_air":1.1,
                "decel_rate":-1.3,
                "decel_rate_air":-0.135,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":28,
                "roll_delay":13,
                "getup_roll_delay":0,
                "itemScaleRatio":0.833333333333333,
                "special_type":1,
                "normalStats_id":"sheik",
                "specialStats_id":null,
                "sounds":{
                    "jump":"sheik_jump1",
                    "jump_midair":"sheik_jump2",
                    "hurt":"sheik_hurt1",
                    "hurt2":"sheik_hurt2",
                    "hurtBad":"sheik_hurtBad1",
                    "hurtBad2":"sheik_hurtBad2",
                    "dead":"sheik_death1",
                    "dead2":"sheik_death2",
                    "pummel":"brawl_punch_s",
                    "screenko":"sheik_hurt2",
                    "starko":"sheik_starko",
                    "ledge_grab":"sheik_edgegrab",
                    "winTheme":"zeldaWin2"
                },
                "hurtFrames":4,
                "grabDamage":2
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "canFallOff":false,
                    "attackSound1_id":"sheik_swing_s",
                    "attackSound2_id":"sheik_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":1,
                            "weightKB":10,
                            "selfHitStun":0,
                            "effect_id":"effect_hit1",
                            "direction":92,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_s"
                        },
                        "attackBox2":{
                            "damage":3,
                            "priority":1,
                            "hitStun":1,
                            "weightKB":10,
                            "selfHitStun":0,
                            "effect_id":"effect_hit1",
                            "direction":92,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_s"
                        }
                    }
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"sheik_usmash",
                    "attackSound1_id":"sheik_usmash_sfx",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":17,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":93,
                            "power":74.9,
                            "kbConstant":78,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox2":{
                            "damage":17,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":93,
                            "power":74.9,
                            "kbConstant":78,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox3":{
                            "damage":17,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":93,
                            "power":74.9,
                            "kbConstant":78,
                            "effectSound":"brawl_punch_m"
                        }
                    }
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"sheik_grunt1",
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackSound1_id":"sheik_swing_m",
                    "cpuAttackQueue":"a_up; a_up_tilt; a_air; a_air_forward",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":6,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":-1.15,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":80,
                            "power":0,
                            "kbConstant":108,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":6,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":-1.15,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":80,
                            "power":0,
                            "kbConstant":108,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox3":{
                            "damage":6,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":-1.15,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":80,
                            "power":0,
                            "kbConstant":108,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "a_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"sheik_grunt1",
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackSound1_id":"sheik_swing_s",
                    "attackSound2_id":"sheik_dashattack",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":60,
                            "power":74.9,
                            "kbConstant":105,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":60,
                            "power":74.9,
                            "kbConstant":105,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"sheik_grunt1",
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackSound1_id":"sheik_swing_s",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.07,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":90,
                            "power":32.1,
                            "kbConstant":105,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":5,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.07,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":90,
                            "power":32.1,
                            "kbConstant":105,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"sheik_fsmash",
                    "attackSound1_id":"sheik_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":55,
                            "power":58,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":5,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":60,
                            "power":50,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"sheik_dsmash",
                    "attackSound1_id":"sheik_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":40,
                            "power":52,
                            "kbConstant":85.6,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":40,
                            "power":52,
                            "kbConstant":85.6,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"sheik_grunt1",
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackSound1_id":"sheik_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":43,
                            "power":25,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":43,
                            "power":25,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox3":{
                            "damage":13,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":43,
                            "power":25,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"sheik_grunt1",
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackSound1_id":"sheik_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":90,
                            "power":20,
                            "kbConstant":95,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":90,
                            "power":20,
                            "kbConstant":95,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"sheik_grunt1",
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackSound1_id":"whoosh1",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1.2,
                            "selfHitStun":3,
                            "effect_id":"effect_hit1",
                            "direction":30,
                            "power":49,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1.2,
                            "selfHitStun":3,
                            "effect_id":"effect_hit1",
                            "direction":30,
                            "power":49,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_m"
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"sheik_grunt1",
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackSound1_id":"sheik_swing_m",
                    "cpuAttackQueue":"a_air; a_air_forward",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":43,
                            "power":18,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":43,
                            "power":18,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox3":{
                            "damage":12,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":43,
                            "power":18,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"sheik_grunt1",
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackSound1_id":"sheik_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":16,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.05,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":60,
                            "power":14,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":16,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.05,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":60,
                            "power":14,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox3":{
                            "damage":16,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.05,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":60,
                            "power":14,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "b":{
                    "linkCharge":"b_air",
                    "isLongRangeMove":true,
                    "cancelWhenAirborne":false,
                    "chargetime_max":61,
                    "charge_retain":true,
                    "customChargeGlow":null,
                    "useChargeBar":false,
                    "attackVoice1_id":"sheik_needle",
                    "attackSound1_id":"sheik_needle_charge",
                    "attackSound2_id":"sheik_needle_throw",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":1,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":30,
                            "power":90,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "linkCharge":"b",
                    "cancelWhenAirborne":false,
                    "isLongRangeMove":true,
                    "chargetime_max":61,
                    "charge_retain":true,
                    "linkFrames":true,
                    "customChargeGlow":null,
                    "useChargeBar":false,
                    "attackVoice1_id":"sheik_needle",
                    "attackSound1_id":"sheik_needle_charge",
                    "attackSound2_id":"sheik_needle_throw",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":1,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":30,
                            "power":90,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "air_ease":0,
                    "cancelWhenAirborne":false,
                    "linkFrames":true,
                    "canFallOff":true,
                    "disableForCPU":true,
                    "xSpeedDecayAir":-0.35,
                    "attackSound1_id":"sheik_uspec1",
                    "attackSound2_id":"sheik_uspec2",
                    "attackSound3_id":"sheik_uspec3",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_firehit1",
                            "direction":70,
                            "power":75,
                            "kbConstant":64,
                            "effectSound":"brawl_fire_m"
                        }}
                },
                "b_up_air":{
                    "air_ease":0,
                    "cancelWhenAirborne":false,
                    "disableForCPU":true,
                    "xSpeedDecayAir":-0.35,
                    "allowControl":true,
                    "isHorizontalRecoveryMove":true,
                    "isRecoveryMove":true,
                    "attackSound1_id":"sheik_uspec1",
                    "attackSound2_id":"sheik_uspec2",
                    "attackSound3_id":"sheik_uspec3",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_firehit1",
                            "direction":70,
                            "power":75,
                            "kbConstant":64,
                            "effectSound":"brawl_fire_m"
                        }}
                },
                "b_forward":{
                    "attackSound1_id":"sheik_whip",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":4,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"hiteffect_electric",
                            "direction":165,
                            "power":42,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_s"
                        },
                        "attackBox2":{
                            "damage":5,
                            "priority":4,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"hiteffect_electric",
                            "direction":43,
                            "power":42,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_s"
                        },
                        "attackBox3":{
                            "damage":5,
                            "priority":4,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"hiteffect_electric",
                            "direction":43,
                            "power":42,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_s"
                        },
                        "attackBox4":{
                            "damage":5,
                            "priority":4,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"hiteffect_electric",
                            "direction":43,
                            "power":42,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_s"
                        }
                    }
                },
                "b_forward_air":{
                    "attackSound1_id":"sheik_whip",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":4,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"hiteffect_electric",
                            "direction":43,
                            "power":42,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_s"
                        },
                        "attackBox2":{
                            "damage":5,
                            "priority":4,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"hiteffect_electric",
                            "direction":43,
                            "power":42,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_s"
                        },
                        "attackBox3":{
                            "damage":5,
                            "priority":4,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"hiteffect_electric",
                            "direction":43,
                            "power":42,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_s"
                        },
                        "attackBox4":{
                            "damage":5,
                            "priority":4,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"hiteffect_electric",
                            "direction":43,
                            "power":42,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_s"
                        }
                    }
                },
                "b_down":{
                    "air_ease":5,
                    "attackSound1_id":"shelda_transform1",
                    "attackSound2_id":"shelda_transform2",
                    "attackSound3_id":"shelda_transform3",
                    "attackSound4_id":"shelda_transform4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":25,
                            "selfHitStun":0,
                            "effect_id":"effect_hit3",
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_down_air":{
                    "air_ease":5,
                    "attackSound1_id":"shelda_transform1",
                    "attackSound2_id":"shelda_transform2",
                    "attackSound3_id":"shelda_transform3",
                    "attackSound4_id":"shelda_transform4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":25,
                            "selfHitStun":0,
                            "effect_id":"effect_hit3",
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackVoice1_id":"sheik_grunt1",
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":0,
                            "hitStun":2,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":80,
                            "reversableAngle":false,
                            "power":55,
                            "kbConstant":90,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "cpuAttackQueue":"a_forward; a_forwardsmash; a_air; a_air_forward",
                    "attackVoice1_id":"sheik_grunt1",
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":85,
                            "reversableAngle":false,
                            "power":67,
                            "kbConstant":55,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackVoice1_id":"sheik_grunt1",
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitLag":-1.5,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":163,
                            "reversableAngle":false,
                            "power":67,
                            "kbConstant":35,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_down":{
                    "cpuAttackQueue":"a_air_forward",
                    "canFallOff":false,
                    "attackVoice1_id":"sheik_grunt1",
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackBoxes":{"attackBox":{
                            "forceTumbleFall":true,
                            "damage":5,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":70,
                            "reversableAngle":false,
                            "power":70,
                            "kbConstant":120,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "crouch_attack":{
                    "attackVoice1_id":"sheik_grunt1",
                    "canFallOff":false,
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackSound1_id":"sheik_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":70,
                            "power":49,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":70,
                            "power":49,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "ledge_attack":{
                    "attackVoice1_id":"sheik_grunt1",
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackSound1_id":"sheik_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":6,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":60,
                            "power":135,
                            "kbConstant":22,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":6,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":60,
                            "power":135,
                            "kbConstant":22,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "getup_attack":{
                    "attackVoice1_id":"sheik_grunt1",
                    "attackVoice2_id":"sheik_grunt2",
                    "attackVoice3_id":"sheik_grunt3",
                    "attackVoice4_id":"sheik_grunt4",
                    "attackSound1_id":"sheik_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":40,
                            "power":56,
                            "kbConstant":65,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":40,
                            "power":56,
                            "kbConstant":65,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "kirby":{
                    "cancelWhenAirborne":false,
                    "isLongRangeMove":true,
                    "customChargeGlow":null,
                    "useChargeBar":false,
                    "attackVoice1_id":"sheik_needle",
                    "attackSound1_id":"sheik_needle_charge",
                    "attackSound2_id":"sheik_needle_throw",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":1,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":30,
                            "power":90,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "cancelWhenAirborne":false,
                    "isLongRangeMove":true,
                    "customChargeGlow":null,
                    "useChargeBar":false,
                    "attackVoice1_id":"sheik_needle",
                    "attackSound1_id":"sheik_needle_charge",
                    "attackSound2_id":"sheik_needle_throw",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":1,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":30,
                            "power":90,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "air_ease":0.5,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackVoice1_id":"sheik_finalsmash1",
                    "attackVoice2_id":"sheik_finalsmash2",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":60,
                            "selfHitStun":0,
                            "direction":90,
                            "power":0,
                            "kbConstant":0
                        }}
                }
            };
            var _local_4:Object = {
                "lightarrow":{
                    "linkage_id":"light_arrow",
                    "width":133,
                    "height":42,
                    "time_max":100,
                    "xspeed":60,
                    "ghost":true,
                    "xoffset":55,
                    "yoffset":-35,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":42,
                                "priority":-1,
                                "sdiDistance":0,
                                "hitStun":6,
                                "selfHitStun":0,
                                "effect_id":"Arrow_explode",
                                "direction":20,
                                "power":75,
                                "kbConstant":75,
                                "bypassShield":true,
                                "effectSound":"brawl_punch_l"
                            }}}
                },
                "uspecNoDamage":{
                    "linkage_id":"sheik_uspecNoDamage",
                    "width":47,
                    "height":48,
                    "time_max":30,
                    "ghost":true,
                    "yoffset":-20,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "hasEffect":false,
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "selfHitStun":0,
                                "direction":0,
                                "power":100,
                                "kbConstant":20,
                                "effectSound":null
                            }}}
                },
                "needle":{
                    "linkage_id":"needle",
                    "width":17,
                    "height":5,
                    "time_max":30,
                    "rotate":true,
                    "xspeed":25,
                    "xoffset":-5,
                    "yoffset":-20,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":3,
                                "ignoreChargeDamage":true,
                                "priority":2,
                                "hitStun":2,
                                "selfHitStun":0,
                                "effect_id":"effect_swordSlash",
                                "direction":70,
                                "power":34,
                                "kbConstant":24,
                                "ignoreChargeDamage":true,
                                "effectSound":"sw_brawl_hit_S"
                            }}}
                },
                "airneedle":{
                    "linkage_id":"needle",
                    "width":17,
                    "height":5,
                    "time_max":30,
                    "rotate":true,
                    "xspeed":20,
                    "yspeed":20,
                    "xoffset":-5,
                    "yoffset":-40,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":3,
                                "ignoreChargeDamage":true,
                                "priority":2,
                                "hitStun":2,
                                "selfHitStun":0,
                                "effect_id":"effect_swordSlash",
                                "direction":70,
                                "power":34,
                                "kbConstant":24,
                                "ignoreChargeDamage":true,
                                "effectSound":"sw_brawl_hit_S"
                            }}}
                },
                "uspecDamage":{
                    "linkage_id":"sheik_uspecDamage",
                    "width":47,
                    "height":48,
                    "time_max":30,
                    "ghost":true,
                    "yoffset":-20,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":10,
                                "priority":2,
                                "hitStun":2,
                                "selfHitStun":0,
                                "direction":70,
                                "power":99,
                                "kbConstant":60,
                                "burn":true,
                                "effectSound":"brawl_fire_l"
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("zelda");
        }

        public function getGUID():String
        {
            return ("68019ba3-5e17-4104-9a4c-3f9b8e4b3fe8");
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package zelda_fla

