// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//pikachu_fla.MainTimeline

package pikachu_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        public function getAudio():Array
        {
            return (new Array(pikaaaa, pika_dairLand, pika_dSmash, pika_dSpec1, pika_dSpec2, pika_dspecial, pika_nspecial, pika_uspecial, pika_fspecialchrg, pika_fspecial, pika_finalsmash, pika_aaah, pika_starko, pika_hitHard, pika_hitHard2, pika_KO, pika_KO2, pika_jumpSound, pika_nair, pika_upB, pika_sideBCharge, pika_sideBLaunch, pika_pokeball1, pika_pokeball3, pika_win1, pika_win2, pika_win3, pika_jump1, pika_taunt, pika_fair, pika_jolt, pika_grunt1, pika_grunt2, pika_grunt3, pika_grunt4, pika_smashF1, pika_smashF2, pika_smashU, pika_smashD, pika_hurt1, pika_hurt2));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"pikachu",
                "displayName":"Pikachu",
                "linkage_id":"pikachu",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"pika_head",
                "seriesIcon":"PokemonSymbol",
                "width":22,
                "height":30,
                "jumpSpeed":14,
                "jumpSpeedMidair":14,
                "jumpStartup":2,
                "shortHopSpeed":7.8,
                "max_jumpSpeed":6.2,
                "wallJump":true,
                "dodgeSpeed":10,
                "gravity":0.98,
                "weight1":77,
                "power":"pikachu",
                "norm_xSpeed":5,
                "max_xSpeed":12.2,
                "max_ySpeed":12.96,
                "fastFallSpeed":16,
                "accel_start":1,
                "accel_start_dash":1.34,
                "accel_rate":0.9,
                "accel_rate_air":0.65,
                "decel_rate":-1.19,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":28,
                "roll_delay":9,
                "getup_roll_delay":0,
                "itemScaleRatio":0.833333333333333,
                "special_type":1,
                "normalStats_id":"pikachu",
                "specialStats_id":"ichigo_special_example",
                "sounds":{
                    "jump":"pika_jump1",
                    "jump_midair":"pika_jumpSound",
                    "hurt":"pika_hurt1",
                    "hurt2":"pika_hurt2",
                    "hurtBad":"pika_hitHard",
                    "hurtBad2":"pika_hitHard2",
                    "dead":"pika_KO",
                    "dead2":"pika_KO2",
                    "pummel":"brawl_zap_m",
                    "screenko":"pika_hitHard",
                    "starko":"pika_starko",
                    "ledge_grab":null,
                    "winTheme":"PokeVictory"
                },
                "hurtFrames":4,
                "grabDamage":1
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":6,
                    "combo_max":9999999,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "reenableTimer":8,
                    "attackSound1_id":"brawl_swing_s",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":2,
                            "sdiDistance":3,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":10,
                            "power":7,
                            "kbConstant":50,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"pika_smashU",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":5,
                            "chargedPriority":7,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":85,
                            "power":40,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"pika_grunt1",
                    "attackVoice2_id":"pika_grunt2",
                    "attackVoice3_id":"pika_grunt3",
                    "attackVoice4_id":"pika_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "cpuAttackQueue":"a_up_tilt;a_up;a_air;a_air_forward;a_air_up;",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":40,
                            "kbConstant":104,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":40,
                            "kbConstant":104,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "a_forward":{
                    "xSpeedDecay":-1,
                    "canFallOff":false,
                    "attackVoice1_id":"pika_grunt1",
                    "attackVoice2_id":"pika_grunt2",
                    "attackVoice3_id":"pika_grunt3",
                    "attackVoice4_id":"pika_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "power":40,
                            "kbConstant":70,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"pika_grunt1",
                    "attackVoice2_id":"pika_grunt2",
                    "attackVoice3_id":"pika_grunt3",
                    "attackVoice4_id":"pika_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":40,
                            "power":10,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"pika_smashF1",
                    "attackVoice2_id":"pika_smashF2",
                    "attackSound1_id":"brawl_zap_l",
                    "attackSound2_id":"brawl_swing_s",
                    "attackBoxes":{"attackBox":{
                            "damage":20,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":3,
                            "selfHitStun":2,
                            "camShake":12,
                            "effect_id":"pikahiteffect_electric",
                            "direction":40,
                            "power":25,
                            "kbConstant":92,
                            "shock":true,
                            "effectSound":"brawl_zap_m"
                        }}
                },
                "a_down":{
                    "refreshRate":3,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"pika_smashD",
                    "attackSound1_id":"pika_dSmash",
                    "attackSound2_id":"pika_nair",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":5,
                            "chargedPriority":6,
                            "sdiDistance":1.2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"pikahiteffect_electric",
                            "direction":175,
                            "power":70,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_l"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":5,
                            "chargedPriority":6,
                            "sdiDistance":1.2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"pikahiteffect_electric",
                            "direction":175,
                            "power":70,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_l"
                        }
                    }
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "maintainSpeed":true,
                    "attackVoice1_id":"pika_grunt1",
                    "attackVoice2_id":"pika_grunt2",
                    "attackVoice3_id":"pika_grunt3",
                    "attackVoice4_id":"pika_grunt4",
                    "attackSound1_id":"pika_nair",
                    "cpuAttackQueue":"a_air;a_air_up;",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":58,
                            "kbConstant":73,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"pika_grunt1",
                    "attackVoice2_id":"pika_grunt2",
                    "attackVoice3_id":"pika_grunt3",
                    "attackVoice4_id":"pika_grunt4",
                    "attackSound1_id":"brawl_swing_s",
                    "cpuAttackQueue":"a_air_forward;a_air_down;a_air;b_down",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.15,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":75,
                            "power":100,
                            "kbConstant":41,
                            "effectSound":"brawl_kick_s",
                            "reversableAngle":false
                        },
                        "attackBox2":{
                            "damage":5,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.15,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":75,
                            "power":100,
                            "kbConstant":41,
                            "effectSound":"brawl_kick_s",
                            "reversableAngle":false
                        }
                    }
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":999,
                    "hit_ease":-3,
                    "allowControl":true,
                    "attackVoice1_id":"pika_grunt1",
                    "attackVoice2_id":"pika_grunt2",
                    "attackVoice3_id":"pika_grunt3",
                    "attackVoice4_id":"pika_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackSound2_id":"brawl_zap_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":3,
                            "hitStun":1,
                            "hitLag":-1.07,
                            "selfHitStun":1,
                            "effect_id":"pikahiteffect_electric",
                            "direction":74,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":20,
                            "effectSound":"brawl_zap_l"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":3,
                            "hitStun":1,
                            "hitLag":-1.07,
                            "selfHitStun":1,
                            "effect_id":"pikahiteffect_electric",
                            "direction":74,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":20,
                            "effectSound":"brawl_zap_l"
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "hit_ease":-3,
                    "allowControl":true,
                    "attackVoice1_id":"pika_grunt1",
                    "attackVoice2_id":"pika_grunt2",
                    "attackVoice3_id":"pika_grunt3",
                    "attackVoice4_id":"pika_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackSound2_id":"brawl_swing_s",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":130,
                            "power":25,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"pika_grunt1",
                    "attackVoice2_id":"pika_grunt2",
                    "attackVoice3_id":"pika_grunt3",
                    "attackVoice4_id":"pika_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackSound2_id":"brawl_zap_l",
                    "attackSound3_id":"pika_dairLand",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"pikahiteffect_electric",
                            "direction":35,
                            "power":45,
                            "kbConstant":98,
                            "effectSound":"brawl_zap_m"
                        }}
                },
                "b":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "chargeInAir":false,
                    "attackVoice1_id":"pika_nspecial",
                    "attackSound1_id":"brawl_zap_l",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":20,
                            "kbConstant":60,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargeInAir":false,
                    "attackVoice1_id":"pika_nspecial",
                    "attackSound1_id":"brawl_zap_l",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":20,
                            "kbConstant":60,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "refreshRate":10,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-1,
                    "xSpeedDecayAir":-1,
                    "air_ease":0,
                    "disableForCPU":true,
                    "allowFastFall":false,
                    "reenableTimer":20,
                    "attackVoice1_id":"pika_uspecial",
                    "attackSound1_id":"pika_upB",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":10,
                            "kbConstant":60,
                            "effectSound":"brawl_zap_l"
                        }}
                },
                "b_up_air":{
                    "refreshRate":10,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-1,
                    "xSpeedDecayAir":-1,
                    "air_ease":0,
                    "isRecoveryMove":true,
                    "disableForCPU":true,
                    "allowFastFall":false,
                    "reenableTimer":20,
                    "attackVoice1_id":"pika_uspecial",
                    "attackSound1_id":"pika_upB",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":10,
                            "kbConstant":60,
                            "effectSound":"sw_scratch"
                        }}
                },
                "b_forward":{
                    "resetMovement":true,
                    "disableForCPU":true,
                    "cancelWhenAirborne":false,
                    "cancelVoiceOnEnd":true,
                    "xSpeedDecayAir":-0.4,
                    "air_ease":7,
                    "chargetime_max":45,
                    "reenableTimer":40,
                    "attackVoice1_id":"pika_fspecialchrg",
                    "attackVoice2_id":"pika_fspecial",
                    "attackSound1_id":"pika_sideBCharge",
                    "attackSound2_id":"pika_sideBLaunch",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":25,
                            "power":40,
                            "kbConstant":80,
                            "shock":true,
                            "effectSound":"brawl_zap_l"
                        }}
                },
                "b_forward_air":{
                    "resetMovement":true,
                    "disableForCPU":true,
                    "cancelVoiceOnEnd":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecayAir":-0.4,
                    "air_ease":7,
                    "chargetime_max":45,
                    "isHorizontalRecoveryMove":true,
                    "reenableTimer":40,
                    "attackVoice1_id":"pika_fspecialchrg",
                    "attackVoice2_id":"pika_fspecial",
                    "attackSound1_id":"pika_sideBCharge",
                    "attackSound2_id":"pika_sideBLaunch",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":25,
                            "power":40,
                            "kbConstant":80,
                            "shock":true,
                            "effectSound":"brawl_zap_l"
                        }}
                },
                "b_down":{
                    "allowFastFall":false,
                    "cancelWhenAirborne":false,
                    "disableForCPU":true,
                    "attackVoice1_id":"pika_dspecial",
                    "attackSound1_id":"pika_dSpec1",
                    "attackSound2_id":"pika_dSpec2",
                    "attackBoxes":{"attackBox":{
                            "damage":17,
                            "priority":6,
                            "hitStun":6,
                            "selfHitStun":6,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"brawl_zap_m"
                        }}
                },
                "b_down_air":{
                    "allowFastFall":false,
                    "cancelWhenAirborne":false,
                    "disableForCPU":true,
                    "attackVoice1_id":"pika_dspecial",
                    "attackSound1_id":"pika_dSpec1",
                    "attackSound2_id":"pika_dSpec2",
                    "attackBoxes":{"attackBox":{
                            "damage":17,
                            "priority":6,
                            "hitStun":6,
                            "selfHitStun":6,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"brawl_zap_m"
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackVoice1_id":"pika_grunt1",
                    "attackVoice2_id":"pika_grunt2",
                    "attackVoice3_id":"pika_grunt3",
                    "attackVoice4_id":"pika_grunt4",
                    "attackSound1_id":"brawl_swing_s",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":0,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "reversableAngle":false,
                            "power":45,
                            "kbConstant":70,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"pika_grunt1",
                    "attackVoice2_id":"pika_grunt2",
                    "attackVoice3_id":"pika_grunt3",
                    "attackVoice4_id":"pika_grunt4",
                    "attackSound1_id":"brawl_swing_s",
                    "attackSound2_id":"brawl_zap_l",
                    "cpuAttackQueue":"a_air;a_air_forward;throw_forward",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "hasEffect":false,
                            "priority":0,
                            "sdiDistance":0,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"hiteffect_electric",
                            "direction":60,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":40,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_zap_m"
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackVoice1_id":"pika_grunt1",
                    "attackVoice2_id":"pika_grunt2",
                    "attackVoice3_id":"pika_grunt3",
                    "attackVoice4_id":"pika_grunt4",
                    "attackSound1_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":135,
                            "reversableAngle":false,
                            "power":75,
                            "kbConstant":50,
                            "bypassNonGrabbed":true,
                            "effectSound":null
                        }}
                },
                "throw_down":{
                    "canFallOff":false,
                    "cancelWhenAirborne":false,
                    "attackVoice1_id":"pika_grunt1",
                    "attackVoice2_id":"pika_grunt2",
                    "attackVoice3_id":"pika_grunt3",
                    "attackVoice4_id":"pika_grunt4",
                    "attackSound1_id":"pika_jumpSound",
                    "attackSound2_id":"brawl_swing_m",
                    "cpuAttackQueue":"a_air_up;a_air;a_up;a_up;a_forwardsmash;a_down;b",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":0,
                            "hitStun":4,
                            "hitLag":-1,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":45,
                            "weightKB":0,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"pika_grunt1",
                    "attackVoice2_id":"pika_grunt2",
                    "attackVoice3_id":"pika_grunt3",
                    "attackVoice4_id":"pika_grunt4",
                    "attackSound1_id":"brawl_swing_s",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":12,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"pika_grunt1",
                    "attackVoice2_id":"pika_grunt2",
                    "attackVoice3_id":"pika_grunt3",
                    "attackVoice4_id":"pika_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "weightKB":100,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":30,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "getup_attack":{
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":2,
                            "direction":40,
                            "power":30,
                            "kbConstant":60,
                            "effectSound":"brawl_kick_s",
                            "effect_id":"effect_lightHit"
                        }}
                },
                "kirby":{
                    "refreshRate":100,
                    "chargeInAir":false,
                    "attackVoice1_id":"pika_nspecial",
                    "attackSound1_id":"brawl_zap_l",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":20,
                            "kbConstant":60,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "refreshRate":100,
                    "allowControl":true,
                    "chargeInAir":false,
                    "attackVoice1_id":"pika_nspecial",
                    "attackSound1_id":"brawl_zap_l",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":20,
                            "kbConstant":60,
                            "effectSound":null
                        }}
                },
                "special":{
                    "refreshRate":2,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"pika_finalsmash",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":-1,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":-2,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"brawl_zap_m"
                        }}
                }
            };
            var _local_4:Object = {
                "thunderJolt":{
                    "linkage_id":"thunderJolt2",
                    "width":25,
                    "height":23,
                    "time_max":90,
                    "xspeed":5,
                    "yspeed":5,
                    "cancelSoundOnEnd":true,
                    "gravity":0,
                    "maxgravity":5,
                    "limit":5,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":6,
                                "priority":2,
                                "hitStun":3,
                                "selfHitStun":0,
                                "effect_id":"pikahiteffect_electric",
                                "direction":70,
                                "power":40,
                                "kbConstant":50,
                                "effectSound":"brawl_zap_m"
                            }}}
                },
                "thunder":{
                    "linkage_id":"thunder",
                    "width":22,
                    "height":156,
                    "yspeed":30,
                    "linkAttackID":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":11,
                                "priority":6,
                                "hitStun":5,
                                "selfHitStun":0,
                                "camShake":6,
                                "effect_id":"pikahiteffect_electric",
                                "direction":270,
                                "power":40,
                                "kbConstant":85,
                                "effectSound":"brawl_zap_m"
                            }}}
                },
                "pika_fs":{
                    "linkage_id":"pika_fs",
                    "width":211,
                    "height":211,
                    "time_max":300,
                    "trailEffect":"pika_fsTrail",
                    "trailEffectInterval":2,
                    "ghost":true,
                    "influenceXMovement":28,
                    "influenceYMovement":28,
                    "influenceXFactor":3,
                    "influenceYFactor":3,
                    "yoffset":-40,
                    "canBeAbsorbed":false,
                    "surviveDeathBounds":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":5,
                                "priority":-1,
                                "hitStun":2,
                                "selfHitStun":0,
                                "effect_id":"pikahiteffect_electric",
                                "direction":-9,
                                "power":50,
                                "kbConstant":110,
                                "shock":true,
                                "effectSound":"shock2"
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("pikachu");
        }

        public function getGUID():String
        {
            return ("946e3554-6365-4321-8a04-aeac03dba42a");
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package pikachu_fla

