// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//peach_fla.MainTimeline

package peach_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        public function getAudio():Array
        {
            return (new Array(Peach_Win_Theme, toad_spore, peach_fair, peach_finalsmash1, fryingpan, golfclub, oddishsfx, peach_finalsmash1, Peach_Land, Peach_TauntWin, peach_jumpSound, peach_jumpSound2, peach_sidespecialhit, turnip_hit, peach_entrance_sfx, peach_slap, tennis, toadsfx, turnippluck, umbrellaclose, umbrellaopen, peach_upspecial, peach_utilt, oddishHit, peach_grunt1, peach_grunt2, peach_grunt3, peach_grunt4, peach_attackF, peach_attackU, peach_attackD, peach_edgegrab, peach_starko, peach_hurt, peach_hurt2, peach_hurtBad, peach_hurtBad2, peach_jump, peach_ko, peach_ko2, peach_sspec1, peach_sspec2, peach_sweet, peach_yeah, peach_dizzy, peach_edgelean, peach_hi, peach_lalala, peach_tech, peach_sideBThump, peach_dress));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"peach",
                "displayName":"Peach",
                "linkage_id":"peach",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"Peach_head",
                "seriesIcon":"Mario_Symbol",
                "width":37,
                "height":59,
                "jumpSpeed":14,
                "jumpSpeedMidair":12,
                "jumpStartup":2,
                "shortHopSpeed":7,
                "max_jumpSpeed":9,
                "midAirHover":75,
                "dodgeSpeed":7,
                "gravity":1.06,
                "weight1":90,
                "power":"peach",
                "norm_xSpeed":3.8,
                "max_xSpeed":7.3,
                "max_ySpeed":8,
                "fastFallSpeed":11,
                "accel_start":0.8,
                "accel_start_dash":-1,
                "accel_rate":1,
                "accel_rate_air":1.2,
                "decel_rate":-1.47,
                "decel_rate_air":-0.2,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":27,
                "roll_delay":13,
                "getup_roll_delay":0,
                "itemScaleRatio":0.657894736842105,
                "special_type":1,
                "normalStats_id":"peach",
                "specialStats_id":null,
                "sounds":{
                    "jump":"peach_jump",
                    "jump_midair":"peach_grunt4",
                    "hurt":"peach_hurt",
                    "hurt2":"peach_hurt2",
                    "hurtBad":"peach_hurtBad",
                    "hurtBad2":"peach_hurtBad2",
                    "dead":"peach_ko",
                    "dead2":"peach_ko2",
                    "pummel":"brawl_kick_m",
                    "screenko":"peach_hurtBad",
                    "starko":"peach_starko",
                    "ledge_grab":"peach_edgegrab",
                    "winTheme":"MarioVictory"
                },
                "hurtFrames":5,
                "grabDamage":2
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":99,
                    "combo_max":1,
                    "attackSound1_id":"brawl_swing_s",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":2,
                            "weightKB":20,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":74,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"peach_slap"
                        }}
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"peach_attackU",
                    "attackSound1_id":"brawl_swing_m",
                    "attackSound2_id":"brawl_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":15,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":40,
                            "power":50,
                            "kbConstant":60,
                            "effectSound":"brawl_punch_m"
                        }
                    }
                },
                "a_up_tilt":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackSound1_id":"peach_utilt",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":5,
                            "hitStun":6,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":65,
                            "power":60,
                            "kbConstant":70,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_forward":{
                    "refreshRate":100,
                    "xSpeedDecay":-1,
                    "canFallOff":false,
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackSound2_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackSound1_id":"peach_dress",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":11,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":100,
                            "power":50,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":11,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":100,
                            "power":50,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forwardsmash":{
                    "refreshRate":100,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"peach_attackF",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":6,
                            "hitStun":2,
                            "hitLag":-1.05,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":28,
                            "power":40,
                            "kbConstant":60,
                            "effectSound":"tennis"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":6,
                            "hitStun":2,
                            "hitLag":-1.05,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":28,
                            "power":40,
                            "kbConstant":60,
                            "effectSound":"tennis"
                        }
                    }
                },
                "a_down":{
                    "refreshRate":99,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"peach_attackD",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":4,
                            "sdiDistance":3,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":157,
                            "power":38,
                            "kbConstant":80,
                            "stackKnockback":false,
                            "effectSound":"punch2"
                        }}
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":55,
                    "allowControl":true,
                    "canUseInAir":true,
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":20,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "cpuAttackQueue":"a_air;a_air_forward",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit3",
                            "direction":80,
                            "power":40,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackSound1_id":"peach_fair",
                    "attackSound2_id":"swing1",
                    "cpuAttackQueue":"a_air_forward;a_air;a_down",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":15,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":2,
                            "direction":53,
                            "power":46,
                            "kbConstant":95,
                            "effectSound":"whack",
                            "effect_id":"effect_heavyHit"
                        },
                        "attackBox2":{
                            "damage":15,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":2,
                            "direction":53,
                            "power":46,
                            "kbConstant":95,
                            "effectSound":"whack",
                            "effect_id":"effect_heavyHit"
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "cpuAttackQueue":"a_air;a_air_backward",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":135,
                            "reversableAngle":false,
                            "power":58,
                            "kbConstant":38,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":99,
                    "allowControl":true,
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackSound1_id":"brawl_swing_s",
                    "cpuAttackQueue":"a_air;a_air_forward;a_down;a_up",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":2,
                            "hitStun":1,
                            "hitLag":10,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":13,
                            "kbConstant":30,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "b":{
                    "forceGrabbable":true,
                    "refreshRate":4,
                    "attackDelay":6,
                    "cancelWhenAirborne":false,
                    "air_ease":4,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "allowFastFall":false,
                    "attackSound1_id":"toadsfx",
                    "attackSound2_id":"toad_spore",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":7,
                            "chargedPriority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":40,
                            "power":40,
                            "kbConstant":180,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "forceGrabbable":true,
                    "refreshRate":4,
                    "attackDelay":6,
                    "xSpeedAccelAir":1,
                    "air_ease":3.2,
                    "allowControlGround":false,
                    "isHorizontalRecoveryMove":true,
                    "chargeInAir":false,
                    "attackSound1_id":"toadsfx",
                    "attackSound2_id":"toad_spore",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":7,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":0,
                            "power":40,
                            "kbConstant":180,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "refreshRate":4,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "air_ease":5,
                    "facedLedgesOnly":true,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "disableForCPU":true,
                    "allowFastFall":false,
                    "attackSound1_id":"peach_upspecial",
                    "attackSound2_id":"umbrellaopen",
                    "attackSound3_id":"umbrellaclose",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":4,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":80,
                            "power":60,
                            "kbConstant":20,
                            "effectSound":"brawl_punch_s"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":4,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":80,
                            "power":60,
                            "kbConstant":20,
                            "effectSound":"brawl_punch_s"
                        }
                    }
                },
                "b_up_air":{
                    "refreshRate":4,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "air_ease":5,
                    "facedLedgesOnly":true,
                    "isRecoveryMove":true,
                    "attackSound1_id":"peach_upspecial",
                    "attackSound2_id":"umbrellaopen",
                    "attackSound3_id":"umbrellaclose",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":75,
                            "power":60,
                            "kbConstant":20,
                            "effectSound":"brawl_punch_s"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":75,
                            "power":60,
                            "kbConstant":20,
                            "effectSound":"brawl_punch_s"
                        }
                    }
                },
                "b_forward":{
                    "resetMovement":true,
                    "isLongRangeMove":true,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "reenableTimer":30,
                    "attackVoice1_id":"peach_sspec1",
                    "attackVoice2_id":"peach_sspec2",
                    "attackSound1_id":"peach_sidespecialhit",
                    "attackSound2_id":"peach_jumpSound",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.05,
                            "selfHitStun":3,
                            "direction":23,
                            "power":50,
                            "kbConstant":40,
                            "effectSound":"peach_utilt"
                        }}
                },
                "b_forward_air":{
                    "resetMovement":true,
                    "air_ease":0,
                    "isHorizontalRecoveryMove":true,
                    "cancelWhenAirborne":false,
                    "isRecoveryMove":true,
                    "reenableTimer":40,
                    "attackVoice1_id":"peach_sspec1",
                    "attackVoice2_id":"peach_sspec2",
                    "attackSound1_id":"peach_sidespecialhit",
                    "attackSound2_id":"peach_jumpSound",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.05,
                            "selfHitStun":3,
                            "direction":23,
                            "power":50,
                            "kbConstant":40,
                            "effectSound":"peach_utilt"
                        }}
                },
                "b_down":{
                    "resetMovement":true,
                    "isLongRangeMove":true,
                    "stale":false,
                    "maintainSpeed":true,
                    "allowFastFall":false,
                    "reenableTimer":20,
                    "attackSound1_id":"turnippluck",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":1,
                            "direction":30,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":null
                        }}
                },
                "b_down_air":{
                    "enabled":false,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":25,
                            "selfHitStun":0,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "throw_up":{
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":80,
                            "reversableAngle":false,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":null
                        }}
                },
                "throw_forward":{
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackSound1_id":"brawl_swing_s",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":80,
                            "reversableAngle":false,
                            "power":10,
                            "kbConstant":0,
                            "effectSound":null
                        }}
                },
                "throw_back":{
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":120,
                            "reversableAngle":false,
                            "power":10,
                            "kbConstant":200,
                            "effectSound":null
                        }}
                },
                "throw_down":{
                    "refreshRate":100,
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":-1.15,
                            "weightKB":20,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "reversableAngle":false,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":null
                        }}
                },
                "crouch_attack":{
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackSound1_id":"brawl_swing_s",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":270,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"whack"
                        }}
                },
                "ledge_attack":{
                    "xSpeedDecay":-1,
                    "xSpeedDecayAir":-1,
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":1,
                            "weightKB":110,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "attackVoice1_id":"peach_grunt1",
                    "attackVoice2_id":"peach_grunt2",
                    "attackVoice3_id":"peach_grunt3",
                    "attackVoice4_id":"peach_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":1,
                            "hitStun":2,
                            "weightKB":110,
                            "selfHitStun":2,
                            "direction":45,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"peach_slap"
                        }}
                },
                "kirby":{
                    "refreshRate":2,
                    "attackDelay":12,
                    "cancelWhenAirborne":false,
                    "air_ease":4,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "allowFastFall":false,
                    "attackSound1_id":"toadsfx",
                    "attackSound2_id":"toad_spore",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":7,
                            "chargedPriority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":40,
                            "power":40,
                            "kbConstant":200,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "refreshRate":2,
                    "attackDelay":12,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "allowFastFall":false,
                    "attackSound1_id":"toadsfx",
                    "attackSound2_id":"toad_spore",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":7,
                            "chargedPriority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":40,
                            "power":40,
                            "kbConstant":200,
                            "effectSound":null
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "canUseInAir":true,
                    "attackVoice1_id":"yeah",
                    "attackSound1_id":"peach_finalsmash1",
                    "attackSound2_id":"peach_beam_sound",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "sdiDistance":3,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":150,
                            "power":10,
                            "kbConstant":40,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object = {"peachBeam":{
                    "linkage_id":"Peach_FinalSmash",
                    "height":3000,
                    "time_max":300,
                    "ghost":true,
                    "xoffset":100,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "limit":1,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":1,
                                "priority":7,
                                "hitStun":1,
                                "selfHitStun":0,
                                "direction":150,
                                "power":30,
                                "kbConstant":100,
                                "effectSound":null
                            }}}
                }};
            var _local_5:Object = {
                "smile":{
                    "class_id":null,
                    "linkage_id":"smile",
                    "displayName":null,
                    "width":25,
                    "height":31,
                    "ricochet":true,
                    "canPickup":true,
                    "canBackToss":true,
                    "ability":"toss",
                    "time_max":2,
                    "gravity":0.7,
                    "max_gravity":10,
                    "useInAir":true,
                    "tossSpeed":3,
                    "throwSpeed":10,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":20,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_toss":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":6,
                                "priority":3,
                                "hitStun":1,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":20,
                                "kbConstant":21,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_throw":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":6,
                                "priority":-1,
                                "hitStun":2,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":20,
                                "kbConstant":21,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_neutral":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":20,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_smash":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":20,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}}
                },
                "stitch":{
                    "class_id":null,
                    "linkage_id":"stitch",
                    "displayName":null,
                    "width":25,
                    "height":31,
                    "ricochet":true,
                    "canPickup":true,
                    "canBackToss":true,
                    "ability":"toss",
                    "time_max":2,
                    "gravity":0.7,
                    "max_gravity":10,
                    "useInAir":true,
                    "tossSpeed":3,
                    "throwSpeed":10,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_toss":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":34,
                                "priority":3,
                                "hitStun":8,
                                "hitLag":-1.25,
                                "selfHitStun":8,
                                "direction":45,
                                "reversableAngle":false,
                                "power":35,
                                "kbConstant":45,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_throw":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":34,
                                "priority":3,
                                "hitStun":8,
                                "hitLag":-1.25,
                                "selfHitStun":8,
                                "direction":45,
                                "reversableAngle":false,
                                "power":35,
                                "kbConstant":45,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_neutral":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_smash":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}}
                },
                "kissy":{
                    "class_id":null,
                    "linkage_id":"kiss",
                    "displayName":null,
                    "width":25,
                    "height":31,
                    "ricochet":true,
                    "canPickup":true,
                    "canBackToss":true,
                    "ability":"toss",
                    "time_max":2,
                    "gravity":0.7,
                    "max_gravity":10,
                    "useInAir":true,
                    "tossSpeed":3,
                    "throwSpeed":10,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_toss":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":15,
                                "priority":3,
                                "hitStun":1,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":35,
                                "kbConstant":35,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_throw":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":15,
                                "priority":3,
                                "hitStun":2,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":35,
                                "kbConstant":35,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_neutral":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_smash":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}}
                },
                "angry":{
                    "class_id":null,
                    "linkage_id":"angry",
                    "displayName":null,
                    "width":25,
                    "height":31,
                    "ricochet":true,
                    "canPickup":true,
                    "canBackToss":true,
                    "ability":"toss",
                    "time_max":2,
                    "gravity":0.7,
                    "max_gravity":10,
                    "useInAir":true,
                    "tossSpeed":3,
                    "throwSpeed":10,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_toss":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":9,
                                "priority":3,
                                "hitStun":1,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":20,
                                "kbConstant":21,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_throw":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":9,
                                "priority":3,
                                "hitStun":2,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":20,
                                "kbConstant":21,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_neutral":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_smash":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}}
                },
                "crying":{
                    "class_id":null,
                    "linkage_id":"crying",
                    "displayName":null,
                    "width":25,
                    "height":31,
                    "ricochet":true,
                    "canPickup":true,
                    "canBackToss":true,
                    "ability":"toss",
                    "time_max":2,
                    "gravity":0.7,
                    "max_gravity":10,
                    "useInAir":true,
                    "tossSpeed":3,
                    "throwSpeed":10,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_toss":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":9,
                                "priority":3,
                                "hitStun":1,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":20,
                                "kbConstant":21,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_throw":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":9,
                                "priority":3,
                                "hitStun":2,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":20,
                                "kbConstant":21,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_neutral":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_smash":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}}
                },
                "eh":{
                    "class_id":null,
                    "linkage_id":"eh",
                    "displayName":null,
                    "width":25,
                    "height":31,
                    "ricochet":true,
                    "canPickup":true,
                    "canBackToss":true,
                    "ability":"toss",
                    "time_max":2,
                    "gravity":0.7,
                    "max_gravity":10,
                    "useInAir":true,
                    "tossSpeed":3,
                    "throwSpeed":10,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_toss":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":6,
                                "priority":3,
                                "hitStun":1,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":29,
                                "kbConstant":27,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_throw":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":6,
                                "priority":3,
                                "hitStun":2,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":29,
                                "kbConstant":27,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_neutral":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_smash":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}}
                },
                "happy":{
                    "class_id":null,
                    "linkage_id":"happy",
                    "displayName":null,
                    "width":25,
                    "height":31,
                    "ricochet":true,
                    "canPickup":true,
                    "canBackToss":true,
                    "ability":"toss",
                    "time_max":2,
                    "gravity":0.7,
                    "max_gravity":10,
                    "useInAir":true,
                    "tossSpeed":3,
                    "throwSpeed":10,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_toss":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":6,
                                "priority":3,
                                "hitStun":1,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":20,
                                "kbConstant":21,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_throw":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":6,
                                "priority":3,
                                "hitStun":2,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":20,
                                "kbConstant":21,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_neutral":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_smash":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}}
                },
                "shock":{
                    "class_id":null,
                    "linkage_id":"shock",
                    "displayName":null,
                    "width":25,
                    "height":31,
                    "ricochet":true,
                    "canPickup":true,
                    "canBackToss":true,
                    "ability":"toss",
                    "time_max":2,
                    "gravity":0.7,
                    "max_gravity":10,
                    "useInAir":true,
                    "tossSpeed":3,
                    "throwSpeed":10,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_toss":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":9,
                                "priority":3,
                                "hitStun":1,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":27,
                                "kbConstant":21,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_throw":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":9,
                                "priority":3,
                                "hitStun":2,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":27,
                                "kbConstant":21,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_neutral":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_smash":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}}
                },
                "whatever":{
                    "class_id":null,
                    "linkage_id":"whatever",
                    "displayName":null,
                    "width":25,
                    "height":31,
                    "ricochet":true,
                    "canPickup":true,
                    "canBackToss":true,
                    "ability":"toss",
                    "time_max":2,
                    "gravity":0.7,
                    "max_gravity":10,
                    "useInAir":true,
                    "tossSpeed":3,
                    "throwSpeed":10,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_toss":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":10,
                                "priority":3,
                                "hitStun":1,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":22,
                                "kbConstant":21,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_throw":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":10,
                                "priority":3,
                                "hitStun":2,
                                "hitLag":-1.25,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":22,
                                "kbConstant":21,
                                "effectSound":"turnip_hit"
                            }}},
                    "attack_neutral":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_smash":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}}
                },
                "ODDISH":{
                    "class_id":null,
                    "linkage_id":"ODDISH",
                    "displayName":null,
                    "width":25,
                    "height":31,
                    "ricochet":true,
                    "canPickup":true,
                    "canBackToss":true,
                    "ability":"toss",
                    "time_max":2,
                    "gravity":0.7,
                    "max_gravity":10,
                    "useInAir":true,
                    "tossSpeed":3,
                    "throwSpeed":10,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_toss":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":2,
                                "priority":7,
                                "hitStun":2,
                                "hitLag":-1.35,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":20,
                                "kbConstant":0,
                                "poison":2,
                                "poisonInterval":25,
                                "effectSound":"oddishHit"
                            }}},
                    "attack_throw":{"attackBoxes":{"attackBox":{
                                "reversableAngle":false,
                                "damage":2,
                                "priority":7,
                                "hitStun":2,
                                "hitLag":-1.35,
                                "selfHitStun":0,
                                "direction":30,
                                "reversableAngle":false,
                                "power":20,
                                "kbConstant":0,
                                "poison":2,
                                "poisonInterval":25,
                                "effectSound":"oddishHit"
                            }}},
                    "attack_neutral":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_smash":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}}
                }
            };
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("peach");
        }

        public function getGUID():String
        {
            return ("e7a05f86-e27b-4066-a4eb-447866207179");
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package peach_fla

