// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//ichigo_fla.MainTimeline

package ichigo_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        public function getAudio():Array
        {
            return (new Array(mario_kick, ichigo_hurt2, ichigo_dead2, ichigo_swing_m, ichigo_swing_l, ichigo_swing_ll, ichigo_swing_s, ichigo_swing_old, handgesture, Ichigoshunposfx, ichigo_attack1, ichigo_attack10, ichigo_attack2, ichigo_attack3, ichigo_attack4, ichigo_attack5, ichigo_attack6, ichigo_attack7, ichigo_attack8, ichigo_attack9, ichigo_bankai, ichigo_dead, ichigo_getsuga, ichigo_hithard, ichigo_hollow, ichigo_hurt, ichigo_jump, ichigo_taunt, Ichigo_Taunt2, ichigo_footstep, ichigo_walkstep, ichigo_jumpSound, Ichigo_Win, IchigoWin, ichigo_special_swing_1, ichigo_special_swing_2, Taunt_dudes));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"ichigo",
                "displayName":"Ichigo",
                "linkage_id":"ichigo",
                "linkage_id2":null,
                "linkage_id_special":"ichigo_special",
                "thumbnail":"ichigo_head",
                "seriesIcon":"bleach_symbol1",
                "width":31,
                "height":45,
                "jumpSpeed":12.5,
                "jumpSpeedMidair":15,
                "jumpStartup":3,
                "shortHopSpeed":9,
                "max_jumpSpeed":6.5,
                "dodgeSpeed":7,
                "gravity":1.16,
                "weight1":100,
                "power":"ichigo",
                "norm_xSpeed":4.2,
                "max_xSpeed":9,
                "max_ySpeed":15.4,
                "fastFallSpeed":18,
                "accel_start":1,
                "accel_start_dash":0.8,
                "accel_rate":0.8,
                "accel_rate_air":1.1,
                "decel_rate":-0.95,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":6,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_delay":13,
                "getup_roll_delay":0,
                "itemScaleRatio":0.819672131147541,
                "special_type":0,
                "normalStats_id":"ichigo",
                "specialStats_id":"ichigo_special",
                "sounds":{
                    "jump":"ichigo_jump",
                    "jump_midair":"Ichigoshunposfx",
                    "hurt":"ichigo_hurt",
                    "hurt2":"ichigo_hurt2",
                    "hurtBad":"ichigo_hithard",
                    "hurtBad2":null,
                    "dead":"ichigo_dead",
                    "dead2":"ichigo_dead2",
                    "pummel":"brawl_kick_m",
                    "screenko":"ichigo_hithard",
                    "starko":"ichigo_dead2",
                    "ledge_grab":null,
                    "winTheme":"IchigoWinv2"
                },
                "hurtFrames":4,
                "grabDamage":1,
                "fs_time_limit":600
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "canFallOff":false,
                    "attackVoice1_id":"ichigo_attack8",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"ichigo_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":70,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"sw_slash"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":70,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"sw_slash"
                        },
                        "attackBox3":{
                            "damage":4,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":70,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"sw_slash"
                        }
                    }
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ichigo_attack9",
                    "attackSound1_id":"ichigo_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":7,
                            "selfHitStun":4,
                            "effect_id":"effect_swordSlash",
                            "direction":90,
                            "power":50,
                            "kbConstant":95,
                            "effectSound":"sw_strongslash"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":7,
                            "selfHitStun":4,
                            "effect_id":"effect_swordSlash",
                            "direction":90,
                            "power":50,
                            "kbConstant":95,
                            "effectSound":"sw_strongslash"
                        },
                        "attackBox3":{
                            "damage":14,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":7,
                            "selfHitStun":4,
                            "effect_id":"effect_swordSlash",
                            "direction":90,
                            "power":50,
                            "kbConstant":95,
                            "effectSound":"sw_strongslash"
                        }
                    }
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack4",
                    "attackVoice3_id":"ichigo_attack6",
                    "attackVoice4_id":"ichigo_attack3",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"ichigo_swing_s",
                    "attackSound3_id":"ichigo_swing_l",
                    "attackSound4_id":"ichigo_swing_ll",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":40,
                            "kbConstant":90,
                            "reversableAngle":false,
                            "effectSound":"sw_slash"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":40,
                            "kbConstant":90,
                            "reversableAngle":false,
                            "effectSound":"sw_slash"
                        },
                        "attackBox3":{
                            "damage":9,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":40,
                            "kbConstant":90,
                            "reversableAngle":false,
                            "effectSound":"sw_slash"
                        }
                    }
                },
                "a_forward":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack4",
                    "attackVoice3_id":"ichigo_attack6",
                    "attackVoice4_id":"ichigo_attack3",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"ichigo_swing_s",
                    "attackSound3_id":"ichigo_swing_l",
                    "attackSound4_id":"ichigo_swing_ll",
                    "attackSound5_id":"Ichigoshunposfx",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":40,
                            "power":85,
                            "kbConstant":30,
                            "effectSound":"sw_scratch"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack4",
                    "attackVoice3_id":"ichigo_attack6",
                    "attackVoice4_id":"ichigo_attack3",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"ichigo_swing_s",
                    "attackSound3_id":"ichigo_swing_l",
                    "attackSound4_id":"ichigo_swing_ll",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":50,
                            "power":40,
                            "kbConstant":70,
                            "effectSound":"sw_slash"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":50,
                            "power":40,
                            "kbConstant":70,
                            "effectSound":"sw_slash"
                        },
                        "attackBox3":{
                            "damage":12,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":50,
                            "power":40,
                            "kbConstant":70,
                            "effectSound":"sw_slash"
                        }
                    }
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ichigo_attack5",
                    "attackSound1_id":"ichigo_swing_l",
                    "attackSound2_id":"sw_strongslash",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":9,
                            "selfHitStun":4,
                            "effect_id":"effect_swordSlash",
                            "direction":35,
                            "power":55,
                            "kbConstant":95,
                            "effectSound":"sw_strongslash"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":9,
                            "selfHitStun":4,
                            "effect_id":"effect_swordSlash",
                            "direction":35,
                            "power":55,
                            "kbConstant":95,
                            "effectSound":"sw_strongslash"
                        }
                    }
                },
                "a_down":{
                    "refreshRate":90,
                    "chargetime_max":40,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ichigo_attack10",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"smallblast",
                    "attackSound3_id":"Ichigoshunposfx",
                    "attackBoxes":{"attackBox":{
                            "ignoreChargeDamage":true,
                            "damage":4,
                            "priority":6,
                            "chargedPriority":7,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":300,
                            "power":30,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_air":{
                    "allowControl":true,
                    "cpuAttackQueue":"a_air_forward;b;b_air",
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack4",
                    "attackVoice3_id":"ichigo_attack6",
                    "attackVoice4_id":"ichigo_attack3",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"ichigo_swing_s",
                    "attackSound3_id":"ichigo_swing_l",
                    "attackSound4_id":"ichigo_swing_ll",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":11,
                            "priority":4,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":55,
                            "power":65,
                            "kbConstant":100,
                            "effectSound":"sw_slash"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1.15,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":55,
                            "power":61,
                            "kbConstant":100,
                            "effectSound":"sw_scratch"
                        },
                        "attackBox3":{
                            "damage":9,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1.15,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":55,
                            "power":61,
                            "kbConstant":100,
                            "effectSound":"sw_scratch"
                        }
                    }
                },
                "a_air_up":{
                    "allowControl":true,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack4",
                    "attackVoice3_id":"ichigo_attack6",
                    "attackVoice4_id":"ichigo_attack3",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"ichigo_swing_s",
                    "attackSound3_id":"ichigo_swing_l",
                    "attackSound4_id":"ichigo_swing_ll",
                    "cpuAttackQueue":"b_up_air",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":90,
                            "power":40,
                            "kbConstant":85,
                            "effectSound":"sw_slash"
                        }}
                },
                "a_air_forward":{
                    "allowControl":true,
                    "cpuAttackQueue":"a_air;a_air_down;a_air_down;a_air_forward;a_air_forward;b_air",
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack4",
                    "attackVoice3_id":"ichigo_attack6",
                    "attackVoice4_id":"ichigo_attack3",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"ichigo_swing_s",
                    "attackSound3_id":"ichigo_swing_l",
                    "attackSound4_id":"ichigo_swing_ll",
                    "attackSound5_id":"Ichigoshunposfx",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":2,
                            "hitStun":5,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":60,
                            "kbConstant":31,
                            "hitLag":-1.15,
                            "effectSound":"sw_slash"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":2,
                            "hitStun":5,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":60,
                            "kbConstant":31,
                            "hitLag":-1.15,
                            "effectSound":"sw_slash"
                        }
                    }
                },
                "a_air_backward":{
                    "allowControl":true,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack4",
                    "attackVoice3_id":"ichigo_attack6",
                    "attackVoice4_id":"ichigo_attack3",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"ichigo_swing_s",
                    "attackSound3_id":"ichigo_swing_l",
                    "attackSound4_id":"ichigo_swing_ll",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"sw_scratch"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"sw_scratch"
                        },
                        "attackBox3":{
                            "damage":14,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"sw_scratch"
                        }
                    }
                },
                "a_air_down":{
                    "allowControl":true,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack4",
                    "attackVoice3_id":"ichigo_attack6",
                    "attackVoice4_id":"ichigo_attack3",
                    "attackSound1_id":"ichigo_swing_l",
                    "attackSound2_id":"ichigo_swing_s",
                    "attackSound3_id":"ichigo_swing_l",
                    "attackSound4_id":"ichigo_swing_ll",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":270,
                            "power":40,
                            "kbConstant":50,
                            "effectSound":"sw_strongslash"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":270,
                            "power":40,
                            "kbConstant":50,
                            "effectSound":"sw_strongslash"
                        }
                    }
                },
                "b":{
                    "refreshRate":8,
                    "reenableTimer":28,
                    "isLongRangeMove":true,
                    "attackVoice1_id":"ichigo_attack2",
                    "attackVoice2_id":"ichigo_getsuga",
                    "attackSound1_id":"ichigo_special_swing_2",
                    "attackSound2_id":"handgesture",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":0,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "refreshRate":8,
                    "xSpeedDecayAir":-0.3,
                    "air_ease":1,
                    "allowControlGround":false,
                    "isLongRangeMove":true,
                    "chargetime_max":60,
                    "chargeInAir":false,
                    "reenableTimer":28,
                    "attackVoice1_id":"ichigo_attack2",
                    "attackVoice2_id":"ichigo_getsuga",
                    "attackSound1_id":"ichigo_special_swing_2",
                    "attackSound2_id":"handgesture",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":0,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "refreshRate":3,
                    "resetMovement":true,
                    "air_ease":5,
                    "canFallOff":false,
                    "disableForCPU":true,
                    "attackVoice1_id":"ichigo_attack7",
                    "attackSound1_id":"whip",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":1,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":-5,
                            "power":30,
                            "kbConstant":20,
                            "effectSound":"sw_scratch"
                        },
                        "attackBox2":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "hasEffect":false,
                            "direction":90,
                            "power":70,
                            "kbConstant":0
                        },
                        "attackBox3":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "hasEffect":false,
                            "direction":145,
                            "power":60,
                            "kbConstant":0
                        }
                    }
                },
                "b_up_air":{
                    "refreshRate":3,
                    "resetMovement":true,
                    "air_ease":5,
                    "allowControl":true,
                    "isRecoveryMove":true,
                    "disableForCPU":true,
                    "attackVoice1_id":"ichigo_attack7",
                    "attackSound1_id":"whip",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":1,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":30,
                            "kbConstant":80,
                            "effectSound":"sw_scratch"
                        }}
                },
                "b_forward":{
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-0.3,
                    "xSpeedDecayAir":-0.3,
                    "chargetime_max":40,
                    "attackVoice1_id":"ichigo_attack5",
                    "attackVoice2_id":"ichigo_attack2",
                    "attackSound1_id":"Ichigoshunposfx",
                    "attackSound2_id":"ichigo_special_swing_1",
                    "attackSound3_id":"handgesture",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":8,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "power":75,
                            "kbConstant":15,
                            "effectSound":"sw_scratch",
                            "reversableAngle":false
                        }}
                },
                "b_forward_air":{
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-0.3,
                    "xSpeedDecayAir":-0.3,
                    "chargetime_max":40,
                    "isHorizontalRecoveryMove":true,
                    "attackVoice1_id":"ichigo_attack5",
                    "attackVoice2_id":"ichigo_attack2",
                    "attackSound1_id":"Ichigoshunposfx",
                    "attackSound2_id":"ichigo_special_swing_1",
                    "attackSound3_id":"handgesture",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":8,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "power":75,
                            "kbConstant":10,
                            "effectSound":"sw_scratch",
                            "reversableAngle":false
                        }}
                },
                "b_down":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "allowFastFall":false,
                    "attackVoice1_id":"ichigo_attack3",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"sw_strongslash",
                    "attackSound3_id":"Ichigoshunposfx",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":7,
                            "hitStun":22,
                            "selfHitStun":2,
                            "effect_id":null,
                            "direction":280,
                            "power":0,
                            "kbConstant":0,
                            "effectSound":null
                        }}
                },
                "b_down_air":{
                    "resetMovement":true,
                    "allowControl":true,
                    "attackVoice1_id":"ichigo_attack3",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"sw_strongslash",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":40,
                            "kbConstant":95,
                            "effectSound":"kick"
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack4",
                    "attackVoice3_id":"ichigo_attack6",
                    "attackVoice4_id":"ichigo_attack3",
                    "attackSound1_id":"Ichigoshunposfx",
                    "attackSound2_id":"whoosh2",
                    "cpuAttackQueue":"a_up_tilt;a_up;a_down;a_down;a_down;a_air_up",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":0,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":90,
                            "power":90,
                            "kbConstant":25,
                            "bypassNonGrabbed":true,
                            "effectSound":"sw_scratch"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack4",
                    "attackVoice3_id":"ichigo_attack6",
                    "attackVoice4_id":"ichigo_attack3",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":60,
                            "bypassNonGrabbed":true,
                            "effectSound":null
                        }}
                },
                "throw_back":{
                    "flip":true,
                    "canFallOff":false,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackSound2_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":25,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":80,
                            "bypassNonGrabbed":true,
                            "effectSound":"kick"
                        }}
                },
                "throw_down":{
                    "refreshRate":999,
                    "canFallOff":false,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack4",
                    "attackVoice3_id":"ichigo_attack6",
                    "attackVoice4_id":"ichigo_attack3",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh2",
                    "cpuAttackQueue":"a_forwardsmash;a_forward_tilt;crouch_attack;a_air;a_air_forward;throw_up;throw_down",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "reversableAngle":false,
                            "direction":280,
                            "power":90,
                            "kbConstant":30,
                            "bypassNonGrabbed":true,
                            "effectSound":"kick"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack4",
                    "attackVoice3_id":"ichigo_attack6",
                    "attackVoice4_id":"ichigo_attack3",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"ichigo_swing_s",
                    "attackSound3_id":"ichigo_swing_l",
                    "attackSound4_id":"ichigo_swing_ll",
                    "attackSound5_id":"Ichigoshunposfx",
                    "cpuAttackQueue":"crouch_attack;a_forward;a_air_forward",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"sw_slash"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "cancelWhenAirborne":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack4",
                    "attackVoice3_id":"ichigo_attack6",
                    "attackVoice4_id":"ichigo_attack3",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"ichigo_swing_s",
                    "attackSound3_id":"ichigo_swing_l",
                    "attackSound4_id":"ichigo_swing_ll",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "weightKB":100,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"sw_scratch"
                        }}
                },
                "getup_attack":{
                    "attackVoice1_id":"ichigo_attack10",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"smallblast",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":2,
                            "weightKB":100,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":50,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "kirby":{
                    "refreshRate":100,
                    "chargetime_max":60,
                    "reenableTimer":28,
                    "attackVoice1_id":"ichigo_attack2",
                    "attackVoice2_id":"ichigo_getsuga",
                    "attackSound1_id":"ichigo_special_swing_2",
                    "attackSound2_id":"handgesture",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":35,
                            "power":20,
                            "kbConstant":105,
                            "effectSound":"sw_slash"
                        }}
                },
                "kirby_air":{
                    "refreshRate":100,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargetime_max":60,
                    "chargeInAir":false,
                    "reenableTimer":28,
                    "attackVoice1_id":"ichigo_attack2",
                    "attackVoice2_id":"ichigo_getsuga",
                    "attackSound1_id":"ichigo_special_swing_2",
                    "attackSound2_id":"handgesture",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":35,
                            "power":20,
                            "kbConstant":105,
                            "effectSound":"sw_slash"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"ichigo_bankai",
                    "attackBoxes":{"attackBox":{
                            "damage":18,
                            "priority":7,
                            "hitStun":7,
                            "selfHitStun":0,
                            "direction":50,
                            "power":50,
                            "kbConstant":95,
                            "effectSound":"brawl_punch_l"
                        }}
                }
            };
            var _local_4:Object = {
                "getsuga2":{
                    "linkage_id":"getsuga2",
                    "width":20,
                    "height":53,
                    "time_max":90,
                    "xspeed":4.8,
                    "rideGround":false,
                    "xoffset":40,
                    "attack_idle":{
                        "refreshRate":4,
                        "attackBoxes":{"attackBox":{
                                "damage":2,
                                "priority":6,
                                "hitStun":2,
                                "selfHitStun":1,
                                "effect_id":"effect_hit2",
                                "direction":82,
                                "power":55,
                                "kbConstant":0,
                                "effectSound":"brawl_punch_l"
                            }}
                    }
                },
                "getsuga":{
                    "linkage_id":"getsuga",
                    "width":36,
                    "height":93,
                    "time_max":42,
                    "xspeed":7,
                    "rideGround":false,
                    "xoffset":-6,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":28,
                                "priority":7,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "effect_id":"effect_hit2",
                                "direction":35,
                                "power":58,
                                "kbConstant":75,
                                "effectSound":"brawl_punch_l"
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getChar2(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"ichigo_special",
                "displayName":"Ichigo",
                "linkage_id":"ichigo_special",
                "linkage_id2":null,
                "linkage_id_special":"ichigo",
                "thumbnail":"ichigo_head_bankai",
                "seriesIcon":"bleach_symbol1",
                "width":26,
                "height":54,
                "jumpSpeed":10,
                "jumpSpeedMidair":10,
                "jumpStartup":2,
                "shortHopSpeed":5,
                "max_jumpSpeed":12,
                "midAirHover":80,
                "dodgeSpeed":15,
                "gravity":1,
                "weight1":102,
                "power":"ichigo",
                "norm_xSpeed":6,
                "max_xSpeed":19,
                "max_ySpeed":9,
                "fastFallSpeed":16,
                "accel_start":0.5,
                "accel_start_dash":0.914,
                "accel_rate":2,
                "accel_rate_air":0.7,
                "decel_rate":0.65,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":999999,
                "max_projectile":2,
                "tetherGrab":false,
                "roll_speed":15,
                "roll_delay":13,
                "getup_roll_delay":0,
                "itemScaleRatio":1,
                "special_type":0,
                "normalStats_id":"ichigo",
                "specialStats_id":"ichigo_bankai",
                "sounds":{
                    "jump":"ichigo_jump",
                    "jump_midair":"ichigo_jump",
                    "hurt":"ichigo_hurt",
                    "hurt2":null,
                    "hurtBad":"ichigo_hithard",
                    "hurtBad2":null,
                    "dead":"ichigo_dead",
                    "dead2":null,
                    "pummel":"brawl_kick_m",
                    "screenko":null,
                    "starko":null,
                    "ledge_grab":null,
                    "winTheme":"IchigoWinv2"
                },
                "hurtFrames":4,
                "grabDamage":2
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":3,
                    "attackDelay":10,
                    "combo_max":2,
                    "holdRepeat":true,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackVoice2_id":"ichigo_attack2",
                    "attackVoice3_id":"ichigo_attack5",
                    "attackSound1_id":"woosh",
                    "attackSound2_id":"whoosh1",
                    "attackSound3_id":"whoosh2",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":2,
                            "hitStun":8,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":60,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"sw_scratch"
                        }}
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ichigo_attack6",
                    "attackSound1_id":"woosh",
                    "attackBoxes":{"attackBox":{
                            "damage":19,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":75,
                            "power":50,
                            "kbConstant":99,
                            "effectSound":"sw_brawl_hit_H"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"ichigo_attack6",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":75,
                            "power":70,
                            "kbConstant":90,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "a_forward":{
                    "xSpeedDecay":-0.9,
                    "canFallOff":false,
                    "attackVoice1_id":"ichigo_attack4",
                    "attackSound1_id":"dash2",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":5,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":70,
                            "power":70,
                            "kbConstant":17,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"ichigo_attack4",
                    "attackSound1_id":"woosh",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":5,
                            "hitStun":3,
                            "hitLag":22,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":38,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ichigo_attack3",
                    "attackSound1_id":"whoosh2",
                    "attackBoxes":{"attackBox":{
                            "damage":17,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":7,
                            "hitLag":-1.1,
                            "selfHitStun":8,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":50,
                            "kbConstant":100,
                            "effectSound":"sw_slash"
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"ichigo_attack3",
                    "attackVoice2_id":"ichigo_attack7",
                    "attackSound1_id":"smallblast",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":6,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_air":{
                    "allowControl":true,
                    "attackVoice1_id":"ichigo_attack1",
                    "attackSound1_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":7,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":35,
                            "kbConstant":105,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "a_air_up":{
                    "allowControl":true,
                    "attackVoice1_id":"ichigo_attack3",
                    "attackSound1_id":"woosh",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":7,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":75,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "a_air_forward":{
                    "air_ease":2,
                    "allowControl":true,
                    "attackVoice1_id":"ichigo_attack10",
                    "attackSound1_id":"woosh",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":7,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":330,
                            "power":20,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_H"
                        }}
                },
                "a_air_backward":{
                    "allowControl":true,
                    "attackVoice1_id":"ichigo_attack10",
                    "attackSound1_id":"woosh",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":7,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":160,
                            "reversableAngle":false,
                            "power":25,
                            "kbConstant":110,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "a_air_down":{
                    "resetMovement":true,
                    "allowControl":true,
                    "attackVoice1_id":"ichigo_attack9",
                    "attackSound1_id":"woosh",
                    "attackBoxes":{"attackBox":{
                            "damage":16,
                            "priority":7,
                            "hitStun":6,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":270,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_H"
                        }}
                },
                "b":{
                    "refreshRate":100,
                    "resetMovement":true,
                    "chargetime_max":119,
                    "charge_retain":true,
                    "useChargeBar":false,
                    "attackVoice1_id":"ichigo_attack2",
                    "attackVoice2_id":"ichigo_getsuga",
                    "attackVoice3_id":"ichigo_hollow",
                    "attackSound1_id":null,
                    "attackSound2_id":"overwhelm",
                    "attackSound3_id":"smallblast",
                    "attackSound4_id":"woosh",
                    "attackSound5_id":"handgesture",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":3,
                            "direction":10,
                            "power":20,
                            "kbConstant":110,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "b_air":{
                    "refreshRate":100,
                    "resetMovement":true,
                    "allowControl":true,
                    "chargetime_max":119,
                    "charge_retain":true,
                    "chargeInAir":false,
                    "attackVoice1_id":"ichigo_attack2",
                    "attackVoice2_id":"ichigo_getsuga",
                    "attackVoice3_id":"ichigo_hollow",
                    "attackSound1_id":null,
                    "attackSound2_id":"overwhelm",
                    "attackSound3_id":"smallblast",
                    "attackSound4_id":"woosh",
                    "attackSound5_id":"handgesture",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":1,
                            "direction":10,
                            "power":20,
                            "kbConstant":110,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "b_up":{
                    "refreshRate":2,
                    "cancelWhenAirborne":false,
                    "airCancel":true,
                    "air_ease":2,
                    "allowControl":true,
                    "attackVoice1_id":"ichigo_attack7",
                    "attackSound1_id":"Ichigoshunposfx",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":70,
                            "power":30,
                            "kbConstant":80,
                            "effectSound":"sw_bigscratch"
                        }}
                },
                "b_up_air":{
                    "refreshRate":20,
                    "cancelWhenAirborne":false,
                    "airCancel":true,
                    "air_ease":2,
                    "allowControl":true,
                    "isRecoveryMove":true,
                    "attackVoice1_id":"ichigo_attack7",
                    "attackSound1_id":"Ichigoshunposfx",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":4,
                            "hitStun":5,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":70,
                            "power":30,
                            "kbConstant":80,
                            "effectSound":"sw_bigscratch"
                        }}
                },
                "b_forward":{
                    "cancelWhenAirborne":false,
                    "jumpCancel":true,
                    "doubleJumpCancelAttack":true,
                    "airCancel":true,
                    "xSpeedDecay":-0.7,
                    "air_ease":1,
                    "allowDoubleJump":true,
                    "attackVoice1_id":"ichigo_attack8",
                    "attackSound1_id":"Ichigoshunposfx",
                    "attackSound2_id":"woosh",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":5,
                            "hitLag":-1.05,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":50,
                            "kbConstant":88,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "b_forward_air":{
                    "cancelWhenAirborne":false,
                    "jumpCancel":true,
                    "doubleJumpCancelAttack":true,
                    "airCancel":true,
                    "xSpeedDecay":-0.5,
                    "air_ease":1,
                    "isRecoveryMove":true,
                    "allowDoubleJump":true,
                    "attackVoice1_id":"ichigo_attack8",
                    "attackSound1_id":"Ichigoshunposfx",
                    "attackSound2_id":"woosh",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":5,
                            "hitLag":-1.05,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":50,
                            "kbConstant":88,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "b_down":{
                    "refreshRate":5,
                    "resetMovement":true,
                    "air_ease":1,
                    "attackVoice1_id":"ichigo_attack3",
                    "attackSound1_id":"woosh",
                    "attackSound2_id":"overwhelm",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":5,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":-5,
                            "power":20,
                            "kbConstant":98,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "b_down_air":{
                    "refreshRate":5,
                    "resetMovement":true,
                    "air_ease":1,
                    "attackVoice1_id":"ichigo_attack3",
                    "attackSound1_id":"woosh",
                    "attackSound2_id":"overwhelm",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":7,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":-5,
                            "power":20,
                            "kbConstant":98,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "throw_up":{
                    "attackVoice1_id":"ichigo_attack3",
                    "attackVoice2_id":"ichigo_attack6",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":70,
                            "power":72,
                            "kbConstant":70,
                            "effectSound":"sw_scratch"
                        }}
                },
                "throw_forward":{
                    "attackVoice1_id":"ichigo_attack3",
                    "attackVoice2_id":"ichigo_attack6",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":"sw_slash"
                        }}
                },
                "throw_back":{
                    "flip":true,
                    "attackVoice1_id":"ichigo_attack3",
                    "attackVoice2_id":"ichigo_attack6",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":"sw_slash"
                        }}
                },
                "throw_down":{
                    "attackVoice1_id":"ichigo_attack3",
                    "attackVoice2_id":"ichigo_attack7",
                    "attackSound1_id":"smallblast",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":-3,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"punch2"
                        }}
                },
                "crouch_attack":{
                    "attackVoice1_id":"ichigo_attack4",
                    "attackSound1_id":"woosh",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":2,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":100,
                            "kbConstant":11,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackSound1_id":"whoosh3",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":1,
                            "weightKB":100,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "getup_attack":{
                    "attackVoice1_id":"ichigo_attack10",
                    "attackSound1_id":"ichigo_swing_m",
                    "attackSound2_id":"smallblast",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":2,
                            "weightKB":100,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "kirby":{
                    "chargetime_max":180,
                    "charge_retain":true,
                    "attackVoice1_id":"kirby_hammer2",
                    "attackVoice2_id":"kirby_hammer",
                    "attackVoice3_id":"kirby_hollow",
                    "attackSound1_id":null,
                    "attackSound2_id":"overwhelm",
                    "attackSound3_id":"smallblast",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":1,
                            "direction":30,
                            "power":10,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "kirby_air":{
                    "chargetime_max":180,
                    "charge_retain":true,
                    "attackVoice1_id":"kirby_hammer2",
                    "attackVoice2_id":"kirby_hammer",
                    "attackVoice3_id":"kirby_hollow",
                    "attackSound1_id":null,
                    "attackSound2_id":"overwhelm",
                    "attackSound3_id":"smallblast",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":1,
                            "direction":30,
                            "power":10,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "special":{
                    "invincible":true,
                    "attackBoxes":{"attackBox":{
                            "damage":25,
                            "priority":-1,
                            "hitStun":5,
                            "hitLag":0.96,
                            "selfHitStun":0,
                            "direction":20,
                            "power":55,
                            "kbConstant":40,
                            "bypassShield":true,
                            "effectSound":"brawl_punch_l"
                        }}
                }
            };
            var _local_4:Object = {
                "blackgetsuga2":{
                    "linkage_id":"blackgetsuga2",
                    "width":62,
                    "height":99,
                    "time_max":80,
                    "xspeed":13,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":30,
                                "priority":7,
                                "hitStun":6,
                                "selfHitStun":0,
                                "effect_id":"effect_heavyHit",
                                "direction":20,
                                "power":25,
                                "kbConstant":120,
                                "effectSound":"brawl_punch_l"
                            }}}
                },
                "blackgetsuga1":{
                    "linkage_id":"blackgetsuga1",
                    "width":69,
                    "height":136,
                    "time_max":80,
                    "xspeed":14,
                    "canBeReversed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":34,
                                "priority":5,
                                "hitStun":7,
                                "selfHitStun":0,
                                "effect_id":"effect_heavyHit",
                                "direction":20,
                                "power":25,
                                "kbConstant":120,
                                "effectSound":"brawl_punch_l"
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("ichigo");
        }

        public function getGUID():String
        {
            return ("17955b8c-7dff-4167-ada2-b89d5e1562b8");
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package ichigo_fla

