// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//fox_fla.MainTimeline

package fox_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        public function getAudio():Array
        {
            return (new Array(fox_fs, fox_footstep, landmaster_rumble, landmaster_jump, landmaster_move, fox_ilstart, fox_il, fox_upsmash, fox_star, fox_shine, fox_shine_hold, fox_jabvoice, fox_illusionvoice, fox_hurtBad, fox_hurtBad2, fox_hurt, fox_hurt2, fox_grunt4, fox_grunt3, fox_grunt2, fox_grunt1, fox_forwardsmash, fox_firecharge, fox_fireblast, fox_downsmash, fox_hereICome, fox_jumpSound, fox_jumpVoice, fox_fire, fox_dead2, fox_dead, Run_start, fox_fsmashsound, fox_blaster, fox_putaway, brawl_fox_swing_S, brawl_fox_swing_M, brawl_fox_swing_ll, brawl_fox_swing_H, fox_shinehit, victory, fox_ledge, fox_ledge_getup, landmaster_blast));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"fox",
                "displayName":"Fox",
                "linkage_id":"fox",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"fox_head",
                "seriesIcon":"Starfox_Symbol",
                "width":31,
                "height":45,
                "revivalEffect":null,
                "jumpSpeed":26,
                "jumpSpeedMidair":25,
                "jumpStartup":2,
                "shortHopSpeed":15,
                "max_jumpSpeed":7.3,
                "dodgeSpeed":8,
                "gravity":2.66,
                "weight1":80,
                "weight2":0,
                "power":"Fox",
                "norm_xSpeed":8,
                "max_xSpeed":13.7,
                "max_ySpeed":17,
                "fastFallSpeed":20,
                "accel_start":1,
                "accel_start_dash":1.12,
                "accel_rate":1.35,
                "accel_rate_air":0.7,
                "decel_rate":-1.3,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":12,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_delay":9,
                "getup_roll_delay":0,
                "itemScaleRatio":0.865800865800866,
                "special_type":1,
                "normalStats_id":"fox",
                "specialStats_id":"fox_special",
                "sounds":{
                    "jump":"fox_jumpVoice",
                    "jump_midair":"fox_jumpSound",
                    "hurt":"fox_hurt",
                    "hurt2":"fox_hurt2",
                    "hurtBad":"fox_hurtBad",
                    "hurtBad2":"fox_hurtBad2",
                    "dead":"fox_dead",
                    "dead2":"fox_dead2",
                    "pummel":"brawl_kick_s",
                    "screenko":"fox_hurtBad2",
                    "starko":"fox_star",
                    "ledge_grab":null,
                    "winTheme":"fox_victory_v2"
                },
                "hurtFrames":4,
                "grabDamage":1,
                "fs_time_limit":600
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "canFallOff":false,
                    "attackVoice1_id":"fox_jabvoice",
                    "attackSound1_id":"brawl_fox_swing_S",
                    "attackSound2_id":"brawl_fox_swing_M",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":47,
                            "power":20,
                            "kbConstant":20,
                            "effectSound":"brawl_punch_s"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":35,
                            "power":0,
                            "kbConstant":30,
                            "effectSound":"brawl_punch_s"
                        },
                        "attackBox3":{
                            "damage":2,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":35,
                            "power":0,
                            "kbConstant":30,
                            "effectSound":"brawl_punch_s"
                        }
                    }
                },
                "a_up":{
                    "cancelWhenAirborne":false,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"fox_upsmash",
                    "attackSound1_id":"brawl_fox_swing_ll",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":16,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":6,
                            "selfHitStun":3,
                            "camShake":11,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":45,
                            "kbConstant":95,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":15,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":6,
                            "selfHitStun":3,
                            "camShake":11,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":45,
                            "kbConstant":95,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"fox_harh",
                    "attackVoice2_id":"fox_grunt1",
                    "attackVoice3_id":"fox_grunt2",
                    "attackVoice4_id":"fox_grunt3",
                    "attackSound1_id":"brawl_fox_swing_M",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":80,
                            "power":30,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":80,
                            "power":30,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forward":{
                    "xSpeedDecay":0.97,
                    "canFallOff":false,
                    "attackVoice1_id":"fox_ha",
                    "attackVoice2_id":"fox_upsmash",
                    "attackSound1_id":"brawl_fox_swing_M",
                    "attackSound2_id":"brawl_fox_swing_ll",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":70,
                            "reversableAngle":false,
                            "power":35,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":70,
                            "reversableAngle":false,
                            "power":35,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"fox_grunt1",
                    "attackVoice2_id":"fox_grunt2",
                    "attackVoice3_id":"fox_grunt3",
                    "attackVoice4_id":"fox_grunt4",
                    "attackSound1_id":"brawl_fox_swing_H",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":40,
                            "power":20,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":40,
                            "power":20,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forwardsmash":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"fox_forwardsmash",
                    "attackSound1_id":"brawl_fox_swing_ll",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":4,
                            "selfHitStun":3,
                            "camShake":11,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":40,
                            "kbConstant":95,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_down":{
                    "refreshRate":90,
                    "resetMovement":true,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"fox_downsmash",
                    "attackSound1_id":"brawl_fox_swing_ll",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":4,
                            "chargedPriority":5,
                            "hitStun":5,
                            "selfHitStun":3,
                            "camShake":10,
                            "effect_id":"effect_heavyHit",
                            "direction":35,
                            "power":30,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":4,
                            "chargedPriority":5,
                            "hitStun":5,
                            "selfHitStun":3,
                            "camShake":10,
                            "effect_id":"effect_heavyHit",
                            "direction":35,
                            "power":30,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox3":{
                            "damage":14,
                            "priority":4,
                            "chargedPriority":5,
                            "hitStun":5,
                            "selfHitStun":3,
                            "camShake":10,
                            "effect_id":"effect_heavyHit",
                            "direction":35,
                            "power":30,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox4":{
                            "damage":14,
                            "priority":4,
                            "chargedPriority":5,
                            "hitStun":5,
                            "selfHitStun":3,
                            "camShake":10,
                            "effect_id":"effect_heavyHit",
                            "direction":35,
                            "power":30,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "cpuAttackQueue":"b_down;a_up;a_forward;a_forwardsmash",
                    "attackVoice1_id":"fox_grunt1",
                    "attackVoice2_id":"fox_grunt2",
                    "attackVoice3_id":"fox_grunt3",
                    "attackVoice4_id":"fox_grunt4",
                    "attackSound1_id":"brawl_fox_swing_M",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":25,
                            "kbConstant":92,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":25,
                            "kbConstant":92,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air_up":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackVoice1_id":"fox_grunt1",
                    "attackSound1_id":"brawl_fox_swing_ll",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1.15,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":92,
                            "power":0,
                            "kbConstant":120,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":5,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1.15,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":92,
                            "power":0,
                            "kbConstant":120,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air_forward":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "cpuAttackQueue":"b_down;a_air;a_air_forward;a_air_down;b_down_air;a_up;a_forward;a_forwardsmash",
                    "attackVoice1_id":"fox_grunt1",
                    "attackVoice2_id":"fox_grunt2",
                    "attackVoice3_id":"fox_grunt3",
                    "attackVoice4_id":"fox_grunt4",
                    "attackSound1_id":"brawl_fox_swing_M",
                    "attackSound2_id":"brawl_fox_swing_H",
                    "attackSound3_id":"brawl_fox_swing_ll",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":75,
                            "reversableAngle":false,
                            "power":10,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air_backward":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackVoice1_id":"fox_grunt1",
                    "attackVoice2_id":"fox_grunt2",
                    "attackVoice3_id":"fox_grunt3",
                    "attackVoice4_id":"fox_grunt4",
                    "attackSound1_id":"brawl_fox_swing_H",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":15,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":20,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":20,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air_down":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "cpuAttackQueue":"b_down;a_air;a_air_forward;a_air_down;b_down_air;a_up;a_forward;a_forwardsmash",
                    "attackVoice1_id":"fox_grunt1",
                    "attackVoice2_id":"fox_grunt2",
                    "attackVoice3_id":"fox_grunt3",
                    "attackVoice4_id":"fox_grunt4",
                    "attackSound1_id":"brawl_fox_swing_M",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":300,
                            "power":33,
                            "kbConstant":40,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "b":{
                    "refreshRate":100,
                    "combo_max":99999,
                    "isLongRangeMove":true,
                    "canBeAbsorbed":true,
                    "disableForCPU":false,
                    "chargeInAir":false,
                    "linkFrames":true,
                    "attackSound1_id":"fox_blaster",
                    "attackSound2_id":"fox_putaway",
                    "attackBoxes":{"attackBox":{
                            "damage":20,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "b_air":{
                    "refreshRate":100,
                    "allowControl":true,
                    "allowControlGround":false,
                    "combo_max":99999,
                    "isLongRangeMove":true,
                    "chargeInAir":false,
                    "linkFrames":true,
                    "attackSound1_id":"fox_blaster",
                    "attackSound2_id":"fox_putaway",
                    "attackBoxes":{"attackBox":{
                            "damage":20,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "b_up":{
                    "refreshRate":6,
                    "allowFastFall":false,
                    "cancelWhenAirborne":false,
                    "xSpeedDecayAir":-0.35,
                    "air_ease":0,
                    "allowControl":true,
                    "disableForCPU":true,
                    "controlDirection":true,
                    "attackVoice1_id":"fox_fire",
                    "attackSound1_id":"fox_firecharge",
                    "attackSound2_id":"fox_fireblast",
                    "attackSound3_id":"fox_fire",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_firehit1",
                            "direction":90,
                            "reversableAngle":false,
                            "power":28,
                            "kbConstant":30,
                            "burn":true,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "b_up_air":{
                    "refreshRate":6,
                    "cancelWhenAirborne":false,
                    "allowFastFall":false,
                    "xSpeedDecayAir":-0.35,
                    "air_ease":0,
                    "allowControl":true,
                    "isHorizontalRecoveryMove":true,
                    "isRecoveryMove":true,
                    "disableForCPU":true,
                    "linkFrames":true,
                    "controlDirection":true,
                    "attackVoice1_id":"fox_fire",
                    "attackSound1_id":"fox_firecharge",
                    "attackSound2_id":"fox_fireblast",
                    "attackSound3_id":"fox_fire",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_firehit1",
                            "direction":90,
                            "reversableAngle":false,
                            "power":28,
                            "kbConstant":30,
                            "burn":true,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "b_forward":{
                    "resetMovement":true,
                    "canFallOff":true,
                    "cancel":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-2,
                    "xSpeedDecayAir":-0.5,
                    "air_ease":0,
                    "disableForCPU":true,
                    "attackVoice1_id":"fox_illusionvoice",
                    "attackSound1_id":"fox_ilstart",
                    "attackSound2_id":"fox_il",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_hit1",
                            "direction":125,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"sw_bigscratch"
                        }}
                },
                "b_forward_air":{
                    "resetMovement":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":false,
                    "cancel":true,
                    "xSpeedDecay":-2,
                    "xSpeedDecayAir":-0.5,
                    "air_ease":0,
                    "isHorizontalRecoveryMove":true,
                    "disableForCPU":true,
                    "attackVoice1_id":"fox_illusionvoice",
                    "attackSound1_id":"fox_ilstart",
                    "attackSound2_id":"fox_il",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_hit1",
                            "direction":125,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"sw_bigscratch"
                        }}
                },
                "b_down":{
                    "refreshRate":45,
                    "jumpCancelAttack":true,
                    "doubleJumpCancelAttack":true,
                    "air_ease":3,
                    "chargetime_max":999999,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "allowJump":true,
                    "allowTurn":true,
                    "attackSound1_id":"fox_shine",
                    "attackSound2_id":"fox_shine_hold",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":6,
                            "priority":-1,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":0,
                            "reverse_character":false,
                            "power":55,
                            "kbConstant":0,
                            "shock":true,
                            "effectSound":"fox_shinehit"
                        },
                        "attackBox2":{
                            "hasEffect":false,
                            "selfHitStun":0,
                            "hitStun":0,
                            "reverse_projectile":true
                        }
                    }
                },
                "b_down_air":{
                    "resetMovement":true,
                    "jumpCancelAttack":true,
                    "doubleJumpCancelAttack":true,
                    "air_ease":3,
                    "chargetime_max":99999,
                    "holdRepeat":true,
                    "maintainSpeed":true,
                    "allowJump":true,
                    "allowTurn":true,
                    "allowDoubleJump":true,
                    "attackSound1_id":"fox_shine",
                    "attackSound2_id":"fox_shine_hold",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":6,
                            "priority":-1,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":0,
                            "reverse_character":false,
                            "power":55,
                            "kbConstant":0,
                            "shock":true,
                            "effectSound":"fox_shinehit"
                        },
                        "attackBox2":{
                            "hasEffect":false,
                            "selfHitStun":0,
                            "hitStun":0,
                            "reverse_projectile":true
                        }
                    }
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackSound1_id":"fox_blaster",
                    "attackSound2_id":"fox_putaway",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "direction":95,
                            "power":105,
                            "kbConstant":30,
                            "canDI":false,
                            "effectSound":"sw_scratch"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"fox_fthrow",
                    "attackSound1_id":"brawl_fox_swing_M",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":35,
                            "power":52,
                            "kbConstant":50,
                            "bypassNonGrabbed":true,
                            "effectSound":"whack"
                        }}
                },
                "throw_back":{
                    "flip":true,
                    "canFallOff":false,
                    "attackSound1_id":"fox_blaster",
                    "attackSound2_id":"fox_putaway",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":45,
                            "power":58,
                            "kbConstant":45,
                            "canDI":false,
                            "bypassNonGrabbed":true,
                            "effectSound":"sw_scratch"
                        }}
                },
                "throw_down":{
                    "refreshRate":5,
                    "canFallOff":false,
                    "attackSound1_id":"fox_blaster",
                    "attackSound2_id":"fox_putaway",
                    "attackBoxes":{"attackBox":{
                            "forceTumbleFall":true,
                            "damage":2,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":17,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":80,
                            "kbConstant":0,
                            "bypassNonGrabbed":true,
                            "meteorBounce":false,
                            "effectSound":"fox_blaster"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"fox_grunt1",
                    "attackVoice2_id":"fox_grunt2",
                    "attackVoice3_id":"fox_grunt3",
                    "attackVoice4_id":"fox_grunt4",
                    "attackSound1_id":"brawl_fox_swing_ll",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":2,
                            "sdiDistance":2,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":30,
                            "power":25,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackSound1_id":"brawl_fox_swing_S",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "weightKB":110,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "getup_attack":{
                    "attackVoice1_id":"fox_grunt1",
                    "attackVoice2_id":"fox_grunt2",
                    "attackVoice3_id":"fox_grunt3",
                    "attackVoice4_id":"fox_grunt4",
                    "attackSound1_id":"brawl_fox_swing_M",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":-4,
                            "power":80,
                            "kbConstant":25,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "kirby":{
                    "refreshRate":100,
                    "combo_max":99999,
                    "canBeAbsorbed":true,
                    "disableForCPU":true,
                    "chargeInAir":false,
                    "linkFrames":true,
                    "attackSound1_id":"fox_blaster",
                    "attackSound2_id":"fox_putaway",
                    "attackBoxes":{"attackBox":{
                            "damage":20,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":-1000,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "kirby_air":{
                    "refreshRate":100,
                    "allowControl":true,
                    "allowControlGround":false,
                    "combo_max":99999,
                    "disableForCPU":true,
                    "chargeInAir":false,
                    "linkFrames":true,
                    "attackSound1_id":"fox_blaster",
                    "attackSound2_id":"fox_putaway",
                    "attackBoxes":{"attackBox":{
                            "damage":20,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":-1000,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "invincible":true,
                    "allowControl":true,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackSound1_id":"fox_blaster",
                    "attackSound2_id":"fox_putaway",
                    "attackBoxes":{"attackBox":{
                            "damage":22,
                            "priority":7,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":50,
                            "power":40,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_l"
                        }}
                }
            };
            var _local_4:Object = {
                "laser":{
                    "linkage_id":"lazor",
                    "time_max":36,
                    "xspeed":24,
                    "rideGround":false,
                    "xoffset":30,
                    "yoffset":-24,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":1,
                                "hasEffect":false,
                                "priority":-1,
                                "hitStun":3,
                                "hitLag":5,
                                "selfHitStun":0,
                                "effect_id":"blasterhit",
                                "direction":0,
                                "power":0,
                                "kbConstant":0,
                                "effectSound":null
                            }}}
                },
                "uthrowLaser":{
                    "linkage_id":"UThrowLaser",
                    "time_max":45,
                    "yspeed":-20,
                    "rotate":true,
                    "xoffset":-5,
                    "yoffset":-44.5,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":1,
                                "hasEffect":false,
                                "priority":-1,
                                "hitStun":0,
                                "hitLag":0,
                                "selfHitStun":0,
                                "effect_id":"blasterhit",
                                "direction":0,
                                "power":0,
                                "kbConstant":0,
                                "effectSound":null
                            }}}
                },
                "bthrowLaser":{
                    "linkage_id":"UThrowLaser",
                    "width":4,
                    "time_max":45,
                    "yspeed":-6,
                    "rotate":true,
                    "xoffset":10,
                    "yoffset":-30,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":1,
                                "hasEffect":false,
                                "priority":-1,
                                "hitStun":5,
                                "selfHitStun":0,
                                "effect_id":"blasterhit",
                                "direction":-9,
                                "power":40,
                                "kbConstant":0,
                                "effectSound":null
                            }}}
                },
                "dthrowLaser":{
                    "linkage_id":"UThrowLaser",
                    "width":4,
                    "time_max":45,
                    "yspeed":20,
                    "rotate":true,
                    "xoffset":-12,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":1,
                                "hasEffect":false,
                                "priority":-1,
                                "hitStun":5,
                                "hitLag":5,
                                "selfHitStun":0,
                                "effect_id":"blasterhit",
                                "direction":0,
                                "power":0,
                                "kbConstant":15,
                                "effectSound":"fox_chyu"
                            }}}
                },
                "landmasterLaser":{
                    "linkage_id":"landmasterLaser",
                    "time_max":36,
                    "xdecay":-3,
                    "xspeed":18,
                    "xoffset":130,
                    "yoffset":-70,
                    "ghost":true,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":22,
                                "priority":7,
                                "hitStun":3,
                                "selfHitStun":0,
                                "effect_id":"blasterhit",
                                "direction":0,
                                "power":0,
                                "kbConstant":135,
                                "effectSound":null
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("fox");
        }

        public function getGUID():String
        {
            return ("f207f49e-ebb8-462c-a8be-0d5b7aced723");
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package fox_fla

