// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//metaknight_fla.MainTimeline

package metaknight_fla
{
    import flash.display.MovieClip;
    import flash.events.Event;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.geom.Point;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
            addEventListener(Event.ADDED_TO_STAGE, this.__setPerspectiveProjection_);
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        public function getAudio():Array
        {
            return (new Array(kirby_footstep, mk_grunt1, mk_grunt2, mk_grunt3, mk_grunt4, mk_death1, mk_death2, mk_dizzy, mk_dspec, mk_edgegrab, mk_fsmash, mk_fullhop, mk_hurt1, mk_hurt2, mk_hurtBad1, mk_hurtBad2, mk_jab, mk_sspec, mk_starko, mk_tech, mk_uthrow, mk_uspec, mk_uspec_sfx, mk_slash_l, mk_slash_m, mk_slash_s, mk_slash_xl, mk_tornado1, mk_tornado2, mk_dash, mk_uspec_start, mk_dodge, mk_sspec1, mk_sspec2, mk_sspec3, mk_sspec4, mk_sspec5, mk_sspec6, mk_sspec7, mk_sspec8, mk_sspec9, mk_step1, mk_step2, mk_turn, mk_glide, mk_jump1, mk_jump2, mk_land, mk_taunt, mk_victory, mk_fs_v1, mk_fs_v2, mk_fs_cape, mk_fs_slash));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"metaknight",
                "displayName":"MetaKnight",
                "linkage_id":"meta_knight",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"mk_head",
                "seriesIcon":"mk_symbol",
                "width":38,
                "height":38,
                "jumpSpeed":8.5,
                "jumpSpeedMidair":0,
                "jumpSpeedList":"11",
                "jumpStartup":2,
                "shortHopSpeed":7,
                "max_jumpSpeed":6,
                "midAirTurn":true,
                "dodgeSpeed":10,
                "gravity":0.8,
                "weight1":79,
                "power":"metaknight",
                "norm_xSpeed":4,
                "max_xSpeed":10.83,
                "max_ySpeed":12.8,
                "fastFallSpeed":15,
                "accel_start":1,
                "accel_start_dash":1.5,
                "accel_rate":1,
                "accel_rate_air":0.7,
                "decel_rate":-1.19,
                "decel_rate_air":-0.075,
                "glideSpeed":0,
                "holdJump":false,
                "max_jump":5,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":16,
                "roll_delay":10,
                "getup_roll_delay":0,
                "itemScaleRatio":1,
                "special_type":1,
                "normalStats_id":"metaknight",
                "specialStats_id":null,
                "sounds":{
                    "jump":"mk_jump1",
                    "jump_midair":null,
                    "hurt":"mk_hurt1",
                    "hurt2":"mk_hurt2",
                    "hurtBad":"mk_hurtBad1",
                    "hurtBad2":"mk_hurtBad2",
                    "dead":"mk_death1",
                    "dead2":"mk_death2",
                    "pummel":"sw_brawl_hit_S",
                    "screenko":"mk_hurt2",
                    "starko":"mk_starko",
                    "ledge_grab":"mk_edgegrab",
                    "winTheme":"mk_victory"
                },
                "hurtFrames":4,
                "grabDamage":3
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "attackVoice1_id":"mk_jab",
                    "attackSound1_id":"mk_slash_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":1,
                            "hitStun":1,
                            "hitLag":-1.05,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":8,
                            "kbConstant":40,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":1,
                            "hitStun":1,
                            "hitLag":-1.05,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":8,
                            "kbConstant":40,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "a_up":{
                    "canFallOff":false,
                    "chargetime_max":40,
                    "chargeClick":true,
                    "attackVoice1_id":"mk_grunt3",
                    "attackSound1_id":"mk_dodge",
                    "attackSound2_id":"mk_slash_xl",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "priority":4,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":150,
                            "power":30,
                            "kbConstant":10,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":3,
                            "priority":4,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":150,
                            "power":30,
                            "kbConstant":10,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "a_up_tilt":{
                    "attackVoice1_id":"mk_grunt1",
                    "attackVoice2_id":"mk_grunt2",
                    "attackVoice3_id":"mk_grunt3",
                    "attackVoice4_id":"mk_grunt4",
                    "attackSound1_id":"mk_slash_xl",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":85,
                            "power":40,
                            "kbConstant":130,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":2,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":85,
                            "power":40,
                            "kbConstant":130,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "a_forward":{
                    "xSpeedDecay":-1.35,
                    "canFallOff":false,
                    "attackVoice1_id":"mk_grunt1",
                    "attackVoice2_id":"mk_grunt2",
                    "attackVoice3_id":"mk_grunt3",
                    "attackVoice4_id":"mk_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":75,
                            "power":60,
                            "kbConstant":60,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forward_tilt":{
                    "combo_max":2,
                    "attackVoice1_id":"mk_grunt1",
                    "attackVoice2_id":"mk_grunt2",
                    "attackVoice3_id":"mk_grunt3",
                    "attackVoice4_id":"mk_grunt4",
                    "attackSound1_id":"mk_slash_s",
                    "attackSound2_id":"mk_slash_m",
                    "attackSound3_id":"mk_slash_l",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":50,
                            "power":6,
                            "kbConstant":60,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "chargeClick":true,
                    "attackVoice1_id":"mk_fsmash",
                    "attackSound1_id":"mk_slash_xl",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":6,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":43,
                            "power":29.4,
                            "kbConstant":120,
                            "effectSound":"sw_brawl_hit_H"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":6,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":43,
                            "power":29.4,
                            "kbConstant":120,
                            "effectSound":"sw_brawl_hit_H"
                        }
                    }
                },
                "a_down":{
                    "chargetime_max":40,
                    "chargeClick":true,
                    "attackVoice1_id":"mk_dsmash",
                    "attackSound1_id":"mk_slash_xl",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":43,
                            "power":55,
                            "kbConstant":85,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"mk_grunt1",
                    "attackVoice2_id":"mk_grunt2",
                    "attackVoice3_id":"mk_grunt3",
                    "attackVoice4_id":"mk_grunt4",
                    "attackSound1_id":"mk_slash_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":35,
                            "power":40,
                            "kbConstant":95,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":35,
                            "power":40,
                            "kbConstant":95,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"mk_grunt1",
                    "attackVoice2_id":"mk_grunt2",
                    "attackVoice3_id":"mk_grunt3",
                    "attackVoice4_id":"mk_grunt4",
                    "attackSound1_id":"mk_slash_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":6,
                            "priority":2,
                            "sdiDistance":2,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":78,
                            "power":42,
                            "kbConstant":90,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":6,
                            "priority":2,
                            "sdiDistance":2,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":78,
                            "power":42,
                            "kbConstant":90,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"mk_grunt1",
                    "attackVoice2_id":"mk_grunt2",
                    "attackVoice3_id":"mk_grunt3",
                    "attackVoice4_id":"mk_grunt4",
                    "attackSound1_id":"mk_slash_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":2,
                            "sdiDistance":2,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":60,
                            "power":25,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":2,
                            "sdiDistance":2,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":60,
                            "power":25,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"mk_grunt1",
                    "attackVoice2_id":"mk_grunt2",
                    "attackVoice3_id":"mk_grunt3",
                    "attackVoice4_id":"mk_grunt4",
                    "attackSound1_id":"mk_slash_m",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":110,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"mk_grunt1",
                    "attackVoice2_id":"mk_grunt2",
                    "attackVoice3_id":"mk_grunt3",
                    "attackVoice4_id":"mk_grunt4",
                    "attackSound1_id":"mk_slash_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":27,
                            "power":38,
                            "kbConstant":88,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":27,
                            "power":38,
                            "kbConstant":88,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "b":{
                    "refreshRate":1,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":0.75,
                    "xSpeedDecayAir":-0.7,
                    "xSpeedAccelAir":4,
                    "xSpeedCap":3,
                    "air_ease":2,
                    "allowControl":true,
                    "linkFrames":true,
                    "attackSound1_id":"mk_tornado1",
                    "attackSound2_id":"mk_tornado2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":0.5,
                            "priority":5,
                            "hitStun":1,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":105,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":0.5,
                            "priority":5,
                            "hitStun":1,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":105,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox3":{
                            "damage":0.5,
                            "priority":5,
                            "hitStun":1,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":105,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "b_air":{
                    "refreshRate":1,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":0.75,
                    "xSpeedDecayAir":-0.7,
                    "xSpeedAccelAir":4,
                    "xSpeedCap":7,
                    "air_ease":2,
                    "allowControl":true,
                    "isHorizontalRecoveryMove":true,
                    "linkFrames":true,
                    "attackSound1_id":"mk_tornado1",
                    "attackSound2_id":"mk_tornado2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":0.5,
                            "priority":5,
                            "hitStun":1,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":105,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":0.5,
                            "priority":5,
                            "hitStun":1,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":105,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox3":{
                            "damage":0.5,
                            "priority":5,
                            "hitStun":1,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":105,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "b_up":{
                    "cancelWhenAirborne":false,
                    "air_ease":2,
                    "attackVoice1_id":"mk_uspec",
                    "attackSound1_id":"mk_uspec_sfx",
                    "attackSound2_id":"mk_uspec_start",
                    "attackSound3_id":"mk_slash_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9,
                            "priority":-1,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":28,
                            "power":70,
                            "kbConstant":99,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":-1,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":28,
                            "power":70,
                            "kbConstant":99,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "b_up_air":{
                    "cancelWhenAirborne":false,
                    "air_ease":2,
                    "isHorizontalRecoveryMove":true,
                    "isRecoveryMove":true,
                    "attackVoice1_id":"mk_uspec",
                    "attackSound1_id":"mk_uspec_sfx",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9,
                            "priority":-1,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":28,
                            "power":70,
                            "kbConstant":99,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":-1,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":28,
                            "power":70,
                            "kbConstant":99,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "b_forward":{
                    "refreshRate":1,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "allowFastFall":false,
                    "linkFrames":true,
                    "controlDirection":true,
                    "attackVoice1_id":"mk_sspec",
                    "attackSound1_id":"mk_dodge",
                    "attackSound2_id":"mk_sspec1",
                    "attackSound3_id":"mk_sspec2",
                    "attackSound4_id":"mk_sspec3",
                    "attackSound5_id":"mk_sspec4",
                    "attackSound6_id":"mk_sspec5",
                    "attackSound7_id":"mk_sspec6",
                    "attackSound8_id":"mk_sspec7",
                    "attackSound9_id":"mk_sspec8",
                    "attackSound10_id":"mk_sspec9",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "reversableAngle":false,
                            "power":57,
                            "kbConstant":14,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "reversableAngle":false,
                            "power":57,
                            "kbConstant":14,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "b_forward_air":{
                    "refreshRate":1,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "isHorizontalRecoveryMove":true,
                    "allowFastFall":false,
                    "linkFrames":true,
                    "controlDirection":true,
                    "attackVoice1_id":"mk_sspec",
                    "attackSound1_id":"mk_dodge",
                    "attackSound2_id":"mk_sspec1",
                    "attackSound3_id":"mk_sspec2",
                    "attackSound4_id":"mk_sspec3",
                    "attackSound5_id":"mk_sspec4",
                    "attackSound6_id":"mk_sspec5",
                    "attackSound7_id":"mk_sspec6",
                    "attackSound8_id":"mk_sspec7",
                    "attackSound9_id":"mk_sspec8",
                    "attackSound10_id":"mk_sspec9",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "reversableAngle":false,
                            "power":57,
                            "kbConstant":14,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "reversableAngle":false,
                            "power":57,
                            "kbConstant":14,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "b_down":{
                    "cancelWhenAirborne":false,
                    "allowFastFall":false,
                    "air_ease":1,
                    "attackVoice1_id":"mk_dspec",
                    "attackSound1_id":"mk_sspec4",
                    "attackSound2_id":"mk_slash_xl",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":11,
                            "priority":4,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "effect_id":"effect_swordSlash",
                            "direction":70,
                            "power":60,
                            "kbConstant":110,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":11,
                            "priority":4,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "effect_id":"effect_swordSlash",
                            "direction":70,
                            "power":60,
                            "kbConstant":110,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "b_down_air":{
                    "cancelWhenAirborne":false,
                    "allowFastFall":false,
                    "air_ease":1,
                    "isHorizontalRecoveryMove":true,
                    "attackVoice1_id":"mk_dspec",
                    "attackSound1_id":"mk_sspec4",
                    "attackSound2_id":"mk_slash_xl",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":11,
                            "priority":4,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "effect_id":"effect_swordSlash",
                            "direction":70,
                            "power":60,
                            "kbConstant":110,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":11,
                            "priority":4,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "effect_id":"effect_swordSlash",
                            "direction":70,
                            "power":60,
                            "kbConstant":110,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "throw_up":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "attackVoice1_id":"mk_uthrow",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":-1,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":60,
                            "kbConstant":110,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"mk_grunt1",
                    "attackVoice2_id":"mk_grunt2",
                    "attackVoice3_id":"mk_grunt3",
                    "attackVoice4_id":"mk_grunt4",
                    "attackSound1_id":"mk_dodge",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":35,
                            "reversableAngle":false,
                            "power":31.5,
                            "kbConstant":115.5,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "throw_back":{
                    "attackVoice1_id":"mk_grunt1",
                    "attackVoice2_id":"mk_grunt2",
                    "attackVoice3_id":"mk_grunt3",
                    "attackVoice4_id":"mk_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":40,
                            "reversableAngle":false,
                            "power":74,
                            "kbConstant":74,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "throw_down":{
                    "refreshRate":1,
                    "canFallOff":false,
                    "attackVoice1_id":"mk_grunt1",
                    "attackVoice2_id":"mk_grunt2",
                    "attackVoice3_id":"mk_grunt3",
                    "attackVoice4_id":"mk_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "hasEffect":false,
                            "priority":-1,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":270,
                            "power":8,
                            "kbConstant":120,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "crouch_attack":{
                    "attackVoice1_id":"mk_grunt1",
                    "attackVoice2_id":"mk_grunt2",
                    "attackVoice3_id":"mk_grunt3",
                    "attackVoice4_id":"mk_grunt4",
                    "attackSound1_id":"mk_slash_m",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "power":40,
                            "kbConstant":10.5,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackSound1_id":"mk_slash_l",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":2,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":20,
                            "kbConstant":75,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "getup_attack":{
                    "attackSound1_id":"mk_slash_m",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":2,
                            "direction":40,
                            "power":59,
                            "kbConstant":57,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "kirby":{
                    "refreshRate":1,
                    "cancelWhenAirborne":false,
                    "xSpeedAccelAir":2,
                    "air_ease":2,
                    "xSpeedCap":10,
                    "allowControl":true,
                    "linkFrames":true,
                    "attackSound1_id":"mk_tornado1",
                    "attackSound2_id":"mk_tornado2",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "power":20,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "kirby_air":{
                    "refreshRate":1,
                    "cancelWhenAirborne":false,
                    "xSpeedAccelAir":2,
                    "air_ease":2,
                    "xSpeedCap":10,
                    "allowControl":true,
                    "linkFrames":true,
                    "attackSound1_id":"mk_tornado1",
                    "attackSound2_id":"mk_tornado2",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "power":20,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "special":{
                    "refreshRate":30,
                    "resetMovement":true,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"mk_fs_v1",
                    "attackVoice2_id":"mk_fs_v2",
                    "attackSound1_id":"mk_fs_cape",
                    "attackSound2_id":"mk_fs_slash",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":7,
                            "sdiDistance":0,
                            "hitStun":90,
                            "selfHitStun":2,
                            "camShake":2,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "power":1,
                            "kbConstant":1,
                            "bypassShield":true,
                            "effectSound":"mk_slash_l"
                        }}
                }
            };
            var _local_4:Object;
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("metaknight");
        }

        public function getGUID():String
        {
            return ("94736651-1a09-4993-a55b-5b96aa402331");
        }

        public function __setPerspectiveProjection_(_arg_1:Event):void
        {
            root.transform.perspectiveProjection.fieldOfView = 55;
            root.transform.perspectiveProjection.projectionCenter = new Point(275, 200);
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package metaknight_fla

