// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//bomberman_fla.MainTimeline

package bomberman_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public var missileExplosion:jetpackExplosion;

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function getAudio():Array
        {
            return (new Array(bomberman_explode, bomberman_kick, bomberman_plant, bomberman_button, bomberman_fail, bomberman_jump1, bomberman_jump2, bomberman_step1, bomberman_step2, bomberman_turn, bomberman_dash, bomberman_uspec1, bomberman_uspec2, bomberman_uspec3, bomberman_uspec_end, bomberman_slide, bomberman_victory, bomberman_fs_sound, bomberman_special_bomb, bomberman_fs_end));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"bomberman",
                "displayName":"Bomberman",
                "linkage_id":"bomberman",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"bomberman_head",
                "seriesIcon":"Bomberman_Symbol",
                "width":20,
                "height":52,
                "jumpSpeed":18,
                "jumpSpeedMidair":18,
                "jumpStartup":2,
                "shortHopSpeed":10,
                "max_jumpSpeed":6.5,
                "dodgeSpeed":8,
                "gravity":1.52,
                "weight1":97,
                "power":"bomberman",
                "norm_xSpeed":6.1,
                "max_xSpeed":10,
                "max_ySpeed":15.1,
                "fastFallSpeed":17.1,
                "accel_start":1.73,
                "accel_start_dash":-1,
                "accel_rate":2,
                "accel_rate_air":2.5,
                "decel_rate":-1.3,
                "decel_rate_air":-0.5,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":20,
                "tetherGrab":false,
                "roll_speed":21,
                "roll_delay":15,
                "getup_roll_delay":0,
                "itemScaleRatio":1,
                "special_type":1,
                "normalStats_id":"bomberman",
                "specialStats_id":null,
                "sounds":{
                    "jump":"bomberman_jump1",
                    "jump_midair":"bomberman_jump2",
                    "hurt":null,
                    "hurt2":null,
                    "hurtBad":null,
                    "hurtBad2":null,
                    "dead":null,
                    "dead2":null,
                    "pummel":"brawl_kick_m",
                    "screenko":null,
                    "starko":null,
                    "ledge_grab":null,
                    "winTheme":"BombermanVictory"
                },
                "hurtFrames":4,
                "grabDamage":2,
                "fs_time_limit":300
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_s",
                    "attackSound2_id":"brawl_swing_s",
                    "attackSound3_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":1,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":55,
                            "power":0,
                            "kbConstant":50,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"bomberman_explode",
                    "attackSound2_id":"sw_brawl_swing_H",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "priority":5,
                            "hitStun":1,
                            "hitLag":-2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":110,
                            "power":80,
                            "kbConstant":0,
                            "effectSound":"brawl_fire_l"
                        },
                        "attackBox2":{
                            "damage":3,
                            "priority":5,
                            "hitStun":1,
                            "hitLag":-2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":110,
                            "power":80,
                            "kbConstant":0,
                            "effectSound":"brawl_fire_l"
                        }
                    }
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackSound1_id":"sw_brawl_swing_M",
                    "cpuAttackQueue":"a_up;a_up_tilt;a_forwardsmash;a_down",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":40,
                            "kbConstant":130,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":40,
                            "kbConstant":130,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox3":{
                            "damage":7,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":40,
                            "kbConstant":130,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forward":{
                    "canFallOff":false,
                    "attackSound1_id":"whoosh3",
                    "cpuAttackQueue":"a_air;a_air_forward;a_air_up;a_air_down",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":2,
                            "direction":50,
                            "power":40,
                            "kbConstant":60,
                            "effectSound":"whack"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":46,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":5,
                            "selfHitStun":3,
                            "direction":42,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":4,
                            "hitStun":5,
                            "selfHitStun":3,
                            "direction":42,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "a_down":{
                    "cancelWhenAirborne":false,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"bomberman_explode",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":6,
                            "hitStun":5,
                            "selfHitStun":1,
                            "camShake":7,
                            "effect_id":"effect_firehit1",
                            "direction":40,
                            "power":84,
                            "kbConstant":75,
                            "burn":true,
                            "effectSound":"brawl_fire_m"
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":6,
                            "hitStun":5,
                            "selfHitStun":1,
                            "camShake":7,
                            "effect_id":"effect_firehit1",
                            "direction":40,
                            "power":84,
                            "kbConstant":75,
                            "burn":true,
                            "effectSound":"brawl_fire_m"
                        }
                    }
                },
                "a_air":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackSound1_id":"brawl_swing_s",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":35,
                            "power":60,
                            "kbConstant":26,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":35,
                            "power":60,
                            "kbConstant":26,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "a_air_up":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":11,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":82,
                            "power":56,
                            "kbConstant":85,
                            "effectSound":"whack"
                        },
                        "attackBox2":{
                            "damage":11,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":82,
                            "power":56,
                            "kbConstant":85,
                            "effectSound":"whack"
                        }
                    }
                },
                "a_air_forward":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackSound1_id":"whoosh3",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":5,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "camShake":2,
                            "effect_id":"effect_hit2",
                            "direction":52,
                            "power":55,
                            "kbConstant":95,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":5,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "camShake":2,
                            "effect_id":"effect_hit2",
                            "direction":52,
                            "power":55,
                            "kbConstant":95,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "a_air_backward":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackSound1_id":"brawl_swing_s",
                    "cpuAttackQueue":"a_air_backward",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":140,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":140,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_down":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackSound1_id":"brawl_swing_s",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.5,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "reversableAngle":false,
                            "power":28,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":5,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.5,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "reversableAngle":false,
                            "power":28,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "b":{
                    "cancelWhenAirborne":false,
                    "isLongRangeMove":true,
                    "xSpeedCap":4,
                    "chargetime_max":1,
                    "holdRepeat":true,
                    "allowTurn":true,
                    "linkFrames":true,
                    "reenableTimer":3,
                    "attackSound1_id":"bomberman_plant",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "cancelWhenAirborne":false,
                    "isLongRangeMove":true,
                    "xSpeedCap":4,
                    "chargetime_max":1,
                    "holdRepeat":true,
                    "allowRun":true,
                    "allowTurn":true,
                    "linkFrames":true,
                    "reenableTimer":3,
                    "attackSound1_id":"bomberman_plant",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":0.01,
                    "allowControl":true,
                    "allowControlGround":false,
                    "canFallOff":false,
                    "isRecoveryMove":true,
                    "attackSound1_id":"bomberman_uspec1",
                    "attackSound2_id":"bomberman_uspec2",
                    "attackSound3_id":"bomberman_uspec3",
                    "attackSound4_id":"bomberman_uspec_end",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":-1,
                            "hitStun":4,
                            "hitLag":-1,
                            "selfHitStun":4,
                            "effect_id":"effect_firehit1",
                            "burn":true,
                            "direction":40,
                            "power":98,
                            "kbConstant":50,
                            "effectSound":"brawl_fire_l"
                        }}
                },
                "b_up_air":{
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":0.01,
                    "allowControl":true,
                    "allowControlGround":false,
                    "isRecoveryMove":true,
                    "attackSound1_id":"bomberman_uspec1",
                    "attackSound2_id":"bomberman_uspec2",
                    "attackSound3_id":"bomberman_uspec3",
                    "attackSound4_id":"bomberman_uspec_end",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":-1,
                            "hitStun":4,
                            "hitLag":-1,
                            "selfHitStun":4,
                            "effect_id":"effect_firehit1",
                            "burn":true,
                            "direction":40,
                            "power":98,
                            "kbConstant":50,
                            "effectSound":"brawl_fire_l"
                        }}
                },
                "b_forward":{
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-1,
                    "attackSound1_id":"bomberman_kick",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":6,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":20,
                            "power":45,
                            "kbConstant":29,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_forward_air":{
                    "attackSound1_id":"bomberman_kick",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":6,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":60,
                            "power":98,
                            "kbConstant":35,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_down":{
                    "reenableTimer":70,
                    "disableForCPU":true,
                    "attackSound1_id":"bomberman_fail",
                    "attackSound2_id":"bomberman_button",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":1,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_down_air":{
                    "reenableTimer":70,
                    "disableForCPU":true,
                    "attackSound1_id":"bomberman_fail",
                    "attackSound2_id":"bomberman_button",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":1,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air;a_air_up;a_air_down;a_up",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":70,
                            "reversableAngle":false,
                            "power":40,
                            "kbConstant":110,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackSound1_id":"bomberman_slide",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":35,
                            "reversableAngle":false,
                            "power":55,
                            "kbConstant":110,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":160,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":45,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_down":{
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air;a_air_down;a_air_up;a_air_forward;a_up_tilt;a_up;a_forwardsmash",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":0,
                            "hitStun":15,
                            "hitLag":-1.15,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":70,
                            "reversableAngle":false,
                            "power":65,
                            "kbConstant":45,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "crouch_attack":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackSound1_id":"bomberman_slide",
                    "cpuAttackQueue":"a_air;a_air_forward;a_air_up",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":68,
                            "power":105,
                            "kbConstant":22,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":50,
                            "power":85,
                            "kbConstant":28,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "getup_attack":{
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":25,
                            "power":63,
                            "kbConstant":30,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "kirby":{
                    "cancelWhenAirborne":false,
                    "xSpeedCap":2,
                    "chargetime_max":80,
                    "holdRepeat":true,
                    "reenableTimer":3,
                    "attackSound1_id":"bomberman_plant",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "cancelWhenAirborne":false,
                    "xSpeedCap":2,
                    "chargetime_max":80,
                    "holdRepeat":true,
                    "reenableTimer":3,
                    "attackSound1_id":"bomberman_plant",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "canUseInAir":true,
                    "attackSound1_id":"bomberman_fs_sound",
                    "attackSound2_id":"bomberman_special_bomb",
                    "attackSound3_id":"bomberman_fail",
                    "attackSound4_id":"bomberman_fs_end",
                    "attackBoxes":{"attackBox":{
                            "damage":18,
                            "priority":7,
                            "hitStun":7,
                            "hitLag":-0.96,
                            "selfHitStun":0,
                            "direction":50,
                            "power":75,
                            "kbConstant":25,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "crash":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackSound1_id":"whoosh3",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_firehit1",
                            "direction":40,
                            "power":45,
                            "kbConstant":13,
                            "effectSound":"sw_slash"
                        }}
                }
            };
            var _local_4:Object = {
                "heldbomb":{
                    "linkage_id":"NSpecBomb",
                    "inheritPalette":true,
                    "time_max":999,
                    "followUser":true,
                    "yoffset":-6,
                    "limit":1,
                    "lockTrajectory":true
                },
                "bomb1dropped":{
                    "linkage_id":"NSpecBomb1Dropped",
                    "inheritPalette":true,
                    "width":20,
                    "height":20,
                    "time_max":-1,
                    "gravity":1.8,
                    "maxgravity":8,
                    "xoffset":10,
                    "yoffset":-10,
                    "canBeAbsorbed":false,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "burn":true,
                                "damage":6,
                                "priority":-1,
                                "hitStun":5,
                                "hitLag":-1.2,
                                "selfHitStun":0,
                                "direction":90,
                                "power":49,
                                "kbConstant":60,
                                "effectSound":"brawl_fire_l"
                            }}}
                },
                "bomb2dropped":{
                    "linkage_id":"NSpecBomb2Dropped",
                    "inheritPalette":true,
                    "width":30,
                    "height":30,
                    "time_max":-1,
                    "gravity":1.8,
                    "maxgravity":9,
                    "xoffset":10,
                    "yoffset":-15,
                    "canBeAbsorbed":false,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "burn":true,
                                "damage":10,
                                "priority":-1,
                                "hitStun":6,
                                "hitLag":-1.2,
                                "selfHitStun":0,
                                "direction":90,
                                "power":63,
                                "kbConstant":60,
                                "effectSound":"brawl_fire_l"
                            }}}
                },
                "bomb3dropped":{
                    "linkage_id":"NSpecBomb3Dropped",
                    "inheritPalette":true,
                    "width":50,
                    "height":50,
                    "time_max":-1,
                    "gravity":1.8,
                    "maxgravity":10,
                    "xoffset":10,
                    "yoffset":-15,
                    "canBeAbsorbed":false,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "burn":true,
                                "damage":14,
                                "priority":-1,
                                "hitStun":7,
                                "hitLag":-1.2,
                                "selfHitStun":0,
                                "direction":90,
                                "power":77,
                                "kbConstant":87,
                                "effectSound":"brawl_fire_l"
                            }}}
                },
                "FSbomb":{
                    "linkage_id":"NSpecBombThrown",
                    "inheritPalette":true,
                    "width":20,
                    "height":20,
                    "time_max":-1,
                    "gravity":1.8,
                    "maxgravity":16,
                    "xoffset":-10,
                    "canBeAbsorbed":false,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "burn":true,
                                "damage":28,
                                "priority":-1,
                                "hitStun":1,
                                "selfHitStun":0,
                                "direction":90,
                                "power":35,
                                "kbConstant":60,
                                "effectSound":"brawl_fire_l"
                            }}}
                },
                "bigFSbomb":{
                    "linkage_id":"bmanFSBomb",
                    "inheritPalette":true,
                    "width":50,
                    "height":50,
                    "time_max":-1,
                    "gravity":1.8,
                    "maxgravity":18,
                    "yoffset":30,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "limit":3,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "burn":true,
                                "damage":10,
                                "priority":-1,
                                "hitStun":7,
                                "hitLag":-1.2,
                                "selfHitStun":0,
                                "direction":90,
                                "power":65,
                                "kbConstant":90,
                                "effectSound":"brawl_fire_l"
                            }}}
                },
                "kirbyBManBomb":{
                    "linkage_id":"NSpecBombThrown",
                    "inheritPalette":true,
                    "width":20,
                    "height":20,
                    "time_max":75,
                    "xspeed":8,
                    "yspeed":-10,
                    "gravity":1.8,
                    "maxgravity":12,
                    "xoffset":10,
                    "yoffset":-45,
                    "canBeAbsorbed":false,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "ignoreChargeDamage":true,
                                "burn":true,
                                "damage":10,
                                "priority":-1,
                                "hitStun":1,
                                "selfHitStun":0,
                                "direction":90,
                                "power":35,
                                "kbConstant":60,
                                "effectSound":"brawl_fire_l"
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("bomberman");
        }

        public function getGUID():String
        {
            return ("5db5bfc3-78aa-4ae8-8208-c39174673a01");
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package bomberman_fla

