// Decompiled by AS3 Sorcerer 6.20
// www.as3sorcerer.com

//naruto_fla.MainTimeline

package naruto_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public var stance:naruto_special;

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function getAudio():Array
        {
            return (new Array(naruto_footstep, Run_start, kyuubi_naruto_taunt_sfx1, naruto_attack10, naruto_attack11, naruto_attack12, naruto_attack13, naruto_attack14, naruto_attack15, naruto_attack16, naruto_attack17, naruto_attackD, naruto_attackF, naruto_attackU, naruto_bforward_throw, naruto_bunshin, naruto_chargerasengan, naruto_dead, naruto_dead2, naruto_explodeoodama, naruto_hitHard, naruto_hitHard2, naruto_hurt, naruto_hurt2, naruto_jump1, naruto_jump2, naruto_kyuubiattack1, naruto_kyuubiattack2, naruto_kyuubiattack3, naruto_kyuubiattack4, naruto_kyuubiattack5, naruto_kyuubiattack6, naruto_oodamarasengan, naruto_rasengan, naruto_seal, naruto_starko, naruto_taunt, naruto_taunt_special, naruto_transform1, naruto_transform2, naruto_transformexplosion, naruto_win, NarutoVictory, new_naruto_rasengan, rasengan_sfx1, Naruto_jump_air, Naruto_jump_air2, naruto_ledge_grab, naruto_ledge_getup, naruto_beam_attack, naruto_cloneattack1, naruto_cloneattack2, naruto_sexy, naruto_kunai, naruto_grunt1, naruto_grunt2, naruto_grunt3, naruto_grunt4));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"naruto",
                "displayName":"Naruto",
                "linkage_id":"naruto",
                "linkage_id2":null,
                "linkage_id_special":"naruto_special",
                "thumbnail":"naruto_head",
                "seriesIcon":"Narutosymbol",
                "width":29,
                "height":52,
                "jumpSpeed":16,
                "jumpSpeedMidair":16,
                "jumpStartup":2,
                "shortHopSpeed":7,
                "max_jumpSpeed":6,
                "dodgeSpeed":8,
                "gravity":1.2,
                "weight1":85,
                "power":"naruto",
                "norm_xSpeed":5.5,
                "max_xSpeed":10,
                "max_ySpeed":12,
                "fastFallSpeed":15,
                "accel_start":1.3,
                "accel_start_dash":1.45,
                "accel_rate":1.2,
                "accel_rate_air":0.9,
                "decel_rate":-1.41,
                "decel_rate_air":-0.13,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_delay":14,
                "getup_roll_delay":0,
                "itemScaleRatio":0.833333333333333,
                "special_type":0,
                "normalStats_id":"naruto",
                "specialStats_id":"naruto_special",
                "sounds":{
                    "jump":"JPN_naruto_jump1",
                    "jump_midair":"JPN_naruto_jump2_2",
                    "hurt":"JPN_naruto_hurt1",
                    "hurt2":"JPN_naruto_hurt2",
                    "hurtBad":"JPN_naruto_hurtBad1",
                    "hurtBad2":"JPN_naruto_hurtBad2",
                    "dead":"JPN_naruto_dead1",
                    "dead2":"JPN_naruto_dead2",
                    "pummel":"brawl_punch_m",
                    "screenko":"JPN_naruto_hurtBad2",
                    "starko":"naruto_starko",
                    "ledge_grab":null,
                    "winTheme":"NarutoVictory"
                },
                "hurtFrames":4,
                "grabDamage":1,
                "crouchWalkSpeed":4.5,
                "fs_time_limit":600
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "combo_max":2,
                    "canFallOff":false,
                    "attackVoice1_id":"JPN_naruto_grunt1",
                    "attackVoice2_id":"JPN_naruto_grunt2",
                    "attackVoice3_id":"ENG_naruto_grunt1",
                    "attackVoice4_id":"ENG_naruto_grunt2",
                    "attackSound1_id":"brawl_swing_s",
                    "attackSound2_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "priority":1,
                            "hitStun":5,
                            "hitLag":-1.3,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":55,
                            "power":15,
                            "kbConstant":0,
                            "effectSound":"brawl_punch_s"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":1,
                            "hitStun":5,
                            "hitLag":-1.3,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":55,
                            "power":15,
                            "kbConstant":0,
                            "effectSound":"brawl_punch_s"
                        }
                    }
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"JPN_naruto_heavy_grunt3",
                    "attackVoice2_id":"ENG_naruto_heavygrunt1",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":2,
                            "camShake":10,
                            "effect_id":"effect_hit1",
                            "direction":90,
                            "power":30,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "cpuAttackQueue":"a_up; a_forwardsmash; a_up_tilt; a_down; a_air; b",
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "power":35,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "power":35,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forward":{
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air; a_air_forward; a_air; a_air_backward; a_air_up; b_up",
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackSound1_id":"brawl_swing_s",
                    "attackSound2_id":"brawl_swing_m",
                    "xSpeedDecay":0,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.05,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":20,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":0,
                            "stackKnockback":false,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.05,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":20,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":0,
                            "stackKnockback":false,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "a_forward_tilt":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":40,
                            "power":14,
                            "kbConstant":140,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "a_forwardsmash":{
                    "xSpeedDecay":0.2,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"JPN_naruto_heavy_grunt1",
                    "attackVoice2_id":"ENG_naruto_takethis",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":5,
                            "selfHitStun":5,
                            "camShake":11,
                            "effect_id":"effect_hit2",
                            "direction":27,
                            "power":29,
                            "kbConstant":101,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":4,
                            "hitStun":5,
                            "selfHitStun":5,
                            "camShake":11,
                            "effect_id":"effect_hit2",
                            "direction":27,
                            "power":29,
                            "kbConstant":101,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox3":{
                            "damage":14,
                            "priority":4,
                            "hitStun":5,
                            "selfHitStun":5,
                            "camShake":11,
                            "effect_id":"effect_hit2",
                            "direction":27,
                            "power":29,
                            "kbConstant":101,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"JPN_naruto_heavy_grunt2",
                    "attackVoice2_id":"ENG_naruto_heavygrunt1",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":2,
                            "camShake":10,
                            "effect_id":"effect_hit2",
                            "direction":25,
                            "power":35,
                            "kbConstant":76,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":2,
                            "camShake":10,
                            "effect_id":"effect_hit2",
                            "direction":25,
                            "power":35,
                            "kbConstant":76,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "cpuAttackQueue":"a_air; a_air_forward; b_air",
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackSound1_id":"brawl_swing_s",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":43,
                            "power":42,
                            "kbConstant":60,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":43,
                            "power":42,
                            "kbConstant":60,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox3":{
                            "damage":8,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":43,
                            "power":42,
                            "kbConstant":60,
                            "effectSound":"brawl_punch_m"
                        }
                    }
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "cpuAttackQueue":"a_air_up; a_air_forward; a_air_backward; a_air",
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.07,
                            "selfHitStun":2,
                            "camShake":11,
                            "effect_id":"effect_hit3",
                            "direction":90,
                            "power":10,
                            "kbConstant":107,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.07,
                            "selfHitStun":2,
                            "camShake":11,
                            "effect_id":"effect_hit3",
                            "direction":90,
                            "power":10,
                            "kbConstant":107,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackSound1_id":"woosh",
                    "attackSound2_id":"brawl_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":5,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":300,
                            "reversableAngle":false,
                            "power":12.8,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":5,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":300,
                            "reversableAngle":false,
                            "power":12.8,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "cpuAttackQueue":"a_air_backward",
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":11,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":150,
                            "reversableAngle":false,
                            "power":28,
                            "kbConstant":108,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":11,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":150,
                            "reversableAngle":false,
                            "power":28,
                            "kbConstant":108,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "resetMovement":true,
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackSound2_id":"whoosh1",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":60,
                            "reversableAngle":false,
                            "power":16,
                            "kbConstant":82,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":60,
                            "reversableAngle":false,
                            "power":16,
                            "kbConstant":82,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox3":{
                            "damage":9,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":60,
                            "reversableAngle":false,
                            "power":16,
                            "kbConstant":82,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "b":{
                    "linkCharge":"b_air",
                    "linkCharge":true,
                    "cancelSoundOnEnd":true,
                    "cancelVoiceOnEnd":true,
                    "allowControlGround":false,
                    "chargetime_max":75,
                    "charge_retain":true,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "customChargeGlow":"naruto_fullChargeFlash",
                    "useChargeBar":false,
                    "attackVoice1_id":"JPN_naruto_chakra",
                    "attackVoice2_id":"JPN_naruto_rasengan",
                    "attackVoice3_id":"ENG_naruto_chakra",
                    "attackVoice4_id":"ENG_naruto_rasengan",
                    "attackVoice5_id":"JPN_naruto_rasenshuriken",
                    "attackVoice6_id":"ENG_naruto_rasenshuriken",
                    "attackSound1_id":"smallblast",
                    "attackSound2_id":"naruto_explodeoodama",
                    "attackSound3_id":"naruto_sfx_rasengan_charge",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":5,
                            "sdiDistance":0,
                            "hitStun":5,
                            "hitLag":0.93,
                            "selfHitStun":0,
                            "camShake":9,
                            "direction":30,
                            "power":30,
                            "kbConstant":60,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_air":{
                    "linkCharge":"b",
                    "linkCharge":true,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargetime_max":75,
                    "charge_retain":true,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "customChargeGlow":"naruto_fullChargeFlash",
                    "useChargeBar":false,
                    "attackVoice1_id":"JPN_naruto_chakra",
                    "attackVoice2_id":"JPN_naruto_rasengan",
                    "attackVoice3_id":"ENG_naruto_chakra",
                    "attackVoice4_id":"ENG_naruto_rasengan",
                    "attackVoice5_id":"JPN_naruto_rasenshuriken",
                    "attackVoice6_id":"ENG_naruto_rasenshuriken",
                    "attackSound1_id":"smallblast",
                    "attackSound2_id":"naruto_explodeoodama",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":5,
                            "sdiDistance":0,
                            "hitStun":5,
                            "hitLag":0.93,
                            "selfHitStun":0,
                            "direction":30,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":60,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_up":{
                    "cancelWhenAirborne":false,
                    "xSpeedCap":6,
                    "attackVoice1_id":"JPN_naruto_dash_chakra",
                    "attackVoice2_id":"ENG_naruto_chakradash_short",
                    "attackSound1_id":"naruto_bunshin",
                    "attackSound2_id":"naruto_seal",
                    "attackSound3_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":2,
                            "hitStun":0,
                            "hitLag":20,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "reversableAngle":false,
                            "power":85,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":2,
                            "hitStun":0,
                            "hitLag":20,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":60,
                            "reversableAngle":false,
                            "power":85,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "b_up_air":{
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "xSpeedCap":6,
                    "allowControl":true,
                    "isRecoveryMove":true,
                    "attackVoice1_id":"JPN_naruto_dash_chakra",
                    "attackVoice2_id":"ENG_naruto_chakradash_short",
                    "attackSound1_id":"naruto_bunshin",
                    "attackSound2_id":"naruto_seal",
                    "attackSound3_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":2,
                            "hitStun":0,
                            "hitLag":20,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "reversableAngle":false,
                            "power":85,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":2,
                            "hitStun":0,
                            "hitLag":20,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":60,
                            "reversableAngle":false,
                            "power":85,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "b_forward":{
                    "resetMovement":true,
                    "isLongRangeMove":true,
                    "linkFrames":true,
                    "reenableTimer":30,
                    "cpuAttackQueue":"a_up; a_up_tilt; b",
                    "attackVoice1_id":"naruto_attack12",
                    "attackSound1_id":"naruto_bforward_throw",
                    "attackSound2_id":"naruto_bunshin",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":0,
                            "power":20,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_forward_air":{
                    "linkFrames":true,
                    "isLongRangeMove":true,
                    "allowControl":false,
                    "allowControlGround":false,
                    "reenableTimer":30,
                    "cpuAttackQueue":"a_air_forward; a_air; a_air_up; b_air;",
                    "attackVoice1_id":"naruto_attack12",
                    "attackSound1_id":"naruto_bforward_throw",
                    "attackSound2_id":"naruto_bunshin",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":0,
                            "power":20,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_down":{
                    "refreshRate":5,
                    "resetMovement":true,
                    "attackDelay":10,
                    "cancelWhenAirborne":false,
                    "xSpeedCap":0,
                    "allowControlGround":false,
                    "canFallOff":false,
                    "linkFrames":true,
                    "attackSound1_id":"naruto_seal",
                    "attackSound2_id":"naruto_bunshin",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":20,
                            "kbConstant":12,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_down_air":{
                    "refreshRate":5,
                    "isLongRangeMove":true,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "allowControlGround":false,
                    "canFallOff":false,
                    "reenableEffect":"cloneReenable_MC",
                    "reenableTimer":40,
                    "attackSound1_id":"naruto_seal",
                    "attackSound2_id":"naruto_bunshin",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":15,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":20,
                            "kbConstant":15,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackVoice5_id":"naruto_attackU",
                    "attackSound1_id":"naruto_bunshin",
                    "attackSound2_id":"whoosh1",
                    "attackSound3_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "hasEffect":false,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1.3,
                            "selfHitStun":2,
                            "direction":70,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":108,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackSound1_id":"woosh",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":40,
                            "reversableAngle":false,
                            "power":51,
                            "kbConstant":44,
                            "bypassNonGrabbed":true,
                            "effectSound":"punch3"
                        }}
                },
                "throw_back":{
                    "flip":true,
                    "canFallOff":false,
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackSound2_id":"whip",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":2,
                            "hitLag":-1.05,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":40,
                            "reversableAngle":false,
                            "power":43,
                            "kbConstant":101,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "throw_down":{
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air; a_air_backward",
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackSound1_id":"naruto_bunshin",
                    "attackSound2_id":"punch2",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":250,
                            "reversableAngle":false,
                            "power":87,
                            "kbConstant":5,
                            "bypassNonGrabbed":true,
                            "effectSound":null
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":2,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":38,
                            "power":17.25,
                            "kbConstant":105,
                            "effectSound":"punch2"
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":2,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":38,
                            "power":17.25,
                            "kbConstant":105,
                            "effectSound":"punch2"
                        }
                    }
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitStun":1,
                            "weightKB":110,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":40,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_s"
                        },
                        "attackBox2":{
                            "damage":7,
                            "priority":2,
                            "hitStun":1,
                            "weightKB":110,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":40,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_s"
                        }
                    }
                },
                "getup_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"naruto_grunt1",
                    "attackVoice2_id":"naruto_grunt2",
                    "attackVoice3_id":"naruto_grunt3",
                    "attackVoice4_id":"naruto_grunt4",
                    "attackSound1_id":"brawl_swing_s",
                    "attackSound2_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":31,
                            "power":69,
                            "kbConstant":25,
                            "effectSound":"brawl_punch_s"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":31,
                            "power":69,
                            "kbConstant":25,
                            "effectSound":"brawl_punch_s"
                        }
                    }
                },
                "kirby":{
                    "chargetime_max":75,
                    "charge_retain":true,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "customChargeGlow":"naruto_fullChargeFlash",
                    "useChargeBar":false,
                    "attackVoice1_id":"Kirby_Attack07",
                    "attackVoice2_id":"Kirby_Attack03",
                    "attackSound1_id":"smallblast",
                    "attackSound2_id":"naruto_explodeoodama",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":5,
                            "sdiDistance":0,
                            "hitStun":5,
                            "hitLag":0.93,
                            "selfHitStun":0,
                            "camShake":9,
                            "direction":30,
                            "power":500,
                            "kbConstant":10,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "kirby_air":{
                    "allowControl":true,
                    "chargetime_max":75,
                    "charge_retain":true,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "customChargeGlow":"naruto_fullChargeFlash",
                    "useChargeBar":false,
                    "attackVoice1_id":"Kirby_Attack07",
                    "attackVoice2_id":"Kirby_Attack03",
                    "attackSound1_id":"smallblast",
                    "attackSound2_id":"naruto_explodeoodama",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":5,
                            "sdiDistance":0,
                            "hitStun":5,
                            "hitLag":0.93,
                            "selfHitStun":0,
                            "direction":30,
                            "reversableAngle":false,
                            "power":500,
                            "kbConstant":10,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"naruto_transform1",
                    "attackVoice2_id":"naruto_transform2",
                    "attackSound1_id":"naruto_transformexplosion",
                    "attackBoxes":{"attackBox":{
                            "damage":22,
                            "priority":7,
                            "hitStun":8,
                            "selfHitStun":0,
                            "direction":55,
                            "power":79,
                            "kbConstant":25,
                            "burn":true,
                            "bypassShield":true,
                            "effectSound":"brawl_punch_l"
                        }}
                }
            };
            var _local_4:Object = {
                "naruto_rasengan":{
                    "linkage_id":"naruto_rasenganexplosionground",
                    "width":55,
                    "height":60,
                    "time_max":36,
                    "xdecay":0.025,
                    "xspeed":4,
                    "ghost":true,
                    "xoffset":41,
                    "yoffset":-28,
                    "attack_idle":{
                        "refreshRate":3,
                        "attackBoxes":{"attackBox":{
                                "damage":2,
                                "priority":7,
                                "sdiDistance":0,
                                "hitStun":1,
                                "hitLag":10,
                                "selfHitStun":0,
                                "effect_id":"effect_hit3",
                                "direction":10,
                                "reversableAngle":false,
                                "power":32,
                                "kbConstant":10,
                                "effectSound":"whack"
                            }}
                    }
                },
                "rasenshuriken":{
                    "linkage_id":"rasenshuriken",
                    "inheritPalette":true,
                    "width":117,
                    "height":105,
                    "time_max":90,
                    "xspeed":15,
                    "yspeed":-1.5,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":28,
                                "priority":6,
                                "sdiDistance":0,
                                "hitStun":6,
                                "hitLag":-1.2,
                                "selfHitStun":3,
                                "camShake":8,
                                "effect_id":"effect_hit2",
                                "direction":45,
                                "power":32,
                                "kbConstant":80,
                                "effectSound":"sw_slash"
                            }}}
                },
                "naruto_fallclone":{
                    "linkage_id":"naruto_fallclone",
                    "inheritPalette":true,
                    "width":32,
                    "height":36,
                    "time_max":600,
                    "yspeed":11,
                    "gravity":9.5,
                    "maxgravity":12,
                    "canBeAbsorbed":false,
                    "limit":1,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":6,
                                "priority":3,
                                "hitStun":20,
                                "hitLag":1,
                                "selfHitStun":0,
                                "direction":270,
                                "power":10,
                                "kbConstant":25,
                                "effectSound":"naruto_bunshin"
                            }}}
                },
                "naruto_shuriken":{
                    "linkage_id":"naruto_shuriken",
                    "inheritPalette":true,
                    "width":29,
                    "height":17,
                    "time_max":40,
                    "xspeed":13,
                    "yspeed":-9,
                    "gravity":1.2,
                    "maxgravity":10,
                    "xoffset":21.5,
                    "yoffset":-21,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{
                            "attackBox":{
                                "damage":6,
                                "priority":3,
                                "hitStun":5,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "effect_id":"effect_hit2",
                                "direction":141,
                                "reversableAngle":false,
                                "power":62,
                                "kbConstant":72,
                                "effectSound":"brawl_punch_m"
                            },
                            "attackBox2":{
                                "damage":6,
                                "priority":3,
                                "hitStun":5,
                                "hitLag":-1,
                                "selfHitStun":0,
                                "effect_id":"effect_hit2",
                                "direction":141,
                                "reversableAngle":false,
                                "power":62,
                                "kbConstant":72,
                                "effectSound":"brawl_punch_m"
                            }
                        }}
                },
                "naruto_clone2":{
                    "linkage_id":"naruto_clone2",
                    "inheritPalette":true,
                    "width":33,
                    "height":32,
                    "time_max":38,
                    "maxgravity":12,
                    "xoffset":30,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":11,
                                "priority":3,
                                "hitStun":2,
                                "hitLag":-1.2,
                                "selfHitStun":0,
                                "camShake":11,
                                "effect_id":"effect_hit2",
                                "direction":90,
                                "power":31,
                                "kbConstant":109,
                                "effectSound":"brawl_punch_m"
                            }}}
                },
                "naruto_clone":{
                    "linkage_id":"naruto_clone",
                    "inheritPalette":true,
                    "width":33,
                    "height":32,
                    "time_max":240,
                    "xspeed":8,
                    "yspeed":11,
                    "gravity":6,
                    "maxgravity":9.5,
                    "xoffset":20,
                    "yoffset":-85,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":11,
                                "priority":3,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "effect_id":"effect_hit2",
                                "direction":45,
                                "power":29,
                                "kbConstant":62,
                                "effectSound":"brawl_punch_m"
                            }}}
                },
                "fthrow_kunai":{
                    "linkage_id":"fthrow_kunai",
                    "time_max":100,
                    "xspeed":25,
                    "yspeed":-12,
                    "ghost":true,
                    "rotate":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":2,
                                "priority":2,
                                "hitStun":-1,
                                "hitLag":-1.1,
                                "selfHitStun":0,
                                "effect_id":"effect_swordSlash",
                                "direction":10,
                                "reversableAngle":false,
                                "power":0,
                                "kbConstant":130,
                                "bypassGrabbed":true,
                                "effectSound":"naruto_bforward_throw"
                            }}}
                },
                "naruto_dodgelog":{
                    "linkage_id":"naruto_logproj",
                    "time_max":200,
                    "limit":2,
                    "gravity":0,
                    "maxgravity":8,
                    "yoffset":-28,
                    "canBeAbsorbed":false,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":-1,
                                "hitStun":0,
                                "hitLag":0,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":0,
                                "effectSound":null
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getChar2(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"naruto_special",
                "displayName":"Naruto",
                "linkage_id":"naruto_special",
                "linkage_id2":null,
                "linkage_id_special":"naruto",
                "thumbnail":"naruto_head_special",
                "seriesIcon":"Narutosymbol",
                "width":29,
                "height":52,
                "jumpSpeed":14,
                "jumpSpeedMidair":14,
                "jumpStartup":2,
                "shortHopSpeed":7,
                "max_jumpSpeed":14,
                "midAirTurn":true,
                "dodgeSpeed":10,
                "gravity":1.4,
                "weight1":90,
                "power":"naruto",
                "norm_xSpeed":6.2,
                "max_xSpeed":14,
                "max_ySpeed":13,
                "fastFallSpeed":14,
                "accel_start":1.3,
                "accel_start_dash":1.2,
                "accel_rate":1.1,
                "accel_rate_air":1.6,
                "decel_rate":-2,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":999,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":30,
                "roll_delay":14,
                "getup_roll_delay":0,
                "itemScaleRatio":0.833333333333333,
                "special_type":0,
                "normalStats_id":"naruto",
                "specialStats_id":"naruto_special",
                "sounds":{
                    "jump":"naruto_attack12",
                    "jump_midair":"naruto_attack12",
                    "hurt":"naruto_hurt",
                    "hurt2":null,
                    "hurtBad":"naruto_hitHard",
                    "hurtBad2":null,
                    "dead":"naruto_dead",
                    "dead2":null,
                    "pummel":"brawl_punch_l",
                    "screenko":null,
                    "starko":null,
                    "ledge_grab":null,
                    "winTheme":"NarutoVictory"
                },
                "hurtFrames":3,
                "grabDamage":3,
                "fs_time_limit":600
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "combo_max":2,
                    "canFallOff":false,
                    "attackVoice1_id":"naruto_attack2",
                    "attackVoice2_id":"naruto_attack13",
                    "attackSound1_id":"mario_lightpunch",
                    "attackSound2_id":"mario_lightpunch",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":2,
                            "hitStun":5,
                            "hitLag":11,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":80,
                            "power":15,
                            "kbConstant":6,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"naruto_attack11",
                    "attackSound1_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":6,
                            "hitStun":1,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":105,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"naruto_attack10",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":6,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "direction":80,
                            "power":45,
                            "kbConstant":62,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_forward":{
                    "canFallOff":false,
                    "xSpeedDecay":-0.1,
                    "attackVoice1_id":"naruto_attack15",
                    "attackSound1_id":"mario_lightpunch",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":6,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":50,
                            "power":70,
                            "kbConstant":55,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "a_forward_tilt":{
                    "jumpCancelAttack":true,
                    "canFallOff":false,
                    "allowJump":true,
                    "attackVoice1_id":"naruto_attack15",
                    "attackSound1_id":"mario_lightpunch",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":50,
                            "power":44,
                            "kbConstant":55,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":null,
                    "attackVoice2_id":"naruto_attack10",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":5,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "direction":45,
                            "power":40,
                            "kbConstant":109,
                            "effectSound":"sw_scratch"
                        }}
                },
                "a_down":{
                    "refreshRate":200,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"naruto_attack4",
                    "attackSound1_id":"swing",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":5,
                            "hitStun":1,
                            "hitLag":20,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":150,
                            "power":22,
                            "kbConstant":0,
                            "effectSound":"sw_scratch"
                        }}
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"naruto_attack1",
                    "attackSound1_id":"mario_lightpunch",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":6,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":300,
                            "power":30,
                            "kbConstant":40,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":null,
                    "attackVoice2_id":"naruto_attack2",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":6,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "power":25,
                            "kbConstant":58,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"naruto_attack8",
                    "attackSound1_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":16,
                            "priority":6,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":55,
                            "power":10,
                            "kbConstant":75,
                            "effectSound":"sw_scratch"
                        }}
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"naruto_attack11",
                    "attackSound1_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":6,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":160,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "resetMovement":true,
                    "allowControl":false,
                    "attackVoice1_id":"naruto_attack13",
                    "attackSound1_id":"mario_lightpunch",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":6,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":60,
                            "power":51,
                            "kbConstant":26,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b":{
                    "linkCharge":"b_air",
                    "linkCharge":true,
                    "chargetime_max":60,
                    "charge_retain":true,
                    "cancelSoundOnEnd":true,
                    "cancelVoiceOnEnd":true,
                    "useChargeBar":false,
                    "attackVoice1_id":"JPN_naruto_chakra",
                    "attackVoice2_id":"naruto_attack15",
                    "attackSound1_id":"naruto_sfx_rasengan_charge",
                    "attackSound2_id":"smallblast",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":30,
                            "power":25,
                            "kbConstant":0,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "linkCharge":"b",
                    "linkCharge":true,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargetime_max":60,
                    "charge_retain":true,
                    "chargeInAir":false,
                    "useChargeBar":false,
                    "attackVoice1_id":"JPN_naruto_chakra",
                    "attackVoice2_id":"naruto_attack15",
                    "attackSound1_id":"naruto_sfx_rasengan_charge",
                    "attackSound2_id":"smallblast",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":0.95,
                            "selfHitStun":0,
                            "direction":30,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "refreshRate":200,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "attackVoice1_id":"naruto_attack4",
                    "attackSound1_id":"whip",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":5,
                            "hitStun":5,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":65,
                            "reversableAngle":false,
                            "power":29,
                            "kbConstant":100,
                            "burn":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_up_air":{
                    "refreshRate":200,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "isRecoveryMove":true,
                    "attackVoice1_id":"naruto_attack4",
                    "attackSound1_id":"whip",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":5,
                            "hitStun":5,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":65,
                            "reversableAngle":false,
                            "power":29,
                            "kbConstant":100,
                            "burn":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_forward":{
                    "superArmor":true,
                    "isLongRangeMove":true,
                    "attackVoice1_id":"naruto_kyuubiattack4",
                    "attackVoice2_id":"naruto_kyuubiattack2",
                    "attackSound1_id":"smallblast",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":5,
                            "hitStun":6,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":55,
                            "power":195,
                            "kbConstant":10,
                            "effectSound":null
                        }}
                },
                "b_forward_air":{
                    "xSpeedDecay":-3,
                    "xSpeedDecayAir":-3,
                    "isLongRangeMove":true,
                    "attackVoice1_id":"naruto_kyuubiattack4",
                    "attackVoice2_id":"naruto_kyuubiattack2",
                    "attackSound1_id":"smallblast",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":5,
                            "hitStun":5,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":5,
                            "power":195,
                            "kbConstant":10,
                            "effectSound":null
                        }}
                },
                "b_down":{
                    "refreshRate":7,
                    "resetMovement":true,
                    "superArmor":true,
                    "attackVoice1_id":"naruto_kyuubiattack5",
                    "attackSound1_id":"smallblast",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":15,
                            "priority":6,
                            "hitStun":3,
                            "hitLag":19,
                            "selfHitStun":5,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":50,
                            "kbConstant":0,
                            "burn":true,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":15,
                            "priority":6,
                            "hitStun":3,
                            "hitLag":19,
                            "selfHitStun":5,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":50,
                            "kbConstant":0,
                            "burn":true,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "b_down_air":{},
                "throw_up":{
                    "attackVoice1_id":"naruto_attack12",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":0,
                            "hitStun":2,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "direction":80,
                            "power":50,
                            "kbConstant":70,
                            "effectSound":"punch3"
                        }}
                },
                "throw_forward":{
                    "attackVoice1_id":"naruto_attack14",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":0,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "direction":50,
                            "power":70,
                            "kbConstant":45,
                            "effectSound":"sw_scratch"
                        }}
                },
                "throw_back":{
                    "flip":true,
                    "attackVoice1_id":"naruto_attack14",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "direction":60,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":"sw_scratch"
                        }}
                },
                "throw_down":{
                    "attackVoice1_id":"naruto_attack12",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitStun":2,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "direction":40,
                            "power":40,
                            "kbConstant":90,
                            "effectSound":"punch2"
                        }}
                },
                "crouch_attack":{
                    "attackVoice1_id":"naruto_kyuubiattack1",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":110,
                            "power":55,
                            "kbConstant":50,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackSound1_id":"mario_lightpunch",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":0,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":30,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "getup_attack":{"attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":0,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":4,
                            "direction":45,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":null
                        }}},
                "kirby":{
                    "attackDelay":15,
                    "attackVoice1_id":"kirby_hah",
                    "attackSound1_id":"mario_fireballsound",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":30,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "attackDelay":15,
                    "attackVoice1_id":"kirby_hah",
                    "attackSound1_id":"mario_fireballsound",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":30,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "invincible":true,
                    "canUseInAir":true,
                    "attackBoxes":{"attackBox":{
                            "damage":21,
                            "priority":7,
                            "hitStun":5,
                            "hitLag":0.96,
                            "selfHitStun":0,
                            "direction":20,
                            "power":55,
                            "kbConstant":40,
                            "burn":true,
                            "bypassShield":true,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object = {
                "kyuubi_yooko_rasengan":{
                    "linkage_id":"naruto_rasenganexplosionground_red",
                    "width":55,
                    "height":60,
                    "time_max":36,
                    "xdecay":0.025,
                    "xspeed":4,
                    "ghost":true,
                    "xoffset":41,
                    "yoffset":-28,
                    "attack_idle":{
                        "refreshRate":3,
                        "attackBoxes":{"attackBox":{
                                "damage":6,
                                "priority":7,
                                "sdiDistance":0,
                                "hitStun":1,
                                "hitLag":10,
                                "selfHitStun":0,
                                "effect_id":"effect_hit3",
                                "direction":10,
                                "reversableAngle":false,
                                "power":32,
                                "kbConstant":10,
                                "effectSound":"whack"
                            }}
                    }
                },
                "kyuubi_kyuubi_rasengan":{
                    "linkage_id":"naruto_redrasengan",
                    "width":117,
                    "height":105,
                    "time_max":55,
                    "xspeed":0.1,
                    "ghost":true,
                    "followUser":true,
                    "canBeReversed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":10,
                                "priority":7,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "effect_id":"effect_heavyHit",
                                "direction":45,
                                "reversableAngle":false,
                                "power":47,
                                "kbConstant":67,
                                "effectSound":"bombexplode"
                            }}}
                },
                "kyuubi_bijuudama":{
                    "linkage_id":"naruto_kyuubiblast",
                    "width":99,
                    "height":75,
                    "time_max":80,
                    "xspeed":14,
                    "xoffset":-30,
                    "yoffset":5,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":35,
                                "priority":7,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "effect_id":"effect_heavyHit",
                                "direction":55,
                                "power":57,
                                "kbConstant":40,
                                "effectSound":"brawl_punch_l"
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("naruto");
        }

        public function getGUID():String
        {
            return ("d6a9d9ac-29fa-4015-bd40-81e2769db6ae");
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package naruto_fla

