// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//captainfalcon_fla.MainTimeline

package captainfalcon_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function getAudio():Array
        {
            return (new Array(Run_start, blueFalcon, blueFalcon_pass, blueFalcon_leaves, falcon_taunt1, falcon_footstep, falcon_dspec, falcon_dspecLand, falcon_starKO, falcon_jumpS1, falcon_death2, falcon_hurtBad2, falcon_jumpS2, falcon_tiltswing, falcon_utiltCrash, falcon_smashswing, falcon_aswing, falcon_uspec1, falcon_uspec2, falcon_tooh, falcon_charge, falcon_toorar, falcon_hteh, falcon_hoah, falcon_death, falcon_hoot, falcon_dsmashcharge, falcon_kick, showmeyourmoves, blueFalcon, falcon_finalSmash, falcon_peturar, falcon_comeOn, falcon_hurt, falcon_hurtBad, falcon_jump, falcon_, pawnch, falconSleep, falcon_tooah, falcon_hoyah, falcon_hyesz, raptorBoost1, raptorBoost2, falcon_victory, falcon_hurt2, entranceOpen, entranceClose, entranceLeave));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"captainfalcon",
                "displayName":"Captain%20Falcon",
                "linkage_id":"falcon",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"captainfalcon_head",
                "seriesIcon":"fzero",
                "width":22,
                "height":60,
                "jumpSpeed":20,
                "jumpSpeedMidair":20,
                "jumpStartup":2,
                "shortHopSpeed":10,
                "max_jumpSpeed":10,
                "dodgeSpeed":8,
                "gravity":1.739,
                "weight1":104,
                "weight2":0,
                "power":"captainfalcon",
                "norm_xSpeed":5.6,
                "max_xSpeed":15,
                "max_ySpeed":16.8,
                "fastFallSpeed":18,
                "accel_start":0.95,
                "accel_start_dash":1.1,
                "accel_rate":1.1,
                "accel_rate_air":0.9,
                "decel_rate":-1.35,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_delay":9,
                "getup_roll_delay":0,
                "itemScaleRatio":0.869565217,
                "special_type":6,
                "normalStats_id":"captainfalcon",
                "specialStats_id":null,
                "sounds":{
                    "jump":"falcon_jump",
                    "jump_midair":"falcon_hoot",
                    "hurt":"falcon_hurt",
                    "hurt2":"falcon_hurt2",
                    "hurtBad":"falcon_hurtBad",
                    "hurtBad2":"falcon_hurtBad2",
                    "dead":"falcon_death",
                    "dead2":"falcon_death2",
                    "pummel":"brawl_kick_s",
                    "screenko":"falcon_hurtBad2",
                    "starko":"falcon_starKO",
                    "ledge_grab":null,
                    "winTheme":"falcon_victory_v2"
                },
                "hurtFrames":5,
                "grabDamage":1,
                "fs_time_limit":235
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "canFallOff":false,
                    "cpuAttackQueue":"crouch_attack",
                    "reenableTimer":15,
                    "attackVoice1_id":"falcon_hoot",
                    "attackVoice2_id":"falcon_tooh",
                    "attackSound1_id":"falcon_aswing",
                    "attackSound2_id":"falcon_tiltswing",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":3,
                            "hitLag":-1.15,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":80,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_up":{
                    "cancelWhenAirborne":false,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"falcon_hoyah",
                    "attackSound1_id":"falcon_smashswing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "camShake":4,
                            "effect_id":"effect_heavyHit",
                            "direction":90,
                            "power":45,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "camShake":4,
                            "effect_id":"effect_heavyHit",
                            "direction":100,
                            "power":45,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_up_tilt":{
                    "xSpeedDecay":-2.8,
                    "canFallOff":false,
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_tiltswing",
                    "attackSound2_id":"falcon_aswing",
                    "attackSound3_id":"falcon_utiltCrash",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forward":{
                    "xSpeedDecay":-1.3,
                    "canFallOff":false,
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_tiltswing",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "power":22,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_forward_tilt":{
                    "xSpeedDecay":-1,
                    "canFallOff":false,
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_tiltswing",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":3,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "power":10,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"falcon_peturar",
                    "attackSound1_id":"falcon_smashswing",
                    "attackBoxes":{"attackBox":{
                            "damage":20,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":3,
                            "camShake":6,
                            "effect_id":"effect_firehit1",
                            "direction":43,
                            "power":20,
                            "kbConstant":100,
                            "burn":true,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "chargeClick":true,
                    "attackVoice1_id":"falcon_toorar",
                    "attackSound1_id":"falcon_smashswing",
                    "attackSound2_id":"falcon_tiltswing",
                    "attackBoxes":{"attackBox":{
                            "damage":18,
                            "priority":6,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air":{
                    "hit_ease":3.85,
                    "allowControl":true,
                    "cancelWhenAirborne":true,
                    "canFallOff":true,
                    "maintainSpeed":true,
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_tiltswing",
                    "attackSound2_id":"falcon_smashswing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":6,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "power":0,
                            "kbConstant":100,
                            "weightKB":50,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox2":{
                            "damage":5,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "power":0,
                            "kbConstant":100,
                            "weightKB":50,
                            "effectSound":"brawl_punch_m"
                        }
                    }
                },
                "a_air_up":{
                    "allowControl":true,
                    "cancelWhenAirborne":true,
                    "canFallOff":true,
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_tiltswing",
                    "cpuAttackQueue":"a_air;a_air_forward;a_air_down",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":50,
                            "power":29,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":50,
                            "power":29,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_forward":{
                    "allowControl":true,
                    "cancelWhenAirborne":true,
                    "canFallOff":true,
                    "allowControlGround":false,
                    "cpuAttackQueue":"a",
                    "canUseInAir":true,
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_aswing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":18,
                            "priority":5,
                            "hitStun":7,
                            "selfHitStun":4,
                            "camShake":4,
                            "effect_id":"falconhiteffect_electric",
                            "direction":32,
                            "power":24,
                            "kbConstant":100,
                            "shock":true,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":18,
                            "priority":5,
                            "hitStun":7,
                            "selfHitStun":4,
                            "camShake":4,
                            "effect_id":"falconhiteffect_electric",
                            "direction":32,
                            "power":24,
                            "kbConstant":100,
                            "shock":true,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air_backward":{
                    "allowControl":true,
                    "cancelWhenAirborne":true,
                    "canFallOff":true,
                    "allowControlGround":false,
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_aswing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":42,
                            "power":20,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":42,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_m"
                        }
                    }
                },
                "a_air_down":{
                    "allowControl":true,
                    "allowControlGround":false,
                    "cancelWhenAirborne":true,
                    "canFallOff":true,
                    "cpuAttackQueue":"a_air_up;a_air_forward;a_air",
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_smashswing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":5,
                            "hitLag":-1,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":270,
                            "power":40,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":16,
                            "priority":4,
                            "hitStun":7,
                            "hitLag":-1,
                            "selfHitStun":5,
                            "effect_id":"effect_heavyHit",
                            "direction":290,
                            "meteorCancel":false,
                            "power":70,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "b":{
                    "canFallOff":false,
                    "disableForCPU":true,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackVoice1_id":"falcon_",
                    "attackVoice2_id":"pawnch",
                    "attackSound1_id":"fPunchCharge",
                    "attackSound2_id":"fPunchSwing",
                    "attackSound3_id":"fPunchImpact",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":27,
                            "priority":7,
                            "hitStun":4,
                            "selfHitStun":2,
                            "camShake":3,
                            "effect_id":"effect_firehit1",
                            "direction":40,
                            "power":30,
                            "kbConstant":102,
                            "burn":true,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":27,
                            "priority":7,
                            "hitStun":4,
                            "selfHitStun":2,
                            "camShake":3,
                            "effect_id":"effect_firehit1",
                            "direction":40,
                            "power":30,
                            "kbConstant":102,
                            "burn":true,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "b_air":{
                    "allowControl":true,
                    "allowControlGround":false,
                    "canFallOff":false,
                    "disableForCPU":true,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "attackVoice1_id":"falcon_",
                    "attackVoice2_id":"pawnch",
                    "attackSound1_id":"fPunchCharge",
                    "attackSound2_id":"fPunchSwing",
                    "attackSound3_id":"fPunchImpact",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":27,
                            "priority":7,
                            "hitStun":4,
                            "selfHitStun":2,
                            "camShake":3,
                            "effect_id":"effect_firehit1",
                            "direction":40,
                            "power":30,
                            "kbConstant":102,
                            "burn":true,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":27,
                            "priority":7,
                            "hitStun":4,
                            "selfHitStun":2,
                            "camShake":3,
                            "effect_id":"effect_firehit1",
                            "direction":40,
                            "power":30,
                            "kbConstant":102,
                            "burn":true,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "b_up":{
                    "cancelWhenAirborne":false,
                    "xSpeedAccelAir":0.8,
                    "air_ease":2,
                    "stale":false,
                    "isRecoveryMove":true,
                    "disableForCPU":true,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackVoice1_id":"falcon_hyesz",
                    "attackSound1_id":"falcon_uspec1",
                    "attackSound2_id":"bombexplode",
                    "attackSound3_id":"falcon_uspec2",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":4,
                            "hitStun":0,
                            "selfHitStun":0,
                            "camShake":4,
                            "direction":45,
                            "power":70,
                            "kbConstant":50,
                            "burn":true,
                            "bypassGrabbed":true,
                            "bypassShield":true,
                            "effectSound":null
                        }}
                },
                "b_up_air":{
                    "xSpeedAccelAir":0.8,
                    "air_ease":1.8,
                    "cancelWhenAirborne":false,
                    "isRecoveryMove":true,
                    "disableForCPU":true,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackVoice1_id":"falcon_hyesz",
                    "attackSound1_id":"falcon_uspec1",
                    "attackSound2_id":"bombexplode",
                    "attackSound3_id":"falcon_uspec2",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "camShake":4,
                            "direction":45,
                            "power":70,
                            "kbConstant":50,
                            "burn":true,
                            "bypassGrabbed":true,
                            "bypassShield":true,
                            "effectSound":null
                        }}
                },
                "b_forward":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-0.7777777,
                    "cpuAttackQueue":"a_air_down;a_air;a_up;a_air_forward",
                    "attackSound1_id":"raptorBoost1",
                    "attackSound2_id":"raptorBoost2",
                    "attackBoxes":{"attackBox":{
                            "allowTurboInterrupt":false,
                            "damage":1,
                            "hasEffect":false,
                            "priority":-1,
                            "hitStun":0,
                            "hitLag":-1.1,
                            "selfHitStun":0,
                            "direction":45,
                            "reversableAngle":false,
                            "power":0,
                            "kbConstant":0,
                            "burn":true,
                            "bypassShield":true,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "b_forward_air":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-0.7777777,
                    "xSpeedDecayAir":-0.7777777,
                    "air_ease":0,
                    "disableForCPU":true,
                    "attackSound1_id":"raptorBoost1",
                    "attackSound2_id":"raptorBoost2",
                    "attackBoxes":{"attackBox":{
                            "allowTurboInterrupt":false,
                            "damage":1,
                            "hasEffect":false,
                            "priority":-1,
                            "hitStun":4,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":35,
                            "burn":true,
                            "bypassShield":true,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "b_down":{
                    "air_ease":0.5,
                    "cancelWhenAirborne":false,
                    "disableForCPU":true,
                    "attackVoice1_id":"falcon_kick",
                    "attackSound1_id":"falcon_dspec",
                    "attackSound2_id":"falcon_dspecLand",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_firehit1",
                            "direction":45,
                            "power":50,
                            "kbConstant":70,
                            "burn":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_down_air":{
                    "resetMovement":true,
                    "air_ease":1,
                    "isHorizontalRecoveryMove":true,
                    "disableForCPU":true,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackVoice1_id":"falcon_kick",
                    "attackSound1_id":"falcon_dspec",
                    "attackSound2_id":"falcon_dspecLand",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_firehit1",
                            "direction":45,
                            "power":40,
                            "kbConstant":70,
                            "burn":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_up":{
                    "resetMovement":true,
                    "xSpeedDecay":-0.1,
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air;a_air_forward;a_air_down;a_air_up",
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_tiltswing",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "forceTumbleFall":true,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":80,
                            "reversableAngle":false,
                            "power":70,
                            "kbConstant":120,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_forward":{
                    "resetMovement":true,
                    "xSpeedDecay":-0.1,
                    "canFallOff":false,
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_aswing",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":45,
                            "reversableAngle":false,
                            "power":70,
                            "kbConstant":105,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_back":{
                    "resetMovement":true,
                    "xSpeedDecay":-0.1,
                    "canFallOff":false,
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_aswing",
                    "attackSound2_id":"falcon_tiltswing",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":135,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":130,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_down":{
                    "resetMovement":true,
                    "xSpeedDecay":-0.1,
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air;a_air_forward;a_air_up",
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_tiltswing",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "forceTumbleFall":true,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":65,
                            "reversableAngle":false,
                            "power":75,
                            "kbConstant":34,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "crouch_attack":{
                    "xSpeedDecay":-1.9,
                    "canFallOff":false,
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_tiltswing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":80,
                            "power":25,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":70,
                            "power":25,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox3":{
                            "damage":12,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":60,
                            "power":25,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "ledge_attack":{
                    "xSpeedDecay":-1,
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_tiltswing",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":75,
                            "kbConstant":25,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "xSpeedDecay":-1,
                    "attackVoice1_id":"falcon_tooh",
                    "attackVoice2_id":"falcon_tooah",
                    "attackVoice3_id":"falcon_hteh",
                    "attackVoice4_id":"falcon_hoah",
                    "attackSound1_id":"falcon_tiltswing",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":4,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "kirby":{
                    "attackDelay":4,
                    "xSpeedDecay":-0.5,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackSound1_id":"fPunchCharge",
                    "attackSound2_id":"fPunchSwing",
                    "attackSound3_id":"fPunchImpact",
                    "attackBoxes":{"attackBox":{
                            "damage":27,
                            "priority":7,
                            "hitStun":2,
                            "selfHitStun":2,
                            "camShake":3,
                            "effect_id":"effect_firehit1",
                            "direction":45,
                            "power":30,
                            "kbConstant":102,
                            "burn":true,
                            "bypassGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "kirby_air":{
                    "attackDelay":4,
                    "xSpeedDecay":-0.5,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackSound1_id":"fPunchCharge",
                    "attackSound2_id":"fPunchSwing",
                    "attackSound3_id":"fPunchImpact",
                    "attackBoxes":{"attackBox":{
                            "damage":27,
                            "priority":7,
                            "hitStun":2,
                            "selfHitStun":2,
                            "camShake":3,
                            "effect_id":"effect_firehit1",
                            "direction":45,
                            "power":30,
                            "kbConstant":102,
                            "burn":true,
                            "bypassGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"falcon_finalSmash",
                    "attackVoice2_id":"blueFalcon",
                    "attackBoxes":{"attackBox":{
                            "damage":42,
                            "priority":7,
                            "hitStun":4,
                            "selfHitStun":0,
                            "camShake":14,
                            "direction":30,
                            "power":100,
                            "kbConstant":150,
                            "effectSound":"brawl_punch_l"
                        }}
                }
            };
            var _local_4:Object;
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "pData":_local_4,
                "iData":_local_5
            });
        }

        public function getID():String
        {
            return ("captainfalcon");
        }

        public function getGUID():String
        {
            return ("addc9f5b-48d8-49df-9b23-e53d64c0c65e");
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package captainfalcon_fla

