// Decompiled by AS3 Sorcerer 6.20
// www.as3sorcerer.com

//link_fla.MainTimeline

package link_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function getAudio():Array
        {
            return (new Array(linkwin, link_bombappear, link_boomerang_catch, link_boomerang_something, link_boomerang_throw, link_bow_charge, link_bow_repeat, link_bow_shoot, link_dair_land, link_hookshot, link_runstart, link_step, link_sunsong, link_swordswing, link_swordswing2, link_taunt_swing, link_taunt_swing2, link_triforce_hit1, link_triforce_hit2, link_death, link_death2, link_dizzy, link_dsmash, link_edgegrab, link_edgelean, link_fs1, link_fs2, link_fs3, link_fsmash, link_grunt1, link_grunt2, link_grunt3, link_grunt4, link_hurt, link_hurt2, link_hurtBad, link_hurtBad2, link_jump, link_lift, link_sleep, link_sspec, link_starko, link_usmash, link_charge1, link_charge2, link_charge3, link_charge4, link_charge5, link_charge6, link_spin1, link_spin2, link_spin3, link_spin4, link_spin5, link_spin6, link_spin7, link_spin8, link_spin9, link_spin10, link_spin11, link_spin_end, link_bow_done, link_taunt_ching));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"link",
                "displayName":"Link",
                "linkage_id":"link",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"link_head",
                "seriesIcon":"zeldaicon",
                "width":41,
                "height":57,
                "jumpSpeed":14.4,
                "jumpSpeedMidair":16,
                "jumpStartup":2,
                "shortHopSpeed":8,
                "max_jumpSpeed":9.5,
                "dodgeSpeed":7,
                "gravity":1.28,
                "weight1":104,
                "power":"link",
                "norm_xSpeed":5.2,
                "max_xSpeed":8.2,
                "max_ySpeed":14.5,
                "fastFallSpeed":18,
                "accel_start":1.2,
                "accel_start_dash":1.022,
                "accel_rate":1,
                "accel_rate_air":0.7,
                "decel_rate":-1.39,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":6,
                "tetherGrab":true,
                "roll_speed":32,
                "roll_delay":14,
                "getup_roll_delay":0,
                "itemScaleRatio":0.909090909090909,
                "special_type":2,
                "normalStats_id":"link",
                "specialStats_id":null,
                "sounds":{
                    "jump":"link_jump",
                    "jump_midair":null,
                    "hurt":"link_hurt",
                    "hurt2":"link_hurt2",
                    "hurtBad":"link_hurtBad",
                    "hurtBad2":"link_hurtBad2",
                    "dead":"link_death",
                    "dead2":"link_death2",
                    "pummel":"brawl_punch_m",
                    "screenko":"link_hurt2",
                    "starko":"link_starko",
                    "ledge_grab":"link_edgegrab",
                    "winTheme":"linkwin2"
                },
                "hurtFrames":4,
                "grabDamage":1
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":60,
                    "combo_max":2,
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackSound1_id":"sw_brawl_swing_S",
                    "attackSound2_id":"sw_brawl_swing_S",
                    "attackSound3_id":"sw_brawl_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":1,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":50,
                            "power":16,
                            "kbConstant":37,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"link_usmash",
                    "attackSound1_id":"link_swordswing",
                    "attackSound2_id":"link_swordswing2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "priority":4,
                            "hitStun":5,
                            "hitLag":-1.15,
                            "weightKB":24,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":115,
                            "power":0,
                            "kbConstant":100,
                            "ignoreChargeDamage":true,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":4,
                            "hitStun":5,
                            "hitLag":-1.15,
                            "weightKB":24,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":115,
                            "power":0,
                            "kbConstant":90,
                            "ignoreChargeDamage":true,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackSound1_id":"link_swordswing",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":85,
                            "power":30,
                            "kbConstant":130,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "a_forward":{
                    "cancelWhenAirborne":false,
                    "xSpeedDecayAir":-1,
                    "canFallOff":false,
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackSound1_id":"link_swordswing2",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":2,
                            "hitStun":6,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":70,
                            "power":30,
                            "kbConstant":80,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackSound1_id":"link_swordswing",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":20,
                            "kbConstant":96,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "a_forwardsmash":{
                    "xSpeedDecay":0.75,
                    "chargetime_max":40,
                    "combo_max":1,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"link_fsmash",
                    "attackSound1_id":"link_swordswing",
                    "attackSound2_id":"link_swordswing2",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":6,
                            "hitStun":8,
                            "selfHitStun":5,
                            "effect_id":"effect_swordSlash",
                            "direction":35,
                            "power":26,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_H"
                        }}
                },
                "a_down":{
                    "refreshRate":500,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"link_dsmash",
                    "attackSound1_id":"link_swordswing2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":68,
                            "reversableAngle":false,
                            "power":73,
                            "kbConstant":84,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox2":{
                            "damage":16,
                            "priority":4,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":68,
                            "reversableAngle":false,
                            "power":73,
                            "kbConstant":90,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "a_air":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":11,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":47,
                            "power":22,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":11,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":47,
                            "power":22,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_up":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackSound1_id":null,
                    "attackSound2_id":"link_swordswing",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":90,
                            "power":28,
                            "kbConstant":90,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "a_air_forward":{
                    "hit_ease":2,
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackSound1_id":"link_swordswing",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":3,
                            "hitStun":7,
                            "hitLag":-1.1,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "reversableAngle":false,
                            "power":5,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "a_air_backward":{
                    "refreshRate":100,
                    "allowControl":true,
                    "hitEffect":"effect_hit2",
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":5,
                            "hitLag":-1.05,
                            "weightKB":40,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air_down":{
                    "refreshRate":11,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackSound1_id":"link_swordswing",
                    "attackSound2_id":"link_dair_land",
                    "attackBoxes":{"attackBox":{
                            "damage":19,
                            "priority":6,
                            "hitStun":2,
                            "selfHitStun":4,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_H"
                        }}
                },
                "b":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "chargetime_max":25,
                    "holdRepeat":true,
                    "linkFrames":true,
                    "attackSound1_id":"link_bow_charge",
                    "attackSound2_id":"link_bow_shoot",
                    "attackSound3_id":"link_bow_done",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "b_air":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargetime_max":25,
                    "holdRepeat":true,
                    "linkFrames":true,
                    "attackSound1_id":"link_bow_charge",
                    "attackSound2_id":"link_bow_shoot",
                    "attackSound3_id":"link_bow_done",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "b_up":{
                    "air_ease":0,
                    "chargetime_max":50,
                    "holdRepeat":true,
                    "attackVoice1_id":"link_dsmash",
                    "attackSound1_id":"link_spin1",
                    "attackSound2_id":"link_spin2",
                    "attackSound3_id":"link_spin3",
                    "attackSound4_id":"link_spin4",
                    "attackSound5_id":"link_spin5",
                    "attackSound6_id":"link_spin6",
                    "attackSound7_id":"link_spin7",
                    "attackSound8_id":"link_spin8",
                    "attackSound9_id":"link_spin9",
                    "attackSound10_id":"link_spin10",
                    "attackSound11_id":"link_spin11",
                    "attackSound12_id":"link_spin_end",
                    "attackSound13_id":"link_charge1",
                    "attackSound14_id":"link_charge2",
                    "attackSound15_id":"link_charge3",
                    "attackSound16_id":"link_charge4",
                    "attackSound17_id":"link_charge5",
                    "attackSound18_id":"link_charge6",
                    "attackSound19_id":"link_bow_done",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":4,
                            "hitStun":6,
                            "selfHitStun":6,
                            "effect_id":"effect_swordSlash",
                            "direction":29,
                            "power":68,
                            "kbConstant":60,
                            "effectSound":"sw_scratch"
                        }}
                },
                "b_up_air":{
                    "refreshRate":4,
                    "cancelWhenAirborne":false,
                    "air_ease":6,
                    "xSpeedCap":5,
                    "allowControl":true,
                    "isRecoveryMove":true,
                    "attackVoice1_id":"link_dsmash",
                    "attackSound1_id":"link_spin1",
                    "attackSound2_id":"link_spin2",
                    "attackSound3_id":"link_spin3",
                    "attackSound4_id":"link_spin4",
                    "attackSound5_id":"link_spin5",
                    "attackSound6_id":"link_spin6",
                    "attackSound7_id":"link_spin7",
                    "attackSound8_id":"link_spin8",
                    "attackSound9_id":"link_spin9",
                    "attackSound10_id":"link_spin10",
                    "attackSound11_id":"link_spin11",
                    "attackSound12_id":"link_spin_end",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":75,
                            "kbConstant":0,
                            "effectSound":"sw_scratch"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":75,
                            "kbConstant":0,
                            "effectSound":"sw_scratch"
                        }
                    }
                },
                "b_forward":{
                    "allowFastFall":false,
                    "isLongRangeMove":true,
                    "linkFrames":true,
                    "attackVoice1_id":"link_sspec",
                    "attackSound1_id":"link_boomerang_throw",
                    "attackSound2_id":"link_boomerang_catch",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":210,
                            "power":2,
                            "kbConstant":1,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_forward_air":{
                    "refreshRate":20,
                    "allowFastFall":false,
                    "linkFrames":true,
                    "attackVoice1_id":"link_sspec",
                    "attackSound1_id":"link_boomerang_throw",
                    "attackSound2_id":"link_boomerang_catch",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":210,
                            "power":2,
                            "kbConstant":1,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_down":{
                    "resetMovement":true,
                    "isLongRangeMove":true,
                    "linkFrames":true,
                    "attackSound1_id":"link_bombappear",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":-2,
                            "power":2,
                            "kbConstant":10,
                            "effectSound":null
                        }}
                },
                "b_down_air":{
                    "allowControl":true,
                    "isLongRangeMove":true,
                    "allowControlGround":false,
                    "maintainSpeed":true,
                    "allowFastFall":false,
                    "linkFrames":true,
                    "attackSound1_id":"link_bombappear",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":-2,
                            "power":2,
                            "kbConstant":10,
                            "effectSound":null
                        }}
                },
                "throw_up":{
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackSound1_id":null,
                    "attackSound2_id":"sw_brawl_swing_M",
                    "cpuAttackQueue":"a_air; a_air_up",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":-1.05,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":20,
                            "power":50,
                            "kbConstant":100,
                            "bypassNonGrabbed":true,
                            "effectSound":null
                        }}
                },
                "throw_forward":{
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":25,
                            "kbConstant":120,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "throw_back":{
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":30,
                            "power":50,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "throw_down":{
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "cpuAttackQueue":"a_air; a_up; a_up_tilt; a_air_down; b_up",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":0,
                            "hitStun":5,
                            "hitLag":-1.05,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":110,
                            "power":60,
                            "kbConstant":90,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "crouch_attack":{
                    "reenableTimer":10,
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackSound1_id":"link_swordswing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":2,
                            "hitStun":6,
                            "selfHitStun":5,
                            "effect_id":"effect_swordSlash",
                            "direction":280,
                            "reversableAngle":false,
                            "power":90,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":2,
                            "hitStun":6,
                            "selfHitStun":5,
                            "effect_id":"effect_swordSlash",
                            "direction":280,
                            "reversableAngle":false,
                            "power":90,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox3":{
                            "damage":14,
                            "priority":2,
                            "hitStun":10,
                            "selfHitStun":10,
                            "effect_id":"effect_swordSlash",
                            "direction":320,
                            "reversableAngle":false,
                            "power":90,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_M",
                            "meteorCancel":false
                        }
                    }
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "cancelWhenAirborne":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackSound1_id":"link_swordswing",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":2,
                            "hitStun":1,
                            "weightKB":110,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "getup_attack":{
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackSound1_id":"link_swordswing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":3,
                            "hitStun":3,
                            "weightKB":110,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":25,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":5,
                            "priority":3,
                            "hitStun":3,
                            "weightKB":110,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":25,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "kirby":{
                    "refreshRate":100,
                    "chargetime_max":30,
                    "holdRepeat":true,
                    "attackSound1_id":"link_bow",
                    "attackSound2_id":"link_arrowshot",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "kirby_air":{
                    "refreshRate":100,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargetime_max":30,
                    "holdRepeat":true,
                    "attackSound1_id":"link_bow",
                    "attackSound2_id":"link_arrowshot",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "special":{
                    "refreshRate":100,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"link_fs1",
                    "attackVoice2_id":"link_fs2",
                    "attackVoice3_id":"link_fs3",
                    "attackSound1_id":"link_triforce_hit2",
                    "attackSound2_id":"link_triforce_hit1",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":-1,
                            "hitStun":99,
                            "selfHitStun":0,
                            "hitLag":0,
                            "direction":0,
                            "power":0,
                            "kbConstant":0,
                            "effect_id":"effect_lightHit",
                            "effectSound":"sw_brawl_hit_H"
                        }}
                },
                "tether":{
                    "allowControl":true,
                    "maintainSpeed":true,
                    "attackVoice1_id":"link_grunt2",
                    "attackVoice2_id":"link_grunt1",
                    "attackVoice3_id":"link_grunt3",
                    "attackVoice4_id":"link_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "direction":25,
                            "power":60,
                            "kbConstant":30,
                            "priority":-1,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effectSound":"sw_brawl_hit_m",
                            "effect_id":"effect_lightHit"
                        }}
                }
            };
            var _local_4:Object = {
                "nSpecArrow":{
                    "linkage_id":"link_arrow",
                    "width":47,
                    "height":6,
                    "time_max":40,
                    "trailEffect":"arrowTrail",
                    "trailEffectRotate":true,
                    "xspeed":45,
                    "yspeed":-2,
                    "rotate":true,
                    "gravity":1,
                    "maxgravity":60,
                    "stale":false,
                    "xoffset":5,
                    "yoffset":-30,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":10,
                                "priority":2,
                                "chargedPriority":6,
                                "hitStun":2,
                                "selfHitStun":0,
                                "effect_id":"effect_swordSlash",
                                "direction":35,
                                "reversableAngle":false,
                                "power":40,
                                "kbConstant":70,
                                "effectSound":"sw_brawl_hit_S"
                            }}}
                },
                "nSpecBomb":{
                    "linkage_id":"bombArrow",
                    "width":47,
                    "height":10,
                    "time_max":40,
                    "xdecay":0.003,
                    "trailEffectRotate":true,
                    "xspeed":40,
                    "yspeed":-2,
                    "rotate":true,
                    "gravity":2,
                    "maxgravity":60,
                    "xoffset":5,
                    "yoffset":-30,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":13,
                                "priority":4,
                                "hitStun":11,
                                "hitLag":-1.15,
                                "selfHitStun":0,
                                "effect_id":"effect_firehit1",
                                "direction":45,
                                "reversableAngle":false,
                                "power":61,
                                "kbConstant":80,
                                "burn":true,
                                "effectSound":null
                            }}}
                },
                "tetherDetect":{
                    "linkage_id":"link_tetherChecker",
                    "width":48,
                    "height":28,
                    "rideGround":false,
                    "time_max":999,
                    "lockTrajectory":true,
                    "ghost":false
                },
                "sSpecBoomerang":{
                    "linkage_id":"linkBoomerang",
                    "width":45,
                    "height":52,
                    "time_max":180,
                    "boomerang":true,
                    "xdecay":1,
                    "xspeed":23,
                    "gravity":0.5,
                    "maxgravity":0.6,
                    "yoffset":-21,
                    "canBeAbsorbed":false,
                    "limit":1,
                    "limitOverwrite":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":7,
                                "priority":3,
                                "sdiDistance":3,
                                "hitStun":2,
                                "selfHitStun":0,
                                "effect_id":"effect_hit2",
                                "direction":50,
                                "reversableAngle":false,
                                "power":80,
                                "kbConstant":40,
                                "effectSound":"brawl_punch_m"
                            }}}
                }
            };
            var _local_5:Object = {"link_bomb":{
                    "class_id":null,
                    "linkage_id":"link_bomb",
                    "displayName":null,
                    "width":17,
                    "height":16,
                    "specialAction":true,
                    "affectsOwner":false,
                    "ownerCanAffect":true,
                    "canPickup":true,
                    "ability":"toss",
                    "uses_max":999,
                    "gravity":0.9,
                    "max_gravity":15,
                    "effectSound":null,
                    "canBackToss":true,
                    "useInAir":true,
                    "throwSpeed":11,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":3,
                                "hitStun":1,
                                "selfHitStun":0,
                                "direction":55,
                                "power":10,
                                "kbConstant":10,
                                "burn":true,
                                "effectSound":null
                            }}},
                    "attack_toss":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":3,
                                "hitStun":1,
                                "selfHitStun":0,
                                "direction":55,
                                "power":10,
                                "kbConstant":10,
                                "burn":true,
                                "effectSound":null
                            }}},
                    "attack_throw":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":3,
                                "hitStun":1,
                                "selfHitStun":0,
                                "direction":55,
                                "power":10,
                                "kbConstant":10,
                                "burn":true,
                                "effectSound":null
                            }}},
                    "attack_neutral":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":3,
                                "hitStun":0,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "burn":true,
                                "effectSound":null
                            }}},
                    "attack_smash":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":3,
                                "hitStun":0,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "burn":true,
                                "effectSound":null
                            }}}
                }};
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("link");
        }

        public function getGUID():String
        {
            return ("6c4013ee-0672-4264-80e8-a3d63c506a6c");
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package link_fla

