// Decompiled by AS3 Sorcerer 6.20
// www.as3sorcerer.com

//marth_fla.MainTimeline

package marth_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public var ikNode_1:marth;

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function getAudio():Array
        {
            return (new Array(MarthVictory, dash_start, footstep, marth_tech, jump_common, marth_grunt1, marth_grunt2, marth_grunt3, marth_grunt4, marth_sword_swing1, marth_uspec, marth_entrance, marth_dspec_ching, marth_fsmash_swing, marth_sword_swing2, marth_sword_swing3, marth_sword_swing4, marth_dizzy, marth_dsmash, marth_dspec, marth_dspec2, marth_dspec3, marth_edgegrab, marth_fsmash, marth_hurt, marth_hurt2, marth_hurtBad, marth_hurtBad2, marth_dead, marth_dead2));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"marth",
                "displayName":"Marth",
                "linkage_id":"marth",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"marth_damageIcon",
                "seriesIcon":"marth_seriesIcon",
                "width":26,
                "height":61,
                "jumpSpeed":14,
                "jumpSpeedMidair":14,
                "jumpStartup":2,
                "shortHopSpeed":10,
                "max_jumpSpeed":8.4,
                "dodgeSpeed":8,
                "gravity":0.98,
                "weight1":87,
                "power":"marth",
                "norm_xSpeed":6,
                "max_xSpeed":10.2,
                "max_ySpeed":13,
                "fastFallSpeed":15.5,
                "accel_start":1.1,
                "accel_start_dash":1.3,
                "accel_rate":1.25,
                "accel_rate_air":0.7,
                "decel_rate":-1.04,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":2,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_delay":8,
                "getup_roll_delay":0,
                "itemScaleRatio":1,
                "special_type":1,
                "normalStats_id":"marth",
                "specialStats_id":null,
                "sounds":{
                    "jump":null,
                    "jump_midair":null,
                    "hurt":"marth_hurt",
                    "hurt2":"marth_hurt2",
                    "hurtBad":"marth_hurtBad",
                    "hurtBad2":"marth_hurtBad2",
                    "dead":"marth_dead",
                    "dead2":"marth_dead2",
                    "pummel":"brawl_kick_s",
                    "screenko":"marth_dead",
                    "starko":"marth_starko",
                    "ledge_grab":"marth_tech",
                    "winTheme":"MarthVictory"
                },
                "hurtFrames":4,
                "grabDamage":2
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "canFallOff":false,
                    "refreshRate":60,
                    "combo_max":1,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackSound1_id":"marth_sword_swing4",
                    "attackSound2_id":"marth_sword_swing2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "power":20,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "power":20,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox3":{
                            "damage":6,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox4":{
                            "damage":6,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "a_up":{
                    "canFallOff":false,
                    "chargetime_max":40,
                    "chargeClick":true,
                    "attackVoice1_id":"marth_usmash",
                    "attackSound1_id":"marth_sword_swing2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":4,
                            "chargedPriority":6,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":90,
                            "power":45,
                            "kbConstant":70,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":5,
                            "priority":3,
                            "chargedPriority":3,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":110,
                            "power":120,
                            "kbConstant":20,
                            "effectSound":"brawl_punch_s"
                        },
                        "attackBox3":{
                            "damage":17,
                            "priority":6,
                            "chargedPriority":6,
                            "hitStun":5,
                            "selfHitStun":4,
                            "effect_id":"effect_swordSlash",
                            "direction":90,
                            "power":50,
                            "kbConstant":98,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackSound1_id":"marth_sword_swing1",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "hitLag":-1.1,
                            "effect_id":"effect_swordSlash",
                            "direction":110,
                            "power":40,
                            "kbConstant":105,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "hitLag":-1.1,
                            "effect_id":"effect_swordSlash",
                            "direction":110,
                            "power":40,
                            "kbConstant":105,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox3":{
                            "damage":12,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":3,
                            "hitLag":-1.1,
                            "effect_id":"effect_swordSlash",
                            "direction":110,
                            "power":40,
                            "kbConstant":90,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox4":{
                            "damage":12,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":3,
                            "hitLag":-1.1,
                            "effect_id":"effect_swordSlash",
                            "direction":110,
                            "power":40,
                            "kbConstant":90,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "a_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackSound1_id":"marth_sword_swing3",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "power":55,
                            "kbConstant":55,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":55,
                            "power":35,
                            "kbConstant":60,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox3":{
                            "damage":12,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":50,
                            "power":65,
                            "kbConstant":55,
                            "hitLag":-1.1,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackSound1_id":"marth_sword_swing3",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":30,
                            "kbConstant":70,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":30,
                            "kbConstant":70,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox3":{
                            "damage":12,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":4,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "a_forwardsmash":{
                    "canFallOff":false,
                    "chargetime_max":40,
                    "chargeClick":true,
                    "attackVoice1_id":"marth_fsmash",
                    "attackSound1_id":"marth_sword_swing2",
                    "attackSound2_id":"marth_fsmash_swing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":50,
                            "power":60,
                            "kbConstant":70,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":50,
                            "power":60,
                            "kbConstant":70,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox3":{
                            "damage":19,
                            "priority":6,
                            "chargedPriority":7,
                            "hitStun":8,
                            "selfHitStun":6,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":80,
                            "kbConstant":70,
                            "effectSound":"sw_brawl_hit_H"
                        },
                        "attackBox4":{
                            "damage":19,
                            "priority":6,
                            "chargedPriority":7,
                            "hitStun":8,
                            "selfHitStun":6,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":80,
                            "kbConstant":70,
                            "effectSound":"sw_brawl_hit_H"
                        }
                    }
                },
                "a_down":{
                    "canFallOff":false,
                    "chargetime_max":40,
                    "chargeClick":true,
                    "attackVoice1_id":"marth_dsmash",
                    "attackSound1_id":"marth_sword_swing3",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":75,
                            "power":56,
                            "kbConstant":70,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox2":{
                            "damage":16,
                            "priority":5,
                            "hitStun":6,
                            "selfHitStun":4,
                            "effect_id":"effect_swordSlash",
                            "direction":70,
                            "power":50,
                            "kbConstant":80,
                            "effectSound":"sw_brawl_hit_H"
                        }
                    }
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackSound1_id":"marth_sword_swing1",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":100,
                            "power":30,
                            "kbConstant":40,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":100,
                            "power":30,
                            "kbConstant":40,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackSound1_id":"marth_sword_swing1",
                    "attackSound2_id":"marth_sword_swing2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":55,
                            "kbConstant":70,
                            "hitLag":-1.15,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":60,
                            "kbConstant":80,
                            "hitLag":-1.15,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox3":{
                            "damage":13,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":60,
                            "kbConstant":80,
                            "hitLag":-1.15,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackSound1_id":"marth_sword_swing4",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":55,
                            "power":40,
                            "kbConstant":70,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":55,
                            "power":40,
                            "kbConstant":70,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox3":{
                            "damage":12,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":55,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox4":{
                            "damage":12,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":55,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "flip":true,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackSound1_id":"marth_sword_swing3",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":55,
                            "power":30,
                            "kbConstant":85,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":55,
                            "power":30,
                            "kbConstant":85,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox3":{
                            "damage":13,
                            "priority":3,
                            "hitStun":7,
                            "selfHitStun":5,
                            "effect_id":"effect_swordSlash",
                            "direction":35,
                            "power":30,
                            "kbConstant":90,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox4":{
                            "damage":13,
                            "priority":3,
                            "hitStun":7,
                            "selfHitStun":5,
                            "effect_id":"effect_swordSlash",
                            "direction":35,
                            "power":30,
                            "kbConstant":90,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackSound1_id":"marth_sword_swing2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "power":30,
                            "kbConstant":70,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "power":30,
                            "kbConstant":70,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox3":{
                            "damage":14,
                            "priority":4,
                            "hitStun":7,
                            "selfHitStun":5,
                            "effect_id":"effect_swordSlash",
                            "direction":280,
                            "reversableAngle":false,
                            "forceTumbleFall":true,
                            "power":60,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_M",
                            "hitLag":-0.7
                        },
                        "attackBox4":{
                            "damage":14,
                            "priority":4,
                            "hitStun":7,
                            "selfHitStun":5,
                            "effect_id":"effect_swordSlash",
                            "direction":280,
                            "reversableAngle":false,
                            "forceTumbleFall":true,
                            "power":60,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_M",
                            "hitLag":-0.7
                        }
                    }
                },
                "b":{
                    "canFallOff":false,
                    "allowControl":false,
                    "chargetime_max":45,
                    "canFallOff":false,
                    "attackVoice1_id":"marth_nspec",
                    "attackSound1_id":"marth_nspec_charge",
                    "attackSound2_id":"marth_nspec_swing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":40,
                            "power":70,
                            "kbConstant":70,
                            "shieldDamage":40,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":5,
                            "hitStun":6,
                            "selfHitStun":5,
                            "effect_id":"effect_swordSlash",
                            "direction":40,
                            "power":70,
                            "kbConstant":75,
                            "shieldDamage":55,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "b_air":{
                    "canFallOff":false,
                    "allowControl":false,
                    "chargetime_max":45,
                    "canFallOff":false,
                    "attackVoice1_id":"marth_nspec",
                    "attackSound1_id":"marth_nspec_charge",
                    "attackSound2_id":"marth_nspec_swing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":40,
                            "power":70,
                            "kbConstant":70,
                            "shieldDamage":40,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":5,
                            "hitStun":6,
                            "selfHitStun":5,
                            "effect_id":"effect_swordSlash",
                            "direction":40,
                            "power":70,
                            "kbConstant":75,
                            "shieldDamage":55,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "b_up":{
                    "resetMovement":true,
                    "isRecoveryMove":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-0.86,
                    "xSpeedDecayAir":-2,
                    "attackSound1_id":"marth_uspec",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":-1,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":75,
                            "power":70,
                            "kbConstant":60,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":-1,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":75,
                            "power":70,
                            "kbConstant":60,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox3":{
                            "damage":13,
                            "priority":-1,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":80,
                            "kbConstant":60,
                            "effectSound":"sw_brawl_hit_H"
                        }
                    }
                },
                "b_up_air":{
                    "resetMovement":true,
                    "isRecoveryMove":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-0.86,
                    "xSpeedDecayAir":-2,
                    "attackSound1_id":"marth_uspec",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":-1,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":75,
                            "power":70,
                            "kbConstant":60,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":-1,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":75,
                            "power":70,
                            "kbConstant":60,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox3":{
                            "damage":13,
                            "priority":-1,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":45,
                            "power":80,
                            "kbConstant":60,
                            "effectSound":"sw_brawl_hit_H"
                        }
                    }
                },
                "b_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackSound1_id":"marth_sword_swing1",
                    "attackSound2_id":"marth_sword_swing2",
                    "attackSound3_id":"marth_sword_swing3",
                    "attackSound4_id":"marth_sword_swing4",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":55,
                            "power":50,
                            "kbConstant":10,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":6,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":55,
                            "power":50,
                            "kbConstant":10,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox3":{
                            "damage":6,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":55,
                            "power":50,
                            "kbConstant":10,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "b_forward_air":{
                    "canFallOff":false,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackSound1_id":"marth_sword_swing3",
                    "attackSound2_id":"marth_sword_swing2",
                    "attackSound3_id":"marth_sword_swing3",
                    "attackSound4_id":"marth_sword_swing4",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "power":50,
                            "kbConstant":10,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":6,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "power":50,
                            "kbConstant":10,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox3":{
                            "damage":6,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "power":50,
                            "kbConstant":10,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "b_down":{
                    "canFallOff":false,
                    "resetMovement":true,
                    "attackVoice1_id":"marth_dspec",
                    "attackVoice2_id":"marth_dspec2",
                    "attackVoice3_id":"marth_dspec3",
                    "attackSound1_id":"marth_dspec_ching",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "hitStun":4,
                            "priority":7,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":50,
                            "power":90,
                            "kbConstant":35,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "b_down_air":{
                    "attackVoice1_id":"marth_dspec",
                    "attackVoice2_id":"marth_dspec2",
                    "attackVoice3_id":"marth_dspec3",
                    "attackSound1_id":"marth_dspec_ching",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "hitStun":4,
                            "priority":7,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":50,
                            "power":90,
                            "kbConstant":35,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackBoxes":{"attackBox":{
                            "hitLag":-1.25,
                            "damage":4,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":85,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":90,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":35,
                            "reversableAngle":false,
                            "power":65,
                            "kbConstant":30,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":135,
                            "reversableAngle":false,
                            "power":45,
                            "kbConstant":60,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_down":{
                    "canFallOff":false,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "forceTumbleFall":true,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":155,
                            "reversableAngle":false,
                            "power":75,
                            "kbConstant":30,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackSound1_id":"marth_sword_swing2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":40,
                            "kbConstant":40,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":40,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackSound1_id":"marth_sword_swing2",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":65,
                            "power":40,
                            "kbConstant":50,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "getup_attack":{
                    "attackVoice1_id":"marth_grunt1",
                    "attackVoice2_id":"marth_grunt2",
                    "attackVoice3_id":"marth_grunt3",
                    "attackVoice4_id":"marth_grunt4",
                    "attackSound1_id":"marth_sword_swing2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":60,
                            "kbConstant":60,
                            "stackKnockback":false,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":60,
                            "kbConstant":60,
                            "stackKnockback":false,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "kirby":{
                    "chargetime_max":90,
                    "attackVoice1_id":"kirby_hammer3",
                    "attackVoice2_id":"kirby_yah",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":5,
                            "kbConstant":100,
                            "stackKnockback":false,
                            "effectSound":"brawl_fan"
                        }}
                },
                "kirby_air":{
                    "allowControl":true,
                    "chargetime_max":90,
                    "attackVoice1_id":"kirby_hammer3",
                    "attackVoice2_id":"kirby_yah",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":5,
                            "kbConstant":100,
                            "stackKnockback":false,
                            "effectSound":"brawl_fan"
                        }}
                },
                "special":{
                    "air_ease":0,
                    "resetMovement":true,
                    "invincible":true,
                    "canUseInAir":true,
                    "attackVoice1_id":"marth_fs_vfx",
                    "attackSound1_id":"marth_fs_sfx1",
                    "attackSound2_id":"marth_fs_sfx2",
                    "attackSound3_id":"marth_fs_sfx3",
                    "attackSound4_id":"marth_fs_sfx4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":-1,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"marth_finalsmash_effect",
                            "direction":0,
                            "power":0,
                            "kbConstant":0,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object;
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("marth");
        }

        public function getGUID():String
        {
            return ("9f391931-db1b-47a9-82b1-2c1d2560c6b7");
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package marth_fla

