// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//samus_fla.MainTimeline

package samus_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public var missileExplosion:missileExplode;

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function getAudio():Array
        {
            return (new Array(samus_uspec1, samus_uspec2, samus_uspec3, samus_uspec4, samus_uspec5, samus_uspec6, samus_aerial_up, samus_bomb_sfx, samus_brake, samus_charge, samus_crouch, samus_dodge_run, samus_grab_beam, samus_jump1, samus_jump2, samus_landing_heavy, samus_landing_light, samus_missile_homing, samus_missile_shoot, samus_poof, samus_shot1, samus_shot2, samus_shot3, samus_shot4, samus_starko, samus_step, samus_swing_l, samus_swing_m, samus_swing_s, samus_tilt_down, samus_tilt_up1, samus_tilt_up2, samus_victory, samus_fs_beam, samus_gun_startup, samus_gun_whir));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"samus",
                "displayName":"Samus",
                "linkage_id":"samus",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"samus_head",
                "seriesIcon":"Series_Metroid",
                "width":31,
                "height":45,
                "revivalEffect":null,
                "jumpSpeed":16.9,
                "jumpSpeedMidair":15.9,
                "jumpStartup":2,
                "shortHopSpeed":12.35,
                "max_jumpSpeed":8.1,
                "dodgeSpeed":8,
                "gravity":1.19,
                "weight1":110,
                "power":"samus",
                "norm_xSpeed":5.5,
                "max_xSpeed":8.8,
                "max_ySpeed":9.3,
                "fastFallSpeed":13,
                "accel_start":0.59,
                "accel_start_dash":1.154,
                "accel_rate":1,
                "accel_rate_air":0.54,
                "decel_rate":-1.27,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":60,
                "tetherGrab":true,
                "roll_speed":25,
                "roll_delay":5,
                "getup_roll_delay":0,
                "itemScaleRatio":0.769230769230769,
                "special_type":1,
                "normalStats_id":"samus",
                "specialStats_id":null,
                "sounds":{
                    "jump":"samus_jump1",
                    "jump_midair":"samus_jump2",
                    "hurt":null,
                    "hurt2":null,
                    "hurtBad":null,
                    "hurtBad2":null,
                    "dead":null,
                    "dead2":null,
                    "pummel":"brawl_punch_s",
                    "screenko":"samus_starko",
                    "starko":"samus_starko",
                    "ledge_grab":null,
                    "winTheme":"MetroidVictory"
                },
                "hurtFrames":4,
                "grabDamage":1
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":100,
                    "combo_max":2,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "reenableTimer":18,
                    "attackSound1_id":"samus_swing_s",
                    "attackSound2_id":"samus_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":5,
                            "kbConstant":100,
                            "stackKnockback":false,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "a_up":{
                    "refreshRate":30,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"samus_poof",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "priority":4,
                            "sdiDistance":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_firehit1",
                            "direction":130,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":20,
                            "canDI":false,
                            "effectSound":"brawl_fire_s"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":4,
                            "sdiDistance":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_firehit1",
                            "direction":130,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":20,
                            "canDI":false,
                            "effectSound":"brawl_fire_s"
                        }
                    }
                },
                "a_up_tilt":{
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "attackSound1_id":"samus_tilt_up1",
                    "attackSound2_id":"samus_tilt_up2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "hitLag":-1.3,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":65,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_l",
                            "onlyAffectsGround":true
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "hitLag":-1.3,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":65,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_l",
                            "onlyAffectsGround":true
                        },
                        "attackBox3":{
                            "damage":13,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "hitLag":-1.3,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":65,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_l",
                            "onlyAffectsGround":true
                        },
                        "attackBox4":{
                            "damage":13,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":50,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_l",
                            "onlyAffectsAir":true
                        },
                        "attackBox5":{
                            "damage":13,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":50,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_l",
                            "onlyAffectsAir":true
                        },
                        "attackBox6":{
                            "damage":13,
                            "priority":3,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":50,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_l",
                            "onlyAffectsAir":true
                        }
                    }
                },
                "a_forward":{
                    "canFallOff":false,
                    "attackSound1_id":"samus_dodge_run",
                    "attackSound2_id":"samus_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":50,
                            "power":110,
                            "kbConstant":20,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackSound1_id":"samus_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"samus_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":16,
                            "priority":6,
                            "chargedPriority":6,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":55,
                            "kbConstant":70,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":16,
                            "priority":6,
                            "chargedPriority":6,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":55,
                            "kbConstant":70,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"samus_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":15,
                            "priority":6,
                            "hitStun":6,
                            "selfHitStun":4,
                            "effect_id":"effect_hit1",
                            "direction":140,
                            "power":90,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":15,
                            "priority":6,
                            "hitStun":6,
                            "selfHitStun":4,
                            "effect_id":"effect_hit1",
                            "direction":140,
                            "power":90,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air":{
                    "allowControl":true,
                    "attackSound1_id":"samus_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":5,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":60,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":5,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":60,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_up":{
                    "allowControl":true,
                    "attackSound1_id":"samus_aerial_up",
                    "cpuAttackQueue":"a_air; a_air_down",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "power":70,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":3,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "power":70,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox3":{
                            "damage":3,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "power":70,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                },
                "a_air_forward":{
                    "allowControl":true,
                    "attackSound1_id":"samus_poof",
                    "cpuAttackQueue":"a_air; a_forwardsmash; a_down; crouch_attack",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "priority":5,
                            "hitStun":3,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_firehit1",
                            "direction":80,
                            "power":40,
                            "kbConstant":35,
                            "burn":true,
                            "effectSound":"brawl_fire_l"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":5,
                            "hitStun":3,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_firehit1",
                            "direction":80,
                            "power":40,
                            "kbConstant":35,
                            "burn":true,
                            "effectSound":"brawl_fire_l"
                        }
                    }
                },
                "a_air_backward":{
                    "allowControl":true,
                    "attackSound1_id":"samus_swing_l",
                    "cpuAttackQueue":"a_air_backward; a_air; a_air_down",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "direction":30,
                            "power":42,
                            "kbConstant":65,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":4,
                            "effect_id":"effect_hit2",
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":13,
                            "direction":30,
                            "power":42,
                            "kbConstant":65,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":4,
                            "effect_id":"effect_hit2",
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox3":{
                            "damage":13,
                            "direction":30,
                            "power":42,
                            "kbConstant":65,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":4,
                            "effect_id":"effect_hit2",
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox4":{
                            "damage":13,
                            "direction":30,
                            "power":42,
                            "kbConstant":65,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":4,
                            "effect_id":"effect_hit2",
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air_down":{
                    "allowControl":true,
                    "attackSound1_id":"samus_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":15,
                            "priority":-1,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":35,
                            "kbConstant":85,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":15,
                            "priority":-1,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":35,
                            "kbConstant":85,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox3":{
                            "damage":15,
                            "priority":-1,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":35,
                            "kbConstant":85,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox4":{
                            "damage":15,
                            "priority":-1,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":35,
                            "kbConstant":85,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "b":{
                    "linkCharge":"b_air",
                    "cancelWhenAirborne":false,
                    "isLongRangeMove":true,
                    "cancelSoundOnEnd":true,
                    "allowControl":false,
                    "chargetime_max":72,
                    "charge_retain":true,
                    "holdRepeat":true,
                    "chargeInAir":false,
                    "reenableTimer":3,
                    "useChargeBar":false,
                    "attackSound1_id":"samus_charge",
                    "attackSound2_id":"samus_shot1",
                    "attackSound3_id":"samus_shot2",
                    "attackSound4_id":"samus_shot3",
                    "attackSound5_id":"samus_shot4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "linkCharge":"b",
                    "cancelWhenAirborne":false,
                    "isLongRangeMove":true,
                    "cancelSoundOnEnd":true,
                    "allowControl":false,
                    "allowControlGround":false,
                    "chargetime_max":72,
                    "charge_retain":true,
                    "holdRepeat":true,
                    "chargeInAir":false,
                    "reenableTimer":3,
                    "useChargeBar":false,
                    "attackSound1_id":"samus_charge",
                    "attackSound2_id":"samus_shot1",
                    "attackSound3_id":"samus_shot2",
                    "attackSound4_id":"samus_shot3",
                    "attackSound5_id":"samus_shot4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "refreshRate":2,
                    "linkCharge":true,
                    "cancelWhenAirborne":false,
                    "xSpeedAccelAir":2,
                    "air_ease":0,
                    "xSpeedCap":3.4,
                    "isRecoveryMove":true,
                    "attackSound1_id":"samus_uspec1",
                    "attackSound2_id":"samus_uspec2",
                    "attackSound3_id":"samus_uspec3",
                    "attackSound4_id":"samus_uspec4",
                    "attackSound5_id":"samus_uspec5",
                    "attackSound6_id":"samus_uspec6",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":150,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "b_up_air":{
                    "refreshRate":1,
                    "linkCharge":true,
                    "cancelWhenAirborne":false,
                    "xSpeedAccelAir":1.1,
                    "air_ease":2.3,
                    "xSpeedCap":5.87,
                    "allowControl":true,
                    "isRecoveryMove":true,
                    "attackSound1_id":"samus_uspec1",
                    "attackSound2_id":"samus_uspec2",
                    "attackSound3_id":"samus_uspec3",
                    "attackSound4_id":"samus_uspec4",
                    "attackSound5_id":"samus_uspec5",
                    "attackSound6_id":"samus_uspec6",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":0,
                            "kbConstant":95,
                            "shock":true,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "b_forward":{
                    "canFallOff":false,
                    "isLongRangeMove":true,
                    "attackSound1_id":"samus_missile_homing",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":30,
                            "reversableAngle":false,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"brawl_fire_s"
                        }}
                },
                "b_forward_air":{
                    "canFallOff":false,
                    "allowControl":false,
                    "allowFastFall":false,
                    "isLongRangeMove":true,
                    "attackSound1_id":"samus_missile_homing",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":30,
                            "reversableAngle":false,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"brawl_fire_s"
                        }}
                },
                "b_down":{
                    "cancelWhenAirborne":false,
                    "allowControl":false,
                    "jumpFrame":"switch5",
                    "allowFastFall":false,
                    "xSpeedAccel":0.2,
                    "attackSound1_id":"samus_bomb_sfx",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":20,
                            "kbConstant":16,
                            "effectSound":"kick"
                        }}
                },
                "b_down_air":{
                    "isHorizontalRecoveryMove":true,
                    "allowFastFall":false,
                    "cancelWhenAirborne":false,
                    "allowControl":false,
                    "xSpeedAccel":0.2,
                    "xSpeedAccelAir":1.5,
                    "jumpFrame":"switch5",
                    "attackSound1_id":"samus_bomb_sfx",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":20,
                            "kbConstant":16,
                            "effectSound":"kick"
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackSound1_id":"samus_grab_beam",
                    "cpuAttackQueue":"a_air; a_air_up; a_up; a_up_tilt",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":80,
                            "reversableAngle":false,
                            "power":25,
                            "kbConstant":100,
                            "shock":true,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_zap_s"
                        }}
                },
                "throw_forward":{
                    "refreshRate":10,
                    "canFallOff":false,
                    "attackSound1_id":"samus_grab_beam",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":42,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":55,
                            "bypassNonGrabbed":true,
                            "effectSound":null
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackSound1_id":"samus_grab_beam",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":140,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":60,
                            "bypassNonGrabbed":true,
                            "effectSound":null
                        }}
                },
                "throw_down":{
                    "canFallOff":false,
                    "attackSound1_id":"samus_grab_beam",
                    "cpuAttackQueue":"crouch_attack; a_down; a_air; a_air_forward",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":0,
                            "hitStun":5,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":95,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":30,
                            "bypassNonGrabbed":true,
                            "effectSound":null
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackSound1_id":"samus_tilt_down",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1.25,
                            "selfHitStun":1,
                            "effect_id":"effect_firehit1",
                            "direction":100,
                            "power":70,
                            "kbConstant":75,
                            "burn":true,
                            "effectSound":"brawl_fire_s"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1.25,
                            "selfHitStun":1,
                            "effect_id":"effect_firehit1",
                            "direction":100,
                            "power":70,
                            "kbConstant":75,
                            "burn":true,
                            "effectSound":"brawl_fire_s"
                        },
                        "attackBox3":{
                            "damage":14,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1.25,
                            "selfHitStun":1,
                            "effect_id":"effect_firehit1",
                            "direction":100,
                            "power":70,
                            "kbConstant":75,
                            "burn":true,
                            "effectSound":"brawl_fire_s"
                        },
                        "attackBox4":{
                            "damage":14,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1.25,
                            "selfHitStun":1,
                            "effect_id":"effect_firehit1",
                            "direction":100,
                            "power":70,
                            "kbConstant":75,
                            "burn":true,
                            "effectSound":"brawl_fire_s"
                        }
                    }
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackSound1_id":"samus_swing_s",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":40,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackSound1_id":"samus_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "kirby":{
                    "cancelSoundOnEnd":true,
                    "isLongRangeMove":true,
                    "allowControl":true,
                    "chargetime_max":72,
                    "charge_retain":true,
                    "holdRepeat":true,
                    "chargeInAir":false,
                    "reenableTimer":3,
                    "useChargeBar":false,
                    "attackSound1_id":"samus_charge",
                    "attackSound2_id":"samus_shot1",
                    "attackSound3_id":"samus_shot2",
                    "attackSound4_id":"samus_shot3",
                    "attackSound5_id":"samus_shot4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "cancelSoundOnEnd":true,
                    "isLongRangeMove":true,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargetime_max":72,
                    "charge_retain":true,
                    "holdRepeat":true,
                    "chargeInAir":false,
                    "reenableTimer":3,
                    "useChargeBar":false,
                    "attackSound1_id":"samus_charge",
                    "attackSound2_id":"samus_shot1",
                    "attackSound3_id":"samus_shot2",
                    "attackSound4_id":"samus_shot3",
                    "attackSound5_id":"samus_shot4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackSound1_id":"samus_fs_beam",
                    "attackSound2_id":"samus_charge",
                    "attackSound3_id":"samus_gun_whir",
                    "attackSound4_id":"samus_gun_startup",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "direction":0,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":null
                        }}
                },
                "tether":{
                    "canUseInAir":true,
                    "allowControl":true,
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":0,
                            "hitStun":5,
                            "selfHitStun":1,
                            "hitLag":-1.1,
                            "effect_id":"effect_hit3",
                            "direction":55,
                            "power":50,
                            "kbConstant":60,
                            "shock":true,
                            "effectSound":"brawl_zap_m"
                        }}
                }
            };
            var _local_4:Object = {
                "unchargedshot":{
                    "linkage_id":"samus_chargeshot",
                    "width":20,
                    "height":20,
                    "time_max":35,
                    "xspeed":8,
                    "rideGround":false,
                    "xoffset":28,
                    "yoffset":-37,
                    "limit":3,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":8,
                                "ignoreChargeDamage":true,
                                "priority":-1,
                                "hitStun":-1,
                                "selfHitStun":-1,
                                "effect_id":"effect_hit3",
                                "direction":40,
                                "power":50,
                                "kbConstant":45,
                                "shock":true,
                                "effectSound":"brawl_zap_m"
                            }}}
                },
                "chargedshot":{
                    "linkage_id":"samus_chargeshot",
                    "width":20,
                    "height":20,
                    "time_max":35,
                    "xspeed":11,
                    "rideGround":false,
                    "xoffset":28,
                    "yoffset":-37,
                    "limit":3,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":25,
                                "priority":6,
                                "hitStun":14,
                                "selfHitStun":0,
                                "effect_id":"effect_hit3",
                                "direction":45,
                                "power":80,
                                "kbConstant":50,
                                "shock":true,
                                "effectSound":"brawl_zap_l"
                            }}}
                },
                "homingmissile":{
                    "linkage_id":"samus_missile",
                    "width":27,
                    "rideGround":true,
                    "height":17,
                    "time_max":100,
                    "xdecay":0.2,
                    "trailEffect":"missileTrail",
                    "trailEffectInterval":5,
                    "homingSpeed":8,
                    "homingEase":30,
                    "xspeed":9,
                    "rotate":true,
                    "rideGround":false,
                    "xoffset":32,
                    "yoffset":-45,
                    "canBeAbsorbed":false,
                    "lockSize":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":5,
                                "priority":2,
                                "hitStun":1,
                                "selfHitStun":-1,
                                "camShake":5,
                                "effect_id":"effect_firehit1",
                                "direction":65,
                                "power":90,
                                "kbConstant":45,
                                "burn":true,
                                "effectSound":"brawl_bomb_l"
                            }}}
                },
                "powermissile":{
                    "linkage_id":"samus_supermissile",
                    "width":20,
                    "height":15,
                    "trailEffect":"missileTrail",
                    "trailEffectInterval":3,
                    "rotate":true,
                    "rideGround":false,
                    "canBeAbsorbed":false,
                    "xoffset":32,
                    "yoffset":-45,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":14,
                                "priority":3,
                                "hitStun":2,
                                "selfHitStun":-1,
                                "camShake":10,
                                "effect_id":"effect_firehit1",
                                "direction":50,
                                "power":65,
                                "kbConstant":75,
                                "burn":true,
                                "effectSound":"brawl_bomb_l"
                            }}}
                },
                "bomb":{
                    "linkage_id":"samus_bomb",
                    "gravity":0.66,
                    "yspeed":-5.6,
                    "maxgravity":8.1,
                    "bounce":5,
                    "bounce_decay":0.5,
                    "canBeAbsorbed":false,
                    "limit":3,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "hasEffect":false,
                                "priority":3,
                                "hitStun":5,
                                "selfHitStun":0,
                                "direction":80,
                                "power":20,
                                "kbConstant":3,
                                "burn":true,
                                "effectSound":"brawl_fire_s"
                            }}}
                },
                "zerolaser":{
                    "linkage_id":"samus_zero_laser",
                    "width":20,
                    "height":20,
                    "time_max":210,
                    "ghost":true,
                    "rideGround":false,
                    "xoffset":92,
                    "yoffset":-33,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":1,
                                "shieldDamage":10,
                                "priority":7,
                                "sdiDistance":0,
                                "hitStun":0,
                                "selfHitStun":0,
                                "effect_id":"effect_hit3",
                                "direction":10,
                                "power":25,
                                "kbConstant":10,
                                "shock":true,
                                "effectSound":null
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("samus");
        }

        public function getGUID():String
        {
            return ("abad854d-8167-43a7-96a8-d0a666a8ffd3");
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package samus_fla

