// Decompiled by AS3 Sorcerer 6.20
// www.as3sorcerer.com

//blackmage_fla.MainTimeline

package blackmage_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public var grabBox:bm_flare;

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function getAudio():Array
        {
            return (new Array(menumove, bm_footstep, iceshoot, iceshoot2, icecharge, haste2, haste1, chocobo, bmvictory2, bmvictory, bmtaunt3, bmtaunt2, BMRandom, BMflood, bmflare, bmfire, bmbolt, bm_Warp_part2, bm_Warp_part1, bm_Usmash_full, bm_taunt3, bm_taunt2, bm_sw_s, bm_sw_m, bm_sw_l, bm_Quake_start, bm_quake_release, BM_Laugh, bm_FS_start, bm_FS_spellcast, bm_FS_firstscreen, bm_FS_Escape, bm_FS_Error, bm_Entrance_last, bm_Enemydie2, bm_doublejump, bm_Dizzy, bm_Death_start, bm_Death_finish, bm_DashAttack, bm_bthrow_hit, bm_Aero_start2, bm_Aero_start1, bio, bm_whoosh, chocobo2, chocobo3, bm_scythe, bm_knife, bm_chocobocut, bm_effect_staff));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"blackmage",
                "displayName":"Black%20Mage",
                "linkage_id":"black_mage",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"blackmage_head",
                "seriesIcon":"bmseries",
                "width":28,
                "height":33,
                "jumpSpeed":14,
                "jumpSpeedMidair":12,
                "jumpStartup":2,
                "shortHopSpeed":7,
                "max_jumpSpeed":6.5,
                "dodgeSpeed":10,
                "gravity":1.1,
                "weight1":92,
                "power":"blackmage",
                "norm_xSpeed":5.5,
                "max_xSpeed":9.5,
                "max_ySpeed":11,
                "fastFallSpeed":14,
                "accel_start":1,
                "accel_start_dash":1.1,
                "accel_rate":1,
                "accel_rate_air":1.2,
                "decel_rate":-0.76,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":100,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_delay":9,
                "getup_roll_delay":0,
                "itemScaleRatio":0.769230769230769,
                "special_type":5,
                "normalStats_id":"blackmage",
                "specialStats_id":null,
                "sounds":{
                    "jump":"menumove",
                    "jump_midair":"bm_doublejump",
                    "hurt":null,
                    "hurt2":null,
                    "hurtBad":null,
                    "hurtBad2":null,
                    "dead":"bm_Enemydie2",
                    "dead2":null,
                    "pummel":"sw_scratch",
                    "screenko":null,
                    "starko":null,
                    "ledge_grab":null,
                    "winTheme":"FinalFantasyVictory"
                },
                "hurtFrames":3,
                "grabDamage":1,
                "fs_time_limit":600
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":100,
                    "canFallOff":false,
                    "attackSound1_id":"bm_sw_s",
                    "attackSound2_id":"bm_sw_s",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":25,
                            "power":21,
                            "kbConstant":55,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"bm_whoosh",
                    "attackSound2_id":"bm_Usmash_full",
                    "attackSound3_id":"bm_sw_s",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":15,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"effect_firehit1",
                            "direction":89,
                            "power":42,
                            "kbConstant":93,
                            "burn":true,
                            "effectSound":"brawl_fire_l"
                        },
                        "attackBox2":{
                            "damage":15,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"effect_firehit1",
                            "direction":89,
                            "power":42,
                            "kbConstant":93,
                            "burn":true,
                            "effectSound":"brawl_fire_l"
                        }
                    }
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackSound1_id":"bm_sw_s",
                    "cpuAttackQueue":"a_air;a_air_backward;a_air_forward;a_up",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":4,
                            "hitStun":1,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":85,
                            "power":42,
                            "kbConstant":80,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_forward":{
                    "xSpeedDecay":-0.5,
                    "canFallOff":false,
                    "attackSound1_id":"bm_DashAttack",
                    "attackSound2_id":"brawl_sw_s",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_hit1",
                            "direction":35,
                            "reversableAngle":false,
                            "power":35,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackSound1_id":"bm_sw_m",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":30,
                            "power":28,
                            "kbConstant":96,
                            "effectSound":"bm_effect_staff"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "canBeAbsorbed":true,
                    "chargeClick":true,
                    "attackSound1_id":"bmbolt",
                    "attackSound2_id":"bm_whoosh",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":8,
                            "selfHitStun":8,
                            "effect_id":"effect_hit3",
                            "direction":40,
                            "power":38,
                            "kbConstant":80,
                            "shock":true,
                            "effectSound":"brawl_zap_m"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":8,
                            "selfHitStun":8,
                            "effect_id":"effect_hit3",
                            "direction":40,
                            "power":38,
                            "kbConstant":80,
                            "shock":true,
                            "effectSound":"brawl_zap_m"
                        },
                        "attackBox3":{
                            "damage":14,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":8,
                            "selfHitStun":8,
                            "effect_id":"effect_hit3",
                            "direction":40,
                            "power":38,
                            "kbConstant":80,
                            "shock":true,
                            "effectSound":"brawl_zap_m"
                        }
                    }
                },
                "a_down":{
                    "cancelSoundOnEnd":true,
                    "refreshRate":999,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"icecharge",
                    "attackSound2_id":"iceshoot",
                    "attackSound3_id":"bm_whoosh",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":1,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "power":50,
                            "kbConstant":85,
                            "freeze":30,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "a_air":{
                    "refreshRate":2,
                    "hit_ease":5,
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "cpuAttackQueue":"a_up;a_up_tilt;a_forward_tilt",
                    "attackSound1_id":"bmfire",
                    "attackSound2_id":"bm_sw_s",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":1,
                            "hitLag":-1.4,
                            "weightKB":70,
                            "selfHitStun":1,
                            "effect_id":"effect_firehit1",
                            "direction":110,
                            "power":0,
                            "kbConstant":50,
                            "effectSound":"brawl_fire_s"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":2,
                            "hitStun":1,
                            "hitLag":-1.4,
                            "weightKB":70,
                            "selfHitStun":1,
                            "effect_id":"effect_firehit1",
                            "direction":110,
                            "power":0,
                            "kbConstant":50,
                            "effectSound":"brawl_fire_s"
                        }
                    }
                },
                "a_air_up":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "maintainSpeed":true,
                    "attackSound1_id":"BMflood",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":-1,
                            "hitStun":3,
                            "hitLag":-1.15,
                            "selfHitStun":1,
                            "effect_id":"effect_icehit",
                            "direction":90,
                            "power":35,
                            "kbConstant":95,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "a_air_forward":{
                    "xSpeedDecay":-0.5,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "cpuAttackQueue":"a_forward_tilt;a_air_forward;a_air_down;b_forward;b_forward_air",
                    "attackVoice1_id":"chocobo",
                    "attackSound1_id":"bm_sw_l",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":50,
                            "power":49,
                            "kbConstant":90,
                            "effectSound":"sw_scratch"
                        }}
                },
                "a_air_backward":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackSound1_id":"bm_sw_m",
                    "cpuAttackQueue":"a_air_backward;a_air_forward;a_air_down",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":150,
                            "reversableAngle":false,
                            "power":35,
                            "kbConstant":100,
                            "effectSound":"sw_scratch"
                        }}
                },
                "a_air_down":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "attackSound1_id":"bm_sw_l",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":4,
                            "hitStun":5,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":270,
                            "power":45,
                            "kbConstant":50,
                            "effectSound":"sw_slash"
                        }}
                },
                "b":{
                    "refreshRate":100,
                    "chargetime_max":180,
                    "canFallOff":false,
                    "cpuAttackQueue":"a_forward;a_forwardsmash",
                    "attackSound1_id":"BMstop1",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":0,
                            "priority":7,
                            "hitStun":15,
                            "hitStunProjectile":15,
                            "weightKB":50,
                            "selfHitStun":0,
                            "direction":50,
                            "power":0,
                            "kbConstant":40,
                            "effectSound":"BMstop2"
                        },
                        "attackBox2":{
                            "damage":0,
                            "priority":7,
                            "hitStun":15,
                            "hitStunProjectile":15,
                            "weightKB":50,
                            "selfHitStun":0,
                            "direction":50,
                            "power":0,
                            "kbConstant":40,
                            "effectSound":"BMstop2"
                        },
                        "attackBox3":{
                            "hasEffect":false,
                            "hitStun":0,
                            "selfHitStun":0,
                            "reverse_projectile":true
                        },
                        "attackBox4":{
                            "hasEffect":false,
                            "hitStun":0,
                            "selfHitStun":0,
                            "reverse_projectile":true
                        }
                    }
                },
                "b_air":{
                    "refreshRate":100,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargetime_max":180,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "attackSound1_id":"BMstop1",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":0,
                            "priority":7,
                            "hitStun":15,
                            "hitStunProjectile":15,
                            "weightKB":50,
                            "selfHitStun":0,
                            "direction":50,
                            "power":0,
                            "kbConstant":40,
                            "effectSound":"BMstop2"
                        },
                        "attackBox2":{
                            "damage":0,
                            "priority":7,
                            "hitStun":15,
                            "hitStunProjectile":15,
                            "weightKB":50,
                            "selfHitStun":0,
                            "direction":50,
                            "power":0,
                            "kbConstant":40,
                            "effectSound":"BMstop2"
                        },
                        "attackBox3":{
                            "hasEffect":false,
                            "hitStun":0,
                            "selfHitStun":0,
                            "reverse_projectile":true
                        },
                        "attackBox4":{
                            "hasEffect":false,
                            "hitStun":0,
                            "selfHitStun":0,
                            "reverse_projectile":true
                        }
                    }
                },
                "b_up":{
                    "cancelWhenAirborne":false,
                    "refreshRate":4,
                    "resetMovement":true,
                    "air_ease":3,
                    "chargetime_max":34,
                    "canFallOff":false,
                    "isRecoveryMove":true,
                    "disableForCPU":true,
                    "attackSound1_id":"bm_Warp_part1",
                    "attackSound2_id":"bm_Warp_part2",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":4,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"sw_scratch"
                        }}
                },
                "b_up_air":{
                    "refreshRate":4,
                    "cancelWhenAirborne":false,
                    "resetMovement":true,
                    "air_ease":3,
                    "chargetime_max":34,
                    "canFallOff":false,
                    "isRecoveryMove":true,
                    "disableForCPU":true,
                    "attackSound1_id":"bm_Warp_part1",
                    "attackSound2_id":"bm_Warp_part2",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":4,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"sw_scratch"
                        }}
                },
                "b_forward":{
                    "canFallOff":false,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-0.5,
                    "xSpeedDecayAir":1,
                    "air_ease":0,
                    "attackSound1_id":"bm_sw_m",
                    "attackSound2_id":"bm_sw_s",
                    "attackSound3_id":"bm_sw_l",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "hasEffect":false,
                            "priority":-1,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":32,
                            "power":75,
                            "kbConstant":85,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "b_forward_air":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-0.5,
                    "xSpeedDecayAir":1,
                    "air_ease":0,
                    "attackSound1_id":"bm_sw_m",
                    "attackSound2_id":"bm_sw_s",
                    "attackSound3_id":"bm_sw_l",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "hasEffect":false,
                            "priority":-1,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":32,
                            "power":75,
                            "kbConstant":85,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "b_down":{
                    "resetMovement":true,
                    "chargetime_max":45,
                    "canFallOff":false,
                    "attackSound1_id":"bm_sw_l",
                    "attackSound2_id":"sw_strongslash",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":4,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":36,
                            "kbConstant":88,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b_down_air":{
                    "air_ease":6,
                    "allowControl":true,
                    "chargetime_max":45,
                    "canFallOff":false,
                    "allowFastFall":false,
                    "linkFrames":true,
                    "attackSound1_id":"bm_sw_l",
                    "attackSound2_id":"sw_strongslash",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":4,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":36,
                            "kbConstant":88,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_up":{
                    "refreshRate":3,
                    "canFallOff":false,
                    "attackSound1_id":"bm_sw_s",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "hasEffect":false,
                            "priority":-1,
                            "hitStun":4,
                            "hitLag":-1.15,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":66,
                            "reversableAngle":false,
                            "power":10,
                            "kbConstant":8,
                            "bypassNonGrabbed":true,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "throw_forward":{
                    "refreshRate":3,
                    "canFallOff":false,
                    "attackSound1_id":"bm_Aero_start1",
                    "attackSound2_id":"bm_Aero_start2",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "hasEffect":false,
                            "priority":-1,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":10,
                            "power":80,
                            "kbConstant":100,
                            "bypassNonGrabbed":true,
                            "effectSound":"launch_s"
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "cpuAttackQueue":"b_forward",
                    "attackSound1_id":"bm_Quake_start",
                    "attackSound2_id":"bm_quake_release",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":-1,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":130,
                            "power":48,
                            "kbConstant":120,
                            "bypassNonGrabbed":true,
                            "effectSound":"sw_scratch"
                        }}
                },
                "throw_down":{
                    "canFallOff":false,
                    "attackSound1_id":"bio",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "hasEffect":false,
                            "priority":-1,
                            "hitStun":5,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "direction":40,
                            "power":40,
                            "kbConstant":120,
                            "bypassNonGrabbed":true,
                            "poison":1,
                            "poisonInterval":25,
                            "effectSound":null
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackSound1_id":"bm_sw_m",
                    "cpuAttackQueue":"b_forward",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":30,
                            "kbConstant":88,
                            "effectSound":"sw_scratch"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "cancelWhenAirborne":false,
                    "maintainSpeed":true,
                    "attackSound1_id":"bm_sw_m",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":-1,
                            "hitStun":1,
                            "weightKB":110,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":30,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "getup_attack":{"attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":2,
                            "direction":30,
                            "power":111,
                            "kbConstant":50,
                            "effectSound":null
                        }}},
                "kirby":{
                    "refreshRate":100,
                    "chargetime_max":180,
                    "canFallOff":false,
                    "cpuAttackQueue":"a_forward",
                    "attackSound1_id":"BMstop1",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":7,
                            "hitStun":15,
                            "hitStunProjectile":15,
                            "weightKB":50,
                            "selfHitStun":0,
                            "direction":50,
                            "power":0,
                            "kbConstant":40,
                            "effectSound":"BMstop2"
                        }}
                },
                "kirby_air":{
                    "refreshRate":100,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargetime_max":180,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "attackSound1_id":"BMstop1",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":7,
                            "hitStun":15,
                            "hitStunProjectile":15,
                            "weightKB":50,
                            "selfHitStun":0,
                            "direction":50,
                            "power":0,
                            "kbConstant":40,
                            "effectSound":"BMstop2"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"ichigo_bankai",
                    "attackSound1_id":"bmflare",
                    "attackSound2_id":"bm_FS_spellcast",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":-1,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":0,
                            "power":2,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object = {
                "fsmashfull":{
                    "linkage_id":"BMfsmashfull",
                    "width":30,
                    "height":90,
                    "time_max":200,
                    "xspeed":4,
                    "limit":1,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":20,
                                "priority":6,
                                "hitStun":10,
                                "hitLag":-1.1,
                                "selfHitStun":0,
                                "camShake":10,
                                "direction":35,
                                "power":63,
                                "kbConstant":28,
                                "shock":true,
                                "effectSound":"brawl_zap_m"
                            }}}
                },
                "dsmashfullright":{
                    "linkage_id":"dsmashfullright",
                    "width":40,
                    "height":20,
                    "time_max":150,
                    "xspeed":2,
                    "gravity":50,
                    "maxgravity":50,
                    "canBeReversed":false,
                    "limit":25,
                    "canFallOff":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":3,
                                "priority":4,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "direction":25,
                                "power":56,
                                "kbConstant":95,
                                "freeze":30,
                                "effectSound":null
                            }}}
                },
                "dsmashfullleft":{
                    "linkage_id":"dsmashfullleft",
                    "width":40,
                    "height":20,
                    "time_max":150,
                    "xspeed":-2,
                    "gravity":50,
                    "maxgravity":50,
                    "canBeReversed":false,
                    "limit":25,
                    "canFallOff":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":3,
                                "priority":4,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "direction":155,
                                "power":56,
                                "kbConstant":95,
                                "freeze":30,
                                "effectSound":null
                            }}}
                },
                "death":{
                    "linkage_id":"bm_dair_death",
                    "width":22,
                    "height":44,
                    "time_max":999,
                    "ghost":true,
                    "stale":false,
                    "xoffset":-10,
                    "yoffset":12,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "latch":true,
                    "latch_x_offset":-12,
                    "latch_y_offset":-8,
                    "limit":2,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "hasEffect":false,
                                "damage":0,
                                "priority":7,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "direction":270,
                                "power":0,
                                "kbConstant":0,
                                "effectSound":null
                            }}}
                },
                "warp":{
                    "linkage_id":"bmwarp",
                    "width":40,
                    "height":20,
                    "time_max":150,
                    "xspeed":12,
                    "yspeed":12,
                    "controlDirection":90,
                    "controlInitDirection":true,
                    "maxgravity":10,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":0,
                                "effectSound":null
                            }}}
                },
                "meteor":{
                    "linkage_id":"bmmeteorprojectile",
                    "width":40,
                    "height":20,
                    "time_max":210,
                    "yspeed":-6,
                    "xoffset":14,
                    "yoffset":-5,
                    "canBeAbsorbed":false,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":5,
                                "priority":6,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "direction":45,
                                "power":35,
                                "kbConstant":100,
                                "effectSound":"brawl_punch_s"
                            }}}
                },
                "meteorair":{
                    "linkage_id":"bmmeteorprojectileair",
                    "width":40,
                    "height":20,
                    "time_max":210,
                    "yspeed":-6,
                    "xoffset":14,
                    "yoffset":-5,
                    "canBeAbsorbed":false,
                    "noFlip":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":5,
                                "priority":6,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "direction":45,
                                "power":35,
                                "kbConstant":100,
                                "effectSound":"brawl_punch_s"
                            }}}
                },
                "bthrowrock":{
                    "linkage_id":"bm_bthrowrock",
                    "gravity":1,
                    "maxgravity":4,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "canFallOff":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":8,
                                "priority":-1,
                                "hitStun":2,
                                "selfHitStun":2,
                                "camShake":7,
                                "direction":130,
                                "reversableAngle":false,
                                "power":65,
                                "kbConstant":125,
                                "bypassNonGrabbed":true,
                                "effectSound":"bm_bthrow_hit"
                            }}}
                },
                "flare":{
                    "linkage_id":"bm_flare",
                    "width":100,
                    "height":100,
                    "time_max":40,
                    "ghost":true,
                    "xoffset":-6,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":38,
                                "priority":-1,
                                "hitStun":3,
                                "selfHitStun":0,
                                "effect_id":"effect_hit1",
                                "direction":-2,
                                "power":146,
                                "kbConstant":40,
                                "effectSound":null
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("blackmage");
        }

        public function getGUID():String
        {
            return ("9b58e501-9135-4535-a349-53d9efde8809");
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package blackmage_fla

