// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//yoshi_fla.MainTimeline

package yoshi_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        public function getAudio():Array
        {
            return (new Array(Yoshi_AttackU, Yoshi_YoshiBomb, Yoshi_Tongue, Yoshi_Throw_Spit, Yoshi_Jump02, Yoshi_Jump01, Yoshi_starKO, Yoshi_AttackD, Yoshi_AttackF, brawl_Yoshi_swing_s, brawl_Yoshi_swing_m, brawl_Yoshi_swing_l, Yoshi_fspecial_stop, Yoshi_fspecial_start, Yoshi_fspecial, Yoshi_layegg, Yoshi_swallow, Yoshi_nspecial_sfx, Yoshi_dspecial_land, Yoshi_dspecial_start, Yoshi_egg_hit, Yoshi_egg_toss, Yoshi_midjump, Yoshi_jump1, Yoshi_tail_whip, yoshi_fireballShot, yoshi_fireballHit, transformation, yoshi_wingflap, yoshi_wingflap2, yoshi_theme, yoshi_death1, yoshi_death2, yoshi_hurtBad1, yoshi_hurtBad2, yoshi_hurt1, yoshi_grunt1, yoshi_grunt2, yoshi_grunt3, yoshi_grunt4, yoshi_dizzy, yoshi_win, yoshi_crouch, yoshi_dash, yoshi_step1, yoshi_step2, yoshi_tech, yoshi_edgegrab));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"yoshi",
                "displayName":"Yoshi",
                "linkage_id":"yoshi",
                "linkage_id2":null,
                "linkage_id_special":"yoshi_special",
                "thumbnail":"yoshi_head",
                "seriesIcon":"Yoshi_Symbol",
                "width":21,
                "height":38,
                "jumpSpeed":17,
                "jumpSpeedMidair":11,
                "jumpStartup":2,
                "shortHopSpeed":11.5,
                "max_jumpSpeed":8.5,
                "midAirTurn":true,
                "midAirJumpConstant":18,
                "midAirJumpConstantDelay":3,
                "midAirJumpConstantAccel":3,
                "dodgeSpeed":7,
                "gravity":1.6,
                "weight1":111,
                "power":"Yoshi",
                "norm_xSpeed":4.5,
                "max_xSpeed":8.2,
                "max_ySpeed":12,
                "fastFallSpeed":15,
                "accel_start":0.5,
                "accel_start_dash":1.263,
                "accel_rate":1,
                "accel_rate_air":1.2,
                "decel_rate":-0.92,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":15,
                "tetherGrab":false,
                "roll_speed":26,
                "roll_delay":9,
                "getup_roll_delay":0,
                "itemScaleRatio":0.862068965517241,
                "special_type":0,
                "normalStats_id":"yoshi",
                "specialStats_id":"yoshi_special",
                "sounds":{
                    "jump":"Yoshi_Jump01",
                    "jump_midair":"Yoshi_Jump02",
                    "hurt":"yoshi_hurt1",
                    "hurt2":null,
                    "hurtBad":"yoshi_hurtBad1",
                    "hurtBad2":"yoshi_hurtBad2",
                    "dead":"yoshi_death1",
                    "dead2":"yoshi_death2",
                    "pummel":"brawl_punch_m",
                    "screenko":"yoshi_hurtBad1",
                    "starko":"Yoshi_starKO",
                    "ledge_grab":null,
                    "winTheme":"YoshiVictory"
                },
                "hurtFrames":4,
                "grabDamage":1,
                "customShield":true,
                "fs_time_limit":600
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":100,
                    "canFallOff":false,
                    "attackVoice1_id":"yoshi_grunt1",
                    "attackVoice2_id":"yoshi_grunt2",
                    "attackVoice3_id":"yoshi_grunt3",
                    "attackVoice4_id":"yoshi_grunt4",
                    "attackSound1_id":"brawl_Yoshi_swing_s",
                    "attackSound2_id":"brawl_Yoshi_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "shieldDamage":7,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":80,
                            "power":8,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"Yoshi_AttackU",
                    "attackSound1_id":"brawl_Yoshi_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":16,
                            "priority":6,
                            "chargedPriority":6,
                            "hitStun":6,
                            "hitLag":-1.1,
                            "selfHitStun":4,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "reversableAngle":false,
                            "power":35,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"yoshi_grunt1",
                    "attackVoice2_id":"yoshi_grunt2",
                    "attackVoice3_id":"yoshi_grunt3",
                    "attackVoice4_id":"yoshi_grunt4",
                    "attackSound1_id":"Yoshi_tail_whip",
                    "cpuAttackQueue":"a_up_tilt; a_up; a_air; a_air_up; a_air_down",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "shieldDamage":10,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":100,
                            "power":72,
                            "kbConstant":55,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":10,
                            "shieldDamage":10,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":100,
                            "power":72,
                            "kbConstant":55,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forward":{
                    "xSpeedDecay":-2.86,
                    "canFallOff":false,
                    "attackVoice1_id":"yoshi_grunt1",
                    "attackVoice2_id":"yoshi_grunt2",
                    "attackVoice3_id":"yoshi_grunt3",
                    "attackVoice4_id":"yoshi_grunt4",
                    "attackSound1_id":"brawl_Yoshi_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":5,
                            "hitStun":4,
                            "hitLag":-1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":60,
                            "power":70,
                            "kbConstant":60,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"yoshi_grunt1",
                    "attackVoice2_id":"yoshi_grunt2",
                    "attackVoice3_id":"yoshi_grunt3",
                    "attackVoice4_id":"yoshi_grunt4",
                    "attackSound1_id":"Yoshi_tail_whip",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "shieldDamage":13,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":80,
                            "power":35,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"Yoshi_AttackF",
                    "attackSound1_id":"brawl_Yoshi_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "shieldDamage":25,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":8,
                            "selfHitStun":8,
                            "effect_id":"effect_heavyHit",
                            "direction":43,
                            "power":37.5,
                            "kbConstant":98.44,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"Yoshi_AttackD",
                    "attackSound1_id":"Yoshi_tail_whip",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":4,
                            "chargedPriority":6,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":31,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":13,
                            "priority":4,
                            "chargedPriority":6,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":31,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air":{
                    "doubleJumpCancel":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"yoshi_grunt1",
                    "attackVoice2_id":"yoshi_grunt2",
                    "attackVoice3_id":"yoshi_grunt3",
                    "attackVoice4_id":"yoshi_grunt4",
                    "attackSound1_id":"brawl_Yoshi_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "shieldDamage":15,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":25,
                            "kbConstant":108,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_air_up":{
                    "doubleJumpCancel":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"yoshi_grunt1",
                    "attackVoice2_id":"yoshi_grunt2",
                    "attackVoice3_id":"yoshi_grunt3",
                    "attackVoice4_id":"yoshi_grunt4",
                    "attackSound1_id":"Yoshi_tail_whip",
                    "cpuAttackQueue":"a_air_up; a_air_forward; a_air_backward; a_air",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":6,
                            "hitStun":4,
                            "hitLag":-1.08,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":35,
                            "kbConstant":87,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_air_forward":{
                    "doubleJumpCancel":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"yoshi_grunt1",
                    "attackVoice2_id":"yoshi_grunt2",
                    "attackVoice3_id":"yoshi_grunt3",
                    "attackVoice4_id":"yoshi_grunt4",
                    "attackSound1_id":"brawl_Yoshi_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "shieldDamage":18,
                            "priority":3,
                            "sdiDistance":3,
                            "hitStun":6,
                            "hitLag":-1.1,
                            "selfHitStun":4,
                            "effect_id":"effect_heavyHit",
                            "direction":280,
                            "power":25,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_air_backward":{
                    "doubleJumpCancel":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"yoshi_grunt1",
                    "attackVoice2_id":"yoshi_grunt2",
                    "attackVoice3_id":"yoshi_grunt3",
                    "attackVoice4_id":"yoshi_grunt4",
                    "attackSound1_id":"Yoshi_tail_whip",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":120,
                            "reversableAngle":false,
                            "power":10,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":120,
                            "reversableAngle":false,
                            "power":10,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_down":{
                    "doubleJumpCancel":true,
                    "refreshRate":1,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"yoshi_grunt1",
                    "attackVoice2_id":"yoshi_grunt2",
                    "attackVoice3_id":"yoshi_grunt3",
                    "attackVoice4_id":"yoshi_grunt4",
                    "attackSound1_id":"brawl_Yoshi_swing_s",
                    "cpuAttackQueue":"a_up_tilt; a_up; a_down; a_forwardsmash; crouch_attack",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.25,
                            "selfHitStun":3,
                            "effect_id":"effect_hit1",
                            "direction":270,
                            "power":5,
                            "kbConstant":45,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b":{
                    "refreshRate":100,
                    "cancelWhenAirborne":false,
                    "conserveJumpConstant":false,
                    "allowControl":true,
                    "allowControlGround":false,
                    "canFallOff":false,
                    "allowFastFall":false,
                    "attackVoice1_id":"Yoshi_Tongue",
                    "attackSound1_id":"Yoshi_nspecial_sfx",
                    "attackSound2_id":"Yoshi_swallow",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":-1,
                            "hitStun":3,
                            "selfHitStun":6,
                            "direction":45,
                            "power":50,
                            "kbConstant":10,
                            "egg":true,
                            "bypassNonGrabbed":true,
                            "effectSound":"Yoshi_layegg"
                        }}
                },
                "b_air":{
                    "refreshRate":100,
                    "conserveJumpConstant":false,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargeInAir":false,
                    "allowFastFall":false,
                    "attackVoice1_id":"Yoshi_Tongue",
                    "attackSound1_id":"Yoshi_nspecial_sfx",
                    "attackSound2_id":"Yoshi_swallow",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":-1,
                            "hitStun":3,
                            "selfHitStun":6,
                            "direction":45,
                            "power":50,
                            "kbConstant":10,
                            "egg":true,
                            "bypassNonGrabbed":true,
                            "effectSound":"Yoshi_layegg"
                        }}
                },
                "b_up":{
                    "refreshRate":4,
                    "conserveJumpConstant":false,
                    "isLongRangeMove":true,
                    "cancelWhenAirborne":false,
                    "reenableTimer":8,
                    "attackSound1_id":"Yoshi_egg_toss",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":4,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"sw_scratch"
                        }}
                },
                "b_up_air":{
                    "refreshRate":4,
                    "conserveJumpConstant":false,
                    "isLongRangeMove":true,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "isHorizontalRecoveryMove":true,
                    "isRecoveryMove":true,
                    "reenableTimer":11,
                    "attackSound1_id":"Yoshi_egg_toss",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":4,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "b_forward":{
                    "refreshRate":25,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "conserveJumpConstant":false,
                    "disableForCPU":true,
                    "linkFrames":true,
                    "attackSound1_id":"Yoshi_fspecial_start",
                    "attackSound2_id":"Yoshi_fspecial",
                    "attackSound3_id":"Yoshi_fspecial_stop",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":50,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_forward_air":{
                    "refreshRate":25,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecayAir":-1,
                    "conserveJumpConstant":false,
                    "disableForCPU":true,
                    "linkFrames":true,
                    "attackSound1_id":"Yoshi_fspecial_start",
                    "attackSound2_id":"Yoshi_fspecial",
                    "attackSound3_id":"Yoshi_fspecial_stop",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":50,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_down":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "conserveJumpConstant":false,
                    "canFallOff":false,
                    "attackVoice1_id":"Yoshi_YoshiBomb",
                    "attackSound1_id":"Yoshi_dspecial_start",
                    "attackSound2_id":"Yoshi_dspecial_land",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":4,
                            "priority":1,
                            "hitStun":5,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":70,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":70,
                            "effectSound":"ssb_hit1"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":1,
                            "hitStun":5,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":70,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":70,
                            "effectSound":"ssb_hit1"
                        }
                    }
                },
                "b_down_air":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "conserveJumpConstant":false,
                    "canFallOff":false,
                    "attackVoice1_id":"Yoshi_YoshiBomb",
                    "attackSound1_id":"Yoshi_dspecial_start",
                    "attackSound2_id":"Yoshi_dspecial_land",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":6,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":70,
                            "power":55,
                            "kbConstant":90,
                            "effectSound":"ssb_hit1"
                        },
                        "attackBox2":{
                            "damage":6,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":70,
                            "power":55,
                            "kbConstant":90,
                            "effectSound":"ssb_hit1"
                        }
                    }
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackVoice1_id":"Yoshi_Throw_Spit",
                    "attackSound1_id":"Yoshi_fspecial_start",
                    "cpuAttackQueue":"a_air; a_air_up; b_down",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":90,
                            "power":65,
                            "kbConstant":95,
                            "bypassNonGrabbed":true,
                            "effectSound":"launch_s"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"Yoshi_Throw_Spit",
                    "attackSound1_id":"Yoshi_fspecial_start",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":45,
                            "power":55,
                            "kbConstant":65,
                            "bypassNonGrabbed":true,
                            "effectSound":"launch_s"
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackVoice1_id":"Yoshi_Throw_Spit",
                    "attackSound1_id":"Yoshi_egg_toss",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":135,
                            "reversableAngle":false,
                            "power":55,
                            "kbConstant":70,
                            "bypassNonGrabbed":true,
                            "effectSound":"launch_s"
                        }}
                },
                "throw_down":{
                    "refreshRate":5,
                    "canFallOff":false,
                    "attackVoice1_id":"Yoshi_Throw_Spit",
                    "attackSound1_id":"Yoshi_fspecial_start",
                    "cpuAttackQueue":"a_down; crouch_attack; a_air_forward; a_air",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "camShake":10,
                            "direction":70,
                            "reversableAngle":false,
                            "power":55,
                            "kbConstant":130,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"yoshi_grunt1",
                    "attackVoice2_id":"yoshi_grunt2",
                    "attackVoice3_id":"yoshi_grunt3",
                    "attackVoice4_id":"yoshi_grunt4",
                    "attackSound1_id":"brawl_Yoshi_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":20,
                            "power":80,
                            "kbConstant":0,
                            "effectSound":"whack"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"yoshi_grunt1",
                    "attackVoice2_id":"yoshi_grunt2",
                    "attackVoice3_id":"yoshi_grunt3",
                    "attackVoice4_id":"yoshi_grunt4",
                    "attackSound1_id":"brawl_Yoshi_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_hit1",
                            "direction":30,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "attackVoice1_id":"yoshi_grunt1",
                    "attackVoice2_id":"yoshi_grunt2",
                    "attackVoice3_id":"yoshi_grunt3",
                    "attackVoice4_id":"yoshi_grunt4",
                    "attackSound1_id":"brawl_Yoshi_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":40,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":"whack"
                        }}
                },
                "kirby":{
                    "refreshRate":100,
                    "cancelWhenAirborne":false,
                    "conserveJumpConstant":false,
                    "allowControl":true,
                    "canFallOff":false,
                    "allowFastFall":false,
                    "attackVoice1_id":"Yoshi_Tongue",
                    "attackSound1_id":"Yoshi_nspecial_sfx",
                    "attackSound2_id":"Yoshi_swallow",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":6,
                            "direction":10,
                            "power":-1000,
                            "kbConstant":16,
                            "egg":true,
                            "effectSound":"Yoshi_layegg"
                        }}
                },
                "kirby_air":{
                    "refreshRate":100,
                    "conserveJumpConstant":false,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargeInAir":false,
                    "allowFastFall":false,
                    "attackVoice1_id":"Yoshi_Tongue",
                    "attackSound1_id":"Yoshi_nspecial_sfx",
                    "attackSound2_id":"Yoshi_swallow",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":6,
                            "direction":10,
                            "power":-1000,
                            "kbConstant":16,
                            "egg":true,
                            "effectSound":"Yoshi_layegg"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"yoshi_grunt3",
                    "attackSound1_id":"transformation",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":0,
                            "power":2,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object = {
                "yoshi_fireball":{
                    "linkage_id":"yoshi_fireball",
                    "height":80,
                    "xspeed":16,
                    "rideGround":false,
                    "xoffset":-30,
                    "yoffset":-65,
                    "limit":100,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":17,
                                "priority":7,
                                "hitStun":3,
                                "selfHitStun":0,
                                "camShake":5,
                                "effect_id":"fireball_hiteffect",
                                "direction":65,
                                "power":50,
                                "kbConstant":87,
                                "burn":true,
                                "effectSound":"yoshi_fireballHit"
                            }}}
                },
                "eggBomb":{
                    "linkage_id":"eggBomb",
                    "inheritPalette":true,
                    "time_max":999,
                    "xspeed":4,
                    "yspeed":-10,
                    "gravity":0.99,
                    "maxgravity":11.5,
                    "canBeAbsorbed":false,
                    "limit":3,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":8,
                                "priority":3,
                                "hitStun":3,
                                "selfHitStun":2,
                                "direction":70,
                                "power":40,
                                "kbConstant":40,
                                "effectSound":null
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getChar2(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"yoshi_special",
                "displayName":"Yoshi",
                "linkage_id":"yoshi_special",
                "linkage_id2":null,
                "linkage_id_special":"yoshi",
                "thumbnail":"yoshi_head",
                "seriesIcon":"Yoshi_Symbol",
                "width":70,
                "height":50,
                "jumpSpeed":5,
                "jumpSpeedMidair":5,
                "shortHopSpeed":5,
                "max_jumpSpeed":8,
                "midAirTurn":true,
                "dodgeSpeed":10,
                "gravity":0.4,
                "weight1":111,
                "power":"Yoshi",
                "norm_xSpeed":5,
                "max_xSpeed":9,
                "max_ySpeed":4,
                "fastFallSpeed":10,
                "accel_start":1,
                "accel_start_dash":-1,
                "accel_rate":1,
                "accel_rate_air":0.9,
                "decel_rate":0.65,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":999999,
                "max_projectile":99999,
                "tetherGrab":false,
                "roll_speed":16,
                "roll_delay":13,
                "getup_roll_delay":0,
                "itemScaleRatio":1,
                "special_type":0,
                "normalStats_id":"yoshi",
                "specialStats_id":"yoshi_special",
                "sounds":{
                    "jump":null,
                    "jump_midair":null,
                    "hurt":null,
                    "hurt2":null,
                    "hurtBad":null,
                    "hurtBad2":null,
                    "dead":"Yoshi_Die",
                    "dead2":null,
                    "pummel":null,
                    "screenko":null,
                    "starko":null,
                    "ledge_grab":null,
                    "winTheme":"YoshiVictory"
                },
                "hurtFrames":4,
                "canDodge":false,
                "canShield":false,
                "canUseItems":false,
                "canTaunt":false,
                "heavyArmor":9999,
                "fs_time_limit":600
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "a_up":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "a_up_tilt":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "a_forward":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "a_forward_tilt":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "a_forwardsmash":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "a_down":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "a_air":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "a_air_up":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "a_air_forward":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "a_air_backward":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "a_air_down":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "b":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "b_up_air":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "b_forward":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "b_forward_air":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "b_down":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "b_down_air":{
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "attackDelay":8,
                    "invincible":true,
                    "attackSound1_id":"yoshi_fireballShot",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":10,
                            "hitLag":4,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":80,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":null
                        }}
                },
                "throw_up":{
                    "attackVoice1_id":"ichigo_attack3",
                    "attackVoice2_id":"ichigo_attack6",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh2",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":90,
                            "power":1500,
                            "kbConstant":16,
                            "effectSound":"sw_scratch"
                        }}
                },
                "throw_forward":{
                    "attackVoice1_id":"ichigo_attack3",
                    "attackVoice2_id":"ichigo_attack6",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":1500,
                            "kbConstant":16,
                            "effectSound":"sw_scratch"
                        }}
                },
                "throw_back":{
                    "attackVoice1_id":"ichigo_attack3",
                    "attackVoice2_id":"ichigo_attack6",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":1500,
                            "kbConstant":16,
                            "effectSound":"sw_scratch"
                        }}
                },
                "throw_down":{
                    "refreshRate":5,
                    "attackVoice1_id":"ichigo_attack3",
                    "attackVoice2_id":"ichigo_attack7",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh2",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":-3,
                            "power":-400,
                            "kbConstant":25,
                            "effectSound":"smallblast"
                        }}
                },
                "crouch_attack":{
                    "cancelWhenAirborne":false,
                    "isLongRangeMove":true,
                    "attackVoice1_id":"ichigo_attack4",
                    "attackSound1_id":"whoosh3",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":2,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":900,
                            "kbConstant":11,
                            "effectSound":"sw_slash"
                        }}
                },
                "ledge_attack":{
                    "attackDelay":5,
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackSound1_id":"whoosh3",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":0,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "effect_id":"effect_swordSlash",
                            "direction":30,
                            "power":800,
                            "kbConstant":13,
                            "effectSound":"sw_slash"
                        }}
                },
                "getup_attack":{},
                "kirby":{
                    "attackDelay":15,
                    "isLongRangeMove":true,
                    "cancelWhenAirborne":false,
                    "chargetime_max":90,
                    "charge_retain":true,
                    "attackVoice1_id":"kirby_hammer3",
                    "attackVoice2_id":"kirby_yah",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":30,
                            "power":1300,
                            "kbConstant":16,
                            "effectSound":"sw_scratch"
                        }}
                },
                "kirby_air":{
                    "attackDelay":15,
                    "isLongRangeMove":true,
                    "allowControl":true,
                    "chargetime_max":90,
                    "charge_retain":true,
                    "chargeInAir":false,
                    "attackVoice1_id":"kirby_hammer3",
                    "attackVoice2_id":"kirby_yah",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":30,
                            "power":1300,
                            "kbConstant":16,
                            "effectSound":"sw_scratch"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "invincible":true,
                    "canUseInAir":true,
                    "attackVoice1_id":"ichigo_bankai",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":0,
                            "power":2,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object = {
                "yoshi_fireball":{
                    "linkage_id":"Yoshi_fireball",
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "height":80,
                    "stale":false,
                    "rotate":true,
                    "xspeed":16,
                    "xoffset":35,
                    "yoffset":-17,
                    "limit":100,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":17,
                                "priority":7,
                                "hitStun":3,
                                "selfHitStun":0,
                                "camShake":5,
                                "direction":40,
                                "reversableAngle":false,
                                "power":50,
                                "kbConstant":87,
                                "burn":true,
                                "effectSound":"yoshi_fireballHit"
                            }}}
                },
                "yoshi_fireball2":{
                    "linkage_id":"Yoshi_fireball",
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "height":80,
                    "stale":false,
                    "rotate":true,
                    "xspeed":12.5,
                    "yspeed":-2,
                    "xoffset":35,
                    "yoffset":-17,
                    "limit":100,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":17,
                                "priority":7,
                                "hitStun":3,
                                "selfHitStun":0,
                                "camShake":5,
                                "direction":40,
                                "reversableAngle":false,
                                "power":50,
                                "kbConstant":87,
                                "burn":true,
                                "effectSound":"yoshi_fireballHit"
                            }}}
                },
                "yoshi_fireball3":{
                    "linkage_id":"Yoshi_fireball",
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "height":80,
                    "stale":false,
                    "rotate":true,
                    "xspeed":12.5,
                    "yspeed":2,
                    "xoffset":35,
                    "yoffset":-17,
                    "limit":100,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":17,
                                "priority":7,
                                "hitStun":3,
                                "selfHitStun":0,
                                "camShake":5,
                                "direction":40,
                                "reversableAngle":false,
                                "power":50,
                                "kbConstant":87,
                                "burn":true,
                                "effectSound":"yoshi_fireballHit"
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("yoshi");
        }

        public function getGUID():String
        {
            return ("cc7f6275-769a-403a-aadf-725696cfbc79");
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package yoshi_fla

