// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//jigglypuff_fla.MainTimeline

package jigglypuff_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        public function getAudio():Array
        {
            return (new Array(jiggs_footstep1, jiggs_footstep2, jiggs_fs_shout2_vfx, jiggs_rest1_vfx, jiggs_rest2_vfx, jiggs_rollout_vfx, jiggs_dizzy, jiggs_sing1_vfx, jiggs_sing2_vfx, jiggs_starko, jiggs_taunt1, jiggs_jump_sfx, jiggs_grunt1, jiggs_grunt2, jiggs_grunt3, jiggs_bubbles, jiggs_skid, jiggs_run1, jiggs_run2, jiggs_dash, jiggs_attack_l, jiggs_attack_m, jiggs_attack_s, jiggs_rollout1, jiggs_rollout2, jiggs_rollout3, jiggs_wakeup, jiggs_pound_sfx, jiggs_fsmash_vfx, jiggs_usmash_vfx, jiggs_death, jiggs_hurt, jiggs_hurtBad, jiggs_hurtBad2, jiggs_fs_grow, jiggs_fs_shrink));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"jigglypuff",
                "displayName":"Jigglypuff",
                "linkage_id":"jigglypuff",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"jiggly_head",
                "seriesIcon":"PokemonSymbol",
                "width":30,
                "height":30,
                "jumpSpeed":10,
                "jumpSpeedMidair":12,
                "jumpSpeedList":"12,11.5,11,10.5,10",
                "jumpStartup":2,
                "shortHopSpeed":8,
                "max_jumpSpeed":7.8,
                "midAirTurn":true,
                "dodgeSpeed":8,
                "gravity":0.77,
                "weight1":73,
                "power":"jigglypuff",
                "norm_xSpeed":3.5,
                "max_xSpeed":7.9,
                "max_ySpeed":7.5,
                "fastFallSpeed":9.5,
                "accel_start":1,
                "accel_start_dash":1.46,
                "accel_rate":0.9,
                "accel_rate_air":1.35,
                "decel_rate":-0.9,
                "decel_rate_air":-0.095,
                "holdJump":false,
                "max_jump":5,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":24,
                "roll_delay":4,
                "getup_roll_delay":0,
                "itemScaleRatio":0.869565217391304,
                "special_type":1,
                "normalStats_id":"jigglypuff",
                "specialStats_id":null,
                "sounds":{
                    "jump":"jiggs_jump_sfx",
                    "jump_midair":"jiggs_jump_sfx",
                    "hurt":"jiggs_hurt",
                    "hurt2":null,
                    "hurtBad":"jiggs_hurtBad",
                    "hurtBad2":"jiggs_hurtBad2",
                    "dead":"jiggs_death",
                    "dead2":"jiggs_death",
                    "pummel":"brawl_punch_m",
                    "screenko":"jiggs_hurt",
                    "starko":"jiggs_starko",
                    "ledge_grab":null,
                    "winTheme":"PokeVictory"
                },
                "hurtFrames":2,
                "shieldBreakPower":155,
                "grabDamage":2
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "combo_max":1,
                    "canFallOff":false,
                    "cpuAttackQueue":"throw_up;throw_forward;a_air;a_forwardsmash;a_down",
                    "reenableTimer":6,
                    "attackSound1_id":"brawl_swing_m",
                    "attackSound2_id":"brawl_swing_s",
                    "attackSound3_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":30,
                            "power":8,
                            "kbConstant":50,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"jiggs_usmash_vfx",
                    "attackSound1_id":"jiggs_attack_l",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":4,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":90,
                            "power":20,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "cpuAttackQueue":"a_up_tilt;a_up;b_down;b_down_air;a_forward_tilt",
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackVoice3_id":"jiggs_grunt3",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":65,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forward":{
                    "refreshRate":999999,
                    "canFallOff":false,
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackVoice3_id":"jiggs_grunt3",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":55,
                            "reversableAngle":false,
                            "power":16,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackVoice3_id":"jiggs_grunt3",
                    "attackSound1_id":"jiggs_attack_s",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":8,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forwardsmash":{
                    "xSpeedDecay":-1,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"jiggs_fsmash_vfx",
                    "attackSound1_id":"jiggs_attack_l",
                    "attackBoxes":{"attackBox":{
                            "damage":16,
                            "priority":6,
                            "hitStun":4,
                            "selfHitStun":4,
                            "effect_id":"effect_heavyHit",
                            "direction":50,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"jiggs_grunt2",
                    "attackSound1_id":"jiggs_attack_l",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":5,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":20,
                            "power":44,
                            "kbConstant":55,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "cpuAttackQueue":"a_air;a_air_forward",
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackVoice3_id":"jiggs_grunt3",
                    "attackSound1_id":"jiggs_attack_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1.05,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":30,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":11,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1.05,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":30,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_up":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "maintainSpeed":true,
                    "cpuAttackQueue":"a_air;a_air_up;a_air;a_air_up;b_down_air",
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackVoice3_id":"jiggs_grunt3",
                    "attackSound1_id":"jiggs_attack_m",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "power":30,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air_forward":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "cpuAttackQueue":"a_air_forward",
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackVoice3_id":"jiggs_grunt3",
                    "attackSound1_id":"jiggs_attack_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":40,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":40,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air_backward":{
                    "allowControl":true,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "cpuAttackQueue":"a_air_backward",
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackVoice3_id":"jiggs_grunt3",
                    "attackSound1_id":"jiggs_attack_m",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":5,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":35,
                            "power":35,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air_down":{
                    "refreshRate":1,
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "reenableTimer":20,
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackVoice3_id":"jiggs_grunt3",
                    "attackSound1_id":"jiggs_attack_s",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.07,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":90,
                            "power":20,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b":{
                    "refreshRate":5,
                    "cancelWhenAirborne":false,
                    "xSpeedDecayAir":1,
                    "chargetime_max":99999999,
                    "combo_max":999,
                    "holdRepeat":true,
                    "disableForCPU":true,
                    "canUseInAir":true,
                    "attackVoice1_id":"jiggs_rollout_vfx",
                    "attackSound1_id":"jiggs_rollout1",
                    "attackSound2_id":"jiggs_rollout2",
                    "attackSound3_id":"jiggs_rollout3",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":-1,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":102,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_air":{
                    "refreshRate":5,
                    "cancelWhenAirborne":false,
                    "xSpeedDecayAir":1,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargetime_max":99999999,
                    "combo_max":999,
                    "holdRepeat":true,
                    "disableForCPU":true,
                    "canUseInAir":true,
                    "attackVoice1_id":"jiggs_rollout_vfx",
                    "attackSound1_id":"jiggs_rollout1",
                    "attackSound2_id":"jiggs_rollout2",
                    "attackSound3_id":"jiggs_rollout3",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":-1,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":102,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_up":{
                    "refreshRate":10000,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecayAir":0.8,
                    "canFallOff":false,
                    "attackVoice1_id":"jiggs_sing1_vfx",
                    "attackVoice2_id":"jiggs_sing2_vfx",
                    "attackSound1_id":"sw_strongslash",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":-1,
                            "hitStun":0,
                            "selfHitStun":1,
                            "effect_id":null,
                            "direction":85,
                            "power":0,
                            "kbConstant":0,
                            "onlyAffectsGround":true,
                            "dizzy":160,
                            "effectSound":"jiggs_bubbles"
                        }}
                },
                "b_up_air":{
                    "refreshRate":10000,
                    "cancelWhenAirborne":false,
                    "xSpeedDecayAir":0.8,
                    "canFallOff":false,
                    "disableForCPU":true,
                    "attackVoice1_id":"jiggs_sing1_vfx",
                    "attackVoice2_id":"jiggs_sing2_vfx",
                    "attackSound1_id":"sw_strongslash",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":-1,
                            "hitStun":0,
                            "selfHitStun":1,
                            "effect_id":null,
                            "direction":85,
                            "power":0,
                            "kbConstant":0,
                            "onlyAffectsGround":true,
                            "dizzy":160,
                            "effectSound":"jiggs_bubbles"
                        }}
                },
                "b_forward":{
                    "resetMovement":true,
                    "xSpeedDecay":-0.2,
                    "canFallOff":false,
                    "attackVoice1_id":"jiggs_grunt2",
                    "attackSound1_id":"jiggs_pound_sfx",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":5,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":115,
                            "power":52,
                            "kbConstant":75,
                            "effectSound":"brawl_fan"
                        }}
                },
                "b_forward_air":{
                    "resetMovement":true,
                    "cpuAttackQueue":"b_down_air",
                    "xSpeedDecayAir":-0.25,
                    "allowControl":true,
                    "canFallOff":false,
                    "isHorizontalRecoveryMove":true,
                    "attackVoice1_id":"jiggs_grunt2",
                    "attackSound1_id":"jiggs_pound_sfx",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":5,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":115,
                            "power":52,
                            "kbConstant":75,
                            "effectSound":"brawl_fan"
                        }}
                },
                "b_down":{
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "disableForCPU":true,
                    "attackVoice1_id":"jiggs_rest1_vfx",
                    "attackVoice2_id":"jiggs_rest2_vfx",
                    "attackSound1_id":"jiggs_bubbles",
                    "attackSound2_id":"jiggs_wakeup",
                    "attackBoxes":{"attackBox":{
                            "damage":18,
                            "priority":7,
                            "hitStun":15,
                            "selfHitStun":15,
                            "camShake":25,
                            "effect_id":"jiggly_restEffect",
                            "direction":45,
                            "power":75,
                            "kbConstant":110,
                            "effectSound":"bat"
                        }}
                },
                "b_down_air":{
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "disableForCPU":true,
                    "attackVoice1_id":"jiggs_rest1_vfx",
                    "attackVoice2_id":"jiggs_rest2_vfx",
                    "attackSound1_id":"jiggs_bubbles",
                    "attackSound2_id":"jiggs_wakeup",
                    "attackBoxes":{"attackBox":{
                            "damage":18,
                            "priority":7,
                            "hitStun":15,
                            "selfHitStun":15,
                            "camShake":25,
                            "effect_id":"jiggly_restEffect",
                            "direction":45,
                            "power":75,
                            "kbConstant":110,
                            "effectSound":"bat"
                        }}
                },
                "throw_up":{
                    "cpuAttackQueue":"throw_up;a_air_up;a_air;a_air_backward;a_air_forward;b_down_air",
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackVoice3_id":"jiggs_grunt3",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":-1,
                            "hitLag":-1.1,
                            "selfHitStun":0,
                            "direction":90,
                            "power":80,
                            "kbConstant":60,
                            "bypassNonGrabbed":true
                        }}
                },
                "throw_forward":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackVoice3_id":"jiggs_grunt3",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":-1,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":55,
                            "reversableAngle":false,
                            "power":40,
                            "kbConstant":110,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_back":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh2",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":-1,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":135,
                            "reversableAngle":false,
                            "power":90,
                            "kbConstant":25,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_down":{
                    "refreshRate":99999,
                    "cpuAttackQueue":"b_down;b_down_air;a_air;a_air_forward;a_up_tilt",
                    "canFallOff":false,
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackVoice3_id":"jiggs_grunt3",
                    "attackSound1_id":"brawl_swing_m",
                    "attackSound2_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "hasEffect":false,
                            "priority":-1,
                            "hitStun":1,
                            "hitLag":-1.07,
                            "selfHitStun":0,
                            "effect_id":"effect_hit1",
                            "direction":75,
                            "power":60,
                            "kbConstant":100,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "crouch_attack":{
                    "xSpeedDecay":-1,
                    "canFallOff":false,
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackVoice3_id":"jiggs_grunt3",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":22,
                            "power":40,
                            "kbConstant":30,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackVoice3_id":"jiggs_grunt3",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":2,
                            "hitStun":2,
                            "weightKB":100,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":20,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "attackVoice1_id":"jiggs_grunt1",
                    "attackVoice2_id":"jiggs_grunt2",
                    "attackVoice3_id":"jiggs_grunt3",
                    "attackSound1_id":"jiggs_attack_l",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":4,
                            "hitStun":2,
                            "weightKB":100,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "kirby":{
                    "refreshRate":5,
                    "cancelWhenAirborne":false,
                    "xSpeedDecayAir":1,
                    "chargetime_max":99999999,
                    "combo_max":999,
                    "holdRepeat":true,
                    "canUseInAir":true,
                    "attackVoice1_id":"kirby_usmash",
                    "attackSound1_id":"jiggs_rollout1",
                    "attackSound2_id":"jiggs_rollout2",
                    "attackSound3_id":"jiggs_rollout3",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":-1,
                            "hitStun":2,
                            "selfHitStun":2,
                            "direction":75,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":102,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "refreshRate":5,
                    "cancelWhenAirborne":false,
                    "xSpeedDecayAir":1,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargetime_max":99999999,
                    "combo_max":999,
                    "holdRepeat":true,
                    "canUseInAir":true,
                    "attackVoice1_id":"kirby_usmash",
                    "attackSound1_id":"jiggs_rollout1",
                    "attackSound2_id":"jiggs_rollout2",
                    "attackSound3_id":"jiggs_rollout3",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":-1,
                            "hitStun":2,
                            "selfHitStun":2,
                            "direction":75,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":102,
                            "effectSound":null
                        }}
                },
                "special":{
                    "refreshRate":1,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "air_ease":0.5,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackVoice1_id":"jiggs_fs_shout2_vfx",
                    "attackSound1_id":"jiggs_fs_grow",
                    "attackSound2_id":"jiggs_fs_shrink",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":7,
                            "sdiDistance":0,
                            "hitStun":0,
                            "weightKB":210,
                            "selfHitStun":0,
                            "direction":25,
                            "power":10,
                            "kbConstant":10,
                            "bypassShield":true,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object;
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("jigglypuff");
        }

        public function getGUID():String
        {
            return ("8fb252a6-b3fe-4572-8424-cc5f0f89f54e");
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package jigglypuff_fla

