// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//wario_fla.MainTimeline

package wario_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function getAudio():Array
        {
            return (new Array(wario1, wario2, wario3, wario4, wario5, wario6, wario7, bellybuldge, wario_die, wario_die2, wario_bikeJump, wario_entrancesfx, brawl_wario_swing_H, brawl_wario_swing_ll, brawl_wario_swing_M, brawl_wario_swing_S, wario_clap, wario_corkscrewsfx, wario_entrance, wario_win, wario_bite, wario_chomp, hurryup, wariobikego, wariobikerev, wariocorkscrew, wario_starko, warioeat, wariogo, wariohurt, wariohurtbad, wariojump, wariojumptwice, wariomanend, wariosleep, wariostun, wariotaunt, wariotransform, WarioVictory, wariowaft1, wariowaft2, wariowaft3, wariowaft4, wario_taunt2, wario_taunt3, wario_miniLaugh, wario_victory));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"wario",
                "displayName":"Wario",
                "linkage_id":"wariobase",
                "linkage_id2":null,
                "linkage_id_special":"warioman",
                "thumbnail":"wario_icon",
                "seriesIcon":"warioseries",
                "width":31,
                "height":45,
                "jumpSpeed":15.5,
                "jumpSpeedMidair":15.5,
                "jumpStartup":3,
                "shortHopSpeed":9.2,
                "max_jumpSpeed":6,
                "dodgeSpeed":10,
                "gravity":1.25,
                "weight1":107,
                "power":"wario",
                "norm_xSpeed":4.2,
                "max_xSpeed":8.1,
                "max_ySpeed":13.5,
                "fastFallSpeed":17,
                "accel_start":1.1,
                "accel_start_dash":1.038,
                "accel_rate":1.3,
                "accel_rate_air":4,
                "decel_rate":-1.52,
                "decel_rate_air":-0.1,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":2,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_delay":10,
                "getup_roll_delay":0,
                "itemScaleRatio":0.72,
                "special_type":0,
                "normalStats_id":"wario",
                "specialStats_id":"warioman",
                "sounds":{
                    "jump":"wariojump",
                    "jump_midair":"wariojumptwice",
                    "hurt":"wariohurt",
                    "hurt2":null,
                    "hurtBad":"wariohurtbad",
                    "hurtBad2":null,
                    "dead":"wario_die",
                    "dead2":"wario_die2",
                    "pummel":"brawl_wario_swing_S",
                    "screenko":null,
                    "starko":"wario_starko",
                    "ledge_grab":null,
                    "winTheme":"WarioVictory"
                },
                "hurtFrames":4,
                "grabDamage":1,
                "fs_time_limit":600
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":100,
                    "combo_max":2,
                    "canFallOff":false,
                    "reenableTimer":10,
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackSound1_id":"brawl_wario_swing_M",
                    "attackSound2_id":"brawl_wario_swing_S",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":70,
                            "power":50,
                            "kbConstant":0,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_up":{
                    "refreshRate":5,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"wario6",
                    "attackSound1_id":"brawl_wario_swing_M",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":5,
                            "chargedPriority":6,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":135,
                            "power":15,
                            "kbConstant":49,
                            "effectSound":"punch2"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air_up;a_air;a_air_forward;a_up_tilt",
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackSound1_id":"brawl_wario_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "power":70,
                            "kbConstant":44,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_forward":{
                    "xSpeedDecay":-0.9,
                    "canFallOff":false,
                    "attackVoice1_id":"hurryup",
                    "attackSound1_id":"brawl_wario_swing_M",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":35,
                            "power":60,
                            "kbConstant":75,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_forward_tilt":{
                    "xSpeedCap":0,
                    "canFallOff":false,
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackSound1_id":"brawl_wario_swing_S",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":36,
                            "power":28,
                            "kbConstant":88,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackSound1_id":"bellybuldge",
                    "attackBoxes":{"attackBox":{
                            "damage":16,
                            "priority":6,
                            "chargedPriority":6,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"warioeffect",
                            "direction":30,
                            "power":30,
                            "kbConstant":75,
                            "effectSound":"sw_minihit"
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "cpuAttackQueue":"a_air;a_forwardsmash;a_air_forward;b_forward",
                    "attackVoice1_id":"wario7",
                    "attackSound1_id":"brawl_wario_swing_ll",
                    "attackSound2_id":"kirby_rockpound",
                    "attackSound3_id":"kirby_rockhitground",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "forceTumbleFall":true,
                            "priority":5,
                            "chargedPriority":6,
                            "sdiDistance":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":270,
                            "power":30,
                            "kbConstant":80,
                            "onlyAffectsGround":true,
                            "meteorBounce":false,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":9,
                    "allowControl":true,
                    "cpuAttackQueue":"a_air_forward;a_air",
                    "attackVoice1_id":"wario5",
                    "attackSound1_id":"brawl_wario_swing_M",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9,
                            "priority":4,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":30,
                            "power":30,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":4,
                            "hitStun":4,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":30,
                            "power":30,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_m"
                        }
                    }
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "cpuAttackQueue":"a_air;a_air_forward",
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackSound1_id":"brawl_wario_swing_H",
                    "attackSound2_id":"wario_clap",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":4,
                            "hitStun":6,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":83,
                            "power":65,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "cpuAttackQueue":"a_air_forward",
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackSound1_id":"brawl_wario_swing_ll",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":55,
                            "power":45,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air_backward":{
                    "refreshRate":2,
                    "allowControl":true,
                    "cpuAttackQueue":"a_air_backward",
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackSound1_id":"brawl_wario_swing_S",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "power":38,
                            "kbConstant":0,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":10,
                    "air_ease":0,
                    "canFallOff":false,
                    "allowFastFall":false,
                    "disableForCPU":true,
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackSound1_id":"brawl_wario_swing_M",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":6,
                            "hitStun":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":270,
                            "power":55,
                            "kbConstant":55,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "b":{
                    "refreshRate":999,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargeInAir":false,
                    "xSpeedDecay":0.01,
                    "attackSound1_id":"wario_chomp",
                    "attackSound2_id":"wario_bite",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "hasEffect":false,
                            "priority":7,
                            "hitStun":1,
                            "hitLag":-2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":10,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":70,
                            "bypassShield":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "b_air":{
                    "refreshRate":999,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargeInAir":false,
                    "attackSound1_id":"wario_chomp",
                    "attackSound2_id":"wario_bite",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "hasEffect":false,
                            "priority":7,
                            "hitStun":1,
                            "hitLag":-2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":10,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":70,
                            "bypassShield":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "b_up":{
                    "refreshRate":3,
                    "disableForCPU":true,
                    "cancelWhenAirborne":false,
                    "air_ease":2,
                    "xSpeedCap":6,
                    "allowControl":false,
                    "attackVoice1_id":"wariocorkscrew",
                    "attackSound1_id":"wario_corkscrewsfx",
                    "xSpeedDecay":1,
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":2,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_hit1",
                            "direction":90,
                            "power":50,
                            "kbConstant":1,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "b_up_air":{
                    "refreshRate":3,
                    "disableForCPU":true,
                    "cancelWhenAirborne":false,
                    "resetMovement":true,
                    "air_ease":2,
                    "xSpeedCap":6,
                    "allowControl":true,
                    "isRecoveryMove":true,
                    "attackVoice1_id":"wariocorkscrew",
                    "attackSound1_id":"wario_corkscrewsfx",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":2,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_hit1",
                            "direction":90,
                            "power":50,
                            "kbConstant":1,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "b_forward":{
                    "cancelWhenAirborne":false,
                    "isLongRangeMove":true,
                    "xSpeedDecay":-0.5,
                    "xSpeedDecayAir":-0.045,
                    "maintainSpeed":true,
                    "jumpFrame":"b_forward_air",
                    "allowFastFall":false,
                    "reenableTimer":15,
                    "attackVoice1_id":"wariogo",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "reversableAngle":false,
                            "power":40,
                            "kbConstant":110,
                            "effectSound":"ssb_hit1"
                        }}
                },
                "b_forward_air":{
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-0.5,
                    "xSpeedDecayAir":-0.045,
                    "isLongRangeMove":true,
                    "maintainSpeed":true,
                    "jumpFrame":"b_forward",
                    "chargeInAir":false,
                    "allowJump":true,
                    "allowFastFall":false,
                    "reenableTimer":17,
                    "attackVoice1_id":"wariogo",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "reversableAngle":false,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"ssb_hit1"
                        }}
                },
                "b_down":{
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"wario_miniLaugh",
                    "attackSound1_id":"wariowaft1",
                    "attackSound2_id":"wariowaft3",
                    "attackSound3_id":"wariowaft2",
                    "attackSound4_id":"wariowaft4",
                    "attackBoxes":{"attackBox":{
                            "damage":17,
                            "priority":-1,
                            "hitStun":2,
                            "hitLag":25,
                            "selfHitStun":0,
                            "direction":-4,
                            "power":75,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "b_down_air":{
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"wario_miniLaugh",
                    "attackSound1_id":"wariowaft1",
                    "attackSound2_id":"wariowaft3",
                    "attackSound3_id":"wariowaft2",
                    "attackSound4_id":"wariowaft4",
                    "attackBoxes":{"attackBox":{
                            "damage":17,
                            "priority":-1,
                            "hitStun":2,
                            "hitLag":25,
                            "selfHitStun":0,
                            "direction":-4,
                            "power":75,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "throw_up":{
                    "cpuAttackQueue":"a_air;a_air_forward;a_air_up;throw_up",
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":0,
                            "hitStun":2,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":72,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "throw_forward":{
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":-1.1,
                            "selfHitStun":0,
                            "direction":75,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":72,
                            "bypassNonGrabbed":true,
                            "effectSound":"launch_s"
                        }}
                },
                "throw_back":{
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackSound1_id":"brawl_wario_swing_M",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":155,
                            "reversableAngle":false,
                            "power":70,
                            "kbConstant":60,
                            "bypassNonGrabbed":true,
                            "effectSound":"ssb_hit5"
                        }}
                },
                "throw_down":{
                    "chargeInAir":false,
                    "allowFastFall":false,
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackSound1_id":"brawl_wario_swing_M",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":15,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":60,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackSound1_id":"brawl_wario_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.07,
                            "selfHitStun":-1,
                            "effect_id":"effect_hit1",
                            "direction":75,
                            "reversableAngle":false,
                            "power":70,
                            "kbConstant":60,
                            "effectSound":"punch2"
                        }}
                },
                "ledge_attack":{
                    "attackDelay":5,
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":5,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "effect_id":"effect_hit1",
                            "direction":30,
                            "power":50,
                            "kbConstant":40,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "getup_attack":{
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":3,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "direction":40,
                            "power":55,
                            "kbConstant":50,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "kirby":{
                    "refreshRate":999,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargeInAir":false,
                    "attackVoice1_id":"wario_bikeJump",
                    "attackSound1_id":"wario_chomp",
                    "attackSound2_id":"wario_bite",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "hasEffect":false,
                            "priority":7,
                            "hitStun":1,
                            "hitLag":-2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":10,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":70,
                            "bypassShield":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "kirby_air":{
                    "refreshRate":999,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargeInAir":false,
                    "attackVoice1_id":"wario_bikeJump",
                    "attackSound1_id":"wario_chomp",
                    "attackSound2_id":"wario_bite",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "hasEffect":false,
                            "priority":7,
                            "hitStun":1,
                            "hitLag":-2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":10,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":70,
                            "bypassShield":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":"ichigo_bankai",
                    "attackSound1_id":"warioeat",
                    "attackSound2_id":"wariotransform",
                    "attackSound3_id":"wariomanend",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":0,
                            "power":2,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "crouch":{
                    "xSpeedDecay":-0.5,
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":-1,
                            "hitStun":1,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "direction":150,
                            "power":1200,
                            "kbConstant":7,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object = {"projectile0":{
                    "linkage_id":"usmashwindbox",
                    "width":125,
                    "height":25,
                    "time_max":14,
                    "ghost":true,
                    "followUser":true,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "limit":2,
                    "lockTrajectory":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "hasEffect":false,
                                "priority":7,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "direction":-5,
                                "power":1500,
                                "kbConstant":4,
                                "bypassShield":true,
                                "effectSound":null
                            }}}
                }};
            var _local_5:Object = {"wario_bike":{
                    "class_id":null,
                    "linkage_id":"wario_bike",
                    "displayName":"Wario%20Bike",
                    "width":60,
                    "height":30,
                    "ricochet":true,
                    "canPickup":true,
                    "midairPickup":false,
                    "dropInMidair":true,
                    "canJumpWith":false,
                    "canAttackWith":false,
                    "canHangWith":false,
                    "canShieldWith":false,
                    "ability":"toss",
                    "gravity":1,
                    "throwSpeed":5,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":0.95,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_toss":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":0.95,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_throw":{"attackBoxes":{"attackBox":{
                                "damage":4,
                                "priority":3,
                                "hitStun":2,
                                "hitLag":0.95,
                                "selfHitStun":0,
                                "direction":20,
                                "power":1200,
                                "kbConstant":16,
                                "effectSound":null
                            }}},
                    "attack_neutral":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":0.95,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}},
                    "attack_smash":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "priority":0,
                                "hitStun":0,
                                "hitLag":0.95,
                                "selfHitStun":0,
                                "direction":0,
                                "power":0,
                                "kbConstant":1,
                                "effectSound":null
                            }}}
                }};
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getChar2(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"warioman",
                "displayName":"Wario-Man",
                "linkage_id":"warioman",
                "linkage_id2":null,
                "linkage_id_special":"wariobase",
                "thumbnail":"warioman_icon",
                "seriesIcon":"warioseries",
                "width":31,
                "height":45,
                "jumpSpeed":10,
                "jumpSpeedMidair":11,
                "jumpStartup":2,
                "shortHopSpeed":5,
                "max_jumpSpeed":7.8,
                "midAirTurn":true,
                "dodgeSpeed":10,
                "gravity":0.7,
                "weight1":1.045,
                "power":"wario",
                "norm_xSpeed":6,
                "max_xSpeed":8,
                "max_ySpeed":7.5,
                "fastFallSpeed":20,
                "accel_start":0.8,
                "accel_start_dash":-1,
                "accel_rate":1,
                "accel_rate_air":5,
                "decel_rate":-2.17,
                "decel_rate_air":-0.01,
                "holdJump":false,
                "max_jump":12345678,
                "max_projectile":3,
                "tetherGrab":true,
                "roll_speed":20,
                "roll_delay":12,
                "getup_roll_delay":0,
                "itemScaleRatio":0.72,
                "special_type":0,
                "normalStats_id":"wario",
                "specialStats_id":"warioman",
                "sounds":{
                    "jump":"wariojump",
                    "jump_midair":"wariojumptwice",
                    "hurt":"wariohurt",
                    "hurt2":null,
                    "hurtBad":"wariohurtbad",
                    "hurtBad2":null,
                    "dead":"wario_die",
                    "dead2":null,
                    "pummel":"bellybuldge",
                    "screenko":null,
                    "starko":"wario_starko",
                    "ledge_grab":null,
                    "winTheme":"WarioVictory"
                },
                "hurtFrames":1,
                "grabDamage":1
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":100,
                    "combo_max":2,
                    "holdRepeat":true,
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario3",
                    "attackSound1_id":"brawl_wario_swing_S",
                    "attackSound2_id":"brawl_wario_swing_S",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":3,
                            "hitStun":4,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":55,
                            "power":20,
                            "kbConstant":0,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_up":{
                    "refreshRate":200,
                    "chargetime_max":40,
                    "chargeClick":true,
                    "attackSound1_id":"wariojumptwice",
                    "attackSound2_id":"bellybuldge",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":6,
                            "chargedPriority":6,
                            "hitStun":2,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "effect_id":"coineffect",
                            "direction":90,
                            "power":39,
                            "kbConstant":75,
                            "effectSound":"punch2"
                        }}
                },
                "a_up_tilt":{
                    "attackVoice1_id":"wario4",
                    "attackSound1_id":"brawl_wario_swing_S",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":-1.3,
                            "selfHitStun":4,
                            "effect_id":"effect_hit2",
                            "direction":90,
                            "power":22,
                            "kbConstant":88,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_forward":{
                    "xSpeedDecay":-1,
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"wariogo",
                    "attackSound1_id":"brawl_wario_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":4,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":20,
                            "power":70,
                            "kbConstant":27,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_forward_tilt":{
                    "resetMovement":true,
                    "attackVoice1_id":"wario2",
                    "attackSound1_id":"brawl_wario_swing_S",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":1,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":25,
                            "power":62,
                            "kbConstant":29,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "chargeClick":true,
                    "attackVoice1_id":"wario6",
                    "attackSound1_id":"sw_brawl_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":20,
                            "priority":6,
                            "chargedPriority":6,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"stareffect",
                            "direction":70,
                            "power":45,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_down":{
                    "refreshRate":100,
                    "chargetime_max":40,
                    "chargeClick":true,
                    "attackVoice1_id":"wario2",
                    "attackSound1_id":"whoosh2",
                    "attackSound2_id":"bombexplode",
                    "attackBoxes":{"attackBox":{
                            "damage":17,
                            "priority":6,
                            "chargedPriority":6,
                            "hitStun":7,
                            "hitLag":-1.3,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":0,
                            "power":0,
                            "kbConstant":0,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":1,
                    "allowControl":true,
                    "attackVoice1_id":"wario5",
                    "attackSound1_id":"brawl_wario_swing_S",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":7,
                            "hitStun":2,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":70,
                            "power":25,
                            "kbConstant":0,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "resetMovement":true,
                    "allowControl":true,
                    "attackSound1_id":"wariojumptwice",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":7,
                            "hitStun":1,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":-3,
                            "power":10,
                            "kbConstant":80,
                            "effectSound":"kick"
                        }}
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "canUseInAir":true,
                    "attackVoice1_id":"wario1",
                    "attackSound1_id":"brawl_wario_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":7,
                            "hitStun":0,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "effect_id":"effect_hit1",
                            "direction":15,
                            "power":38,
                            "kbConstant":46,
                            "effectSound":"ssb_hit1"
                        }}
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"wario3",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":7,
                            "hitStun":1,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":330,
                            "power":66,
                            "kbConstant":31,
                            "effectSound":"kick"
                        }}
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "allowFastFall":false,
                    "attackVoice1_id":"wario2",
                    "attackSound1_id":"brawl_wario_swing_S",
                    "attackBoxes":{"attackBox":{
                            "damage":16,
                            "priority":7,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":0,
                            "power":25,
                            "kbConstant":75,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "b":{
                    "refreshRate":20,
                    "cancelWhenAirborne":false,
                    "chargeInAir":false,
                    "attackVoice1_id":"hurryup",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":5,
                            "hitStun":3,
                            "hitLag":-0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "refreshRate":20,
                    "cancelWhenAirborne":false,
                    "chargeInAir":false,
                    "attackVoice1_id":"hurryup",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":5,
                            "hitStun":3,
                            "hitLag":-0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "refreshRate":3,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "airCancel":true,
                    "airCancelSpecial":true,
                    "air_ease":0,
                    "xSpeedCap":1,
                    "allowControl":false,
                    "attackVoice1_id":"wariocorkscrew",
                    "attackSound1_id":"whoosh3",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":3,
                            "hitStun":0,
                            "hitLag":-1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":29,
                            "kbConstant":15,
                            "effectSound":"sw_scratch"
                        }}
                },
                "b_up_air":{
                    "refreshRate":3,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "airCancel":true,
                    "airCancelSpecial":true,
                    "air_ease":0,
                    "xSpeedCap":1,
                    "allowControl":false,
                    "isRecoveryMove":true,
                    "attackVoice1_id":"wariocorkscrew",
                    "attackSound1_id":"whoosh3",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":3,
                            "hitStun":0,
                            "hitLag":-1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":29,
                            "kbConstant":15,
                            "effectSound":"sw_scratch"
                        }}
                },
                "b_forward":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-1,
                    "xSpeedDecayAir":-1,
                    "superArmor":true,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "allowTurn":true,
                    "attackVoice1_id":"wariogo",
                    "attackSound1_id":"wariobikerev",
                    "attackBoxes":{"attackBox":{
                            "hasEffect":false,
                            "damage":0,
                            "priority":6,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "camShake":5,
                            "effect_id":"effect_firehit1",
                            "direction":-1,
                            "power":50,
                            "kbConstant":40,
                            "effectSound":null
                        }}
                },
                "b_forward_air":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-1,
                    "xSpeedDecayAir":-1,
                    "superArmor":true,
                    "air_ease":0,
                    "maintainSpeed":true,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "allowTurn":true,
                    "attackVoice1_id":"wariogo",
                    "attackSound1_id":"wariobikerev",
                    "attackBoxes":{"attackBox":{
                            "hasEffect":false,
                            "damage":1,
                            "priority":6,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "camShake":5,
                            "effect_id":"effect_firehit1",
                            "direction":-1,
                            "power":50,
                            "kbConstant":40,
                            "effectSound":null
                        }}
                },
                "b_down":{
                    "cancelWhenAirborne":false,
                    "air_ease":1,
                    "canUseInAir":true,
                    "attackVoice1_id":"wario6",
                    "attackSound1_id":"wariowaft3",
                    "attackBoxes":{"attackBox":{
                            "damage":17,
                            "priority":7,
                            "hitStun":8,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "camShake":1,
                            "effect_id":"effect_firehit1",
                            "direction":25,
                            "power":25,
                            "kbConstant":100,
                            "burn":true,
                            "effectSound":null
                        }}
                },
                "b_down_air":{
                    "cancelWhenAirborne":false,
                    "isRecoveryMove":true,
                    "canUseInAir":true,
                    "attackVoice1_id":"wario6",
                    "attackSound1_id":"wariowaft3",
                    "attackBoxes":{"attackBox":{
                            "damage":17,
                            "priority":7,
                            "hitStun":8,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "camShake":1,
                            "effect_id":"effect_firehit1",
                            "direction":25,
                            "power":25,
                            "kbConstant":100,
                            "burn":true,
                            "effectSound":null
                        }}
                },
                "throw_up":{
                    "attackVoice1_id":"wario7",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh2",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":90,
                            "power":75,
                            "kbConstant":50,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_forward":{
                    "attackVoice1_id":"wario2",
                    "attackSound1_id":"brawl_wario_swing_S",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "direction":30,
                            "power":40,
                            "kbConstant":75,
                            "effectSound":"launch_s"
                        }}
                },
                "throw_back":{
                    "attackVoice1_id":"wario1",
                    "attackSound1_id":"brawl_wario_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":90,
                            "power":31,
                            "kbConstant":90,
                            "effectSound":"ssb_hit1"
                        }}
                },
                "throw_down":{
                    "chargeInAir":false,
                    "allowFastFall":false,
                    "attackVoice1_id":"wario2",
                    "attackSound1_id":"whoosh2",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":-1.3,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":15,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"ssb_hit1"
                        }}
                },
                "crouch_attack":{
                    "attackVoice1_id":"wario1",
                    "attackSound1_id":"brawl_wario_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":270,
                            "power":90,
                            "kbConstant":1,
                            "onlyAffectsGround":true,
                            "pitfall":15,
                            "effectSound":"punch2"
                        }}
                },
                "ledge_attack":{
                    "attackDelay":5,
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"wario7",
                    "attackSound1_id":"brawl_wario_swing_S",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":5,
                            "hitStun":0,
                            "hitLag":-0.9,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":1500,
                            "kbConstant":15,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "getup_attack":{
                    "refreshRate":3,
                    "attackVoice1_id":"wario1",
                    "attackVoice2_id":"wario2",
                    "attackVoice3_id":"wario3",
                    "attackVoice4_id":"wario4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":3,
                            "direction":45,
                            "power":75,
                            "kbConstant":50,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackVoice1_id":null,
                    "attackSound1_id":"warioeat",
                    "attackSound2_id":"wariotransform",
                    "attackSound3_id":"wariomanend",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":-0.9,
                            "selfHitStun":0,
                            "direction":0,
                            "power":2,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object = {
                "warioman_nspec":{
                    "linkage_id":"warioman_bomb",
                    "time_max":240,
                    "xspeed":11,
                    "gravity":0.5,
                    "maxgravity":4,
                    "stale":false,
                    "bounce":1,
                    "yoffset":-55,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":13,
                                "priority":4,
                                "hitStun":2,
                                "hitLag":-1.3,
                                "selfHitStun":0,
                                "effect_id":"warioboom",
                                "direction":55,
                                "power":30,
                                "kbConstant":50,
                                "burn":true,
                                "effectSound":"bombexplode"
                            }}}
                },
                "warioman_bike_kaboom":{
                    "linkage_id":"HUGEBOOM",
                    "time_max":27,
                    "ghost":true,
                    "stale":false,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":20,
                                "priority":7,
                                "hitStun":5,
                                "selfHitStun":2,
                                "camShake":10,
                                "effect_id":"effect_heavyHit",
                                "direction":30,
                                "power":40,
                                "kbConstant":110,
                                "burn":true,
                                "effectSound":null
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("wario");
        }

        public function getGUID():String
        {
            return ("e98d84bd-4a2d-4a2a-8440-f38caa78b7d4");
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package wario_fla

