// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//sonic_fla.MainTimeline

package sonic_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public var stance:super_sonic_afterimage;

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function getAudio():Array
        {
            return (new Array(Run_start, footstep, sonic_shouldBe, sonic_quickRev, sonic_bounce, sonic_dash, sonic_dash2, sonic_finaleffect1, sonic_finaleffect2, sonic_finalvoice1, sonic_finalvoice2, sonic_jump1, sonic_jump2, sonic_rev, sonic_rev2, sonic_zip, supersonic_taunt, sonic_attack_sound1, sonic_attack_sound2, sonic_attack_sound3, sonic_attack_sound4, sonic_bluetornado, supersonic_airdodge, Supertauntsfx, snd_se_Sonic_008, sonic_revving, sonic_entrance, supersonictaunt1, strongpunch, new_Sonic_win, new_Sonic_fspecial, new_Sonic_fspecialchrg, new_Sonic_attack0, new_Sonic_attack1, new_Sonic_attack2, new_Sonic_attack3, new_Sonic_attack4, new_Sonic_attack5, new_Sonic_attack6, new_Sonic_attack7, new_Sonic_attack8, new_Sonic_damage, sonic_starko, sonic_dsmash_voice, sonic_step_it_up, sonic_death, sonic_death2, sonic_fsmash_voice, sonic_usmash_voice, sonic_hurtBad, sonic_hurtBad2, sonic_finalsmash, too_slow, sonic_teeter));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"sonic",
                "displayName":"Sonic",
                "linkage_id":"sonicremastered",
                "linkage_id2":null,
                "linkage_id_special":"newsupersonic1",
                "thumbnail":"sonic_head",
                "seriesIcon":"sonic_symbol1",
                "width":22,
                "height":35,
                "jumpSpeed":15,
                "jumpSpeedMidair":15,
                "jumpStartup":2,
                "shortHopSpeed":8,
                "max_jumpSpeed":6.5,
                "wallJump":true,
                "dodgeSpeed":10,
                "gravity":1.1,
                "weight1":95,
                "power":"sonic",
                "norm_xSpeed":7,
                "max_xSpeed":15.137,
                "max_ySpeed":14,
                "fastFallSpeed":17,
                "accel_start":1.1,
                "accel_start_dash":1.3,
                "accel_rate":1.4,
                "accel_rate_air":0.7,
                "decel_rate":-1.52,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":5,
                "tetherGrab":false,
                "roll_speed":31,
                "roll_delay":7,
                "getup_roll_delay":0,
                "itemScaleRatio":0.645161290322581,
                "special_type":0,
                "normalStats_id":"sonic",
                "specialStats_id":"supersonic",
                "sounds":{
                    "jump":"sonic_jump1",
                    "jump_midair":"sonic_jump2",
                    "hurt":"hurt",
                    "hurt2":"hurt2",
                    "hurtBad":"hurtBad",
                    "hurtBad2":"hurtBad2",
                    "dead":"sonic_death",
                    "dead2":"sonic_death2",
                    "pummel":"brawl_kick_s",
                    "screenko":"sonic_hurtBad2",
                    "starko":"sonic_starko",
                    "ledge_grab":null,
                    "winTheme":"SonicVictoryv2"
                },
                "hurtFrames":5,
                "grabDamage":1,
                "fs_time_limit":600
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "canFallOff":false,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_attack_sound1",
                    "attackSound2_id":"sonic_attack_sound4",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":80,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"sonic_usmash_voice",
                    "attackSound1_id":"sonic_rev",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":4,
                            "sdiDistance":0.2,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":60,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "a_up_tilt":{
                    "refreshRate":8,
                    "canFallOff":false,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_attack_sound4",
                    "cpuAttackQueue":"a_air;crouch_attack;a_up_tilt;a_forwardsmash;a_up",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitStun":5,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":85,
                            "power":10,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_forward":{
                    "xSpeedAccel":1,
                    "canFallOff":false,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_rev",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":50,
                            "power":40,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forward_tilt":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_attack_sound4",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":30,
                            "power":30,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"sonic_fsmash_voice",
                    "attackSound1_id":"whip",
                    "attackSound2_id":"punch2",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "camShake":10,
                            "effect_id":"effect_heavyHit",
                            "direction":33,
                            "power":30,
                            "kbConstant":98,
                            "effectSound":"whack"
                        }}
                },
                "a_down":{
                    "refreshRate":75,
                    "xSpeedDecay":0.9,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"sonic_dsmash_voice",
                    "attackSound1_id":"sonic_revving",
                    "attackSound2_id":"sonic_rev",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":40,
                            "kbConstant":75,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_rev",
                    "cpuAttackQueue":"a_air_forward;a_air_down;b_down_air",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":35,
                            "power":45,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_attack_sound1",
                    "cpuAttackQueue":"a_air;a_air_up;b_up_air",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "camShake":4,
                            "effect_id":"effect_lightHit",
                            "direction":145,
                            "power":20,
                            "kbConstant":30,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":500,
                    "hit_ease":-5,
                    "allowControl":true,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_attack_sound4",
                    "cpuAttackQueue":"a_air_backward;a_air_forward;a_air_down;b_down_air;a_forwardsmash;a_down;a_up;throw_up",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":1,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":40,
                            "power":30,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_attack_sound3",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":5,
                            "hitStun":5,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":25,
                            "power":30,
                            "kbConstant":99,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":60,
                    "allowFastFall":false,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"armswing",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "hitLag":-1,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "power":50,
                            "kbConstant":70,
                            "effectSound":"whack"
                        }}
                },
                "b":{
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "reenableTimer":60,
                    "attackVoice1_id":"grunt1",
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"new_sonic_homing",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":35,
                            "power":45,
                            "kbConstant":70,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "b_air":{
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "isHorizontalRecoveryMove":true,
                    "isRecoveryMove":true,
                    "reenableTimer":60,
                    "attackVoice1_id":"grunt1",
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"new_sonic_homing",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":35,
                            "power":45,
                            "kbConstant":70,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "b_up":{
                    "refreshRate":5,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedCap":7,
                    "allowControl":true,
                    "reenableTimer":999,
                    "disableJump":true,
                    "attackSound1_id":"sonic_bounce",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hurtSelf":true,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":-1,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":null
                        }}
                },
                "b_up_air":{
                    "refreshRate":5,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedCap":7,
                    "allowControl":true,
                    "isRecoveryMove":true,
                    "reenableTimer":999,
                    "disableJump":true,
                    "attackSound1_id":"sonic_bounce",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":-1,
                            "power":0,
                            "kbConstant":10,
                            "effectSound":null
                        }}
                },
                "b_forward":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-1,
                    "air_ease":1,
                    "chargetime":5,
                    "allowFastFall":false,
                    "attackVoice1_id":"new_Sonic_fspecialchrg",
                    "attackVoice2_id":"new_Sonic_fspecial",
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"new_sonic_airboost",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":1,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":120,
                            "power":30,
                            "kbConstant":75,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "b_forward_air":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-1,
                    "air_ease":1,
                    "chargetime":5,
                    "allowFastFall":false,
                    "attackVoice1_id":"new_Sonic_fspecialchrg",
                    "attackVoice2_id":"new_Sonic_fspecial",
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"new_sonic_airboost",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":1,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":120,
                            "power":30,
                            "kbConstant":75,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "b_down":{
                    "cancel":true,
                    "cancelWhenAirborne":false,
                    "airCancel":true,
                    "airCancelSpecial":true,
                    "canFallOff":false,
                    "allowFastFall":false,
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"sonic_rev2",
                    "attackSound3_id":"sonic_quickRev",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":-1,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":50,
                            "power":75,
                            "kbConstant":45,
                            "effectSound":"brawl_kick_l",
                            "reversableAngle":false
                        }}
                },
                "b_down_air":{
                    "refreshRate":99,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "chargeInAir":false,
                    "attackVoice1_id":"grunt2",
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"sonic_rev2",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":6,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":270,
                            "power":70,
                            "kbConstant":40,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "throw_up":{
                    "refreshRate":100,
                    "canFallOff":false,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_rev",
                    "cpuAttackQueue":"a_up;a_up_tilt;a_down;crouch_attack;a_air",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":75,
                            "kbConstant":90,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_attack_sound4",
                    "cpuAttackQueue":"a_air_forward;a_forward;b_forward",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":55,
                            "reversableAngle":false,
                            "power":100,
                            "kbConstant":10,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_attack_sound3",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "camShake":9,
                            "effect_id":"effect_lightHit",
                            "direction":145,
                            "reversableAngle":false,
                            "power":70,
                            "kbConstant":60,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "throw_down":{
                    "refreshRate":4,
                    "canFallOff":false,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_rev",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":30,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":80,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "cpuAttackQueue":"a;a_air;a_air_forward;a_up_tilt",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":2,
                            "hitStun":2,
                            "hitLag":-1.15,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":70,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_attack_sound4",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":7,
                            "hitStun":0,
                            "weightKB":100,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":15,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_attack_sound4",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":6,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":30,
                            "power":100,
                            "kbConstant":20,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "kirby":{
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "reenableTimer":60,
                    "attackVoice1_id":"grunt1",
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"new_sonic_homing",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":35,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "kirby_air":{
                    "air_ease":0,
                    "isHorizontalRecoveryMove":true,
                    "isRecoveryMove":true,
                    "reenableTimer":60,
                    "attackVoice1_id":"grunt1",
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"new_sonic_homing",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":35,
                            "power":50,
                            "kbConstant":50,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "invincible":true,
                    "air_ease":0,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackVoice1_id":"finalsmash",
                    "attackSound1_id":"sonic_finaleffect1",
                    "attackSound2_id":"sonic_finaleffect2",
                    "attackBoxes":{"attackBox":{
                            "damage":18,
                            "priority":7,
                            "hitStun":7,
                            "selfHitStun":0,
                            "direction":40,
                            "power":75,
                            "kbConstant":40,
                            "bypassShield":true,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object = {
                "sonic_spring_ground_during":{
                    "linkage_id":"sonic_spring_uspec",
                    "time_max":10,
                    "limit":1,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "hasEffect":false,
                                "priority":7,
                                "hurtSelf":true,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "direction":90,
                                "power":0,
                                "kbConstant":0,
                                "onlyAffectsFall":true,
                                "effectSound":null
                            }}}
                },
                "sonic_spring_ground":{
                    "linkage_id":"sonic_spring1",
                    "time_max":120,
                    "gravity":2,
                    "maxgravity":5,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "limit":2,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "hasEffect":false,
                                "priority":7,
                                "hurtSelf":true,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "direction":90,
                                "power":0,
                                "kbConstant":0,
                                "onlyAffectsFall":true,
                                "effectSound":null
                            }}}
                },
                "sonic_spring_air":{
                    "linkage_id":"springidle",
                    "width":100,
                    "height":100,
                    "yspeed":-5,
                    "gravity":1,
                    "maxgravity":15,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "limit":2,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":6,
                                "priority":-1,
                                "hitStun":2,
                                "selfHitStun":0,
                                "direction":155,
                                "power":50,
                                "kbConstant":20,
                                "effectSound":"brawl_kick_m"
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getChar2(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"supersonic",
                "displayName":"Super Sonic",
                "linkage_id":"newsupersonic1",
                "linkage_id2":null,
                "linkage_id_special":"sonicremastered",
                "thumbnail":"supersonic_head",
                "seriesIcon":"sonic_symbol1",
                "width":26,
                "height":42,
                "jumpSpeed":15,
                "jumpSpeedMidair":15,
                "jumpStartup":2,
                "shortHopSpeed":7.5,
                "max_jumpSpeed":14,
                "dodgeSpeed":10,
                "gravity":1.1,
                "weight1":95,
                "power":null,
                "norm_xSpeed":7,
                "max_xSpeed":20,
                "max_ySpeed":9.5,
                "fastFallSpeed":13,
                "accel_start":0.7,
                "accel_start_dash":-1,
                "accel_rate":2,
                "accel_rate_air":2,
                "decel_rate":0.8,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":99999998,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_delay":4,
                "getup_roll_delay":0,
                "itemScaleRatio":0.833333333333333,
                "special_type":0,
                "normalStats_id":"sonic",
                "specialStats_id":"supersonic",
                "sounds":{
                    "jump":"sonic_jump1",
                    "jump_midair":"sonic_jump2",
                    "hurt":"new_Sonic_damage",
                    "hurt2":"new_Sonic_damage2",
                    "hurtBad":"new_Sonic_hitHard",
                    "hurtBad2":"new_Sonic_hitHard2",
                    "dead":"supersonic_ko1",
                    "dead2":"supersonic_ko2",
                    "pummel":"brawl_punch_m",
                    "screenko":"supersonic_ko2",
                    "starko":"sonic_starko",
                    "ledge_grab":null,
                    "winTheme":"SonicVictoryv2"
                },
                "hurtFrames":2,
                "grabDamage":2,
                "fs_time_limit":600
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":15,
                    "combo_max":2,
                    "holdRepeat":true,
                    "attackVoice1_id":"new_Sonic_attack1",
                    "attackSound1_id":"sonic_attack_sound1",
                    "attackSound2_id":"sonic_attack_sound3",
                    "attackSound3_id":"sonic_rev",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":6,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_up":{
                    "refreshRate":8,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"new_Sonic_attack7",
                    "attackSound1_id":"sonic_revving",
                    "attackSound2_id":"sonic_rev",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":5,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":90,
                            "power":60,
                            "kbConstant":95,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"new_Sonic_attack2",
                    "attackSound1_id":"sonic_attack_sound4",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "camShake":8,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":20,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_forward":{
                    "cancel":true,
                    "canFallOff":false,
                    "attackSound1_id":"sonic_dash",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "camShake":11,
                            "effect_id":"effect_heavyHit",
                            "direction":25,
                            "power":25,
                            "kbConstant":115,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_forward_tilt":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackVoice1_id":"new_Sonic_attack8",
                    "attackSound1_id":"sonic_attack_sound3",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":5,
                            "hitStun":10,
                            "selfHitStun":1,
                            "camShake":10,
                            "effect_id":"effect_lightHit",
                            "direction":40,
                            "power":75,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_forwardsmash":{
                    "resetMovement":true,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"new_Sonic_fspecial",
                    "attackSound1_id":"armswing1",
                    "attackSound2_id":"sonic_attack_sound4",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":3,
                            "camShake":11,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "power":40,
                            "kbConstant":95,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"new_Sonic_attack6",
                    "attackSound1_id":"sonic_revving",
                    "attackSound2_id":"sonic_rev",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":5,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":40,
                            "kbConstant":110,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "resetMovement":true,
                    "air_ease":5,
                    "allowControl":true,
                    "attackSound1_id":"overwhelm",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":7,
                            "hitStun":-1,
                            "selfHitStun":0,
                            "effect_id":"effect_hit1",
                            "direction":60,
                            "power":65,
                            "kbConstant":80,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"new_Sonic_attack4",
                    "attackSound1_id":"sonic_attack_sound4",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":7,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":100,
                            "power":45,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":90,
                    "allowControl":true,
                    "attackVoice1_id":"new_Sonic_attack8",
                    "attackSound1_id":"sonic_attack_sound4",
                    "attackBoxes":{"attackBox":{
                            "damage":17,
                            "priority":7,
                            "hitStun":4,
                            "selfHitStun":1,
                            "camShake":12,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":25,
                            "kbConstant":85,
                            "effectSound":"strongpunch"
                        }}
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"Sonic_US_Attack01",
                    "attackSound1_id":"sonic_attack_sound4",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":7,
                            "hitStun":5,
                            "selfHitStun":5,
                            "effect_id":"effect_heavyHit",
                            "direction":160,
                            "reversableAngle":false,
                            "power":35,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "resetMovement":true,
                    "airCancel":true,
                    "air_ease":0,
                    "allowControl":true,
                    "attackSound1_id":"armswing",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":7,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":270,
                            "power":80,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "air_ease":1,
                    "canUseInAir":true,
                    "homingSpeed":30,
                    "attackVoice1_id":"new_Sonic_attack5",
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"new_sonic_homing",
                    "attackBoxes":{"attackBox":{
                            "damage":29,
                            "priority":3,
                            "hitStun":15,
                            "selfHitStun":15,
                            "effect_id":"effect_hit1",
                            "direction":55,
                            "reversableAngle":false,
                            "power":100,
                            "kbConstant":50,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "b_air":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "air_ease":1,
                    "homingSpeed":30,
                    "attackVoice1_id":"new_Sonic_attack5",
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"new_sonic_homing",
                    "attackBoxes":{"attackBox":{
                            "damage":29,
                            "priority":3,
                            "hitStun":15,
                            "selfHitStun":15,
                            "effect_id":"effect_hit1",
                            "direction":55,
                            "reversableAngle":false,
                            "power":100,
                            "kbConstant":50,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "b_up":{
                    "refreshRate":2,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "controlDirection":true,
                    "attackSound1_id":"new_sonic_boost",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":7,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":60,
                            "power":60,
                            "kbConstant":86,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_up_air":{
                    "refreshRate":2,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "controlDirection":true,
                    "attackSound1_id":"new_sonic_airboost",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":7,
                            "hitStun":0,
                            "selfHitStun":1,
                            "direction":60,
                            "power":60,
                            "kbConstant":86,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_forward":{
                    "refreshRate":4,
                    "resetMovement":true,
                    "cancel":true,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "chargetime_max":60,
                    "holdRepeat":true,
                    "allowJump":true,
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"sonic_rev2",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":25,
                            "reversableAngle":false,
                            "power":55,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "b_forward_air":{
                    "refreshRate":4,
                    "resetMovement":true,
                    "cancel":true,
                    "cancelWhenAirborne":false,
                    "airCancel":true,
                    "allowControl":true,
                    "chargetime_max":60,
                    "holdRepeat":true,
                    "allowJump":true,
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"sonic_rev2",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":-9,
                            "reversableAngle":false,
                            "power":55,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "b_down":{
                    "refreshRate":4,
                    "air_ease":1,
                    "attackVoice1_id":"sonic_takethis",
                    "attackSound1_id":"sonic_bluetornado",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":4,
                            "hitStun":0,
                            "hitLag":10,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":-9,
                            "power":40,
                            "kbConstant":17,
                            "effectSound":null
                        }}
                },
                "b_down_air":{
                    "refreshRate":4,
                    "air_ease":1,
                    "attackVoice1_id":"sonic_takethis",
                    "attackSound1_id":"sonic_bluetornado",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":4,
                            "hitStun":1,
                            "hitLag":10,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":-9,
                            "power":40,
                            "kbConstant":17,
                            "effectSound":null
                        }}
                },
                "throw_up":{
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":90,
                            "power":24,
                            "kbConstant":55,
                            "effectSound":"kick"
                        }}
                },
                "throw_forward":{
                    "attackVoice1_id":"Sonic_US_Attack04",
                    "attackSound1_id":"sonic_attack_sound4",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":5,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":10,
                            "power":28,
                            "kbConstant":99,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "throw_back":{
                    "flip":true,
                    "attackVoice1_id":"sonic_go",
                    "attackSound1_id":"armswing1",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":65,
                            "kbConstant":80,
                            "effectSound":"punch2"
                        }}
                },
                "throw_down":{
                    "refreshRate":5,
                    "attackSound1_id":"sonic_rev",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "power":80,
                            "kbConstant":45,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "crouch_attack":{
                    "attackVoice1_id":"Sonic_US_Attack04",
                    "attackSound1_id":"sonic_attack_sound4",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":25,
                            "kbConstant":60,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "ledge_attack":{
                    "attackDelay":5,
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackSound1_id":"sonic_rev",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":0,
                            "hitLag":0.9,
                            "weightKB":100,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":30,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackVoice1_id":"grunt1",
                    "attackVoice2_id":"grunt2",
                    "attackVoice3_id":"grunt3",
                    "attackVoice4_id":"grunt4",
                    "attackSound1_id":"sonic_attack_sound4",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":6,
                            "hitStun":2,
                            "weightKB":100,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":30,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "kirby":{
                    "resetMovement":true,
                    "attackDelay":10,
                    "air_ease":1,
                    "homingSpeed":18,
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"sonic_rev2",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":3,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":1200,
                            "kbConstant":14,
                            "effectSound":"kick"
                        }}
                },
                "kirby_air":{
                    "resetMovement":true,
                    "attackDelay":10,
                    "air_ease":1,
                    "homingSpeed":18,
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"sonic_rev2",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":3,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":1200,
                            "kbConstant":14,
                            "effectSound":"kick"
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "invincible":true,
                    "canUseInAir":true,
                    "attackVoice1_id":"ichigo_bankai",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":7,
                            "hitStun":5,
                            "selfHitStun":0,
                            "direction":40,
                            "power":75,
                            "kbConstant":40,
                            "bypassShield":true,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "jump":{
                    "allowControl":true,
                    "allowFullInterrupt":true,
                    "attackVoice1_id":"new_Sonic_attack8",
                    "attackSound1_id":"sonic_attack_sound4",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":7,
                            "hitStun":4,
                            "selfHitStun":1,
                            "camShake":12,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":25,
                            "kbConstant":80,
                            "effectSound":"strongpunch"
                        }}
                },
                "jump_midair":{
                    "allowControl":true,
                    "allowFullInterrupt":true,
                    "attackVoice1_id":"new_Sonic_attack8",
                    "attackSound1_id":"sonic_attack_sound4",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":7,
                            "hitStun":4,
                            "selfHitStun":1,
                            "camShake":12,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":25,
                            "kbConstant":80,
                            "effectSound":"strongpunch"
                        }}
                }
            };
            var _local_4:Object = {
                "supersonic_spring":{
                    "linkage_id":"sonic_spring1",
                    "time_max":120,
                    "gravity":2,
                    "maxgravity":5,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "limit":2,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":0,
                                "hasEffect":false,
                                "priority":7,
                                "hurtSelf":true,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "direction":90,
                                "power":0,
                                "kbConstant":0,
                                "onlyAffectsFall":true,
                                "effectSound":null
                            }}}
                },
                "supersonic_spring_idle":{
                    "linkage_id":"springidle",
                    "width":100,
                    "height":100,
                    "yspeed":-5,
                    "gravity":1,
                    "maxgravity":15,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "limit":2,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":7,
                                "priority":-1,
                                "hitStun":2,
                                "selfHitStun":0,
                                "direction":170,
                                "power":50,
                                "kbConstant":20,
                                "effectSound":"brawl_kick_m"
                            }}}
                },
                "supersonic_tornado":{
                    "linkage_id":"super_sonic_dspecial_projectile1",
                    "width":100,
                    "height":100,
                    "xspeed":12,
                    "canBeAbsorbed":false,
                    "suction":true,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":12,
                                "priority":7,
                                "hitStun":-1,
                                "selfHitStun":0,
                                "direction":90,
                                "power":25,
                                "kbConstant":90,
                                "bypassShield":true,
                                "effectSound":"launch_s"
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("sonic");
        }

        public function getGUID():String
        {
            return ("7b84c137-a56c-4db9-b154-154c9da71076");
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package sonic_fla

