// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//kirby_fla.MainTimeline

package kirby_fla
{
    import flash.display.MovieClip;
    import flash.events.Event;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.geom.Point;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
            addEventListener(Event.ADDED_TO_STAGE, this.__setPerspectiveProjection_);
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        public function getAudio():Array
        {
            return (new Array(KirbyVictory, kirby_Thworp, hammersfx, Kirby_Falcon, Kirby_Punch, kirby_airspin, kirby_derock, kirby_fire, kirby_dash, kirby_puff, kirby_hah, kirby_hammer, kirby_hi_melee, kirby_hithard, kirby_hollow, kirby_hiyah, kirby_powersteal, kirby_rockhitground, kirby_rockpound, kirby_spit, kirby_star, kirby_shortsuck, kirby_suck, kirby_flying, kirbytauntstar, kirbywin, ichigo_special_swing_2, SkullKidlaugh, kirby_entrance, brawl_kirby_swing_s, kirby_jump1, kirby_uspecial_sfx1, kirby_uspecial_sfx2, kirby_dspecial_start, kirby_dspecial_end, sora_keyhit1, sora_keyhit2, sora_keyhit3, sora_keyhit4, sora_keyhit5, handgesture, naruto_bunshin, rasengan_sfx1, naruto_explodeoodama, ness_flashProjectile, ness_flashExplode, sora_fireSFX, toadsfx, toad_spore, sonic_rev, sonic_rev2, tails_bshot, fireball, Kirby_Cooking, kirby_fryingpan, kirby_fssalt, kirby_fsdestroy, kirby_fsbg, splash_char, splash_item, kirby_DK, kirby_yoshi1, kirby_yoshi2, kirby_wario1, kirby_wario2, kirby_ness, kirby_pikachu, kirby_sonic, kirby_ike, kirby_tauntmelee, kirby_footstep, kirby_uspec_yaa, kirby_grunt1, kirby_grunt2, kirby_grunt3, kirby_grunt4, kirby_hammer, kirby_uspec_ayy, kirby_uspec_ee, kirby_uspec_yaa, kirby_taunt_brawl, kirby_fsmash, kirby_usmash, kirby_dsmash, kirby_hurt, kirby_hurt2, kirby_dead, kirby_dead2, kirby_hurtBad, kirby_hurtBad2, kirby_starko, kirby_dizzy, kirby_crouch1, kirby_crouch2, kirby_attackstar));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"kirby",
                "displayName":"Kirby",
                "linkage_id":"kirby",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"kirby_head",
                "seriesIcon":"Kirby_Symbol",
                "width":30,
                "height":30,
                "jumpSpeed":12,
                "jumpSpeedMidair":12,
                "jumpStartup":2,
                "shortHopSpeed":6,
                "max_jumpSpeed":5.8,
                "midAirTurn":true,
                "dodgeSpeed":10,
                "gravity":0.85,
                "weight1":78,
                "power":null,
                "norm_xSpeed":4,
                "max_xSpeed":8,
                "max_ySpeed":10,
                "fastFallSpeed":15,
                "accel_start":1,
                "accel_start_dash":1.2,
                "accel_rate":0.9,
                "accel_rate_air":1.4,
                "decel_rate":-1.07,
                "decel_rate_air":-0.075,
                "holdJump":false,
                "max_jump":5,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":16,
                "roll_delay":10,
                "getup_roll_delay":0,
                "itemScaleRatio":0.869565217391304,
                "special_type":3,
                "normalStats_id":"kirby",
                "specialStats_id":null,
                "sounds":{
                    "jump":"kirby_jump1",
                    "jump_midair":"kirby_puff",
                    "hurt":"kirby_hurt",
                    "hurt2":"kirby_hurt2",
                    "hurtBad":"kirby_hurtBad",
                    "hurtBad2":"kirby_hurtBad2",
                    "dead":"kirby_dead",
                    "dead2":"kirby_dead2",
                    "pummel":"brawl_punch_m",
                    "screenko":"kirby_hithard",
                    "starko":"kirby_starko",
                    "ledge_grab":null,
                    "winTheme":"KirbyVictory"
                },
                "hurtFrames":2,
                "grabDamage":1
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "combo_max":999,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "reenableTimer":6,
                    "attackSound1_id":"brawl_swing_m",
                    "attackSound2_id":"brawl_swing_s",
                    "attackSound3_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":1,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":30,
                            "power":8,
                            "kbConstant":30,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"kirby_usmash",
                    "attackSound1_id":"sw_brawl_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":4,
                            "hitStun":5,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_swordSlash",
                            "direction":90,
                            "power":34,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air_up;a_air_backward",
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackVoice3_id":"kirby_grunt3",
                    "attackVoice4_id":"kirby_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":85,
                            "power":50,
                            "kbConstant":55,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":5,
                            "priority":2,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":85,
                            "power":50,
                            "kbConstant":55,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forward":{
                    "refreshRate":4,
                    "canFallOff":false,
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackVoice3_id":"kirby_grunt3",
                    "attackVoice4_id":"kirby_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":25,
                            "reversableAngle":false,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackVoice3_id":"kirby_grunt3",
                    "attackVoice4_id":"kirby_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":12,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_forwardsmash":{
                    "xSpeedDecay":-1,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"kirby_fsmash",
                    "attackSound1_id":"sw_brawl_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":15,
                            "priority":6,
                            "hitStun":4,
                            "selfHitStun":4,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":38,
                            "kbConstant":98,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"kirby_dsmash",
                    "attackSound1_id":"sw_brawl_swing_H",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":5,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox2":{
                            "damage":14,
                            "priority":5,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l"
                        },
                        "attackBox3":{
                            "damage":14,
                            "priority":5,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l"
                        }
                    }
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackVoice3_id":"kirby_grunt3",
                    "attackVoice4_id":"kirby_grunt4",
                    "attackSound1_id":"kirby_airspin",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":40,
                            "power":20,
                            "kbConstant":80,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "maintainSpeed":true,
                    "cpuAttackQueue":"a_air_up;a_air_backward",
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackVoice3_id":"kirby_grunt3",
                    "attackVoice4_id":"kirby_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "power":35,
                            "kbConstant":55,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackVoice3_id":"kirby_grunt3",
                    "attackVoice4_id":"kirby_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":2,
                            "hitStun":5,
                            "hitLag":-1.2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "reversableAngle":false,
                            "power":35,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackVoice3_id":"kirby_grunt3",
                    "attackVoice4_id":"kirby_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitStun":4,
                            "selfHitStun":3,
                            "effect_id":"effect_hit1",
                            "direction":150,
                            "reversableAngle":false,
                            "power":20,
                            "kbConstant":105,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "refreshRate":4,
                    "hit_ease":3.13,
                    "allowControl":true,
                    "cpuAttackQueue":"throw_down",
                    "reenableTimer":20,
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackVoice3_id":"kirby_grunt3",
                    "attackVoice4_id":"kirby_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":1,
                            "hitStun":4,
                            "hitLag":-0.7,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":278,
                            "power":20,
                            "kbConstant":107,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b":{
                    "reenableTimer":-1,
                    "refreshRate":5,
                    "combo_max":999,
                    "holdRepeat":true,
                    "attackSound1_id":"kirby_suck",
                    "attackSound2_id":"kirby_spit",
                    "attackSound3_id":"kirby_powersteal",
                    "attackSound4_id":"kirby_shortsuck",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":-1,
                            "sdiDistance":0,
                            "hitStun":4,
                            "selfHitStun":0,
                            "direction":160,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":9,
                            "bypassShield":true,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "reenableTimer":-1,
                    "combo_max":999,
                    "holdRepeat":true,
                    "allowFastFall":false,
                    "attackSound1_id":"kirby_suck",
                    "attackSound2_id":"kirby_spit",
                    "attackSound3_id":"kirby_powersteal",
                    "attackSound4_id":"kirby_shortsuck",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":160,
                            "reversableAngle":false,
                            "power":50,
                            "kbConstant":1,
                            "bypassShield":true,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "refreshRate":10000,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "canFallOff":false,
                    "attackVoice1_id":"kirby_uspec_ee",
                    "attackVoice2_id":"kirby_uspec_yaa",
                    "attackVoice3_id":"kirby_uspec_ayy",
                    "attackSound1_id":"kirby_uspecial_sfx1",
                    "attackSound2_id":"kirby_uspecial_sfx2",
                    "attackSound3_id":"sw_strongslash",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":85,
                            "power":60,
                            "kbConstant":40,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "b_up_air":{
                    "refreshRate":10000,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "canFallOff":false,
                    "isRecoveryMove":true,
                    "attackVoice1_id":"kirby_uspec_ee",
                    "attackVoice2_id":"kirby_uspec_yaa",
                    "attackVoice3_id":"kirby_uspec_ayy",
                    "attackSound1_id":"kirby_uspecial_sfx1",
                    "attackSound2_id":"kirby_uspecial_sfx2",
                    "attackSound3_id":"sw_strongslash",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":85,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "b_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"kirby_hammer",
                    "attackSound1_id":"hammersfx",
                    "attackBoxes":{"attackBox":{
                            "damage":23,
                            "priority":6,
                            "hitStun":5,
                            "selfHitStun":3,
                            "camShake":10,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":65,
                            "kbConstant":72,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_forward_air":{
                    "hit_ease":-8,
                    "allowControl":true,
                    "attackVoice1_id":"kirby_hammer",
                    "attackSound1_id":"hammersfx",
                    "attackBoxes":{"attackBox":{
                            "damage":17,
                            "priority":6,
                            "hitStun":5,
                            "selfHitStun":3,
                            "camShake":10,
                            "effect_id":"effect_heavyHit",
                            "direction":35,
                            "power":50,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_down":{
                    "resetMovement":true,
                    "cancel":true,
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "forceGrabbable":true,
                    "attackVoice1_id":"kirby_derock",
                    "attackVoice2_id":"SkullKidlaugh",
                    "attackVoice3_id":null,
                    "attackVoice4_id":"kirby_Thworp",
                    "attackSound1_id":"kirby_dspecial_start",
                    "attackSound2_id":"kirby_dspecial_end",
                    "attackSound3_id":"kirby_rockhitground",
                    "attackBoxes":{"attackBox":{
                            "damage":18,
                            "priority":7,
                            "hitStun":4,
                            "selfHitStun":4,
                            "effect_id":"effect_heavyHit",
                            "direction":70,
                            "power":40,
                            "kbConstant":80,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "b_down_air":{
                    "resetMovement":true,
                    "cancel":true,
                    "canFallOff":false,
                    "forceGrabbable":true,
                    "attackVoice1_id":"kirby_derock",
                    "attackVoice2_id":"SkullKidlaugh",
                    "attackVoice3_id":null,
                    "attackVoice4_id":"kirby_Thworp",
                    "attackSound1_id":"kirby_dspecial_start",
                    "attackSound2_id":"kirby_dspecial_end",
                    "attackSound3_id":"kirby_rockhitground",
                    "attackBoxes":{"attackBox":{
                            "damage":18,
                            "priority":7,
                            "hitStun":4,
                            "selfHitStun":4,
                            "effect_id":"effect_heavyHit",
                            "direction":70,
                            "power":40,
                            "kbConstant":70,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "throw_up":{
                    "cancelWhenAirborne":false,
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackVoice3_id":"kirby_grunt3",
                    "attackVoice4_id":"kirby_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":-1,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":3,
                            "effect_id":"effect_firehit1",
                            "direction":85,
                            "power":90,
                            "kbConstant":70,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "throw_forward":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackVoice3_id":"kirby_grunt3",
                    "attackVoice4_id":"kirby_grunt4",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":-1,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "reversableAngle":false,
                            "power":40,
                            "kbConstant":100,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_back":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "attackVoice1_id":"kirby_hammer2",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh2",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":-1,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_heavyHit",
                            "direction":130,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":50,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "throw_down":{
                    "refreshRate":3,
                    "canFallOff":false,
                    "cpuAttackQueue":"a_air_down",
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackVoice3_id":"kirby_grunt3",
                    "attackVoice4_id":"kirby_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackSound2_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "hasEffect":false,
                            "priority":-1,
                            "hitStun":4,
                            "hitLag":-1.07,
                            "selfHitStun":0,
                            "effect_id":"effect_hit1",
                            "direction":20,
                            "power":40,
                            "kbConstant":150,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "crouch_attack":{
                    "xSpeedDecay":-1,
                    "canFallOff":false,
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackVoice3_id":"kirby_grunt3",
                    "attackVoice4_id":"kirby_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":35,
                            "power":30,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "cancelWhenAirborne":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackVoice3_id":"kirby_grunt3",
                    "attackVoice4_id":"kirby_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":2,
                            "hitStun":2,
                            "weightKB":100,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":30,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_grunt2",
                    "attackVoice3_id":"kirby_grunt3",
                    "attackVoice4_id":"kirby_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "weightKB":100,
                            "selfHitStun":0,
                            "direction":55,
                            "power":0,
                            "kbConstant":110,
                            "effectSound":null
                        }}
                },
                "kirby":{
                    "combo_max":999,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "attackSound1_id":"kirby_suck",
                    "attackSound2_id":"kirby_spit",
                    "attackSound3_id":"kirby_powersteal",
                    "attackSound4_id":"kirby_shortsuck",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":1,
                            "direction":30,
                            "power":1,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "combo_max":999,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "attackSound1_id":"kirby_suck",
                    "attackSound2_id":"kirby_spit",
                    "attackSound3_id":"kirby_powersteal",
                    "attackSound4_id":"kirby_shortsuck",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":1,
                            "direction":30,
                            "power":1,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "special":{
                    "refreshRate":3,
                    "resetMovement":true,
                    "invincible":true,
                    "air_ease":0,
                    "canFallOff":false,
                    "canUseInAir":true,
                    "attackVoice1_id":"kirby_taunt",
                    "attackVoice2_id":"kirby_hah",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "hasEffect":false,
                            "priority":7,
                            "hitStun":12,
                            "selfHitStun":0,
                            "direction":-2,
                            "power":35,
                            "kbConstant":170,
                            "effectSound":null
                        }}
                },
                "kirby_blackmage":{
                    "parentAttack":"b",
                    "refreshRate":100,
                    "chargetime_max":180,
                    "canFallOff":false,
                    "attackSound1_id":"BMstop1",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":7,
                            "hitStun":15,
                            "hitStunProjectile":15,
                            "weightKB":50,
                            "selfHitStun":0,
                            "direction":50,
                            "power":0,
                            "kbConstant":40,
                            "effectSound":"BMstop2"
                        }}
                },
                "kirby_bomberman":{
                    "parentAttack":"b",
                    "cancelWhenAirborne":false,
                    "xSpeedCap":4,
                    "holdRepeat":true,
                    "allowTurn":false,
                    "reenableTimer":3,
                    "attackVoice1_id":"kirby_derock",
                    "attackSound1_id":"bomberman_plant",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "kirby_captainfalcon":{
                    "parentAttack":"b",
                    "canFallOff":false,
                    "disableForCPU":true,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "attackVoice1_id":"Kirby_Falcon",
                    "attackVoice2_id":"Kirby_Punch",
                    "attackSound1_id":"fPunchCharge",
                    "attackSound2_id":"fPunchSwing",
                    "attackSound3_id":"fPunchImpact",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":20,
                            "priority":7,
                            "hitStun":4,
                            "selfHitStun":2,
                            "camShake":3,
                            "effect_id":"effect_firehit1",
                            "direction":35,
                            "power":30,
                            "kbConstant":93,
                            "burn":true,
                            "effectSound":"brawl_punch_l"
                        },
                        "attackBox2":{
                            "damage":20,
                            "priority":7,
                            "hitStun":4,
                            "selfHitStun":2,
                            "camShake":3,
                            "effect_id":"effect_firehit1",
                            "direction":35,
                            "power":30,
                            "kbConstant":93,
                            "burn":true,
                            "effectSound":"brawl_punch_l"
                        }
                    }
                },
                "kirby_chibirobo":{
                    "parentAttack":"b",
                    "isLongRangeMove":true,
                    "allowFastFall":false,
                    "attackSound1_id":"samus_charge",
                    "attackSound2_id":"samus_shot1",
                    "attackSound3_id":"samus_shot2",
                    "attackSound4_id":"samus_shot3",
                    "attackSound5_id":"samus_shot4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "kirby_dkong":{
                    "parentAttack":"b",
                    "refreshRate":100,
                    "cancelWhenAirborne":false,
                    "allowControlGround":false,
                    "chargetime_max":72,
                    "charge_retain":true,
                    "canUseInAir":true,
                    "allowFastFall":false,
                    "customChargeGlow":"kirby_dkbar",
                    "useChargeBar":false,
                    "attackVoice1_id":"kirby_DK",
                    "attackSound1_id":"dk_spin",
                    "attackSound2_id":"brawl_dk_swing_H",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":6,
                            "chargedPriority":7,
                            "hitStun":5,
                            "selfHitStun":5,
                            "camShake":4,
                            "effect_id":"effect_heavyHit",
                            "direction":25,
                            "power":15,
                            "kbConstant":90,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "kirby_Fox":{
                    "parentAttack":"b",
                    "refreshRate":100,
                    "combo_max":99999,
                    "canBeAbsorbed":true,
                    "disableForCPU":true,
                    "chargeInAir":false,
                    "attackSound1_id":"fox_blaster",
                    "attackSound2_id":"fox_putaway",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":105,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "kirby_goku":{
                    "parentAttack":"b",
                    "refreshRate":0,
                    "cancelWhenAirborne":false,
                    "air_ease":3,
                    "chargetime_max":400,
                    "canFallOff":false,
                    "hitEffect":"effect_hit2",
                    "disableForCPU":true,
                    "chargeInAir":false,
                    "attackVoice1_id":"kirby_grunt4",
                    "attackVoice2_id":"kirby_dash",
                    "attackVoice3_id":"kirby_hah",
                    "attackVoice4_id":"kirby_dash",
                    "attackVoice5_id":"kirby_hiyah",
                    "attackSound1_id":"goku_kame_charge",
                    "attackSound2_id":"goku_kame_shoot_2",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":80,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":70,
                            "power":40,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "kirby_ichigo":{
                    "parentAttack":"b",
                    "refreshRate":8,
                    "reenableTimer":28,
                    "attackVoice1_id":"kirby_ike",
                    "attackSound1_id":"ichigo_special_swing_2",
                    "attackSound2_id":"handgesture",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":0,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":null
                        }}
                },
                "kirby_jigglypuff":{
                    "parentAttack":"b",
                    "refreshRate":5,
                    "cancelWhenAirborne":false,
                    "xSpeedDecayAir":1,
                    "chargetime_max":99999999,
                    "combo_max":999,
                    "holdRepeat":true,
                    "disableForCPU":true,
                    "canUseInAir":true,
                    "attackVoice1_id":"kirby_hat_jiggs",
                    "attackSound1_id":"jiggs_rollout1",
                    "attackSound2_id":"jiggs_rollout2",
                    "attackSound3_id":"jiggs_rollout3",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":-1,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":102,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "kirby_link":{
                    "parentAttack":"b",
                    "refreshRate":100,
                    "isLongRangeMove":true,
                    "chargetime_max":25,
                    "holdRepeat":true,
                    "attackSound1_id":"link_bow_charge",
                    "attackSound2_id":"link_bow_shoot",
                    "attackSound3_id":"link_bow_done",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "kirby_lloyd":{
                    "parentAttack":"b",
                    "cancelWhenAirborne":false,
                    "customChargeGlow":"DFoverlay",
                    "attackVoice1_id":"kirby_grunt1",
                    "attackVoice2_id":"kirby_sonic",
                    "attackSound1_id":"sw_tos_singleslash",
                    "attackSound2_id":"tos_swordswing",
                    "isLongRangeMove":true,
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "hasEffect":false,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":45,
                            "power":0,
                            "kbConstant":70,
                            "effectSound":"tos_swordcut"
                        },
                        "attackBox2":{
                            "damage":3,
                            "hasEffect":false,
                            "priority":3,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"sliceBlue",
                            "direction":45,
                            "power":0,
                            "kbConstant":70,
                            "effectSound":"tos_swordcut"
                        }
                    }
                },
                "kirby_mario":{
                    "parentAttack":"b",
                    "attackSound1_id":"fireball",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":30,
                            "power":0,
                            "kbConstant":1,
                            "burn":true,
                            "effectSound":null
                        }}
                },
                "kirby_marth":{
                    "parentAttack":"b",
                    "canFallOff":false,
                    "allowControl":false,
                    "chargetime_max":45,
                    "canFallOff":false,
                    "attackVoice1_id":null,
                    "attackSound1_id":"marth_nspec_charge",
                    "attackSound2_id":"marth_nspec_swing",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":40,
                            "power":70,
                            "kbConstant":70,
                            "shieldDamage":50,
                            "effectSound":"sw_brawl_hit_M"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":40,
                            "power":70,
                            "kbConstant":75,
                            "shieldDamage":50,
                            "effectSound":"sw_brawl_hit_M"
                        }
                    }
                },
                "kirby_megaman":{
                    "parentAttack":"b",
                    "cancelWhenAirborne":false,
                    "xSpeedCap":9,
                    "chargetime_max":45,
                    "holdRepeat":true,
                    "allowJump":true,
                    "allowRun":true,
                    "allowTurn":true,
                    "allowDoubleJump":true,
                    "reenableTimer":3,
                    "attackSound1_id":null,
                    "attackSound2_id":"megaman_shoot",
                    "attackSound3_id":"megaman_blast",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":-0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":"punch2"
                        }}
                },
                "kirby_metaknight":{
                    "parentAttack":"b",
                    "refreshRate":1,
                    "cancelWhenAirborne":false,
                    "xSpeedAccelAir":2,
                    "air_ease":2,
                    "xSpeedCap":10,
                    "allowControl":true,
                    "attackSound1_id":"mk_tornado1",
                    "attackSound2_id":"mk_tornado2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":105,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":105,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox3":{
                            "damage":1,
                            "priority":5,
                            "hitStun":1,
                            "hitLag":-1.2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":105,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "kirby_naruto":{
                    "parentAttack":"b",
                    "cancelSoundOnEnd":true,
                    "cancelVoiceOnEnd":true,
                    "allowControlGround":false,
                    "chargetime_max":75,
                    "charge_retain":true,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "customChargeGlow":"naruto_fullChargeFlash",
                    "useChargeBar":false,
                    "attackVoice1_id":"kirby_naruto",
                    "attackVoice2_id":"kirby_naruto_shuriken",
                    "attackSound1_id":"smallblast",
                    "attackSound2_id":"naruto_explodeoodama",
                    "attackSound3_id":"naruto_sfx_rasengan_charge",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":5,
                            "sdiDistance":0,
                            "hitStun":5,
                            "hitLag":0.93,
                            "selfHitStun":0,
                            "camShake":9,
                            "direction":30,
                            "power":30,
                            "kbConstant":60,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "kirby_ness":{
                    "parentAttack":"b",
                    "conserveJumpConstant":false,
                    "air_ease":3,
                    "chargetime_max":70,
                    "forceUseAtMaxCharge":true,
                    "holdRepeat":true,
                    "canFallOff":false,
                    "attackVoice1_id":"kirby_ness",
                    "attackSound1_id":"ness_flashProjectile",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":3,
                            "hitStun":2,
                            "hitLag":1,
                            "selfHitStun":2,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "kirby_peach":{
                    "parentAttack":"b",
                    "refreshRate":2,
                    "attackDelay":6,
                    "cancelWhenAirborne":false,
                    "air_ease":4,
                    "canFallOff":false,
                    "forceGrabbable":true,
                    "allowFastFall":false,
                    "attackSound1_id":"toadsfx",
                    "attackSound2_id":"toad_spore",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":7,
                            "chargedPriority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "direction":40,
                            "power":40,
                            "kbConstant":180,
                            "effectSound":null
                        }}
                },
                "kirby_pikachu":{
                    "parentAttack":"b",
                    "refreshRate":100,
                    "chargeInAir":false,
                    "attackVoice1_id":"kirby_pikachu",
                    "attackSound1_id":"brawl_zap_l",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":10,
                            "power":20,
                            "kbConstant":60,
                            "effectSound":null
                        }}
                },
                "kirby_samus":{
                    "parentAttack":"b",
                    "cancelSoundOnEnd":true,
                    "allowControl":false,
                    "allowControlGround":false,
                    "chargetime_max":72,
                    "charge_retain":true,
                    "holdRepeat":true,
                    "chargeInAir":false,
                    "reenableTimer":3,
                    "useChargeBar":false,
                    "attackSound1_id":"samus_charge",
                    "attackSound2_id":"samus_shot1",
                    "attackSound3_id":"samus_shot2",
                    "attackSound4_id":"samus_shot3",
                    "attackSound5_id":"samus_shot4",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "kirby_sheik":{
                    "parentAttack":"b",
                    "cancelWhenAirborne":false,
                    "chargetime_max":61,
                    "charge_retain":true,
                    "customChargeGlow":null,
                    "useChargeBar":false,
                    "attackVoice1_id":"sheik_needle",
                    "attackSound1_id":"sheik_needle_charge",
                    "attackSound2_id":"sheik_needle_throw",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":1,
                            "hitStun":1,
                            "selfHitStun":1,
                            "direction":30,
                            "power":90,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                },
                "kirby_sora":{
                    "parentAttack":"b",
                    "cancelWhenAirborne":false,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":5,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":0,
                            "power":0,
                            "kbConstant":1,
                            "shock":true,
                            "effectSound":null
                        }}
                },
                "kirby_sonic":{
                    "parentAttack":"b",
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "reenableTimer":60,
                    "attackVoice1_id":"kirby_sonic",
                    "attackSound1_id":"sonic_rev",
                    "attackSound2_id":"new_sonic_homing",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":35,
                            "power":45,
                            "kbConstant":70,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "kirby_tails":{
                    "parentAttack":"b",
                    "refreshRate":100,
                    "canFallOff":false,
                    "chargeInAir":false,
                    "canUseInAir":true,
                    "attackVoice1_id":"kirby_grunt1",
                    "attackSound1_id":"tails_bshot",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":0,
                            "kbConstant":16,
                            "effectSound":"sw_strongslash"
                        }}
                },
                "kirby_wario":{
                    "parentAttack":"b",
                    "refreshRate":999,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargeInAir":false,
                    "xSpeedDecay":0.01,
                    "attackVoice1_id":"kirby_wario1",
                    "attackVoice2_id":"kirby_wario2",
                    "attackSound1_id":"wario_chomp",
                    "attackSound2_id":"wario_bite",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "hasEffect":false,
                            "priority":7,
                            "hitStun":1,
                            "hitLag":-2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":10,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":70,
                            "bypassShield":true,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "kirby_Yoshi":{
                    "parentAttack":"b",
                    "refreshRate":100,
                    "cancelWhenAirborne":false,
                    "conserveJumpConstant":false,
                    "allowControl":true,
                    "allowControlGround":false,
                    "canFallOff":false,
                    "allowFastFall":false,
                    "attackVoice1_id":"kirby_yoshi1",
                    "attackVoice2_id":"kirby_yoshi2",
                    "attackSound1_id":"Yoshi_nspecial_sfx",
                    "attackSound2_id":"Yoshi_swallow",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":-1,
                            "hitStun":3,
                            "selfHitStun":6,
                            "direction":45,
                            "power":50,
                            "kbConstant":10,
                            "egg":true,
                            "bypassNonGrabbed":true,
                            "effectSound":"Yoshi_layegg"
                        }}
                },
                "kirby_zamus":{
                    "parentAttack":"b",
                    "isLongRangeMove":true,
                    "reenableTimer":3,
                    "attackSound1_id":"zamus_nspec_charge",
                    "attackSound2_id":"zamus_nspec",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "kirby_zelda":{
                    "parentAttack":"b",
                    "refreshRate":5,
                    "air_ease":3,
                    "attackVoice1_id":null,
                    "attackSound1_id":"zelda_nayru",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":0,
                            "direction":25,
                            "power":0,
                            "kbConstant":60,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox2":{
                            "damage":3,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":0,
                            "direction":25,
                            "power":0,
                            "kbConstant":60,
                            "effectSound":"brawl_kick_s"
                        },
                        "attackBox3":{
                            "hasEffect":false,
                            "reverse_projectile":true
                        },
                        "attackBox4":{
                            "damage":3,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":0,
                            "direction":25,
                            "power":0,
                            "kbConstant":60,
                            "effectSound":"brawl_kick_s"
                        }
                    }
                }
            };
            var _local_4:Object = {"kirby_swordwave":{
                    "linkage_id":"kirby_swordwave",
                    "width":27,
                    "height":33,
                    "time_max":8,
                    "xspeed":20,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":5,
                                "priority":0,
                                "hitStun":1,
                                "selfHitStun":0,
                                "effect_id":"effect_swordSlash",
                                "direction":60,
                                "power":50,
                                "kbConstant":75,
                                "effectSound":"sw_swipe"
                            }}}
                }};
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("kirby");
        }

        public function getGUID():String
        {
            return ("5f670bf6-edee-4bbf-b247-3a51d5ebddd3");
        }

        public function __setPerspectiveProjection_(_arg_1:Event):void
        {
            root.transform.perspectiveProjection.fieldOfView = 55;
            root.transform.perspectiveProjection.projectionCenter = new Point(275, 200);
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package kirby_fla

