// Decompiled by AS3 Sorcerer 6.20
// www.as3sorcerer.com

//chibirobo_fla.MainTimeline

package chibirobo_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function getAudio():Array
        {
            return (new Array(chibi_AStep, chibi_BStep, chibi_DStep, chibi_EStep, chibi_GStep, chibi_Bend, chibi_CloseHead, chibi_OpenHead, chibi_StoreItem, chibi_Jump, chibi_Turn, chibi_LedgeClimb, chibi_Prop_Quick, chibi_Prop_Release, chibi_ItemOnHead, chibi_GrabRope, chibi_Spoon1, chibi_Spoon2, chibi_Spoon3, chibi_Spoon4, chibi_dSpec_grab, chibi_Confirm, chibi_DropPlug, chibi_PlugIn, chibi_PikaShock));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"chibirobo",
                "displayName":"Chibi-Robo",
                "linkage_id":"chibirobo",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"chibi_head",
                "seriesIcon":"chibi_icon",
                "width":31,
                "height":45,
                "revivalEffect":null,
                "jumpSpeed":17,
                "jumpSpeedMidair":17,
                "jumpStartup":2,
                "shortHopSpeed":11,
                "max_jumpSpeed":7.5,
                "dodgeSpeed":8,
                "gravity":1.6,
                "weight1":82,
                "power":"chibirobo",
                "norm_xSpeed":5.5,
                "max_xSpeed":9,
                "max_ySpeed":13.5,
                "fastFallSpeed":16,
                "accel_start":1,
                "accel_start_dash":1.55,
                "accel_rate":1,
                "accel_rate_air":0.7,
                "decel_rate":-1.5,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":60,
                "tetherGrab":false,
                "roll_speed":25,
                "roll_delay":5,
                "getup_roll_delay":0,
                "itemScaleRatio":0.769230769230769,
                "special_type":1,
                "normalStats_id":"chibirobo",
                "specialStats_id":null,
                "sounds":{
                    "jump":"chibi_Jump",
                    "jump_midair":"chibi_Jump",
                    "hurt":null,
                    "hurt2":null,
                    "hurtBad":null,
                    "hurtBad2":null,
                    "dead":null,
                    "dead2":null,
                    "pummel":"brawl_zap_s",
                    "screenko":null,
                    "starko":null,
                    "ledge_grab":null,
                    "winTheme":"chibiVictory"
                },
                "hurtFrames":4,
                "grabDamage":1,
                "fs_time_limit":500
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_s",
                    "attackSound2_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":45,
                            "power":5,
                            "kbConstant":100,
                            "stackKnockback":false,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "a_up":{
                    "refreshRate":30,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"chibi_PichuAttack",
                    "attackSound2_id":"chibi_PlugIn",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "effectSound":"brawl_zap_m",
                            "shock":true,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":90,
                            "power":50,
                            "kbConstant":20,
                            "effectSound":"brawl_fire_s"
                        }}
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackSound1_id":"chibi_ItemOnHead",
                    "cpuAttackQueue":"a_up;a_up_tilt;a_air;a_air_forward;a_air_backward;a_air_up;a_air_down;throw_down",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":9,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":100,
                            "power":55,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":2,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":100,
                            "power":55,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forward":{
                    "canFallOff":false,
                    "attackSound1_id":"chibi_GrabRope",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":2,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":70,
                            "power":50,
                            "kbConstant":60,
                            "effectSound":"brawl_punch_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":3,
                            "shock":true,
                            "hitStun":4,
                            "hitLag":-1,
                            "selfHitStun":4,
                            "effect_id":"effect_hit2",
                            "direction":35,
                            "power":40,
                            "kbConstant":90,
                            "effectSound":"brawl_zap_m"
                        }
                    }
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "refreshRate":2,
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "shock":true,
                            "effect_id":"effect_hit1",
                            "direction":40,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"brawl_zap_s"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"chibi_FSmash",
                    "attackSound2_id":"chibi_FSmash2",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "shock":true,
                            "reversableAngle":false,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":340,
                            "power":30,
                            "kbConstant":50,
                            "effectSound":"brawl_zap_s"
                        }}
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackSound1_id":"chibi_PlugIn",
                    "attackSound2_id":"chibi_PikaShock",
                    "attackBoxes":{
                        "attackBox":{
                            "shock":true,
                            "damage":15,
                            "priority":-1,
                            "hitStun":6,
                            "selfHitStun":6,
                            "effect_id":"effect_hit1",
                            "direction":90,
                            "power":90,
                            "kbConstant":67,
                            "effectSound":"brawl_zap_l"
                        },
                        "attackBox2":{
                            "shock":true,
                            "damage":10,
                            "priority":-1,
                            "hitStun":4,
                            "selfHitStun":4,
                            "effect_id":"effect_hit1",
                            "direction":60,
                            "power":50,
                            "kbConstant":75,
                            "effectSound":"brawl_zap_m"
                        }
                    }
                },
                "a_air":{
                    "allowControl":true,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":40,
                            "kbConstant":75,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":6,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "hitLag":-1.1,
                            "effect_id":"effect_hit2",
                            "direction":60,
                            "power":30,
                            "kbConstant":60,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_up":{
                    "allowControl":true,
                    "attackSound1_id":"bat_swing",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":3,
                            "hitStun":7,
                            "selfHitStun":4,
                            "effect_id":"effect_swordSlash",
                            "direction":90,
                            "power":50,
                            "kbConstant":115,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "a_air_forward":{
                    "allowControl":true,
                    "attackSound1_id":"sw_brawl_swing_M",
                    "cpuAttackQueue":"a_air;a_air_down",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "hitLag":-1.05,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":1,
                            "effect_id":"effect_swordSlash",
                            "direction":62,
                            "power":52,
                            "kbConstant":80,
                            "effectSound":"brawl_punch_l"
                        }}
                },
                "a_air_backward":{
                    "allowControl":true,
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":14,
                            "priority":4,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":40,
                            "power":20,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "a_air_down":{
                    "allowControl":true,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":13,
                            "priority":5,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":270,
                            "power":50,
                            "kbConstant":100,
                            "shock":true,
                            "effectSound":"brawl_zap_m"
                        }}
                },
                "b":{
                    "isLongRangeMove":true,
                    "attackSound1_id":"chibi_Spoon1",
                    "attackSound2_id":"chibi_Spoon2",
                    "attackSound3_id":"chibi_Spoon3",
                    "attackSound4_id":"chibi_Spoon4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":"brawl_magic_s"
                        }}
                },
                "b_air":{
                    "isLongRangeMove":true,
                    "allowFastFall":false,
                    "attackSound1_id":"chibi_Spoon1",
                    "attackSound2_id":"chibi_Spoon2",
                    "attackSound3_id":"chibi_Spoon3",
                    "attackSound4_id":"chibi_Spoon4",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":"brawl_magic_s"
                        }}
                },
                "b_up":{
                    "refreshRate":2,
                    "cancelWhenAirborne":false,
                    "xSpeedAccelAir":2,
                    "air_ease":0,
                    "xSpeedCap":3.4,
                    "attackSound1_id":"chibi_Prop_Release",
                    "attackSound2_id":"chibi_Prop_Quick",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":55,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "b_up_air":{
                    "refreshRate":2,
                    "cancelWhenAirborne":false,
                    "xSpeedAccelAir":1.1,
                    "air_ease":2.3,
                    "xSpeedCap":5.87,
                    "allowControl":true,
                    "isRecoveryMove":true,
                    "attackSound1_id":"chibi_Prop_Release",
                    "attackSound2_id":"chibi_Prop_Quick",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":90,
                            "power":55,
                            "kbConstant":10,
                            "stackKnockback":false,
                            "effectSound":"sw_brawl_hit_S"
                        }}
                },
                "b_forward":{
                    "cancelSoundOnEnd":true,
                    "canFallOff":true,
                    "air_ease":2,
                    "cancelWhenAirborne":false,
                    "attackSound1_id":"chibi_Toothbrush",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_hit1",
                            "direction":20,
                            "power":40,
                            "kbConstant":30,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "b_forward_air":{
                    "cancelSoundOnEnd":true,
                    "isHorizontalRecoveryMove":true,
                    "canFallOff":true,
                    "air_ease":2,
                    "cancelWhenAirborne":false,
                    "attackSound1_id":"chibi_Toothbrush",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":3,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_hit1",
                            "direction":20,
                            "power":40,
                            "kbConstant":30,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "b_down":{
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "allowControlGround":false,
                    "allowFastFall":false,
                    "attackSound1_id":"chibi_pickplug",
                    "attackSound2_id":"chibi_dSpec_grab",
                    "attackSound3_id":"chibi_Confirm",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":20,
                            "kbConstant":16,
                            "effectSound":"kick"
                        }}
                },
                "b_down_air":{
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "allowControlGround":false,
                    "attackSound1_id":"chibi_pickplug",
                    "attackSound2_id":"chibi_dSpec_grab",
                    "attackSound3_id":"chibi_Confirm",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":80,
                            "power":20,
                            "kbConstant":16,
                            "effectSound":"kick"
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackSound1_id":"chibi_squirter",
                    "cpuAttackQueue":"a_air_up;a_air",
                    "attackBoxes":{"attackBox":{
                            "damage":3,
                            "hitLag":-1.12,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":2,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":85,
                            "reversableAngle":false,
                            "power":25,
                            "kbConstant":100,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "throw_forward":{
                    "refreshRate":10,
                    "canFallOff":false,
                    "attackSound1_id":null,
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_heavyHit",
                            "direction":42,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":55,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackSound1_id":null,
                    "cpuAttackQueue":"a_air;throw_back;throw_down;a_air_backward",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":0,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":135,
                            "reversableAngle":false,
                            "power":60,
                            "kbConstant":60,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "throw_down":{
                    "refreshRate":3,
                    "canFallOff":false,
                    "attackSound1_id":"chibi_DThrow",
                    "cpuAttackQueue":"a_up_tilt;a_up;a_down;a_air;a_air_up;a_air_backward",
                    "attackBoxes":{"attackBox":{
                            "hasEffect":false,
                            "damage":1,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":100,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":30,
                            "bypassNonGrabbed":true,
                            "effectSound":null
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":null,
                    "attackSound1_id":"chibi_DropPlug",
                    "cpuAttackQueue":"a_forward_tilt;a_forwardsmash;a_air;a_air_forward",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":70,
                            "power":30,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_s"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":40,
                            "power":130,
                            "kbConstant":40,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "kirby":{
                    "cancelSoundOnEnd":true,
                    "allowControl":true,
                    "chargetime_max":72,
                    "charge_retain":true,
                    "holdRepeat":true,
                    "chargeInAir":false,
                    "reenableTimer":3,
                    "useChargeBar":false,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "cancelSoundOnEnd":true,
                    "allowControl":true,
                    "allowControlGround":false,
                    "chargetime_max":72,
                    "charge_retain":true,
                    "holdRepeat":true,
                    "chargeInAir":false,
                    "reenableTimer":3,
                    "useChargeBar":false,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackSound1_id":"giga_summon",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":-1,
                            "selfHitStun":-1,
                            "direction":0,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object = {
                "chibi_blaster":{
                    "linkage_id":"chibi_lazor",
                    "rotate":true,
                    "time_max":10,
                    "xspeed":24,
                    "xoffset":30,
                    "yoffset":-24,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "damage":2,
                                "hasEffect":true,
                                "priority":-1,
                                "hitStun":3,
                                "shock":true,
                                "hitLag":-0.5,
                                "selfHitStun":1,
                                "effect_id":"blasterhit",
                                "direction":-9,
                                "power":15,
                                "kbConstant":15,
                                "effectSound":null
                            }}}
                },
                "telly_vision":{
                    "linkage_id":"telly_vision",
                    "canBeReversed":false,
                    "ghost":true,
                    "dangerous":false,
                    "limit":1,
                    "time_max":-1,
                    "xoffset":30,
                    "yoffset":-24,
                    "surviveDeathBounds":true,
                    "inheritPalette":true
                },
                "gigarobo":{
                    "linkage_id":"gigarobo",
                    "limit":1,
                    "canBeReversed":false,
                    "time_max":999,
                    "gravity":2,
                    "maxgravity":13,
                    "surviveDeathBounds":false,
                    "attack_idle":{"attackBoxes":{
                            "attackBox":{
                                "damage":12,
                                "hasEffect":true,
                                "priority":-1,
                                "hitStun":5,
                                "hitLag":-1,
                                "selfHitStun":4,
                                "effect_id":"effect_heavyHit",
                                "direction":270,
                                "power":80,
                                "kbConstant":90,
                                "pitfall":20
                            },
                            "attackBox2":{
                                "damage":12,
                                "hasEffect":true,
                                "priority":-1,
                                "hitStun":5,
                                "hitLag":-1,
                                "selfHitStun":4,
                                "effect_id":"effect_heavyHit",
                                "direction":270,
                                "power":80,
                                "kbConstant":90,
                                "pitfall":20
                            }
                        }}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("chibirobo");
        }

        public function getGUID():String
        {
            return ("c51a5173-a652-4c9a-9410-87b46e9702c3");
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package chibirobo_fla

