// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//zamus_fla.MainTimeline

package zamus_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function getAudio():Array
        {
            return (new Array(zamus_tether, zamus_dspec, zamus_isThatAll, zamus_tryMe, zamus_youreMine, zamus_grunt1, zamus_grunt2, zamus_grunt3, zamus_grunt4, zamus_fsmash_vfx, zamus_usmash_vfx, zamus_dsmash_vfx, zamus_hurt, zamus_hurt2, zamus_hurtBad, zamus_hurtBad2, zamus_dizzy, zamus_sleep, zamus_dead, zamus_dead2, zamus_starko, zamus_usmash, zamus_uspec, zamus_nair, zamus_sspec, zamus_fsmash, zamus_grab, zamus_turn, zamus_jump, zamus_jump2, zamus_nspec, zamus_kick, zamus_swing_l, zamus_swing_m, zamus_swing_s, zamus_nspec_charge, zamus_dsmash, zamus_dair_start, zamus_dair_drop, zamus_dair_land, zamus_beStill));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"zamus",
                "displayName":"Zero%20Suit%20Samus",
                "linkage_id":"zamus",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"zamus_head",
                "seriesIcon":"Series_Metroid",
                "width":30,
                "height":67,
                "revivalEffect":null,
                "jumpSpeed":18.2,
                "jumpSpeedMidair":19,
                "jumpStartup":2,
                "shortHopSpeed":8,
                "max_jumpSpeed":9,
                "dodgeSpeed":6,
                "gravity":1.2,
                "weight1":85,
                "power":"zamus",
                "norm_xSpeed":5.5,
                "max_xSpeed":11,
                "max_ySpeed":12,
                "fastFallSpeed":16,
                "accel_start":0.59,
                "accel_start_dash":1.135,
                "accel_rate":1,
                "accel_rate_air":0.8,
                "decel_rate":-1.52,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":60,
                "tetherGrab":false,
                "roll_speed":32,
                "roll_delay":4,
                "getup_roll_delay":2,
                "itemScaleRatio":0.769230769230769,
                "special_type":1,
                "normalStats_id":"zamus",
                "sounds":{
                    "jump":"zamus_jump",
                    "jump_midair":"zamus_jump2",
                    "hurt":"zamus_hurt",
                    "hurt2":"zamus_hurt2",
                    "hurtBad":"zamus_hurtBad",
                    "hurtBad2":"zamus_hurtBad2",
                    "dead":"zamus_dead",
                    "dead2":"zamus_dead2",
                    "pummel":"brawl_kick_s",
                    "screenko":"zamus_hurtBad",
                    "starko":"zamus_starko",
                    "ledge_grab":"zamus_tether",
                    "winTheme":"MetroidVictory"
                },
                "hurtFrames":4,
                "grabDamage":1
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "refreshRate":100,
                    "combo_max":2,
                    "canFallOff":false,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_swing_s",
                    "attackSound2_id":"zamus_swing_m",
                    "attackSound3_id":"zamus_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":2,
                            "priority":1,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":61,
                            "power":3,
                            "kbConstant":120,
                            "stackKnockback":false,
                            "effectSound":"brawl_punch_s"
                        }}
                },
                "a_up":{
                    "refreshRate":30,
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"zamus_usmash_vfx",
                    "attackSound1_id":"zamus_usmash",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":1,
                            "priority":4,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_firehit1",
                            "direction":110,
                            "reversableAngle":false,
                            "power":90,
                            "kbConstant":20,
                            "canDI":false,
                            "effectSound":"brawl_zap_s"
                        },
                        "attackBox2":{
                            "damage":4,
                            "priority":4,
                            "hitStun":1,
                            "selfHitStun":1,
                            "effect_id":"effect_firehit1",
                            "direction":110,
                            "reversableAngle":false,
                            "power":90,
                            "kbConstant":20,
                            "canDI":false,
                            "effectSound":"brawl_zap_m"
                        }
                    }
                },
                "a_up_tilt":{
                    "cancelWhenAirborne":false,
                    "canFallOff":false,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_swing_m",
                    "attackSound2_id":"zamus_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":5,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":120,
                            "power":37,
                            "kbConstant":46,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox2":{
                            "damage":5,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":130,
                            "power":50,
                            "kbConstant":46,
                            "effectSound":"sw_brawl_hit_S"
                        },
                        "attackBox3":{
                            "damage":5,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":80,
                            "power":37,
                            "kbConstant":55,
                            "effectSound":"sw_brawl_hit_S"
                        }
                    }
                },
                "a_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.2,
                            "selfHitStun":2,
                            "effect_id":"effect_lightHit",
                            "direction":50,
                            "power":110,
                            "kbConstant":20,
                            "effectSound":"brawl_punch_m"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":4,
                            "hitStun":2,
                            "hitLag":-1.3,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"zamus_fsmash_vfx",
                    "attackSound1_id":"zamus_fsmash",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":10,
                            "priority":4,
                            "chargedPriority":6,
                            "hitStun":5,
                            "selfHitStun":3,
                            "effect_id":"effect_hit3",
                            "direction":40,
                            "power":55,
                            "kbConstant":110,
                            "effectSound":"brawl_zap_l"
                        },
                        "attackBox2":{
                            "damage":8,
                            "priority":4,
                            "chargedPriority":6,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":40,
                            "power":50,
                            "kbConstant":90,
                            "effectSound":"brawl_zap_m"
                        }
                    }
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"zamus_dsmash_vfx",
                    "attackSound1_id":"zamus_dsmash",
                    "cpuAttackQueue":"a_down; a_forwardsmash; a_air",
                    "attackBoxes":{"attackBox":{
                            "paralysis":30,
                            "damage":11,
                            "priority":6,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":75,
                            "power":40,
                            "kbConstant":50,
                            "effectSound":"brawl_zap_m"
                        }}
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_nair",
                    "cpuAttackQueue":"a_air; a_air_forward; b_forward",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":5,
                            "hitStun":6,
                            "hitLag":-1,
                            "selfHitStun":3,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":60,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":9,
                            "priority":5,
                            "hitStun":8,
                            "hitLag":-1,
                            "selfHitStun":5,
                            "effect_id":"effect_hit2",
                            "direction":45,
                            "power":60,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_kick",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":5,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":80,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"sw_brawl_hit_M"
                        }}
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_swing_m",
                    "cpuAttackQueue":"a_air_up; a_air; b; b_forward",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":7,
                            "priority":4,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "power":35,
                            "kbConstant":85,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":10,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":50,
                            "power":40,
                            "kbConstant":110,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":13,
                            "priority":5,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":40,
                            "power":33,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":5,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":40,
                            "power":33,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }
                    }
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":false,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_dair_start",
                    "attackSound2_id":"zamus_dair_drop",
                    "attackSound3_id":"zamus_dair_land",
                    "disableForCPU":true,
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":5,
                            "hitStun":4,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":275,
                            "power":45,
                            "kbConstant":90,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "b":{
                    "linkFrames":true,
                    "isLongRangeMove":true,
                    "reenableTimer":3,
                    "attackSound1_id":"zamus_nspec_charge",
                    "attackSound2_id":"zamus_nspec",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "linkFrames":true,
                    "isLongRangeMove":true,
                    "reenableTimer":3,
                    "attackSound1_id":"zamus_nspec_charge",
                    "attackSound2_id":"zamus_nspec",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "refreshRate":90,
                    "cancelWhenAirborne":false,
                    "isRecoveryMove":true,
                    "attackSound1_id":"zamus_uspec",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "canDI":false,
                            "reversableAngle":false,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_lightHit",
                            "direction":110,
                            "power":95,
                            "kbConstant":50,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_zap_s"
                        }}
                },
                "b_up_air":{
                    "refreshRate":90,
                    "isRecoveryMove":true,
                    "attackSound1_id":"zamus_uspec",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "canDI":false,
                            "reversableAngle":false,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":3,
                            "effect_id":"effect_lightHit",
                            "direction":110,
                            "power":95,
                            "kbConstant":50,
                            "stackKnockback":false,
                            "shock":true,
                            "effectSound":"brawl_zap_s"
                        }}
                },
                "b_forward":{
                    "canFallOff":false,
                    "isLongRangeMove":true,
                    "attackSound1_id":"zamus_sspec",
                    "attackBoxes":{
                        "attackBox":{
                            "shock":true,
                            "damage":3,
                            "priority":5,
                            "hitStun":5,
                            "selfHitStun":4,
                            "effect_id":"effect_hit3",
                            "direction":15,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_s"
                        },
                        "attackBox2":{
                            "shock":true,
                            "damage":3,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":15,
                            "reversableAngle":false,
                            "power":40,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_s"
                        },
                        "attackBox3":{
                            "shock":true,
                            "damage":3,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":15,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_s"
                        }
                    }
                },
                "b_forward_air":{
                    "attackSound1_id":"zamus_sspec",
                    "isLongRangeMove":true,
                    "attackBoxes":{
                        "attackBox":{
                            "shock":true,
                            "damage":3,
                            "priority":5,
                            "hitStun":5,
                            "selfHitStun":4,
                            "effect_id":"effect_hit3",
                            "direction":15,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_s"
                        },
                        "attackBox2":{
                            "shock":true,
                            "damage":3,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":15,
                            "reversableAngle":false,
                            "power":40,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_s"
                        },
                        "attackBox3":{
                            "shock":true,
                            "damage":3,
                            "priority":5,
                            "hitStun":3,
                            "selfHitStun":2,
                            "effect_id":"effect_hit3",
                            "direction":15,
                            "reversableAngle":false,
                            "power":30,
                            "kbConstant":30,
                            "effectSound":"brawl_zap_s"
                        }
                    }
                },
                "b_down":{
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "allowFastFall":false,
                    "attackSound1_id":"zamus_dair_drop",
                    "attackSound2_id":"zamus_kick",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":-1,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":270,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "b_down_air":{
                    "resetMovement":true,
                    "isHorizontalRecoveryMove":true,
                    "cancelWhenAirborne":false,
                    "allowFastFall":false,
                    "attackSound1_id":"zamus_dair_drop",
                    "attackSound2_id":"zamus_kick",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":-1,
                            "hitStun":4,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":270,
                            "power":60,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_swing_m",
                    "cpuAttackQueue":"a_air; a_air_forward; a_air_up; a_air_backward",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":2,
                            "hitLag":-1.1,
                            "selfHitStun":0,
                            "effect_id":null,
                            "direction":88,
                            "reversableAngle":false,
                            "power":15,
                            "kbConstant":0,
                            "bypassNonGrabbed":true,
                            "effectSound":null
                        }}
                },
                "throw_forward":{
                    "refreshRate":10,
                    "canFallOff":false,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":null,
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":1,
                            "selfHitStun":0,
                            "effect_id":null,
                            "direction":45,
                            "reversableAngle":false,
                            "power":45,
                            "kbConstant":130,
                            "shock":true,
                            "bypassNonGrabbed":true,
                            "effectSound":null
                        }}
                },
                "throw_back":{
                    "flip":true,
                    "canFallOff":false,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":2,
                            "effect_id":null,
                            "direction":50,
                            "reversableAngle":false,
                            "power":100,
                            "kbConstant":35,
                            "bypassNonGrabbed":true,
                            "effectSound":null
                        }}
                },
                "throw_down":{
                    "canFallOff":false,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":0,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":50,
                            "reversableAngle":false,
                            "power":100,
                            "kbConstant":35,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":6,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":75,
                            "power":65,
                            "kbConstant":70,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "maintainSpeed":true,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":2,
                            "hitStun":3,
                            "selfHitStun":0,
                            "effect_id":"effect_hit2",
                            "direction":40,
                            "power":40,
                            "kbConstant":100,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "getup_attack":{
                    "resetMovement":true,
                    "canFallOff":false,
                    "attackVoice1_id":"zamus_grunt1",
                    "attackVoice2_id":"zamus_grunt2",
                    "attackVoice3_id":"zamus_grunt3",
                    "attackVoice4_id":"zamus_grunt4",
                    "attackSound1_id":"zamus_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":4,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":45,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"brawl_kick_m"
                        }}
                },
                "kirby":{
                    "cancelSoundOnEnd":true,
                    "linkFrames":true,
                    "reenableTimer":3,
                    "attackSound1_id":"zamus_nspec_charge",
                    "attackSound2_id":"zamus_nspec",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "cancelSoundOnEnd":true,
                    "linkFrames":true,
                    "reenableTimer":3,
                    "attackSound1_id":"zamus_nspec_charge",
                    "attackSound2_id":"zamus_nspec",
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":3,
                            "selfHitStun":0,
                            "direction":10,
                            "power":30,
                            "kbConstant":16,
                            "effectSound":null
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "refreshRate":4,
                    "cancelWhenAirborne":false,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackSound1_id":"zamus_fs1",
                    "attackSound2_id":"zamus_fs2",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":0,
                            "priority":-1,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":170,
                            "hasEffect":false,
                            "power":60,
                            "kbConstant":80,
                            "effectSound":null
                        },
                        "attackBox2":{
                            "damage":0,
                            "priority":-1,
                            "hitStun":2,
                            "selfHitStun":0,
                            "direction":-6,
                            "hasEffect":false,
                            "power":60,
                            "kbConstant":80,
                            "effectSound":null
                        }
                    }
                }
            };
            var _local_4:Object = {
                "paralyzer_weak":{
                    "linkage_id":"zamus_pshot_weak",
                    "width":11,
                    "height":4,
                    "time_max":11,
                    "xspeed":8,
                    "rideGround":false,
                    "xoffset":22,
                    "yoffset":-34,
                    "limit":2,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "paralysis":10,
                                "damage":4,
                                "priority":-1,
                                "hitStun":1,
                                "selfHitStun":-1,
                                "effect_id":"effect_hit3",
                                "direction":50,
                                "power":0,
                                "kbConstant":100,
                                "shock":true,
                                "effectSound":"brawl_zap_m"
                            }}}
                },
                "paralyzer_strong":{
                    "linkage_id":"zamus_pshot_strong",
                    "width":11,
                    "height":4,
                    "time_max":21,
                    "xspeed":10,
                    "rideGround":false,
                    "xoffset":22,
                    "yoffset":-34,
                    "limit":2,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "paralysis":20,
                                "damage":6,
                                "priority":-1,
                                "hitStun":1,
                                "weightKB":38,
                                "selfHitStun":-1,
                                "effect_id":"effect_hit3",
                                "direction":50,
                                "power":0,
                                "kbConstant":100,
                                "shock":true,
                                "effectSound":"brawl_zap_m"
                            }}}
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "iData":_local_5,
                "pData":_local_4
            });
        }

        public function getID():String
        {
            return ("zamus");
        }

        public function getGUID():String
        {
            return ("1ce8dafd-54ea-480a-a2d0-30c1e6db4dbf");
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package zamus_fla

