// Decompiled by AS3 Sorcerer 6.30
// www.as3sorcerer.com

//mario_fla.MainTimeline

package mario_fla
{
    import flash.display.MovieClip;
    import com.mcleodgaming.ssf2api.core.SSF2API;
    import flash.system.Security;

    public dynamic class MainTimeline extends MovieClip 
    {

        public function MainTimeline()
        {
            addFrameScript(0, this.frame1);
        }

        public function getAudio():Array
        {
            return (new Array(coin, fireball, fsmash_sfx, jump_common, letsago, mario_cape, mario_charge, mario_dead, mario_dead2, mario_dizzy, mario_doublejumpsfx, mario_Dsmash, mario_finale, mario_footstep, mario_fscream, mario_Fsmash, mario_fsready, mario_grow1, mario_grow2, mario_grunt1, mario_grunt2, mario_grunt3, mario_grunt4, mario_ha, mario_hammer, mario_hammer_fire, mario_heeyah, mario_herewego, mario_hoo, mario_hoo_old, mario_hurt, mario_hurt2, mario_hurtBad, mario_hurtBad2, mario_jumpsfx, mario_kick, mario_kick_l, mario_lift, mario_powerup2, mario_punch, mario_spin, mario_star, mario_tauntSide, mario_Usmash, mario_whip, mario_woohoo, mario_yahoo, pipe, Run_start, special_dash_fire, super_jump_punch));
        }

        public function getChar1(_arg_1:Object):Object
        {
            var _local_2:Object = new Object();
            _local_2 = {
                "statsName":"mario",
                "displayName":"Mario",
                "linkage_id":"mario",
                "linkage_id2":null,
                "linkage_id_special":null,
                "thumbnail":"mario_head",
                "seriesIcon":"Mario_Symbol",
                "width":26,
                "height":45,
                "jumpSpeed":15.4,
                "jumpSpeedMidair":15.4,
                "jumpStartup":2,
                "shortHopSpeed":7.7,
                "max_jumpSpeed":7,
                "dodgeSpeed":8,
                "gravity":1.1,
                "weight1":100,
                "power":"mario",
                "norm_xSpeed":4,
                "max_xSpeed":10,
                "max_ySpeed":13,
                "fastFallSpeed":16,
                "accel_start":1.07,
                "accel_start_dash":1.25,
                "accel_rate":1.1,
                "accel_rate_air":0.7,
                "decel_rate":-1.04,
                "decel_rate_air":-0.15,
                "holdJump":false,
                "max_jump":1,
                "max_projectile":10,
                "tetherGrab":false,
                "roll_speed":22,
                "roll_delay":7,
                "getup_roll_delay":0,
                "itemScaleRatio":0.6212,
                "special_type":1,
                "normalStats_id":"mario",
                "specialStats_id":"mario_special",
                "sounds":{
                    "jump":null,
                    "jump_midair":"mario_woohoo",
                    "hurt":"mario_hurt",
                    "hurt2":"mario_hurt2",
                    "hurtBad":"mario_hurtBad",
                    "hurtBad2":"mario_hurtBad2",
                    "dead":"mario_dead",
                    "dead2":"mario_dead2",
                    "pummel":"punch3",
                    "screenko":"mario_hurtBad",
                    "starko":"mario_star",
                    "ledge_grab":null,
                    "winTheme":"MarioVictory"
                },
                "hurtFrames":3,
                "grabDamage":1
            };
            var _local_3:Object = new Object();
            _local_3 = {
                "a":{
                    "canFallOff":false,
                    "attackVoice1_id":"mario_grunt2",
                    "attackVoice2_id":"mario_grunt3",
                    "attackVoice3_id":"mario_grunt4",
                    "attackVoice4_id":"mrio_grunt5",
                    "attackSound1_id":"brawl_swing_l",
                    "attackSound2_id":"brawl_swing_l",
                    "attackSound3_id":"brawl_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":3,
                            "priority":1,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":80,
                            "weightKB":20,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_s"
                        },
                        "attackBox2":{
                            "damage":3,
                            "priority":1,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":80,
                            "weightKB":20,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"brawl_punch_s"
                        }
                    }
                },
                "a_up":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"mario_Usmash",
                    "attackSound1_id":null,
                    "attackSound2_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":16,
                            "priority":5,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":75,
                            "power":35,
                            "kbConstant":95,
                            "effectSound":"punch3"
                        },
                        "attackBox2":{
                            "damage":18,
                            "priority":5,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":83,
                            "power":35,
                            "kbConstant":95,
                            "effectSound":"punch3"
                        },
                        "attackBox3":{
                            "damage":18,
                            "priority":5,
                            "hitStun":2,
                            "hitLag":-1,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":83,
                            "power":35,
                            "kbConstant":95,
                            "effectSound":"punch3"
                        }
                    }
                },
                "a_up_tilt":{
                    "canFallOff":false,
                    "attackVoice1_id":"mario_grunt1",
                    "attackVoice2_id":"mario_grunt2",
                    "attackVoice3_id":"mario_grunt3",
                    "attackVoice4_id":"mario_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "cpuAttackQueue":"a_up_tilt;a_up_smash;a_air_up;throw_down;throw_up",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":96,
                            "power":26,
                            "kbConstant":125,
                            "effectSound":"mario_kick_l"
                        }}
                },
                "a_forward":{
                    "xSpeedDecay":-1.35,
                    "canFallOff":false,
                    "attackVoice1_id":"mario_grunt1",
                    "attackVoice2_id":"mario_grunt2",
                    "attackVoice3_id":"mario_grunt3",
                    "attackVoice4_id":"mario_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "cpuAttackQueue":"a_air;a_air_up;a_up_tilt;a_forwardsmash",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":75,
                            "power":70,
                            "kbConstant":50,
                            "effectSound":"punch2"
                        }}
                },
                "a_forward_tilt":{
                    "canFallOff":false,
                    "allowFastFall":false,
                    "attackVoice1_id":"mario_grunt1",
                    "attackVoice2_id":"mario_grunt2",
                    "attackVoice3_id":"mario_grunt3",
                    "attackVoice4_id":"mario_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "attackBoxes":{"attackBox":{
                            "damage":7,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_hit1",
                            "direction":40,
                            "power":10,
                            "kbConstant":100,
                            "effectSound":"mario_kick"
                        }}
                },
                "a_forwardsmash":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"mario_Fsmash",
                    "attackSound1_id":"fsmash_sfx",
                    "attackSound2_id":"brawl_swing_m",
                    "attackBoxes":{
                        "attackBox2":{
                            "damage":11,
                            "priority":5,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"effect_hit1",
                            "direction":35,
                            "power":25,
                            "kbConstant":96,
                            "effectSound":"punch2"
                        },
                        "attackBox":{
                            "damage":19,
                            "priority":-1,
                            "hitStun":5,
                            "selfHitStun":2,
                            "effect_id":"fireballexplosion",
                            "direction":47,
                            "power":25,
                            "kbConstant":95,
                            "burn":true,
                            "effectSound":"fire"
                        }
                    }
                },
                "a_down":{
                    "chargetime_max":40,
                    "canFallOff":false,
                    "chargeClick":true,
                    "attackVoice1_id":"mario_Dsmash",
                    "attackSound1_id":"brawl_swing_l",
                    "attackSound2_id":"brawl_swing_s",
                    "attackBoxes":{"attackBox":{
                            "damage":18,
                            "priority":5,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":2,
                            "effect_id":"effect_hit2",
                            "direction":40,
                            "power":25,
                            "kbConstant":95,
                            "effectSound":"ssb_hit2"
                        }}
                },
                "a_air":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"mario_grunt1",
                    "attackVoice2_id":"mario_grunt2",
                    "attackVoice3_id":"mario_grunt3",
                    "attackVoice4_id":"mario_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitStun":5,
                            "hitLag":-1,
                            "selfHitStun":2,
                            "effect_id":"effect_heavyHit",
                            "direction":45,
                            "power":60,
                            "kbConstant":60,
                            "effectSound":"mario_kick_l"
                        }}
                },
                "a_air_up":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"mario_grunt1",
                    "attackVoice2_id":"mario_grunt2",
                    "attackVoice3_id":"mario_grunt3",
                    "attackVoice4_id":"mario_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "cpuAttackQueue":"a_air;a_air;a_air_forward;a_air_backward;a_air_up;a_air_up;a_air_down;b_up_air",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":12,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.25,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":55,
                            "power":11,
                            "kbConstant":100,
                            "effectSound":"mario_kick"
                        },
                        "attackBox2":{
                            "damage":12,
                            "priority":3,
                            "hitStun":3,
                            "hitLag":-1.25,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":55,
                            "power":11,
                            "kbConstant":100,
                            "effectSound":"mario_kick"
                        }
                    }
                },
                "a_air_forward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"mario_yoohoo",
                    "attackSound1_id":"brawl_swing_l",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":14,
                            "priority":6,
                            "hitStun":2,
                            "selfHitStun":1,
                            "hitLag":-1.1,
                            "camShake":2,
                            "effect_id":"effect_heavyHit",
                            "direction":55,
                            "power":15,
                            "kbConstant":110,
                            "effectSound":"mario_kick"
                        },
                        "attackBox2":{
                            "damage":16,
                            "priority":6,
                            "hitStun":4,
                            "selfHitStun":2,
                            "camShake":4,
                            "effect_id":"effect_heavyHit",
                            "direction":330,
                            "power":20,
                            "kbConstant":75,
                            "effectSound":"mario_kick",
                            "reversableAngle":false
                        }
                    }
                },
                "a_air_backward":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"mario_grunt1",
                    "attackVoice2_id":"mario_grunt2",
                    "attackVoice3_id":"mario_grunt3",
                    "attackVoice4_id":"mario_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "cpuAttackQueue":"a_air_backward",
                    "attackBoxes":{"attackBox":{
                            "damage":11,
                            "priority":4,
                            "hitStun":3,
                            "hitLag":-1.1,
                            "selfHitStun":1,
                            "effect_id":"effect_heavyHit",
                            "direction":30,
                            "power":10,
                            "kbConstant":100,
                            "effectSound":"mario_kick"
                        }}
                },
                "a_air_down":{
                    "canFallOff":true,
                    "cancelWhenAirborne":true,
                    "allowControl":true,
                    "attackVoice1_id":"mario_grunt1",
                    "attackVoice2_id":"mario_grunt2",
                    "attackVoice3_id":"mario_grunt3",
                    "attackVoice4_id":"mario_grunt4",
                    "attackSound1_id":"brawl_swing_m",
                    "cpuAttackQueue":"a_air_up;a_up_tilt;throw_up;throw_down;crouch_attack",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":2,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1,
                            "weightKB":30,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":80,
                            "power":70,
                            "kbConstant":10,
                            "effectSound":"mario_kick_l"
                        },
                        "attackBox2":{
                            "damage":2,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1,
                            "weightKB":30,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":80,
                            "power":70,
                            "kbConstant":10,
                            "effectSound":"mario_kick_l"
                        }
                    }
                },
                "b":{
                    "attackSound1_id":"fireball",
                    "linkFrames":true,
                    "isLongRangeMove":true,
                    "cancelWhenAirborne":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":30,
                            "power":0,
                            "kbConstant":1,
                            "burn":true,
                            "effectSound":null
                        }}
                },
                "b_air":{
                    "allowControl":true,
                    "linkFrames":true,
                    "allowControlGround":false,
                    "cancelWhenAirborne":false,
                    "attackSound1_id":"fireball",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":30,
                            "power":0,
                            "kbConstant":1,
                            "burn":true,
                            "effectSound":null
                        }}
                },
                "b_up":{
                    "refreshRate":99,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-0.86,
                    "xSpeedDecayAir":-2,
                    "disableForCPU":true,
                    "attackSound1_id":"super_jump_punch",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":3,
                            "hitStun":2,
                            "weightKB":120,
                            "selfHitStun":2,
                            "effect_id":"mario_coin",
                            "direction":70,
                            "reversableAngle":false,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"coin"
                        }}
                },
                "b_up_air":{
                    "refreshRate":999,
                    "resetMovement":true,
                    "cancelWhenAirborne":false,
                    "xSpeedDecay":-1,
                    "xSpeedDecayAir":-2,
                    "isRecoveryMove":true,
                    "disableForCPU":true,
                    "attackSound1_id":"super_jump_punch",
                    "attackBoxes":{"attackBox":{
                            "damage":4,
                            "priority":3,
                            "hitStun":2,
                            "weightKB":120,
                            "selfHitStun":2,
                            "effect_id":"mario_coin",
                            "direction":70,
                            "reversableAngle":false,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"coin"
                        }}
                },
                "b_forward":{
                    "cancelWhenAirborne":false,
                    "allowControlGround":false,
                    "xSpeedAccel":0.1,
                    "xSpeedAccelAir":0.1,
                    "xSpeedDecayAir":-1,
                    "air_ease":5,
                    "attackVoice1_id":"mario_wahah",
                    "attackSound1_id":"mario_cape",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "hasEffect":false,
                            "reverse_character":true,
                            "priority":-1,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":180,
                            "reversableAngle":false,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":null
                        },
                        "attackBox2":{
                            "hasEffect":false,
                            "hitStun":0,
                            "selfHitStun":0,
                            "reverse_projectile":true
                        }
                    }
                },
                "b_forward_air":{
                    "air_ease":5,
                    "allowControlGround":false,
                    "isHorizontalRecoveryMove":true,
                    "attackVoice1_id":"mario_wahah",
                    "attackSound1_id":"mario_cape",
                    "attackBoxes":{
                        "attackBox":{
                            "damage":8,
                            "hasEffect":false,
                            "reverse_character":true,
                            "priority":-1,
                            "hitStun":0,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":180,
                            "reversableAngle":false,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":null
                        },
                        "attackBox2":{
                            "hasEffect":false,
                            "hitStun":0,
                            "selfHitStun":0,
                            "reverse_projectile":true
                        }
                    }
                },
                "b_down":{
                    "cancelWhenAirborne":false,
                    "xSpeedCap":3,
                    "allowControl":true,
                    "canFallOff":false,
                    "allowFastFall":false,
                    "attackSound1_id":"mario_spin",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":3,
                            "hitStun":1,
                            "weightKB":40,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":145,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":"ssb_hit4"
                        }}
                },
                "b_down_air":{
                    "xSpeedCap":3,
                    "cancelWhenAirborne":false,
                    "allowControl":true,
                    "canFallOff":false,
                    "isHorizontalRecoveryMove":true,
                    "isRecoveryMove":true,
                    "allowFastFall":false,
                    "reenableTimer":10,
                    "attackSound1_id":"mario_spin",
                    "attackBoxes":{"attackBox":{
                            "damage":1,
                            "priority":3,
                            "hitStun":1,
                            "hitLag":-1,
                            "weightKB":40,
                            "selfHitStun":0,
                            "effect_id":"effect_lightHit",
                            "direction":145,
                            "power":40,
                            "kbConstant":0,
                            "effectSound":"ssb_hit4"
                        }}
                },
                "throw_up":{
                    "canFallOff":false,
                    "attackVoice1_id":"mario_grunt1",
                    "attackVoice2_id":"mario_grunt2",
                    "attackVoice3_id":"mario_grunt3",
                    "attackVoice4_id":"mario_grunt4",
                    "attackSound1_id":"whoosh1",
                    "cpuAttackQueue":"a_air_forward;a_air;a_up_tilt;a_air_down;a_air_up;a_air_up;b_forward;throw_up;throw_down",
                    "attackBoxes":{"attackBox":{
                            "damage":8,
                            "priority":0,
                            "hitStun":0,
                            "hitLag":-1.25,
                            "selfHitStun":0,
                            "direction":85,
                            "power":70,
                            "kbConstant":72,
                            "bypassNonGrabbed":true,
                            "effectSound":"launch_s"
                        }}
                },
                "throw_forward":{
                    "canFallOff":false,
                    "attackVoice1_id":"mario_grunt1",
                    "attackVoice2_id":"mario_grunt2",
                    "attackVoice3_id":"mario_grunt3",
                    "attackVoice4_id":"mario_grunt4",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh1",
                    "cpuAttackQueue":"a_forward;b;b_air",
                    "attackBoxes":{"attackBox":{
                            "damage":9,
                            "hasEffect":true,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":1,
                            "direction":45,
                            "power":60,
                            "kbConstant":72,
                            "bypassNonGrabbed":true,
                            "effectSound":"launch_s"
                        }}
                },
                "throw_back":{
                    "canFallOff":false,
                    "attackVoice1_id":"mario_heeyah",
                    "attackSound1_id":null,
                    "attackSound2_id":"whoosh1",
                    "attackBoxes":{"attackBox":{
                            "damage":12,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":145,
                            "reversableAngle":false,
                            "power":80,
                            "kbConstant":65,
                            "effectSound":"launch_s"
                        }}
                },
                "throw_down":{
                    "canFallOff":false,
                    "attackVoice1_id":"mario_grunt1",
                    "attackVoice2_id":"mario_grunt2",
                    "attackVoice3_id":"mario_grunt3",
                    "attackVoice4_id":"mario_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "cpuAttackQueue":"throw_down;a_air;a_air_up;a_air_forward",
                    "attackBoxes":{"attackBox":{
                            "reversableAngle":false,
                            "damage":6,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":-1,
                            "selfHitStun":0,
                            "effect_id":"effect_hit3",
                            "direction":75,
                            "power":75,
                            "kbConstant":30,
                            "bypassNonGrabbed":true,
                            "effectSound":"brawl_kick_l"
                        }}
                },
                "crouch_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"mario_grunt1",
                    "attackVoice2_id":"mario_grunt2",
                    "attackVoice3_id":"mario_grunt3",
                    "attackVoice4_id":"mario_grunt4",
                    "attackSound1_id":"brawl_swing_l",
                    "cpuAttackQueue":"a_up_tilt;crouch_attack;a_forwardsmash;a_down;",
                    "attackBoxes":{"attackBox":{
                            "damage":10,
                            "priority":2,
                            "hitStun":3,
                            "hitLag":-1,
                            "selfHitStun":1,
                            "effect_id":"effect_lightHit",
                            "direction":65,
                            "power":20,
                            "kbConstant":80,
                            "effectSound":"mario_kick_l"
                        }}
                },
                "ledge_attack":{
                    "canFallOff":false,
                    "cancelWhenAirborne":false,
                    "attackVoice1_id":"mario_grunt1",
                    "attackVoice2_id":"mario_grunt2",
                    "attackVoice3_id":"mario_grunt3",
                    "attackVoice4_id":"mario_grunt4",
                    "attackSound1_id":"mario_lightpunch",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":6,
                            "hitStun":2,
                            "weightKB":110,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":30,
                            "power":0,
                            "kbConstant":100,
                            "effectSound":"mario_kick"
                        }}
                },
                "getup_attack":{
                    "canFallOff":false,
                    "attackVoice1_id":"mario_grunt1",
                    "attackVoice2_id":"mario_grunt2",
                    "attackVoice3_id":"mario_grunt3",
                    "attackVoice4_id":"mario_grunt4",
                    "attackSound1_id":"mario_lightpunch",
                    "attackBoxes":{"attackBox":{
                            "damage":5,
                            "priority":3,
                            "hitStun":2,
                            "selfHitStun":1,
                            "effect_id":"effect_hit2",
                            "direction":-4,
                            "power":80,
                            "kbConstant":50,
                            "effectSound":"mario_kick"
                        }}
                },
                "kirby":{
                    "attackSound1_id":"fireball",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":30,
                            "power":0,
                            "kbConstant":1,
                            "burn":true,
                            "effectSound":null
                        }}
                },
                "kirby_air":{
                    "allowControl":true,
                    "maintainSpeed":true,
                    "attackSound1_id":"fireball",
                    "isLongRangeMove":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "hasEffect":false,
                            "priority":0,
                            "hitStun":0,
                            "selfHitStun":0,
                            "direction":30,
                            "power":0,
                            "kbConstant":1,
                            "burn":true,
                            "effectSound":null
                        }}
                },
                "special":{
                    "resetMovement":true,
                    "invincible":true,
                    "air_ease":0,
                    "canUseInAir":true,
                    "attackBoxes":{"attackBox":{
                            "damage":0,
                            "priority":0,
                            "hitStun":1,
                            "hitLag":0.9,
                            "selfHitStun":0,
                            "direction":0,
                            "power":2,
                            "kbConstant":1,
                            "effectSound":null
                        }}
                }
            };
            var _local_4:Object = {
                "mario_fireball":{
                    "linkage_id":"mario_fireball",
                    "width":11,
                    "height":11,
                    "time_max":40,
                    "xspeed":6.75,
                    "gravity":1,
                    "maxgravity":10,
                    "bounce":8,
                    "bounce_decay":0.7,
                    "limit":6,
                    "attack_idle":{"attackBoxes":{"attackBox":{
                                "burn":true,
                                "effectSound":"brawl_fire_m",
                                "damage":5,
                                "direction":40,
                                "power":30,
                                "kbConstant":25,
                                "priority":2,
                                "hitStun":1,
                                "selfHitStun":0,
                                "hitLag":-1,
                                "effect_id":"fireballexplosion"
                            }}}
                },
                "mario_finale":{
                    "linkage_id":"mario_finale_projectile",
                    "width":245,
                    "height":182,
                    "time_max":160,
                    "xspeed":4,
                    "ghost":true,
                    "canBeReversed":false,
                    "canBeAbsorbed":false,
                    "surviveDeathBounds":true,
                    "yoffset":-10,
                    "attack_idle":{
                        "refreshRate":2,
                        "attackBoxes":{"attackBox":{
                                "burn":true,
                                "effectSound":"smallexplosion",
                                "damage":5,
                                "direction":0,
                                "power":45,
                                "kbConstant":25,
                                "priority":7,
                                "hitStun":0,
                                "selfHitStun":0,
                                "hitLag":-1,
                                "priority":7,
                                "effect_id":"fireballexplosion_special"
                            }}
                    }
                }
            };
            var _local_5:Object;
            return ({
                "cData":_local_2,
                "aData":_local_3,
                "pData":_local_4,
                "iData":_local_5
            });
        }

        public function getID():String
        {
            return ("mario");
        }

        public function getGUID():String
        {
            return ("b4768513-c851-4f19-8c73-6f18e4f27b64");
        }

        public function initAPI(_arg_1:*):Class
        {
            return (SSF2API.init(_arg_1));
        }

        internal function frame1():*
        {
            Security.allowDomain("*mcleodgaming.com*");
            this.visible = false;
            stop();
        }


    }
}//package mario_fla

